export const BUILD_PHRASE_DISTRACTOR_MEANINGS = Object.freeze({
  "sulčių": "juice",
  toli: "far",
  "kairėn": "to the left",
  "viešbutį": "hotel (the form used after į: to the hotel)",
  "kavinę": "café (the form used after į: to the café)",
  "viešbutyje": "in the hotel",
  mieste: "in the city",
  "iš": "from / out of",
  "stotį": "station (the form used after į: to the station)",
  "vaistinę": "pharmacy (the form used after į: to the pharmacy)",
  suprantu: "I understand",
  kalbu: "I speak",
  stotis: "station",
  galiu: "I can",
  vakaras: "evening",
  dar: "still / more",
  rytas: "morning",
  "jūsų": "your (polite/plural)",
  irgi: "too / also",
  draugas: "male friend",
  brolis: "brother",
  pakartokite: "repeat (polite/plural command)",
  "angliškai": "in English",
  "šiek": "a little / a bit",
  "lėčiau": "more slowly",
  "padėti": "to help",
  "čia": "here",
  "viešbutis": "hotel",
  bankas: "bank",
  galite: "you can (polite/plural)",
  vandens: "water",
  kavos: "coffee",
  parodyti: "to show",
  negaliu: "I can't",
  ta: "that (feminine form)",
  to: "that (masculine form)",
  "kavų": "coffees",
  "metų": "years",
  "trisdešimt": "thirty",
  "dviejų": "two (quantity form)",
  tas: "that (masculine form)",
  "mokėti": "to pay",
  turiu: "I have",
  noriu: "I want",
  kortele: "by card",
  dabar: "now",
  "vėliau": "later",
  "šeštą": "at six",
  trys: "three",
  "pinigų": "money",
  pakanka: "enough / it is enough",
  viena: "one (feminine basic form)",
  laiko: "time",
  "vieną": "one (feminine object form)",
  "kavą": "coffee",
  su: "with",
  pienu: "with milk",
  dvi: "two (feminine form)",
  arbatas: "teas",
  be: "without",
  cukraus: "sugar",
  "šito": "this / this one (masculine form)",
  man: "for me / to me",
  lietuvos: "Lithuania's / of Lithuania",
});

export function normalizeBuildPhraseToken(text) {
  return String(text || "")
    .trim()
    .toLocaleLowerCase("lt")
    .replace(/[.,!?;:]+$/g, "");
}

export function getBuildPhraseDistractorMeaning(text) {
  return BUILD_PHRASE_DISTRACTOR_MEANINGS[normalizeBuildPhraseToken(text)] || null;
}
