// src/content/learning/section3/module_3_1.js
// Module 3.1 — Essential Numbers

export default function createModule_3_1(profile = {}) {
  const { userNameSafe = "Davidas" } = profile;

  return {
    id: "module_3_1",
    code: "3.1",
    title: "Essential Numbers",
    status: "active",
    lessonCount: 4,
    lessons: [

      // ── Lesson 1 — 0 to 10 ──────────────────────────────────────────────────
      {
        id: "section_3_module_1_lesson_1",
        code: "3.1.1",
        title: "Zero to Ten",
        purpose: "Build fast recognition and production of the core base numbers.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Lithuanian numbers are the foundation for prices, times, and quantities. Aim to hear them and say them quickly — speed matters more than perfection right now.",
          usage: [
            "nulis — zero",
            "vienas — one",
            "du — two",
            "trys — three",
            "keturi — four",
            "penki — five",
            "šeši — six",
            "septyni — seven",
            "aštuoni — eight",
            "devyni — nine",
            "dešimt — ten",
          ],
        },
        blocks: [
          {
            id: "s3m1l1_b1",
            type: "learn",
            title: "Zero to ten",
            items: [
              { id: "n0",  lt: "nulis",   en: "zero",  audioText: "nulis",   saveable: false },
              { id: "n1",  lt: "vienas",  en: "one",   audioText: "vienas",  saveable: false },
              { id: "n2",  lt: "du",      en: "two",   audioText: "du",      saveable: false },
              { id: "n3",  lt: "trys",    en: "three", audioText: "trys",    saveable: false },
              { id: "n4",  lt: "keturi",  en: "four",  audioText: "keturi",  saveable: false },
              { id: "n5",  lt: "penki",   en: "five",  audioText: "penki",   saveable: false },
              { id: "n6",  lt: "šeši",    en: "six",   audioText: "šeši",    saveable: false },
              { id: "n7",  lt: "septyni", en: "seven", audioText: "septyni", saveable: false },
              { id: "n8",  lt: "aštuoni", en: "eight", audioText: "aštuoni", saveable: false },
              { id: "n9",  lt: "devyni",  en: "nine",  audioText: "devyni",  saveable: false },
              { id: "n10", lt: "dešimt",  en: "ten",   audioText: "dešimt",  saveable: false },
              { id: "noun_min", lt: "minutė", en: "minute", audioText: "minutė", core: false, saveable: true },
            ],
          },
          {
            id: "s3m1l1_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "aštuoni", audioText: "aštuoni" },
            options: [
              { id: "a", text: "six", isCorrect: false },
              { id: "b", text: "eight", isCorrect: true },
              { id: "c", text: "nine", isCorrect: false },
            ],
          },
          {
            id: "s3m1l1_b5",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "septyni", audioText: "septyni" },
            options: [
              { id: "a", text: "six", isCorrect: false },
              { id: "b", text: "seven", isCorrect: true },
              { id: "c", text: "nine", isCorrect: false },
            ],
          },
          {
            id: "s3m1l1_b6",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "dešimt", audioText: "dešimt" },
            options: [
              { id: "a", text: "eight", isCorrect: false },
              { id: "b", text: "nine", isCorrect: false },
              { id: "c", text: "ten", isCorrect: true },
            ],
          },
          {
            id: "s3m1l1_b7",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: six",
            targetText: "šeši",
            audioText: "šeši",
          },
        ],
      },

      // ── Lesson 2 — 11 to 20 ─────────────────────────────────────────────────
      {
        id: "section_3_module_1_lesson_2",
        code: "3.1.2",
        title: "Eleven to Twenty",
        purpose: "Extend the number range into teen numbers and twenty.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Lithuanian teen numbers mostly end in -lika. You don't need to memorise the rule — just get familiar with hearing them. Twenty is dvidešimt, which you'll use a lot in prices.",
          usage: [
            "vienuolika — eleven",
            "dvylika — twelve",
            "trylika — thirteen",
            "keturiolika — fourteen",
            "penkiolika — fifteen",
            "šešiolika — sixteen",
            "septyniolika — seventeen",
            "aštuoniolika — eighteen",
            "devyniolika — nineteen",
            "dvidešimt — twenty",
          ],
        },
        blocks: [
          {
            id: "s3m1l2_b1",
            type: "learn",
            title: "Eleven to twenty",
            items: [
              { id: "n11", lt: "vienuolika",   en: "eleven",    audioText: "vienuolika",   saveable: false },
              { id: "n12", lt: "dvylika",       en: "twelve",    audioText: "dvylika",       saveable: false },
              { id: "n13", lt: "trylika",       en: "thirteen",  audioText: "trylika",       saveable: false },
              { id: "n14", lt: "keturiolika",   en: "fourteen",  audioText: "keturiolika",   saveable: false },
              { id: "n15", lt: "penkiolika",    en: "fifteen",   audioText: "penkiolika",    saveable: false },
              { id: "n16", lt: "šešiolika",     en: "sixteen",   audioText: "šešiolika",     saveable: false },
              { id: "n17", lt: "septyniolika",  en: "seventeen", audioText: "septyniolika",  saveable: false },
              { id: "n18", lt: "aštuoniolika",  en: "eighteen",  audioText: "aštuoniolika",  saveable: false },
              { id: "n19", lt: "devyniolika",   en: "nineteen",  audioText: "devyniolika",   saveable: false },
              { id: "n20", lt: "dvidešimt",     en: "twenty",    audioText: "dvidešimt",     saveable: false },
            ],
          },
          {
            id: "s3m1l2_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "aštuoniolika", audioText: "aštuoniolika" },
            options: [
              { id: "a", text: "seventeen", isCorrect: false },
              { id: "b", text: "nineteen", isCorrect: false },
              { id: "c", text: "eighteen", isCorrect: true },
            ],
          },
          {
            id: "s3m1l2_b5",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "dvidešimt", audioText: "dvidešimt" },
            options: [
              { id: "a", text: "twelve", isCorrect: false },
              { id: "b", text: "twenty", isCorrect: true },
              { id: "c", text: "nineteen", isCorrect: false },
            ],
          },
          {
            id: "s3m1l2_b6",
            type: "best_response",
            title: "Choose the best response",
            noOptionAudio: true,
            prompt: { text: "Someone says their son is aštuoniolika years old. How old is he?" },
            options: [
              { id: "a", text: "Fourteen", isCorrect: false },
              { id: "b", text: "Eighteen", isCorrect: true },
              { id: "c", text: "Eighty", isCorrect: false },
            ],
            feedback: { correct: "Aštuoniolika — eighteen. The -lika ending is the clue." },
          },
          {
            id: "s3m1l2_b7",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "It costs twenty euros" },
            tokens: [
              { id: "t1", text: "Tai",       correctIndex: 0 },
              { id: "t2", text: "kainuoja",  correctIndex: 1 },
              { id: "t3", text: "dvidešimt", correctIndex: 2 },
              { id: "t4", text: "eurų",      correctIndex: 3 },
              { id: "t5", text: "trisdešimt", isDistractor: true },
            ],
            answerText: "Tai kainuoja dvidešimt eurų",
          },
        ],
      },

      // ── Lesson 3 — Tens That Matter ──────────────────────────────────────────
      {
        id: "section_3_module_1_lesson_3",
        code: "3.1.3",
        title: "Tens That Matter",
        purpose: "Recognise and produce the key tens most useful in prices, times, and amounts.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Lithuanian tens above twenty follow a pattern — trisdešimt (thirty), keturiasdešimt (forty), penkiasdešimt (fifty). Šimtas is one hundred. These are the amounts you'll hear most often in real situations.",
          usage: [
            "dvidešimt — twenty (already known)",
            "trisdešimt — thirty",
            "keturiasdešimt — forty",
            "penkiasdešimt — fifty",
            "šimtas — one hundred",
          ],
        },
        blocks: [
          {
            id: "s3m1l3_b1",
            type: "learn",
            title: "The key tens",
            items: [
              { id: "t30",  lt: "trisdešimt",      en: "thirty",      audioText: "trisdešimt",      saveable: false },
              { id: "t40",  lt: "keturiasdešimt",  en: "forty",       audioText: "keturiasdešimt",  saveable: false },
              { id: "t50",  lt: "penkiasdešimt",   en: "fifty",       audioText: "penkiasdešimt",   saveable: false },
              { id: "t100", lt: "šimtas",           en: "one hundred", audioText: "šimtas",           saveable: false },
              { id: "noun_eur", lt: "eurai / eurų", en: "euros", audioText: "eurai", core: false, saveable: true },
            ],
          },
          {
            id: "s3m1l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "trisdešimt", audioText: "trisdešimt" },
            options: [
              { id: "a", text: "twenty", isCorrect: false },
              { id: "b", text: "thirty", isCorrect: true },
              { id: "c", text: "forty", isCorrect: false },
            ],
          },
          {
            id: "s3m1l3_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "šimtas", audioText: "šimtas" },
            options: [
              { id: "a", text: "fifty", isCorrect: false },
              { id: "b", text: "seventy", isCorrect: false },
              { id: "c", text: "one hundred", isCorrect: true },
            ],
          },
          {
            id: "s3m1l3_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "keturiasdešimt", audioText: "keturiasdešimt" },
            options: [
              { id: "a", text: "thirty", isCorrect: false },
              { id: "b", text: "forty", isCorrect: true },
              { id: "c", text: "fifty", isCorrect: false },
            ],
          },
          {
            id: "s3m1l3_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: thirty",
            targetText: "trisdešimt",
            audioText: "trisdešimt",
          },
          {
            id: "s3m1l3_b6",
            type: "best_response",
            title: "Choose the best response",
            noOptionAudio: true,
            prompt: { text: "A market seller says 'penkiasdešimt eurų'. How much is it?" },
            options: [
              { id: "a", text: "Fifteen euros", isCorrect: false },
              { id: "b", text: "Fifty euros", isCorrect: true },
              { id: "c", text: "Five hundred euros", isCorrect: false },
            ],
            feedback: { correct: "Penkiasdešimt — fifty. Not penkiolika (fifteen) or penkis šimtus (five hundred)." },
          },
        ],
      },

      // ── Lesson 4 — Hearing Numbers in Context ───────────────────────────────
      {
        id: "section_3_module_1_lesson_4",
        code: "3.1.4",
        title: "Numbers in Context",
        purpose: "Stop numbers being flashcards — hear and use them inside real phrases.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "Numbers in Lithuanian sit inside real phrases. Hearing 'dešimt' in isolation is different from hearing it inside 'Tai kainuoja dešimt eurų'. This lesson is about making that connection.",
          usage: [
            "Tai kainuoja dešimt eurų — it costs ten euros",
            "Mes esame du — we are two",
            "Man reikia trijų bilietų — I need three tickets",
            "Pradedame penktą valandą — we start at five o'clock",
          ],
        },
        blocks: [
          {
            id: "s3m1l4_b1",
            type: "learn",
            title: "Numbers in real phrases",
            items: [
              { id: "ctx1", lt: "Tai kainuoja dešimt eurų",    en: "It costs ten euros",         audioText: "Tai kainuoja dešimt eurų",    saveable: true, core: true },
              { id: "ctx2", lt: "Mes esame du",                 en: "We are two",                 audioText: "Mes esame du",                 saveable: true, core: true },
              { id: "ctx3", lt: "Man reikia trijų bilietų",    en: "I need three tickets",       audioText: "Man reikia trijų bilietų",    saveable: true, core: true },
              { id: "ctx4", lt: "Pradedame penktą valandą",    en: "We start at five o'clock",   audioText: "Pradedame penktą valandą",    saveable: true, core: true },
              { id: "noun_val", lt: "valanda", en: "hour / o'clock", audioText: "valanda", core: false, saveable: true },
            ],
          },
          {
            id: "s3m1l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Tai kainuoja dešimt eurų", audioText: "Tai kainuoja dešimt eurų" },
            options: [
              { id: "a", text: "It costs three euros", isCorrect: false },
              { id: "b", text: "It costs ten euros", isCorrect: true },
              { id: "c", text: "It costs twenty euros", isCorrect: false },
            ],
          },
          {
            id: "s3m1l4_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Mes esame du", audioText: "Mes esame du" },
            options: [
              { id: "a", text: "We are ten", isCorrect: false },
              { id: "b", text: "We are five", isCorrect: false },
              { id: "c", text: "We are two", isCorrect: true },
            ],
          },
          {
            id: "s3m1l4_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Man reikia trijų bilietų", audioText: "Man reikia trijų bilietų" },
            options: [
              { id: "a", text: "I want two coffees", isCorrect: false },
              { id: "b", text: "I need three tickets", isCorrect: true },
              { id: "c", text: "I have five euros", isCorrect: false },
            ],
          },
          {
            id: "s3m1l4_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're at a ticket desk. You need tickets for yourself and one friend. What do you say?" },
            options: [
              { id: "a", text: "Man reikia trijų bilietų", isCorrect: false },
              { id: "b", text: "Mes esame du", isCorrect: false },
              { id: "c", text: "Man reikia dviejų bilietų", isCorrect: true },
            ],
            feedback: { correct: "Two of you — dviejų bilietų. It's the same pattern as trijų bilietų." },
          },
          {
            id: "s3m1l4_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You're at a café counter. The server asks how many coffees.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Kiek kavų?",
                audioText: "Laba diena! Kiek kavų?",
                helperText: "How many coffees?",
                options: [
                  { id: "a", text: "Viso gero", isCorrect: false },
                  { id: "b", text: "Dvi kavas, prašau", isCorrect: true },
                  { id: "c", text: "Šimtas kavų", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Tai kainuoja šešis eurus.",
                audioText: "Tai kainuoja šešis eurus",
                helperText: "It costs six euros.",
                options: [
                  { id: "a", text: "Aš nesuprantu", isCorrect: false },
                  { id: "b", text: "Labas rytas", isCorrect: false },
                  { id: "c", text: "Gerai, ačiū", isCorrect: true },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom!",
                audioText: "Prašom",
                helperText: "Here you go!",
                options: [
                  { id: "a", text: "Viso gero", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", isCorrect: true },
                  { id: "c", text: "Atsiprašau", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Module 3.1 Checkpoint ────────────────────────────────────────────────
      {
        id: "section_3_module_1_checkpoint",
        code: "3.1.C",
        title: "Numbers Check",
        purpose: "Prove you can recognise and use core numbers quickly in real contexts.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s3m1c_b1",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "penkiolika", audioText: "penkiolika" },
            options: [
              { id: "a", text: "fifty", isCorrect: false },
              { id: "b", text: "fifteen", isCorrect: true },
              { id: "c", text: "five", isCorrect: false },
            ],
          },
          {
            id: "s3m1c_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "keturiasdešimt", audioText: "keturiasdešimt" },
            options: [
              { id: "a", text: "fourteen", isCorrect: false },
              { id: "b", text: "forty", isCorrect: true },
              { id: "c", text: "four", isCorrect: false },
            ],
          },
          {
            id: "s3m1c_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Tai kainuoja trisdešimt eurų", audioText: "Tai kainuoja trisdešimt eurų" },
            options: [
              { id: "a", text: "It costs thirteen euros", isCorrect: false },
              { id: "b", text: "It costs thirty euros", isCorrect: true },
              { id: "c", text: "It costs three hundred euros", isCorrect: false },
            ],
          },
          {
            id: "s3m1c_b4",
            type: "best_response",
            title: "Choose the best response",
            noOptionAudio: true,
            prompt: { text: "Someone at a ticket desk holds up eight fingers and says 'aštuoni'. What are they telling you?" },
            options: [
              { id: "a", text: "The price is eighty euros", isCorrect: false },
              { id: "b", text: "There are eight tickets available", isCorrect: false },
              { id: "c", text: "The number eight — probably eight euros or eight tickets", isCorrect: true },
            ],
            feedback: { correct: "Aštuoni — eight. Context tells you whether it's a price, a count, or something else." },
          },
          {
            id: "s3m1c_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "I need three tickets" },
            tokens: [
              { id: "t1", text: "Man",     correctIndex: 0 },
              { id: "t2", text: "reikia",  correctIndex: 1 },
              { id: "t3", text: "trijų",   correctIndex: 2 },
              { id: "t4", text: "bilietų", correctIndex: 3 },
              { id: "t5", text: "dviejų",  isDistractor: true },
            ],
            answerText: "Man reikia trijų bilietų",
          },
          {
            id: "s3m1c_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You're at a train station ticket window. A quick number exchange.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Kiek bilietų?",
                audioText: "Laba diena! Kiek bilietų?",
                helperText: "How many tickets?",
                options: [
                  { id: "a", text: "Viso gero", isCorrect: false },
                  { id: "b", text: "Du bilietai, prašau", isCorrect: true },
                  { id: "c", text: "Šimtas", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Dvidešimt eurų.",
                audioText: "Dvidešimt eurų",
                helperText: "Twenty euros.",
                options: [
                  { id: "a", text: "Atsiprašau, nesuprantu", isCorrect: false },
                  { id: "b", text: "Dvidešimt? Gerai.", isCorrect: true },
                  { id: "c", text: "Iki", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom, du bilietai.",
                audioText: "Prašom, du bilietai",
                helperText: "Here you go, two tickets.",
                options: [
                  { id: "a", text: "Atsiprašau", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", isCorrect: true },
                  { id: "c", text: "Nesuprantu", isCorrect: false },
                ],
              },
            ],
          },
          {
            id: "s3m1c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "vienas",        en: "one",         audioText: "vienas" },
              { id: "m2",  lt: "du",             en: "two",         audioText: "du" },
              { id: "m3",  lt: "trys",           en: "three",       audioText: "trys" },
              { id: "m4",  lt: "keturi",         en: "four",        audioText: "keturi" },
              { id: "m5",  lt: "penki",          en: "five",        audioText: "penki" },
              { id: "m6",  lt: "šeši",           en: "six",         audioText: "šeši" },
              { id: "m7",  lt: "septyni",        en: "seven",       audioText: "septyni" },
              { id: "m8",  lt: "aštuoni",        en: "eight",       audioText: "aštuoni" },
              { id: "m9",  lt: "devyni",         en: "nine",        audioText: "devyni" },
              { id: "m10", lt: "dešimt",         en: "ten",         audioText: "dešimt" },
              { id: "m11", lt: "vienuolika",     en: "eleven",      audioText: "vienuolika" },
              { id: "m12", lt: "dvylika",        en: "twelve",      audioText: "dvylika" },
              { id: "m13", lt: "penkiolika",     en: "fifteen",     audioText: "penkiolika" },
              { id: "m14", lt: "aštuoniolika",   en: "eighteen",    audioText: "aštuoniolika" },
              { id: "m15", lt: "dvidešimt",      en: "twenty",      audioText: "dvidešimt" },
              { id: "m16", lt: "trisdešimt",     en: "thirty",      audioText: "trisdešimt" },
              { id: "m17", lt: "keturiasdešimt", en: "forty",       audioText: "keturiasdešimt" },
              { id: "m18", lt: "penkiasdešimt",  en: "fifty",       audioText: "penkiasdešimt" },
              { id: "m19", lt: "šimtas",         en: "one hundred", audioText: "šimtas" },
              { id: "m20", lt: "minutė",         en: "minute",      audioText: "minutė" },
            ],
          },
        ],
      },
    ],
  };
}
