// src/content/learning/section1.js

const section1 = {
  id: "section_1",
  code: "1",
  title: "First Contact",
  description: "Essential greetings, polite responses, and survival phrases.",
  status: "active",
  modules: [
    {
      id: "module_1_1",
      code: "1.1",
      title: "Greeting and Politeness",
      status: "active",
      lessonCount: 5,
      lessons: [

        // ── Lesson 1 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_1",
          code: "1.1.1",
          title: "Hello and Goodbye",
          purpose: "Introduce first-contact opening and closing language.",
          supportLevel: "high",
          newLanguageLoad: "very_low",
          notes: {
            pattern: "Lithuanian greetings change by time of day. Labas works any time; Laba diena is daytime only.",
            usage: [
              "Labas — casual, any time of day",
              "Laba diena — formal or daytime",
              "Labas rytas / Labas vakaras — morning and evening specifically",
              "Viso gero / Iki — both mean goodbye, Iki is more casual",
            ],
          },
          blocks: [
            {
              id: "s1m1l1_b1",
              type: "learn",
              title: "Greetings and farewells",
              items: [
                { id: "g1", lt: "Labas", en: "Hello (casual)", audioText: "Labas", saveable: true, core: true },
                { id: "g2", lt: "Laba diena", en: "Good day / Hello (formal)", audioText: "Laba diena", saveable: true, core: true },
                { id: "g3", lt: "Labas rytas", en: "Good morning", audioText: "Labas rytas", saveable: true, core: true },
                { id: "g4", lt: "Labas vakaras", en: "Good evening", audioText: "Labas vakaras", saveable: true, core: true },
                { id: "g5", lt: "Viso gero", en: "Goodbye (take care)", audioText: "Viso gero", saveable: true, core: true },
                { id: "g6", lt: "Iki", en: "Bye (casual)", audioText: "Iki", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l1_b2",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Labas", audioText: "Labas" },
              options: [
                { id: "a", text: "Goodbye", isCorrect: false },
                { id: "b", text: "Hello", isCorrect: true },
                { id: "c", text: "Good morning", isCorrect: false },
              ],
            },
            {
              id: "s1m1l1_b3",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Laba diena", audioText: "Laba diena" },
              options: [
                { id: "a", text: "Good morning", isCorrect: false },
                { id: "b", text: "Good day / Hello", isCorrect: true },
                { id: "c", text: "Goodbye", isCorrect: false },
              ],
            },
            {
              id: "s1m1l1_b3b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Labas vakaras", audioText: "Labas vakaras" },
              options: [
                { id: "a", text: "Good morning", isCorrect: false },
                { id: "b", text: "Good evening", isCorrect: true },
                { id: "c", text: "Goodbye", isCorrect: false },
              ],
            },
            {
              id: "s1m1l1_b3c",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Iki", audioText: "Iki" },
              options: [
                { id: "a", text: "Hello", isCorrect: false },
                { id: "b", text: "Good evening", isCorrect: false },
                { id: "c", text: "Bye (casual)", isCorrect: true },
              ],
            },
            {
              id: "s1m1l1_b4",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone says Laba diena to you in a shop." },
              options: [
                { id: "a", text: "Labas rytas", isCorrect: false },
                { id: "b", text: "Laba diena", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
              feedback: { correct: "Match the register — laba diena for laba diena." },
            },
            {
              id: "s1m1l1_b5",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "Say hello in Lithuanian",
              targetText: "Labas",
              audioText: "Labas",
            },
            {
              id: "s1m1l1_b6",
              type: "build_phrase",
              title: "Build the phrase",
              prompt: { text: "Good morning" },
              tokens: [
                { id: "t3", text: "vakaras", isDistractor: true },
                { id: "t2", text: "rytas", correctIndex: 1 },
                { id: "t1", text: "Labas", correctIndex: 0 },
              ],
              answerText: "Labas rytas",
            },
            {
              id: "s1m1l1_b7",
              type: "scenario_chain",
              title: "Conversation",
              description: "Complete a short greeting exchange.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Labas!",
                  audioText: "Labas",
                  options: [
                    { id: "a", text: "Labas!", isCorrect: true },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Ne", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Laba diena", isCorrect: false },
                    { id: "b", text: "Iki!", isCorrect: true },
                    { id: "c", text: "Taip", isCorrect: false },
                  ],
                },
              ],
            },
          ],
        },

        // ── Lesson 2 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_2",
          code: "1.1.2",
          title: "Yes, No, Please, Thank You",
          purpose: "Core polite responses that work in almost every situation.",
          supportLevel: "high",
          newLanguageLoad: "very_low",
          notes: {
            pattern: "Prašau does double duty — it means both 'please' and 'here you go / you're welcome'. Words combine naturally: Ne, ačiū is the polite way to say no.",
            usage: [
              "Taip / Ne — yes and no",
              "Taip, prašau — yes please (accepting something politely)",
              "Ne, ačiū — no thank you (declining something politely)",
              "Prašau — please (when asking) or here you go / you're welcome (when giving)",
              "Ačiū — thank you",
              "Ačiū labai — thank you very much",
            ],
          },
          blocks: [
            {
              id: "s1m1l2_b1",
              type: "learn",
              title: "Essential polite words",
              items: [
                { id: "p1", lt: "Taip", en: "Yes", audioText: "Taip", saveable: true, core: true },
                { id: "p2", lt: "Ne", en: "No", audioText: "Ne", saveable: true, core: true },
                { id: "p3", lt: "Prašau", en: "Please / Here you go / You're welcome", audioText: "Prašau", saveable: true, core: true },
                { id: "p4", lt: "Ačiū", en: "Thank you", audioText: "Ačiū", saveable: true, core: true },
                { id: "p5", lt: "Ačiū labai", en: "Thank you very much", audioText: "Ačiū labai", saveable: true, core: true },
                { id: "p6", lt: "Taip, prašau", en: "Yes please", audioText: "Taip, prašau", saveable: true, core: true },
                { id: "p7", lt: "Ne, ačiū", en: "No thank you", audioText: "Ne, ačiū", saveable: true, core: true },
                { id: "p8", lt: "Norėčiau kavos, prašau", en: "I'd like a coffee, please", audioText: "Norėčiau kavos, prašau", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l2_b1b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Taip", audioText: "Taip" },
              options: [
                { id: "a", text: "No", isCorrect: false },
                { id: "b", text: "Please", isCorrect: false },
                { id: "c", text: "Yes", isCorrect: true },
              ],
            },
            {
              id: "s1m1l2_b1c",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone offers you a second helping and you don't want it." },
              options: [
                { id: "a", text: "Taip, prašau", isCorrect: false },
                { id: "b", text: "Ne, ačiū", isCorrect: true },
                { id: "c", text: "Ačiū labai", isCorrect: false },
              ],
              feedback: { correct: "Ne, ačiū — no thank you. Bare 'Ne' can sound abrupt; adding ačiū keeps it polite." },
            },
            {
              id: "s1m1l2_b1d",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone offers you a coffee and you'd like one." },
              options: [
                { id: "a", text: "Ne, ačiū", isCorrect: false },
                { id: "b", text: "Taip, prašau", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
              feedback: { correct: "Taip, prašau — yes please. Much more natural than Taip alone." },
            },
            {
              id: "s1m1l2_b2",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Ačiū", audioText: "Ačiū" },
              options: [
                { id: "a", text: "Please", isCorrect: false },
                { id: "b", text: "Yes", isCorrect: false },
                { id: "c", text: "Thank you", isCorrect: true },
              ],
            },
            {
              id: "s1m1l2_b3",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone hands you something and says Prašau." },
              options: [
                { id: "a", text: "Ačiū", isCorrect: true },
                { id: "b", text: "Ne", isCorrect: false },
                { id: "c", text: "Labas", isCorrect: false },
              ],
              feedback: { correct: "Prašau here means 'here you go' — Ačiū is the natural reply." },
            },
            {
              id: "s1m1l2_b4",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Ačiū labai", audioText: "Ačiū labai" },
              options: [
                { id: "a", text: "Thank you very much", isCorrect: true },
                { id: "b", text: "You're welcome", isCorrect: false },
                { id: "c", text: "Please", isCorrect: false },
              ],
            },
            {
              id: "s1m1l2_b4b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Ne, ačiū", audioText: "Ne, ačiū" },
              options: [
                { id: "a", text: "Yes please", isCorrect: false },
                { id: "b", text: "No thank you", isCorrect: true },
                { id: "c", text: "Thank you very much", isCorrect: false },
              ],
            },
            {
              id: "s1m1l2_b4c",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Norėčiau kavos, prašau", audioText: "Norėčiau kavos, prašau" },
              options: [
                { id: "a", text: "Here is your coffee", isCorrect: false },
                { id: "b", text: "I'd like a coffee, please", isCorrect: true },
                { id: "c", text: "No thank you", isCorrect: false },
              ],
              feedback: { correct: "Norėčiau means 'I would like' — a polite and natural way to order anything." },
            },
            {
              id: "s1m1l2_b5",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "Say thank you in Lithuanian",
              targetText: "Ačiū",
              audioText: "Ačiū",
            },
            {
              id: "s1m1l2_b6",
              type: "scenario_chain",
              title: "Conversation",
              description: "You walk into a café. Order a coffee and complete the exchange.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Laba diena!",
                  audioText: "Laba diena",
                  options: [
                    { id: "a", text: "Laba diena!", isCorrect: true },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Ne, ačiū", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Taip?",
                  audioText: "Taip",
                  options: [
                    { id: "a", text: "Ačiū labai", isCorrect: false },
                    { id: "b", text: "Ne, ačiū", isCorrect: false },
                    { id: "c", text: "Norėčiau kavos, prašau", isCorrect: true },
                  ],
                },
                {
                  id: "step_3",
                  actor: "other",
                  text: "Prašau.",
                  audioText: "Prašau",
                  options: [
                    { id: "a", text: "Ačiū labai!", isCorrect: true },
                    { id: "b", text: "Ne, ačiū", isCorrect: false },
                    { id: "c", text: "Taip", isCorrect: false },
                  ],
                },
                {
                  id: "step_4",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Atsiprašau", isCorrect: false },
                    { id: "b", text: "Taip, prašau", isCorrect: false },
                    { id: "c", text: "Iki!", isCorrect: true },
                  ],
                },
              ],
            },
          ],
        },

        // ── Lesson 3 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_3",
          code: "1.1.3",
          title: "Sorry and Excuse Me",
          purpose: "Teach interruption and light apology language.",
          supportLevel: "medium",
          newLanguageLoad: "low_to_medium",
          notes: {
            pattern: "One English idea often maps to different Lithuanian words depending on situation.",
            usage: [
              "Atsiprašau — sorry (apology) or excuse me (interruption)",
              "Atleiskite — more formal excuse me / forgive me",
              "Prašau dar kartą — one more time please (when you didn't catch something)",
            ],
          },
          blocks: [
            {
              id: "s1m1l3_b1",
              type: "learn",
              title: "Apology and interruption language",
              items: [
                { id: "sorry_1", lt: "Atsiprašau", en: "Sorry / Excuse me", audioText: "Atsiprašau", saveable: true, core: true },
                { id: "sorry_2", lt: "Prašau dar kartą", en: "One more time, please", audioText: "Prašau dar kartą", saveable: true, core: true },
                { id: "sorry_3", lt: "Atleiskite", en: "Excuse me / Forgive me (formal)", audioText: "Atleiskite", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l3_b2",
              type: "recognise_mcq",
              title: "Choose the right phrase",
              prompt: { text: "You bump into someone lightly and want to apologise." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: true },
                { id: "b", text: "Taip", isCorrect: false },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
            },
            {
              id: "s1m1l3_b3",
              type: "recognise_mcq",
              title: "Choose the right phrase",
              prompt: { text: "You need someone to repeat what they said." },
              options: [
                { id: "a", text: "Prašau dar kartą", isCorrect: true },
                { id: "b", text: "Labas vakaras", isCorrect: false },
                { id: "c", text: "Ne", isCorrect: false },
              ],
            },
            {
              id: "s1m1l3_b3b",
              type: "recognise_mcq",
              title: "Choose the right phrase",
              prompt: { text: "You want to formally excuse yourself — more polite than usual." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: false },
                { id: "b", text: "Atleiskite", isCorrect: true },
                { id: "c", text: "Prašau", isCorrect: false },
              ],
              feedback: { correct: "Atleiskite is the more formal version — used when you want to be especially polite or respectful." },
            },
            {
              id: "s1m1l3_b4",
              type: "build_phrase",
              title: "Build the phrase",
              prompt: { text: "One more time, please" },
              tokens: [
                { id: "t3", text: "kartą", correctIndex: 2 },
                { id: "t1", text: "Prašau", correctIndex: 0 },
                { id: "t2", text: "dar", correctIndex: 1 },
              ],
              answerText: "Prašau dar kartą",
            },
            {
              id: "s1m1l3_b5",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Atsiprašau", audioText: "Atsiprašau" },
              options: [
                { id: "a", text: "Thank you", isCorrect: false },
                { id: "b", text: "Sorry / Excuse me", isCorrect: true },
                { id: "c", text: "Please / Here you go", isCorrect: false },
              ],
            },
            {
              id: "s1m1l3_b5b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Atleiskite", audioText: "Atleiskite" },
              options: [
                { id: "a", text: "One more time please", isCorrect: false },
                { id: "b", text: "Sorry / Excuse me (casual)", isCorrect: false },
                { id: "c", text: "Excuse me / Forgive me (formal)", isCorrect: true },
              ],
            },
            {
              id: "s1m1l3_b6",
              type: "best_response",
              title: "Use the right phrase",
              prompt: { text: "You want to get someone's attention politely on the street." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: true },
                { id: "b", text: "Iki", isCorrect: false },
                { id: "c", text: "Ne", isCorrect: false },
              ],
              feedback: { correct: "Atsiprašau works both as 'excuse me' to get attention and 'sorry' to apologise." },
            },
            {
              id: "s1m1l3_b7",
              type: "best_response",
              title: "Use the right phrase",
              prompt: { text: "Someone speaks too quickly and you didn't catch it." },
              options: [
                { id: "a", text: "Prašau dar kartą", isCorrect: true },
                { id: "b", text: "Ačiū labai", isCorrect: false },
                { id: "c", text: "Labas rytas", isCorrect: false },
              ],
              feedback: { correct: "Prašau dar kartą — one more time please. A phrase you'll use constantly as a learner." },
            },
          ],
        },

        // ── Lesson 4 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_4",
          code: "1.1.4",
          title: "Polite Mini Exchanges",
          purpose: "Move from isolated words to short realistic exchanges.",
          supportLevel: "medium",
          newLanguageLoad: "very_low",
          notes: {
            pattern: "This lesson is about chaining phrases together — real conversations are just short chains.",
            usage: [
              "Kaip sekasi? — How are you? (casual, very common)",
              "Gerai, ačiū — Good, thank you (the standard reply)",
              "Puiku — Great (a more upbeat reply)",
            ],
          },
          blocks: [
            {
              id: "s1m1l4_b0",
              type: "learn",
              title: "How are you?",
              items: [
                { id: "ks1", lt: "Kaip sekasi?", en: "How are you?", audioText: "Kaip sekasi", saveable: true, core: true },
                { id: "ks2", lt: "Gerai, ačiū", en: "Good, thank you", audioText: "Gerai, ačiū", saveable: true, core: true },
                { id: "ks3", lt: "Puiku", en: "Great", audioText: "Puiku", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l4_b0b",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Kaip sekasi?", audioText: "Kaip sekasi" },
              options: [
                { id: "a", text: "What would you like?", isCorrect: false },
                { id: "b", text: "How are you?", isCorrect: true },
                { id: "c", text: "Where are you going?", isCorrect: false },
              ],
              feedback: { correct: "Kaip sekasi? — you'll hear this constantly. It's casual and warm." },
            },
            {
              id: "s1m1l4_b0c",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone asks: Kaip sekasi?", audioText: "Kaip sekasi" },
              options: [
                { id: "a", text: "Norėčiau kavos, prašau", isCorrect: false },
                { id: "b", text: "Gerai, ačiū", isCorrect: true },
                { id: "c", text: "Atsiprašau", isCorrect: false },
              ],
              feedback: { correct: "Gerai, ačiū — good, thank you. Simple, natural, and expected." },
            },
            {
              id: "s1m1l4_b0d",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "Someone asks Kaip sekasi? — reply out loud",
              targetText: "Gerai, ačiū",
              audioText: "Gerai, ačiū",
            },
            {
              id: "s1m1l4_b0e",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Puiku", audioText: "Puiku" },
              options: [
                { id: "a", text: "Good, thank you", isCorrect: false },
                { id: "b", text: "How are you?", isCorrect: false },
                { id: "c", text: "Great", isCorrect: true },
              ],
            },
            {
              id: "s1m1l4_b0f",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone asks Kaip sekasi? and things are going well." },
              options: [
                { id: "a", text: "Ne, ačiū", isCorrect: false },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Puiku", isCorrect: true },
              ],
              feedback: { correct: "Puiku — great! A more upbeat reply than Gerai, ačiū when things are going well." },
            },
            {
              id: "s1m1l4_b1",
              type: "best_response",
              title: "Choose the correct response",
              prompt: { text: "Someone greets you with Labas as you walk in.", audioText: "Labas" },
              options: [
                { id: "a", text: "Labas!", isCorrect: true },
                { id: "b", text: "Viso gero", isCorrect: false },
                { id: "c", text: "Ne", isCorrect: false },
              ],
              feedback: { correct: "Match the greeting — Labas to Labas." },
            },
            {
              id: "s1m1l4_b2",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone helps you and hands something over saying Prašau.", audioText: "Prašau" },
              options: [
                { id: "a", text: "Ačiū", isCorrect: true },
                { id: "b", text: "Iki", isCorrect: false },
                { id: "c", text: "Labas rytas", isCorrect: false },
              ],
              feedback: { correct: "Prašau here means 'here you go' — Ačiū is the natural reply." },
            },
            {
              id: "s1m1l4_b3",
              type: "speak_self_check",
              title: "Say the response",
              prompt: "Someone says Labas to you — reply out loud",
              targetText: "Labas",
              audioText: "Labas",
            },
            {
              id: "s1m1l4_b4",
              type: "speak_self_check",
              title: "Say the response",
              prompt: "Someone hands you your coffee and says Prašau — reply out loud",
              targetText: "Ačiū",
              audioText: "Ačiū",
            },
            {
              id: "s1m1l4_b5",
              type: "scenario_chain",
              title: "Conversation",
              description: "You're at a hotel reception. The receptionist checks you in.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Laba diena!",
                  audioText: "Laba diena",
                  options: [
                    { id: "a", text: "Laba diena!", isCorrect: true },
                    { id: "b", text: "Ne", isCorrect: false },
                    { id: "c", text: "Ačiū", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Kaip sekasi?",
                  audioText: "Kaip sekasi",
                  options: [
                    { id: "a", text: "Atsiprašau", isCorrect: false },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Gerai, ačiū", isCorrect: true },
                  ],
                },
                {
                  id: "step_3",
                  actor: "other",
                  text: "Prašau.",
                  audioText: "Prašau",
                  options: [
                    { id: "a", text: "Ačiū!", isCorrect: true },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Atsiprašau", isCorrect: false },
                  ],
                },
                {
                  id: "step_4",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Iki!", isCorrect: true },
                    { id: "b", text: "Taip", isCorrect: false },
                    { id: "c", text: "Prašau dar kartą", isCorrect: false },
                  ],
                },
              ],
            },
          ],
        },

        // ── Checkpoint ────────────────────────────────────────────────────────
        // No verbatim repeats from lessons. Every block uses a new framing,
        // new situation, or reversed prompt so the user has to actually recall
        // rather than recognise something they just saw.
        {
          id: "section_1_module_1_checkpoint",
          code: "1.1.C",
          title: "Checkpoint",
          purpose: "Check you can recall and use Module 1.1 language without support.",
          supportLevel: "none",
          newLanguageLoad: "none",
          isCheckpoint: true,
          blocks: [
            // Greetings — time-of-day reasoning (not just matching a sound)
            {
              id: "s1m1c_b1",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "It's 9am. You walk into a shop. What do you say?" },
              options: [
                { id: "a", text: "Labas vakaras", isCorrect: false },
                { id: "b", text: "Labas rytas", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
              feedback: { correct: "Labas rytas — good morning. Time-appropriate and natural." },
            },
            // Farewell — choose the right register
            {
              id: "s1m1c_b2",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "You're leaving a formal meeting. What's the right farewell?" },
              options: [
                { id: "a", text: "Iki", isCorrect: false },
                { id: "b", text: "Labas", isCorrect: false },
                { id: "c", text: "Viso gero", isCorrect: true },
              ],
              feedback: { correct: "Viso gero is more formal. Iki is casual — save it for friends." },
            },
            // Polite decline — new framing
            {
              id: "s1m1c_b3",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "A waiter offers you dessert and you don't want any." },
              options: [
                { id: "a", text: "Taip, prašau", isCorrect: false },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Ne, ačiū", isCorrect: true },
              ],
              feedback: { correct: "Ne, ačiū — polite, clear, and natural in any service situation." },
            },
            // Listen — Prašau dar kartą (new context: heard in the wild)
            {
              id: "s1m1c_b4",
              type: "listen_mcq",
              title: "Listen and identify",
              prompt: { text: "Prašau dar kartą", audioText: "Prašau dar kartą" },
              options: [
                { id: "a", text: "Here you go", isCorrect: false },
                { id: "b", text: "One more time, please", isCorrect: true },
                { id: "c", text: "You're welcome", isCorrect: false },
              ],
            },
            // Formal vs informal — Atleiskite vs Atsiprašau
            {
              id: "s1m1c_b5",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "You need to interrupt an older person politely to ask for directions." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: false },
                { id: "b", text: "Atleiskite", isCorrect: true },
                { id: "c", text: "Prašau dar kartą", isCorrect: false },
              ],
              feedback: { correct: "Atleiskite signals more respect — the right choice with someone older or in a formal context." },
            },
            // Build phrase — Labas vakaras this time (not Labas rytas)
            {
              id: "s1m1c_b6",
              type: "build_phrase",
              title: "Build the phrase",
              prompt: { text: "Good evening" },
              tokens: [
                { id: "t2", text: "vakaras", correctIndex: 1 },
                { id: "t3", text: "rytas", isDistractor: true },
                { id: "t1", text: "Labas", correctIndex: 0 },
              ],
              answerText: "Labas vakaras",
            },
            // Speak — Atsiprašau (different prompt from the lesson)
            {
              id: "s1m1c_b7",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "You've just bumped into someone — say sorry",
              targetText: "Atsiprašau",
              audioText: "Atsiprašau",
            },
            // Listen — Ačiū labai in a new option set
            {
              id: "s1m1c_b8",
              type: "listen_mcq",
              title: "Listen and identify",
              prompt: { text: "Ačiū labai", audioText: "Ačiū labai" },
              options: [
                { id: "a", text: "No thank you", isCorrect: false },
                { id: "b", text: "You're welcome", isCorrect: false },
                { id: "c", text: "Thank you very much", isCorrect: true },
              ],
            },
            // Scenario — café order but in reverse: user is the server
            // Tests whether they can produce the right response even when
            // the role is flipped
            {
              id: "s1m1c_b9",
              type: "scenario_chain",
              title: "Conversation",
              description: "You're meeting a Lithuanian colleague for the first time at a café.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Laba diena!",
                  audioText: "Laba diena",
                  options: [
                    { id: "a", text: "Viso gero!", isCorrect: false },
                    { id: "b", text: "Laba diena!", isCorrect: true },
                    { id: "c", text: "Atsiprašau", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Kaip sekasi?",
                  audioText: "Kaip sekasi",
                  options: [
                    { id: "a", text: "Ne, ačiū", isCorrect: false },
                    { id: "b", text: "Prašau dar kartą", isCorrect: false },
                    { id: "c", text: "Gerai, ačiū", isCorrect: true },
                  ],
                },
                {
                  id: "step_3",
                  actor: "other",
                  text: "Prašau.",
                  audioText: "Prašau",
                  options: [
                    { id: "a", text: "Ne, ačiū", isCorrect: false },
                    { id: "b", text: "Ačiū labai!", isCorrect: true },
                    { id: "c", text: "Atsiprašau", isCorrect: false },
                  ],
                },
                {
                  id: "step_4",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Taip, prašau", isCorrect: false },
                    { id: "b", text: "Labas rytas", isCorrect: false },
                    { id: "c", text: "Iki!", isCorrect: true },
                  ],
                },
              ],
            },
            // Final block — match pairs covering all vocabulary from Module 1.1
            // 17 pairs, 5 per page = 4 pages (last page has 2)
            {
              id: "s1m1c_b10",
              type: "word_match",
              title: "Match the pairs",
              pairs: [
                { id: "m1",  lt: "Labas",                   en: "Hello (casual)",             audioText: "Labas" },
                { id: "m2",  lt: "Laba diena",               en: "Good day / Hello (formal)",  audioText: "Laba diena" },
                { id: "m3",  lt: "Labas rytas",              en: "Good morning",               audioText: "Labas rytas" },
                { id: "m4",  lt: "Labas vakaras",            en: "Good evening",               audioText: "Labas vakaras" },
                { id: "m5",  lt: "Viso gero",                en: "Goodbye (take care)",        audioText: "Viso gero" },
                { id: "m6",  lt: "Iki",                      en: "Bye (casual)",               audioText: "Iki" },
                { id: "m7",  lt: "Taip",                     en: "Yes",                        audioText: "Taip" },
                { id: "m8",  lt: "Ne",                       en: "No",                         audioText: "Ne" },
                { id: "m9",  lt: "Prašau",                   en: "Please / Here you go",       audioText: "Prašau" },
                { id: "m10", lt: "Ačiū",                     en: "Thank you",                  audioText: "Ačiū" },
                { id: "m11", lt: "Ačiū labai",               en: "Thank you very much",        audioText: "Ačiū labai" },
                { id: "m12", lt: "Taip, prašau",             en: "Yes please",                 audioText: "Taip, prašau" },
                { id: "m13", lt: "Ne, ačiū",                 en: "No thank you",               audioText: "Ne, ačiū" },
                { id: "m14", lt: "Norėčiau kavos, prašau",   en: "I'd like a coffee, please",  audioText: "Norėčiau kavos, prašau" },
                { id: "m15", lt: "Atsiprašau",               en: "Sorry / Excuse me",          audioText: "Atsiprašau" },
                { id: "m16", lt: "Prašau dar kartą",         en: "One more time, please",      audioText: "Prašau dar kartą" },
                { id: "m17", lt: "Atleiskite",               en: "Excuse me (formal)",         audioText: "Atleiskite" },
                { id: "m18", lt: "Kaip sekasi?",             en: "How are you?",               audioText: "Kaip sekasi" },
                { id: "m19", lt: "Gerai, ačiū",              en: "Good, thank you",            audioText: "Gerai, ačiū" },
                { id: "m20", lt: "Puiku",                    en: "Great",                      audioText: "Puiku" },
              ],
            },
          ],
        },
      ],
    },
    // ── Module 1.2 ───────────────────────────────────────────────────────────
// Module 1.2 — Who I Am
{
  id: "module_1_2",
  code: "1.2",
  title: "Who I Am",
  status: "active",
  lessonCount: 5,
  lessons: [

    // ── Lesson 1 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_1",
      code: "1.2.1",
      title: "I Am / My Name Is",
      purpose: "Teach the learner to identify themselves clearly.",
      supportLevel: "high",
      newLanguageLoad: "medium",
      notes: {
        pattern: "Both Aš esu and Mano vardas work for introducing yourself. Mano vardas is often the cleaner starter — it is direct and natural.",
        usage: [
          "Aš esu Davidas — I am Davidas",
          "Mano vardas Barbora — My name is Barbora",
          "Koks tavo vardas? — What is your name? (informal)",
          "Koks jūsų vardas? — What is your name? (formal/polite)",
        ],
      },
      blocks: [
        {
          id: "s1m2l1_b1",
          type: "learn",
          title: "Who you are",
          items: [
            { id: "wi1", lt: "Aš esu", en: "I am", audioText: "Aš esu", saveable: true, core: true },
            { id: "wi2", lt: "Mano vardas", en: "My name is", audioText: "Mano vardas", saveable: true, core: true },
            { id: "wi3", lt: "Aš esu Davidas", en: "I am Davidas", audioText: "Aš esu Davidas", saveable: true, core: true },
            { id: "wi4", lt: "Mano vardas Barbora", en: "My name is Barbora", audioText: "Mano vardas Barbora", saveable: true, core: true },
            { id: "wi5", lt: "Koks tavo vardas?", en: "What is your name? (informal)", audioText: "Koks tavo vardas", saveable: true, core: true },
            { id: "wi6", lt: "Koks jūsų vardas?", en: "What is your name? (formal)", audioText: "Koks jūsų vardas", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l1_b2",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Mano vardas", audioText: "Mano vardas" },
          options: [
            { id: "a", text: "What is your name?", isCorrect: false },
            { id: "b", text: "I am", isCorrect: false },
            { id: "c", text: "My name is", isCorrect: true },
          ],
        },
        {
          id: "s1m2l1_b3",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Aš esu Davidas", audioText: "Aš esu Davidas" },
          options: [
            { id: "a", text: "My name is Davidas", isCorrect: false },
            { id: "b", text: "I am Davidas", isCorrect: true },
            { id: "c", text: "What is your name?", isCorrect: false },
          ],
        },
        {
          id: "s1m2l1_b4",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Koks jūsų vardas?", audioText: "Koks jūsų vardas" },
          options: [
            { id: "a", text: "What is your name? (informal)", isCorrect: false },
            { id: "b", text: "My name is", isCorrect: false },
            { id: "c", text: "What is your name? (formal)", isCorrect: true },
          ],
          feedback: { correct: "Jūsų is the polite/formal form — use it with strangers and people you don't know well." },
        },
        {
          id: "s1m2l1_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "My name is Barbora" },
          tokens: [
            { id: "t3", text: "Barbora", correctIndex: 2 },
            { id: "t1", text: "Mano", correctIndex: 0 },
            { id: "t4", text: "Aš", isDistractor: true },
            { id: "t2", text: "vardas", correctIndex: 1 },
          ],
          answerText: "Mano vardas Barbora",
        },
        {
          id: "s1m2l1_b6",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Say your name in Lithuanian — start with Mano vardas",
          targetText: "Mano vardas",
          audioText: "Mano vardas",
        },
        {
          id: "s1m2l1_b7",
          type: "scenario_chain",
          title: "Conversation",
          description: "You're at a language exchange event. Someone comes over to introduce themselves.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Aš esu Tomas.",
              audioText: "Laba diena. Aš esu Tomas",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Laba diena! Mano vardas Davidas.", isCorrect: true },
                { id: "c", text: "Ne, ačiū", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Koks tavo vardas?",
              audioText: "Koks tavo vardas",
              options: [
                { id: "a", text: "Mano vardas Davidas.", isCorrect: true },
                { id: "b", text: "Labas rytas", isCorrect: false },
                { id: "c", text: "Atsiprašau", isCorrect: false },
              ],
            },
          ],
        },
      ],
    },

    // ── Lesson 2 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_2",
      code: "1.2.2",
      title: "I'm From…",
      purpose: "Add origin and location identity.",
      supportLevel: "high",
      newLanguageLoad: "medium",
      notes: {
        pattern: "Iš means 'from'. Place names change their ending when used with iš — notice Škotija becomes Škotijos. You don't need to explain this yet, just notice the pattern.",
        usage: [
          "Aš esu iš Škotijos — I am from Scotland",
          "Aš esu iš Anglijos — I am from England",
          "Aš esu iš Lietuvos — I am from Lithuania",
          "Iš kur jūs esate? — Where are you from? (formal)",
          "Iš kur tu esi? — Where are you from? (informal)",
        ],
      },
      blocks: [
        {
          id: "s1m2l2_b1",
          type: "learn",
          title: "Where you're from",
          items: [
            { id: "fr1", lt: "Aš esu iš Škotijos", en: "I am from Scotland", audioText: "Aš esu iš Škotijos", saveable: true, core: true },
            { id: "fr2", lt: "Aš esu iš Anglijos", en: "I am from England", audioText: "Aš esu iš Anglijos", saveable: true, core: true },
            { id: "fr3", lt: "Aš esu iš Lietuvos", en: "I am from Lithuania", audioText: "Aš esu iš Lietuvos", saveable: true, core: true },
            { id: "fr4", lt: "Aš esu iš Ukrainos", en: "I am from Ukraine", audioText: "Aš esu iš Ukrainos", saveable: true, core: true },
            { id: "fr5", lt: "Aš esu iš Amerikos", en: "I am from America", audioText: "Aš esu iš Amerikos", saveable: true, core: true },
            { id: "fr6", lt: "Iš kur jūs esate?", en: "Where are you from? (formal)", audioText: "Iš kur jūs esate", saveable: true, core: true },
            { id: "fr7", lt: "Iš kur tu esi?", en: "Where are you from? (informal)", audioText: "Iš kur tu esi", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l2_b2",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Aš esu iš Lietuvos", audioText: "Aš esu iš Lietuvos" },
          options: [
            { id: "a", text: "I am from Scotland", isCorrect: false },
            { id: "b", text: "I am from Lithuania", isCorrect: true },
            { id: "c", text: "I am from Ukraine", isCorrect: false },
          ],
        },
        {
          id: "s1m2l2_b3",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Iš kur jūs esate?", audioText: "Iš kur jūs esate" },
          options: [
            { id: "a", text: "Where are you from? (informal)", isCorrect: false },
            { id: "b", text: "What is your name?", isCorrect: false },
            { id: "c", text: "Where are you from? (formal)", isCorrect: true },
          ],
          feedback: { correct: "Jūs esate is the formal/polite form — use it with strangers and older people." },
        },
        {
          id: "s1m2l2_b4",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Iš kur tu esi?", audioText: "Iš kur tu esi" },
          options: [
            { id: "a", text: "Where are you from? (formal)", isCorrect: false },
            { id: "b", text: "Where are you going?", isCorrect: false },
            { id: "c", text: "Where are you from? (informal)", isCorrect: true },
          ],
        },
        {
          id: "s1m2l2_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "I am from Scotland" },
          tokens: [
            { id: "t4", text: "Škotijos", correctIndex: 3 },
            { id: "t1", text: "Aš", correctIndex: 0 },
            { id: "t5", text: "Lietuvos", isDistractor: true },
            { id: "t3", text: "iš", correctIndex: 2 },
            { id: "t2", text: "esu", correctIndex: 1 },
          ],
          answerText: "Aš esu iš Škotijos",
        },
        {
          id: "s1m2l2_b6",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Say where you are from in Lithuanian",
          targetText: "Aš esu iš Škotijos",
          audioText: "Aš esu iš Škotijos",
        },
        {
          id: "s1m2l2_b7",
          type: "scenario_chain",
          title: "Conversation",
          description: "You meet someone at a local community event in Vilnius.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Iš kur jūs esate?",
              audioText: "Laba diena. Iš kur jūs esate",
              options: [
                { id: "a", text: "Aš esu iš Škotijos.", isCorrect: true },
                { id: "b", text: "Mano vardas Barbora.", isCorrect: false },
                { id: "c", text: "Ne, ačiū.", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Aš esu iš Lietuvos.",
              audioText: "Aš esu iš Lietuvos",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Labas rytas!", isCorrect: false },
                { id: "c", text: "Malonu susipažinti!", isCorrect: true },
              ],
            },
          ],
        },
      ],
    },

    // ── Lesson 3 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_3",
      code: "1.2.3",
      title: "Nice to Meet You",
      purpose: "Complete the first-meeting exchange.",
      supportLevel: "medium",
      newLanguageLoad: "low",
      notes: {
        pattern: "Malonu susipažinti is a fixed phrase — learn it as one chunk, not word by word. Man irgi is the natural reply.",
        usage: [
          "Malonu susipažinti — Nice to meet you",
          "Man irgi — Me too / Likewise",
          "Labai malonu — Very pleased to meet you (slightly warmer)",
        ],
      },
      blocks: [
        {
          id: "s1m2l3_b1",
          type: "learn",
          title: "First meeting phrases",
          items: [
            { id: "nm1", lt: "Malonu susipažinti", en: "Nice to meet you", audioText: "Malonu susipažinti", saveable: true, core: true },
            { id: "nm2", lt: "Man irgi", en: "Me too / Likewise", audioText: "Man irgi", saveable: true, core: true },
            { id: "nm3", lt: "Labai malonu", en: "Very pleased to meet you", audioText: "Labai malonu", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l3_b2",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Malonu susipažinti", audioText: "Malonu susipažinti" },
          options: [
            { id: "a", text: "Goodbye", isCorrect: false },
            { id: "b", text: "Nice to meet you", isCorrect: true },
            { id: "c", text: "How are you?", isCorrect: false },
          ],
        },
        {
          id: "s1m2l3_b3",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "Tomas says: Malonu susipažinti.", audioText: "Malonu susipažinti" },
          options: [
            { id: "a", text: "Viso gero", isCorrect: false },
            { id: "b", text: "Man irgi", isCorrect: true },
            { id: "c", text: "Atsiprašau", isCorrect: false },
          ],
          feedback: { correct: "Man irgi — me too / likewise. The natural response to Malonu susipažinti." },
        },
        {
          id: "s1m2l3_b4",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Labai malonu", audioText: "Labai malonu" },
          options: [
            { id: "a", text: "Nice to meet you", isCorrect: false },
            { id: "b", text: "Me too", isCorrect: false },
            { id: "c", text: "Very pleased to meet you", isCorrect: true },
          ],
          feedback: { correct: "Labai means 'very' — so labai malonu is a slightly warmer version of nice to meet you." },
        },
        {
          id: "s1m2l3_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "Nice to meet you" },
          tokens: [
            { id: "t2", text: "susipažinti", correctIndex: 1 },
            { id: "t1", text: "Malonu", correctIndex: 0 },
            { id: "t3", text: "irgi", isDistractor: true },
          ],
          answerText: "Malonu susipažinti",
        },
        {
          id: "s1m2l3_b6",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Someone introduces themselves — respond politely",
          targetText: "Malonu susipažinti",
          audioText: "Malonu susipažinti",
        },
        {
          id: "s1m2l3_b7",
          type: "scenario_chain",
          title: "Conversation",
          description: "You're introduced to a new colleague, Ona, at the office.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Aš esu Ona.",
              audioText: "Laba diena. Aš esu Ona",
              options: [
                { id: "a", text: "Iki!", isCorrect: false },
                { id: "b", text: "Laba diena! Mano vardas Davidas. Malonu susipažinti.", isCorrect: true },
                { id: "c", text: "Ne, ačiū", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Malonu susipažinti!",
              audioText: "Malonu susipažinti",
              options: [
                { id: "a", text: "Man irgi!", isCorrect: true },
                { id: "b", text: "Prašau dar kartą", isCorrect: false },
                { id: "c", text: "Atsiprašau", isCorrect: false },
              ],
            },
          ],
        },
      ],
    },

    // ── Lesson 4 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_4",
      code: "1.2.4",
      title: "This Is…",
      purpose: "Introduce another person in a simple social setting.",
      supportLevel: "medium",
      newLanguageLoad: "medium",
      notes: {
        pattern: "Čia yra introduces a person or thing. Jis yra means he is, ji yra means she is. Lithuanian marks gender — draugas is a male friend, draugė is a female friend.",
        usage: [
          "Čia Barbora — This is Barbora (shorter, natural in speech)",
          "Čia yra Tomas — This is Tomas (slightly fuller form)",
          "Jis yra mano draugas — He is my friend",
          "Ji yra mano draugė — She is my friend",
          "Jis yra iš Lenkijos — He is from Poland",
          "Ji yra iš Vokietijos — She is from Germany",
        ],
      },
      blocks: [
        {
          id: "s1m2l4_b1",
          type: "learn",
          title: "Introducing others",
          items: [
            { id: "ti1", lt: "Čia Barbora", en: "This is Barbora", audioText: "Čia Barbora", saveable: true, core: true },
            { id: "ti2", lt: "Čia yra Tomas", en: "This is Tomas", audioText: "Čia yra Tomas", saveable: true, core: true },
            { id: "ti3", lt: "Jis yra mano draugas", en: "He is my friend", audioText: "Jis yra mano draugas", saveable: true, core: true },
            { id: "ti4", lt: "Ji yra mano draugė", en: "She is my friend", audioText: "Ji yra mano draugė", saveable: true, core: true },
            { id: "ti5", lt: "Jis yra iš Lenkijos", en: "He is from Poland", audioText: "Jis yra iš Lenkijos", saveable: true, core: true },
            { id: "ti6", lt: "Ji yra iš Vokietijos", en: "She is from Germany", audioText: "Ji yra iš Vokietijos", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l4_b2",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Čia yra Tomas", audioText: "Čia yra Tomas" },
          options: [
            { id: "a", text: "He is my friend", isCorrect: false },
            { id: "b", text: "This is Tomas", isCorrect: true },
            { id: "c", text: "She is my friend", isCorrect: false },
          ],
        },
        {
          id: "s1m2l4_b3",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Ji yra mano draugė", audioText: "Ji yra mano draugė" },
          options: [
            { id: "a", text: "He is my friend", isCorrect: false },
            { id: "b", text: "This is my friend", isCorrect: false },
            { id: "c", text: "She is my friend", isCorrect: true },
          ],
          feedback: { correct: "Ji means she — draugė is the female form of friend. Draugas is the male form." },
        },
        {
          id: "s1m2l4_b4",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "You want to introduce your female friend Barbora to someone." },
          options: [
            { id: "a", text: "Jis yra mano draugas", isCorrect: false },
            { id: "b", text: "Čia Barbora. Ji yra mano draugė.", isCorrect: true },
            { id: "c", text: "Aš esu iš Škotijos", isCorrect: false },
          ],
          feedback: { correct: "Čia Barbora introduces her, and ji yra mano draugė tells them she's your friend." },
        },
        {
          id: "s1m2l4_b5",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Jis yra iš Lenkijos", audioText: "Jis yra iš Lenkijos" },
          options: [
            { id: "a", text: "She is from Poland", isCorrect: false },
            { id: "b", text: "He is from Lithuania", isCorrect: false },
            { id: "c", text: "He is from Poland", isCorrect: true },
          ],
        },
        {
          id: "s1m2l4_b6",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "She is my friend" },
          tokens: [
            { id: "t1", text: "Ji", correctIndex: 0 },
            { id: "t2", text: "yra", correctIndex: 1 },
            { id: "t5", text: "draugas", isDistractor: true },
            { id: "t3", text: "mano", correctIndex: 2 },
            { id: "t4", text: "draugė", correctIndex: 3 },
          ],
          answerText: "Ji yra mano draugė",
        },
        {
          id: "s1m2l4_b7",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Introduce a female friend — say 'She is my friend'",
          targetText: "Ji yra mano draugė",
          audioText: "Ji yra mano draugė",
        },
        {
          id: "s1m2l4_b8",
          type: "scenario_chain",
          title: "Conversation",
          description: "You run into an old colleague, Tomas, and introduce your friend Barbora.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Labas! Kaip sekasi?",
              audioText: "Labas. Kaip sekasi",
              options: [
                { id: "a", text: "Gerai, ačiū! Čia Barbora. Ji yra mano draugė.", isCorrect: true },
                { id: "b", text: "Ne, ačiū", isCorrect: false },
                { id: "c", text: "Prašau dar kartą", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Malonu susipažinti, Barbora!",
              audioText: "Malonu susipažinti, Barbora",
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: false },
                { id: "b", text: "Ji yra iš Škotijos.", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
            },
          ],
        },
      ],
    },

    // ── Checkpoint ────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_checkpoint",
      code: "1.2.C",
      title: "Checkpoint",
      purpose: "Check you can recall and use Module 1.2 language without support.",
      supportLevel: "none",
      newLanguageLoad: "none",
      isCheckpoint: true,
      blocks: [
        {
          id: "s1m2c_b1",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "You meet someone at a formal event. They ask: Koks jūsų vardas?" },
          options: [
            { id: "a", text: "Aš esu iš Škotijos", isCorrect: false },
            { id: "b", text: "Mano vardas Davidas.", isCorrect: true },
            { id: "c", text: "Malonu susipažinti", isCorrect: false },
          ],
          feedback: { correct: "Mano vardas is the direct and natural reply to a name question." },
        },
        {
          id: "s1m2c_b2",
          type: "listen_mcq",
          title: "Listen and identify",
          prompt: { text: "Aš esu iš Ukrainos", audioText: "Aš esu iš Ukrainos" },
          options: [
            { id: "a", text: "I am from Lithuania", isCorrect: false },
            { id: "b", text: "I am from America", isCorrect: false },
            { id: "c", text: "I am from Ukraine", isCorrect: true },
          ],
        },
        {
          id: "s1m2c_b3",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "You want to introduce your male colleague Tomas to someone." },
          options: [
            { id: "a", text: "Ji yra mano draugė", isCorrect: false },
            { id: "b", text: "Čia Tomas. Jis yra mano draugas.", isCorrect: true },
            { id: "c", text: "Koks tavo vardas?", isCorrect: false },
          ],
          feedback: { correct: "Čia Tomas introduces him, jis yra mano draugas confirms he is your friend — and draugas is the male form." },
        },
        {
          id: "s1m2c_b4",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Jis yra iš Vokietijos", audioText: "Jis yra iš Vokietijos" },
          options: [
            { id: "a", text: "She is from Germany", isCorrect: false },
            { id: "b", text: "He is from Poland", isCorrect: false },
            { id: "c", text: "He is from Germany", isCorrect: true },
          ],
        },
        {
          id: "s1m2c_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "Where are you from? (formal)" },
          tokens: [
            { id: "t1", text: "Iš", correctIndex: 0 },
            { id: "t2", text: "kur", correctIndex: 1 },
            { id: "t3", text: "jūsų", isDistractor: true },
            { id: "t4", text: "jūs", correctIndex: 2 },
            { id: "t5", text: "esate?", correctIndex: 3 },
          ],
          answerText: "Iš kur jūs esate?",
        },
        {
          id: "s1m2c_b6",
          type: "listen_mcq",
          title: "Listen and identify",
          prompt: { text: "Malonu susipažinti", audioText: "Malonu susipažinti" },
          options: [
            { id: "a", text: "How are you?", isCorrect: false },
            { id: "b", text: "Nice to meet you", isCorrect: true },
            { id: "c", text: "Me too", isCorrect: false },
          ],
        },
        {
          id: "s1m2c_b7",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Say where you are from",
          targetText: "Aš esu iš Škotijos",
          audioText: "Aš esu iš Škotijos",
        },
        {
          id: "s1m2c_b8",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "Ona says Malonu susipažinti. What do you say back?" },
          options: [
            { id: "a", text: "Man irgi.", isCorrect: true },
            { id: "b", text: "Gerai, ačiū", isCorrect: false },
            { id: "c", text: "Iš kur tu esi?", isCorrect: false },
          ],
          feedback: { correct: "Man irgi — me too. The natural reply to Malonu susipažinti." },
        },
        {
          id: "s1m2c_b9",
          type: "scenario_chain",
          title: "Conversation",
          description: "You're at a welcome event in Vilnius. A local, Tomas, comes over to say hello.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Aš esu Tomas. Koks jūsų vardas?",
              audioText: "Laba diena. Aš esu Tomas. Koks jūsų vardas",
              options: [
                { id: "a", text: "Ne, ačiū", isCorrect: false },
                { id: "b", text: "Laba diena! Mano vardas Davidas.", isCorrect: true },
                { id: "c", text: "Prašau dar kartą", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Iš kur jūs esate?",
              audioText: "Iš kur jūs esate",
              options: [
                { id: "a", text: "Aš esu iš Škotijos.", isCorrect: true },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Gerai, ačiū", isCorrect: false },
              ],
            },
            {
              id: "step_3",
              actor: "other",
              text: "Malonu susipažinti!",
              audioText: "Malonu susipažinti",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Man irgi!", isCorrect: true },
                { id: "c", text: "Iki", isCorrect: false },
              ],
            },
          ],
        },
        {
          id: "s1m2c_b10",
          type: "word_match",
          title: "Match the pairs",
          pairs: [
            { id: "wm1",  lt: "Aš esu",                    en: "I am",                             audioText: "Aš esu" },
            { id: "wm2",  lt: "Mano vardas",                en: "My name is",                       audioText: "Mano vardas" },
            { id: "wm3",  lt: "Koks tavo vardas?",          en: "What is your name? (informal)",    audioText: "Koks tavo vardas" },
            { id: "wm4",  lt: "Koks jūsų vardas?",          en: "What is your name? (formal)",      audioText: "Koks jūsų vardas" },
            { id: "wm5",  lt: "Aš esu iš Škotijos",         en: "I am from Scotland",               audioText: "Aš esu iš Škotijos" },
            { id: "wm6",  lt: "Aš esu iš Lietuvos",         en: "I am from Lithuania",              audioText: "Aš esu iš Lietuvos" },
            { id: "wm7",  lt: "Aš esu iš Ukrainos",         en: "I am from Ukraine",                audioText: "Aš esu iš Ukrainos" },
            { id: "wm8",  lt: "Aš esu iš Amerikos",         en: "I am from America",                audioText: "Aš esu iš Amerikos" },
            { id: "wm9",  lt: "Iš kur jūs esate?",          en: "Where are you from? (formal)",     audioText: "Iš kur jūs esate" },
            { id: "wm10", lt: "Iš kur tu esi?",             en: "Where are you from? (informal)",   audioText: "Iš kur tu esi" },
            { id: "wm11", lt: "Malonu susipažinti",          en: "Nice to meet you",                 audioText: "Malonu susipažinti" },
            { id: "wm12", lt: "Man irgi",                   en: "Me too / Likewise",                audioText: "Man irgi" },
            { id: "wm13", lt: "Labai malonu",               en: "Very pleased to meet you",         audioText: "Labai malonu" },
            { id: "wm14", lt: "Čia Barbora",                en: "This is Barbora",                  audioText: "Čia Barbora" },
            { id: "wm15", lt: "Jis yra mano draugas",       en: "He is my friend",                  audioText: "Jis yra mano draugas" },
            { id: "wm16", lt: "Ji yra mano draugė",         en: "She is my friend",                 audioText: "Ji yra mano draugė" },
            { id: "wm17", lt: "Jis yra iš Lenkijos",        en: "He is from Poland",                audioText: "Jis yra iš Lenkijos" },
            { id: "wm18", lt: "Ji yra iš Vokietijos",       en: "She is from Germany",              audioText: "Ji yra iš Vokietijos" },
            { id: "wm19", lt: "Aš esu iš Anglijos",         en: "I am from England",                audioText: "Aš esu iš Anglijos" },
            { id: "wm20", lt: "Čia yra Tomas",              en: "This is Tomas",                    audioText: "Čia yra Tomas" },
          ],
        },
      ],
    },
  ],
},

  ],
};

export default section1;
