// src/content/learning/section1/module_1_4.js
// Module 1.4 — Help and Contact
// Factory function — receives profile for personalised scenario options

export default function createModule_1_4(profile = {}) {
  const {
    userNameSafe = "Davidas",
    userFromPhrase = "Aš esu iš Škotijos",
    userFromCountryLabelEn = "Scotland",
  } = profile;

  return {
    id: "module_1_4",
    code: "1.4",
    title: "Help and Contact",
    status: "active",
    lessonCount: 5,
    lessons: [

      // ── Lesson 1 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_4_lesson_1",
        code: "1.4.1",
        title: "Can You Help Me?",
        purpose: "Teach direct help-seeking language. Properly introduces 'Ar galiu jums padėti?' which appeared with helper text in Module 1.3 scenarios.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Ar galite…? is the polite plural/formal frame for asking someone to do something. You'll use it constantly.",
          usage: [
            "Ar galite man padėti? — Can you help me? (polite, to a stranger or staff)",
            "Padėkite man, prašau — Help me, please (more direct but still polite)",
            "Man reikia pagalbos — I need help (stating the need)",
            "Ar galiu jums padėti? — Can I help you? (what staff will say to you — now you know what it means)",
          ],
        },
        blocks: [
          {
            id: "s1m4l1_b1",
            type: "learn",
            title: "Asking for help",
            items: [
              { id: "h1", lt: "Ar galite man padėti?", en: "Can you help me?", audioText: "Ar galite man padėti", saveable: true, core: true },
              { id: "h2", lt: "Padėkite man, prašau", en: "Help me, please", audioText: "Padėkite man, prašau", saveable: true, core: true },
              { id: "h3", lt: "Man reikia pagalbos", en: "I need help", audioText: "Man reikia pagalbos", saveable: true, core: true },
              { id: "h4", lt: "Ar galiu jums padėti?", en: "Can I help you?", audioText: "Ar galiu jums padėti", saveable: true, core: true },
              { id: "h5", lt: "Pagalba", en: "Help", audioText: "Pagalba", saveable: true, core: false },
            ],
          },
          {
            id: "s1m4l1_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar galite man padėti?", audioText: "Ar galite man padėti" },
            options: [
              { id: "a", text: "Can I help you?", isCorrect: false },
              { id: "b", text: "Can you help me?", isCorrect: true },
              { id: "c", text: "I need help", isCorrect: false },
            ],
          },
          {
            id: "s1m4l1_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Man reikia pagalbos", audioText: "Man reikia pagalbos" },
            options: [
              { id: "a", text: "Can you help me?", isCorrect: false },
              { id: "b", text: "Help me, please", isCorrect: false },
              { id: "c", text: "I need help", isCorrect: true },
            ],
          },
          {
            id: "s1m4l1_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar galiu jums padėti?", audioText: "Ar galiu jums padėti" },
            options: [
              { id: "a", text: "I need help", isCorrect: false },
              { id: "b", text: "Can I help you?", isCorrect: true },
              { id: "c", text: "Help me, please", isCorrect: false },
            ],
          },
          {
            id: "s1m4l1_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You've lost your wallet and need to get someone's attention." },
            options: [
              { id: "a", text: "Ačiū labai!", isCorrect: false },
              { id: "b", text: "Aš nesuprantu", isCorrect: false },
              { id: "c", text: "Atsiprašau, man reikia pagalbos!", isCorrect: true },
            ],
            feedback: { correct: "Atsiprašau to get attention, then man reikia pagalbos — exactly right." },
          },
          {
            id: "s1m4l1_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask someone if they can help you",
            targetText: "Ar galite man padėti?",
            audioText: "Ar galite man padėti",
          },
          {
            id: "s1m4l1_b7",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "I need help" },
            tokens: [
              { id: "t1", text: "Man", correctIndex: 0 },
              { id: "t2", text: "reikia", correctIndex: 1 },
              { id: "t3", text: "pagalbos", correctIndex: 2 },
              { id: "t4", text: "padėti", isDistractor: true },
            ],
            answerText: "Man reikia pagalbos",
          },
          {
  id: "s1m4l1_b8_v2",
  type: "scenario_v2",
  title: "When someone offers help",
  description: "You're checking a map on the street and genuinely need help. A passer-by notices and stops.",
  sceneIntro: "You're checking a map on the street and genuinely need help. A passer-by notices and stops.",
  location: "street",
  userRole: "learner",
  register: "polite_neutral",
  goal: "Recognise an offer of help and accept it clearly.",
  focus: ["Ar galiu jums padėti?", "Man reikia pagalbos"],
  participants: [
    {
      id: "local",
      label: "Passer-by",
      name: "Rasa",
      role: "passer-by",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_neutral",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Passer-by",
      speakerText: "Ar galiu jums padėti?",
      sceneDirection: "A passer-by notices you studying your map and stops to offer help.",
      learnerPrompt: "Accept the offer and say that you need help.",
      options: [
        {
          id: "a",
          text: "Taip, man reikia pagalbos.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "You need help and the passer-by has just offered it.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ačiū labai!",
          result: "wrong",
          feedback: "Thanking them is polite, but first accept the offer and say that you need help.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "local",
        speakerLabel: "Passer-by",
        speakerText: "Taip.",
        sceneDirection: "She stops and waits for you to explain what you need.",
      },
    },
  ],
},
        ],
      },

      // ── Lesson 2 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_4_lesson_2",
        code: "1.4.2",
        title: "Is It Here? Is It Over There?",
        purpose: "Turn the pointing language from Module 1.3 into clear location checks using čia for here and ten for there / over there.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Čia means here; ten means there. For places, anchoring the question physically is clearer than translating tai/ten as an abstract English this/that pair.",
          usage: [
            "Ar čia…? — Is it here? / Is this…? (the place you are at)",
            "Ar ten…? — Is it there / over there? / Is that…? (a place further away)",
            "Ar čia tualetas? — Is this the toilet?",
            "Ar ten restoranas? — Is that a restaurant over there?",
            "Ar ten parduotuvė? — Is that a shop over there?",
          ],
        },
        blocks: [
          {
            id: "s1m4l2_b1",
            type: "learn",
            title: "Checking a place",
            items: [
              { id: "c1", lt: "Ar čia…?", en: "Is it here? / Is this…?", audioText: "Ar čia", saveable: true, core: true },
              { id: "c2", lt: "Ar ten…?", en: "Is it over there? / Is that…?", audioText: "Ar ten", saveable: true, core: true },
              { id: "c3", lt: "Ar čia tualetas?", en: "Is this the toilet?", audioText: "Ar čia tualetas", saveable: true, core: true },
              { id: "c4", lt: "Ar ten restoranas?", en: "Is that a restaurant over there?", audioText: "Ar ten restoranas", saveable: true, core: true },
              { id: "c5", lt: "Restoranas", en: "Restaurant", audioText: "Restoranas", saveable: true, core: false },
              { id: "c6", lt: "Parduotuvė", en: "Shop / Store", audioText: "Parduotuvė", saveable: true, core: false },
            ],
          },
          {
            id: "s1m4l2_b2",
            type: "context_gap_select",
            title: "Here or over there?",
            prompt: "You are standing at a door and want to check whether this is the toilet.",
            sentence: "___ tualetas?",
            translation_en: "Is this the toilet?",
            options: [
              { id: "a", text: "Ar čia", isCorrect: true },
              { id: "b", text: "Ar ten", isCorrect: false },
              { id: "c", text: "Kur yra", isCorrect: false },
            ],
            explanation: "Čia means here. Use Ar čia…? when you are checking the place you are at.",
          },
          {
            id: "s1m4l2_b3",
            type: "context_gap_select",
            title: "Here or over there?",
            prompt: "You point to a building across the street and want to check whether it is the restaurant.",
            sentence: "___ restoranas?",
            translation_en: "Is that a restaurant over there?",
            options: [
              { id: "a", text: "Ar čia", isCorrect: false },
              { id: "b", text: "Ar ten", isCorrect: true },
              { id: "c", text: "Kur yra", isCorrect: false },
            ],
            explanation: "Ten means there. Use Ar ten…? for the building further away.",
          },
          {
            id: "s1m4l2_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You are standing beside a door and want to check whether this is the shop." },
            options: [
              { id: "a", text: "Ar ten parduotuvė?", isCorrect: false },
              { id: "b", text: "Ar čia parduotuvė?", isCorrect: true },
              { id: "c", text: "Kas ten?", isCorrect: false },
            ],
            feedback: { correct: "Ar čia parduotuvė? — you are checking the place right where you are standing." },
          },
          {
            id: "s1m4l2_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Point to a building across the street and ask if it is a restaurant",
            targetText: "Ar ten restoranas?",
            audioText: "Ar ten restoranas",
          },
          {
            id: "s1m4l2_b6",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Is that a shop over there?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "ten", correctIndex: 1 },
              { id: "t3", text: "parduotuvė?", correctIndex: 2 },
              { id: "t4", text: "čia", isDistractor: true },
            ],
            answerText: "Ar ten parduotuvė?",
          },
          {
  id: "s1m4l2_b7_v2",
  type: "scenario_v2",
  title: "Finding the right place",
  description: "You're comparing two nearby storefronts and want to check which one is the restaurant.",
  sceneIntro: "You're comparing two nearby storefronts and want to check which one is the restaurant.",
  location: "street",
  userRole: "learner",
  register: "polite_neutral",
  goal: "Use čia and ten to check a place based on where it is.",
  focus: ["Ar čia…?", "Ar ten…?"],
  participants: [
    {
      id: "local",
      label: "Local",
      name: "Rasa",
      role: "local resident",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_neutral",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Ar galiu jums padėti?",
      sceneDirection: "A local notices you looking between the doorway beside you and a building across the street.",
      learnerPrompt: "Ask whether the building across the street is the restaurant.",
      options: [
        {
          id: "a",
          text: "Taip. Ar ten restoranas?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ar čia tualetas?",
          result: "wrong",
          feedback: "You are asking about the building across the street, not the doorway beside you.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero!",
          result: "wrong",
          feedback: "The local has offered to help you find the place.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Ne, ten parduotuvė. Restoranas čia.",
      sceneDirection: "She points across the street to the shop, then to the doorway beside you.",
      learnerPrompt: "Acknowledge the help.",
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "She has just shown you the restaurant you were looking for.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ar ten restoranas?",
          result: "wrong",
          feedback: "She has already explained that the restaurant is here beside you.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "local",
        speakerLabel: "Local",
        speakerText: "Prašom.",
        sceneDirection: "She smiles and continues on her way.",
      },
    },
  ],
},
        ],
      },

      // ── Lesson 3 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_4_lesson_3",
        code: "1.4.3",
        title: "Where Is…?",
        purpose: "Introduce Kur yra…? as a reusable location question frame. Places kept tight — tualetas, stotis, autobusų stotelė. New nouns added naturally.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Kur yra…? is one of the most reusable frames in Lithuanian. Learn the full form first. In everyday speech you may also hear short questions without yra; recognise them, but you do not need to produce that variation yet.",
          usage: [
            "Kur yra tualetas? — Where is the toilet?",
            "Kur yra stotis? — Where is the station?",
            "Kur yra autobusų stotelė? — Where is the bus stop?",
            "Kur yra viešbutis? — Where is the hotel?",
            "Kur yra bankas? — Where is the bank?",
            "Ten — there",
            "Va ten — over there (more definite, often with pointing)",
            "Čia — Here",
          ],
        },
        blocks: [
          {
            id: "s1m4l3_b1",
            type: "learn",
            title: "Asking where things are",
            items: [
              { id: "w1", lt: "Kur yra tualetas?", en: "Where is the toilet?", audioText: "Kur yra tualetas", saveable: true, core: true },
              { id: "w2", lt: "Kur yra stotis?", en: "Where is the station?", audioText: "Kur yra stotis", saveable: true, core: true },
              { id: "w3", lt: "Kur yra autobusų stotelė?", en: "Where is the bus stop?", audioText: "Kur yra autobusų stotelė", saveable: true, core: true },
              { id: "w4", lt: "Kur yra viešbutis?", en: "Where is the hotel?", audioText: "Kur yra viešbutis", saveable: true, core: true },
              { id: "w5", lt: "Kur yra bankas?", en: "Where is the bank?", audioText: "Kur yra bankas", saveable: true, core: true },
              { id: "w6", lt: "Viešbutis", en: "Hotel", audioText: "Viešbutis", saveable: true, core: false },
              { id: "w7", lt: "Bankas", en: "Bank", audioText: "Bankas", saveable: true, core: false },
              { id: "w8", lt: "Ten", en: "There", audioText: "Ten", saveable: false, core: false },
              { id: "w9", lt: "Va ten", en: "Over there", audioText: "Va ten", saveable: false, core: false },
            ],
          },
          {
            id: "s1m4l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kur yra stotis?", audioText: "Kur yra stotis" },
            options: [
              { id: "a", text: "Where is the hotel?", isCorrect: false },
              { id: "b", text: "Where is the bus stop?", isCorrect: false },
              { id: "c", text: "Where is the station?", isCorrect: true },
            ],
          },
          {
            id: "s1m4l3_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kur yra autobusų stotelė?", audioText: "Kur yra autobusų stotelė" },
            options: [
              { id: "a", text: "Where is the station?", isCorrect: false },
              { id: "b", text: "Where is the bus stop?", isCorrect: true },
              { id: "c", text: "Where is the hotel?", isCorrect: false },
            ],
          },
          {
            id: "s1m4l3_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kur yra bankas?", audioText: "Kur yra bankas" },
            options: [
              { id: "a", text: "Where is the shop?", isCorrect: false },
              { id: "b", text: "Where is the restaurant?", isCorrect: false },
              { id: "c", text: "Where is the bank?", isCorrect: true },
            ],
          },
          {
            id: "s1m4l3_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask where the hotel is",
            targetText: "Kur yra viešbutis?",
            audioText: "Kur yra viešbutis",
          },
          {
            id: "s1m4l3_b6",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Where is the bank?" },
            tokens: [
              { id: "t1", text: "Kur", correctIndex: 0 },
              { id: "t2", text: "yra", correctIndex: 1 },
              { id: "t3", text: "bankas?", correctIndex: 2 },
              { id: "t4", text: "viešbutis?", isDistractor: true },
            ],
            answerText: "Kur yra bankas?",
          },
          {
  id: "s1m4l3_b7_v2",
  type: "scenario_v2",
  title: "Finding your hotel",
  description: "You've arrived near the station and need to find your hotel. A local notices you checking your map.",
  sceneIntro: "You've arrived near the station and need to find your hotel. A local notices you checking your map.",
  location: "street near the station",
  userRole: "guest",
  register: "polite_neutral",
  goal: "Ask where a place is and understand Va ten when someone points it out.",
  focus: ["Kur yra…?", "Va ten"],
  participants: [
    {
      id: "local",
      label: "Local",
      name: "Austėja",
      role: "local resident",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_neutral",
    },
  ],
  objects: [
    {
      id: "hotel",
      lt: "viešbutis",
      en: "hotel",
      gender: "masculine",
      number: "singular",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Ar galiu jums padėti?",
      sceneDirection: "A local notices you checking your map and stops.",
      learnerPrompt: "Say what you need to find.",
      options: [
        {
          id: "a",
          text: "Taip! Kur yra viešbutis?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "She has offered to help you find something.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ar galime pradėti?",
          result: "wrong",
          feedback: "That does not answer the offer of help.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Viešbutis — va ten.",
      sceneDirection: "She points across the street directly at the hotel entrance.",
      learnerPrompt: "If you understand, thank her. If you do not, use Nesuprantu.",
      help: {
        levels: [
          {
            sceneDirection: "She points more clearly at the hotel sign.",
            speakerText: "Viešbutis. Va ten.",
          },
          {
            sceneDirection: "She traces the word VIEŠBUTIS on the sign with her finger and points to the entrance.",
            speakerText: "Viešbutis.",
          },
          {
            speakerText: "Hotel. Over there.",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "She has just shown you where the hotel is.",
          progresses: false,
        },
        {
          id: "c",
          text: "Man reikia pagalbos.",
          result: "wrong",
          feedback: "You already asked for help. Thank her if the answer is now clear, or use Nesuprantu if it is not.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "local",
        speakerLabel: "Local",
        speakerText: "Prašom. Viso gero!",
        sceneDirection: "She smiles and heads on her way.",
      },
    },
  ],
},
        ],
      },

      // ── Lesson 4 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_4_lesson_4",
        code: "1.4.4",
        title: "Can I…? / Can We…?",
        purpose: "Introduce Ar galiu? and Ar galime? as reusable permission and coordination frames.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Ar galiu…? (can I?) and Ar galime…? (can we?) are hugely reusable frames. Slot in different actions and you have dozens of useful questions.",
          usage: [
            "Ar galiu? — Can I?",
            "Ar galime? — Can we?",
            "Ar galiu čia atsisėsti? — Can I sit here?",
            "Ar galime pradėti? — Can we start?",
            "Ar galiu čia sustoti? — Can I stop here?",
            "Taip, prašau — Yes, please (the reply you'll hear)",
          ],
        },
        blocks: [
          {
            id: "s1m4l4_b1",
            type: "learn",
            title: "Can I…? Can we…?",
            items: [
              { id: "g1", lt: "Ar galiu?", en: "Can I?", audioText: "Ar galiu", saveable: true, core: true },
              { id: "g2", lt: "Ar galime?", en: "Can we?", audioText: "Ar galime", saveable: true, core: true },
              { id: "g3", lt: "Ar galiu čia atsisėsti?", en: "Can I sit here?", audioText: "Ar galiu čia atsisėsti", saveable: true, core: true },
              { id: "g4", lt: "Ar galime pradėti?", en: "Can we start?", audioText: "Ar galime pradėti", saveable: true, core: true },
              { id: "g5", lt: "Ar galiu čia sustoti?", en: "Can I stop here?", audioText: "Ar galiu čia sustoti", saveable: true, core: false },
            ],
          },
          {
            id: "s1m4l4_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar galiu čia atsisėsti?", audioText: "Ar galiu čia atsisėsti" },
            options: [
              { id: "a", text: "Can we sit here?", isCorrect: false },
              { id: "b", text: "Is there a seat here?", isCorrect: false },
              { id: "c", text: "Can I sit here?", isCorrect: true },
            ],
          },
          {
            id: "s1m4l4_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar galime pradėti?", audioText: "Ar galime pradėti" },
            options: [
              { id: "a", text: "Can I start?", isCorrect: false },
              { id: "b", text: "Can we start?", isCorrect: true },
              { id: "c", text: "Can we stop?", isCorrect: false },
            ],
          },
          {
            id: "s1m4l4_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're at a café and spot an empty chair at a table where someone is sitting." },
            options: [
              { id: "a", text: "Ar galime pradėti?", isCorrect: false },
              { id: "b", text: "Ar galiu čia atsisėsti?", isCorrect: true },
              { id: "c", text: "Man reikia pagalbos", isCorrect: false },
            ],
            feedback: { correct: "Ar galiu čia atsisėsti? — polite and exactly right in this situation." },
          },
          {
            id: "s1m4l4_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask if you can sit here",
            targetText: "Ar galiu čia atsisėsti?",
            audioText: "Ar galiu čia atsisėsti",
          },
          {
            id: "s1m4l4_b6",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Can we start?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "galime", correctIndex: 1 },
              { id: "t3", text: "pradėti?", correctIndex: 2 },
              { id: "t4", text: "galiu", isDistractor: true, repairHint: "galiu means “I can”. The prompt asks “Can we start?”, so the “I” form doesn’t match the subject." },
            ],
            answerText: "Ar galime pradėti?",
          },
          {
  id: "s1m4l4_b7_v2",
  type: "scenario_v2",
  title: "Finding a seat",
  description: "You're at a busy café and ask a server whether you can sit at an empty table.",
  sceneIntro: "You're at a busy café and ask a server whether you can sit at an empty table.",
  location: "café",
  userRole: "customer",
  register: "polite_service",
  goal: "Use Ar galiu…? naturally, then handle a simple follow-up offer.",
  focus: ["Ar galiu…?", "Taip, prašau"],
  participants: [
    {
      id: "server",
      label: "Server",
      name: "Rasa",
      role: "server",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  objects: [
    {
      id: "coffee",
      lt: "kava",
      en: "coffee",
      gender: "feminine",
      number: "singular",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Ar galiu jums padėti?",
      sceneDirection: "A server notices you looking for somewhere to sit.",
      learnerPrompt: "Ask whether you can sit at the empty table.",
      options: [
        {
          id: "a",
          text: "Taip. Ar galiu čia atsisėsti?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ar galime pradėti?",
          result: "wrong",
          feedback: "You are looking for a seat, not asking to start something.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero!",
          result: "wrong",
          feedback: "The server has offered to help you.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Taip, prašau.",
      sceneDirection: "She gestures to the empty chair.",
      learnerPrompt: "Acknowledge the help.",
      options: [
        {
          id: "a",
          text: "Ačiū!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "She has just confirmed that you can sit here.",
          progresses: false,
        },
        {
          id: "c",
          text: "Kur yra stotis?",
          result: "wrong",
          feedback: "You have just asked about the seat.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_3",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Ar norite kavos?",
      sceneDirection: "As you sit down, the server picks up the coffee pot and gestures towards your cup.",
      learnerPrompt: "Respond to the offer. If you do not understand it, use Nesuprantu.",
      help: {
        levels: [
          {
            sceneDirection: "She lifts the coffee pot and points to your cup.",
            speakerText: "Kavos?",
          },
          {
            sceneDirection: "She mimics pouring coffee into your cup.",
            speakerText: "Kava?",
          },
          {
            speakerText: "Coffee?",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Taip, prašau!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ne, ačiū.",
          result: "acceptable",
          feedback: "Also completely natural if you do not want coffee.",
          progresses: true,
        },
        {
          id: "c",
          text: "Kur yra tualetas?",
          result: "wrong",
          feedback: "The server is offering coffee, not asking about the toilet.",
          progresses: false,
        },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 5 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_4_lesson_5",
        code: "1.4.5",
        title: "Tu and Jūs — A Pattern to Notice",
        purpose: "Make the familiar tu/jūs distinction explicit through recognition and application rather than re-teaching known phrases.",
        supportLevel: "high",
        newLanguageLoad: "none",
        notes: {
          pattern: "You have already seen both forms in earlier phrases. Tu is informal — typically family, friends and people you are on familiar terms with. Jūs is polite/formal or plural. With an unfamiliar adult, jūs is the safe starting point until the relationship becomes more informal.",
          usage: [
            "tu — you (one person, informal)",
            "jūs — you (polite, or more than one person)",
            "Koks tavo vardas? — What's your name? (tu form — casual)",
            "Koks jūsų vardas? — What's your name? (jūs form — polite)",
            "Ar tu kalbi angliškai? — Do you speak English? (casual)",
            "Ar jūs kalbate angliškai? — Do you speak English? (polite — what you've been learning)",
          ],
        },
        blocks: [
          {
            id: "s1m4l5_b2",
            type: "recognise_mcq",
            title: "Tu or jūs?",
            prompt: { text: "You're asking a shop assistant for help. Which form should you use?" },
            options: [
              { id: "a", text: "Tu", isCorrect: false },
              { id: "b", text: "Jūs", isCorrect: true },
              { id: "c", text: "Either — it doesn't matter", isCorrect: false },
            ],
            feedback: { correct: "Jūs — the safe polite form with anyone you don't know well." },
          },
          {
            id: "s1m4l5_b3",
            type: "recognise_mcq",
            title: "Tu or jūs?",
            prompt: { text: "You're chatting with a close Lithuanian friend. Which form would they normally use with you?" },
            options: [
              { id: "a", text: "Jūs", isCorrect: false },
              { id: "b", text: "Tu", isCorrect: true },
              { id: "c", text: "Either — it doesn't matter", isCorrect: false },
            ],
            feedback: { correct: "Tu — the normal informal form with a close friend." },
          },
          {
            id: "s1m4l5_b4",
            type: "best_response",
            title: "Which is the polite version?",
            prompt: { text: "You want to ask someone's name politely — which do you use?" },
            options: [
              { id: "a", text: "Koks tavo vardas?", isCorrect: false },
              { id: "b", text: "Koks jūsų vardas?", isCorrect: true },
              { id: "c", text: "Kas tavo vardas?", isCorrect: false },
            ],
            feedback: { correct: "Koks jūsų vardas? — jūs form, right for any formal or unfamiliar situation." },
          },
          {
            id: "s1m4l5_b6_v2",
            type: "conversation_turn_fill",
            scene_label: "Same question, different relationship",
            prompt: "A close friend uses tavo. At reception, choose the form that fits the unfamiliar receptionist.",
            lines: [
              { speaker: "Friend", text: "Labas! Koks tavo vardas?", audioText: "Labas! Koks tavo vardas?", hasGap: false },
              { speaker: "Receptionist", text: "Laba diena. Koks ___ vardas?", hasGap: true },
            ],
            options: [
              { id: "a", text: "tavo", isCorrect: false },
              { id: "b", text: "jūsų", isCorrect: true },
              { id: "c", text: "mano", isCorrect: false },
            ],
            explanation: "A close friend can use tavo. With an unfamiliar receptionist, the polite jūsų form fits.",
            translation_en: "Friend: Hi! What's your name? — Receptionist: Good day. What's your name?",
          },
        ],
      },

      // ── Checkpoint ──────────────────────────────────────────────────────────
      {
        id: "section_1_module_4_checkpoint",
        code: "1.4.C",
        title: "Checkpoint",
        purpose: "Check you can use Module 1.4 language in real situations without support.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          // Situational choice — help-seeking
          {
            id: "s1m4c_b1",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You drop your bag in the street and things fall everywhere. A passer-by stops and catches your attention." },
            options: [
              { id: "a", text: "Ar galiu čia atsisėsti?", isCorrect: false },
              { id: "b", text: "Man reikia pagalbos!", isCorrect: true },
              { id: "c", text: "Kur yra stotis?", isCorrect: false },
            ],
            feedback: { correct: "Man reikia pagalbos — direct and clear for an urgent situation." },
          },
          // Listen — Ar galite man padėti?
          {
            id: "s1m4c_b2",
            type: "listen_mcq",
            title: "Listen and identify",
            prompt: { text: "Ar galite man padėti?", audioText: "Ar galite man padėti" },
            options: [
              { id: "a", text: "Can I help you?", isCorrect: false },
              { id: "b", text: "I need help", isCorrect: false },
              { id: "c", text: "Can you help me?", isCorrect: true },
            ],
          },
          // Ar tai / Ar ten distinction
          {
            id: "s1m4c_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You can see a building across the street and want to check if it's the station." },
            options: [
              { id: "a", text: "Ar čia stotis?", isCorrect: false },
              { id: "b", text: "Kas tai?", isCorrect: false },
              { id: "c", text: "Ar ten stotis?", isCorrect: true },
            ],
            feedback: { correct: "Ar ten…? for the building across the street. Ar čia…? is for the place you are at." },
          },
          // Build — Kur yra viešbutis
          {
            id: "s1m4c_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Where is the hotel?" },
            tokens: [
              { id: "t1", text: "Kur", correctIndex: 0 },
              { id: "t2", text: "yra", correctIndex: 1 },
              { id: "t3", text: "viešbutis?", correctIndex: 2 },
              { id: "t4", text: "bankas?", isDistractor: true },
            ],
            answerText: "Kur yra viešbutis?",
          },
          // Tu vs Jūs — formal context
          {
            id: "s1m4c_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're asking an unfamiliar adult on the street for directions. Which form do you start with?" },
            options: [
              { id: "a", text: "Tu", isCorrect: false },
              { id: "b", text: "Jūs", isCorrect: true },
              { id: "c", text: "Either — it doesn't matter", isCorrect: false },
            ],
            feedback: { correct: "Jūs — the safe polite starting point with an unfamiliar adult." },
          },
          // Speak
          {
            id: "s1m4c_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask where the bus stop is",
            targetText: "Kur yra autobusų stotelė?",
            audioText: "Kur yra autobusų stotelė",
          },
          // Scenario — full help interaction
          {
  id: "s1m4c_b7_v2",
  type: "scenario_v2",
  title: "Finding the bank",
  description: "You need to find the bank. A local notices you looking around and offers help.",
  sceneIntro: "You need to find the bank. A local notices you looking around and offers help.",
  location: "street",
  userRole: "learner",
  register: "polite_neutral",
  goal: "Combine an offer of help, a Kur yra…? question, Va ten, repair help and a natural closing.",
  focus: ["Ar galiu jums padėti?", "Kur yra…?", "Va ten", "Nesuprantu"],
  participants: [
    {
      id: "local",
      label: "Local",
      name: "Rasa",
      role: "local resident",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_neutral",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Laba diena! Ar galiu jums padėti?",
      sceneDirection: "A local notices you looking around and stops.",
      learnerPrompt: "Accept the help and ask where the bank is.",
      options: [
        {
          id: "a",
          text: "Taip! Kur yra bankas?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "You need help and the local has just offered it.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ar galime pradėti?",
          result: "wrong",
          feedback: "That does not fit the situation.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Bankas — va ten.",
      sceneDirection: "She points across the street towards a bank sign.",
      learnerPrompt: "If you understand, thank her. If you do not, use Nesuprantu.",
      help: {
        levels: [
          {
            sceneDirection: "She points directly at the bank sign.",
            speakerText: "Bankas. Va ten.",
          },
          {
            sceneDirection: "She traces the word BANKAS on the sign with her finger.",
            speakerText: "Bankas.",
          },
          {
            speakerText: "Bank. Over there.",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "She has just shown you where the bank is.",
          progresses: false,
        },
        {
          id: "c",
          text: "Man reikia pagalbos.",
          result: "wrong",
          feedback: "You already have help. Thank her if the answer is clear, or use Nesuprantu if it is not.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_3",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Prašom. Viso gero!",
      sceneDirection: "She smiles and starts to leave.",
      learnerPrompt: "Close the exchange.",
      options: [
        {
          id: "a",
          text: "Viso gero!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Taip, prašau.",
          result: "wrong",
          feedback: "The conversation is ending.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ar čia bankas?",
          result: "wrong",
          feedback: "She has already pointed out the bank across the street.",
          progresses: false,
        },
      ],
    },
  ],
},
          // Word match — 20 pairs covering all of module 1.4
          {
            id: "s1m4c_b8",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Ar galite man padėti?",    en: "Can you help me?",         audioText: "Ar galite man padėti" },
              { id: "m2",  lt: "Padėkite man, prašau",     en: "Help me, please",           audioText: "Padėkite man, prašau" },
              { id: "m3",  lt: "Man reikia pagalbos",       en: "I need help",               audioText: "Man reikia pagalbos" },
              { id: "m4",  lt: "Ar galiu jums padėti?",    en: "Can I help you?",           audioText: "Ar galiu jums padėti" },
              { id: "m5",  lt: "Va ten",                   en: "Over there",                audioText: "Va ten" },
              { id: "m6",  lt: "Ar čia…?",                 en: "Is it here? / Is this…?",   audioText: "Ar čia" },
              { id: "m7",  lt: "Ar ten…?",                 en: "Is it over there? / Is that…?", audioText: "Ar ten" },
              { id: "m8",  lt: "Restoranas",               en: "Restaurant",                audioText: "Restoranas" },
              { id: "m9",  lt: "Parduotuvė",               en: "Shop / Store",              audioText: "Parduotuvė" },
              { id: "m10", lt: "Kur yra tualetas?",        en: "Where is the toilet?",      audioText: "Kur yra tualetas" },
              { id: "m11", lt: "Kur yra stotis?",          en: "Where is the station?",     audioText: "Kur yra stotis" },
              { id: "m12", lt: "Kur yra autobusų stotelė?", en: "Where is the bus stop?",   audioText: "Kur yra autobusų stotelė" },
              { id: "m13", lt: "Viešbutis",                en: "Hotel",                     audioText: "Viešbutis" },
              { id: "m14", lt: "Bankas",                   en: "Bank",                      audioText: "Bankas" },
              { id: "m15", lt: "Ar galiu?",                en: "Can I?",                    audioText: "Ar galiu" },
              { id: "m16", lt: "Ar galime?",               en: "Can we?",                   audioText: "Ar galime" },
              { id: "m17", lt: "Ar galiu čia atsisėsti?",  en: "Can I sit here?",           audioText: "Ar galiu čia atsisėsti" },
              { id: "m18", lt: "Ar galime pradėti?",       en: "Can we start?",             audioText: "Ar galime pradėti" },
              { id: "m19", lt: "Tu",                       en: "You (informal)",            audioText: "Tu" },
              { id: "m20", lt: "Jūs",                      en: "You (polite / plural)",     audioText: "Jūs" },
            ],
          },
        ],
      },

    ],
  };
}
