// src/content/learning/section1/module_1_2.js
// Module 1.2 — Who I Am

const module_1_2 = {
  id: "module_1_2",
  code: "1.2",
  title: "Who I Am",
  status: "active",
  lessonCount: 5,
  lessons: [

    // ── Lesson 1 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_1",
      code: "1.2.1",
      title: "I Am / My Name Is",
      purpose: "Teach the learner to identify themselves clearly.",
      supportLevel: "high",
      newLanguageLoad: "medium",
      notes: {
        pattern: "Both Aš esu and Mano vardas work for introducing yourself. Mano vardas is often the cleaner starter — it is direct and natural.",
        usage: [
          "Aš esu [vardas] — I am [name]",
          "Mano vardas [vardas] — My name is [name]",
          "Koks tavo vardas? — What is your name? (informal)",
          "Koks jūsų vardas? — What is your name? (formal/polite)",
        ],
      },
      blocks: [
        {
          id: "s1m2l1_b1",
          type: "learn",
          title: "Who you are",
          items: [
            { id: "wi1", lt: "Aš esu", en: "I am", audioText: "Aš esu", saveable: true, core: true },
            { id: "wi2", lt: "Mano vardas", en: "My name is", audioText: "Mano vardas", saveable: true, core: true },
            { id: "wi5", lt: "Koks tavo vardas?", en: "What is your name? (informal)", audioText: "Koks tavo vardas", saveable: true, core: true },
            { id: "wi6", lt: "Koks jūsų vardas?", en: "What is your name? (formal)", audioText: "Koks jūsų vardas", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l1_b2",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Mano vardas", audioText: "Mano vardas" },
          options: [
            { id: "a", text: "What is your name?", isCorrect: false },
            { id: "b", text: "I am", isCorrect: false },
            { id: "c", text: "My name is", isCorrect: true },
          ],
        },
        {
          id: "s1m2l1_b3",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Aš esu", audioText: "Aš esu" },
          options: [
            { id: "a", text: "My name is", isCorrect: false },
            { id: "b", text: "I am", isCorrect: true },
            { id: "c", text: "What is your name?", isCorrect: false },
          ],
        },
        {
          id: "s1m2l1_b4",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Koks jūsų vardas?", audioText: "Koks jūsų vardas" },
          options: [
            { id: "a", text: "What is your name? (informal)", isCorrect: false },
            { id: "b", text: "My name is", isCorrect: false },
            { id: "c", text: "What is your name? (formal)", isCorrect: true },
          ],
          feedback: { correct: "Jūsų is the polite/formal form — use it with strangers and people you don't know well." },
        },
        {
          id: "s1m2l1_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "What is your name? (informal)" },
          tokens: [
            { id: "t1", text: "Koks", correctIndex: 0 },
            { id: "t2", text: "tavo", correctIndex: 1 },
            { id: "t3", text: "vardas?", correctIndex: 2 },
            { id: "t4", text: "jūsų", isDistractor: true },
          ],
          answerText: "Koks tavo vardas?",
        },
        {
          id: "s1m2l1_b6",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Say your name in Lithuanian — start with Mano vardas",
          targetText: "Mano vardas",
          audioText: "Mano vardas",
        },
        {
          id: "s1m2l1_b7",
          type: "scenario_chain",
          title: "Conversation",
          description: "You're at a language event. A stranger introduces themselves — respond with a greeting and your name.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Koks jūsų vardas?",
              audioText: "Laba diena. Koks jūsų vardas",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Laba diena! Mano vardas Davidas.", isCorrect: true },
                { id: "c", text: "Ne, ačiū", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Aš esu Rokas. Kaip sekasi?",
              audioText: "Aš esu Rokas. Kaip sekasi",
              options: [
                { id: "a", text: "Labas rytas", isCorrect: false },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Gerai, ačiū!", isCorrect: true },
              ],
            },
          ],
        },
      ],
    },

    // ── Lesson 2 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_2",
      code: "1.2.2",
      title: "I'm From…",
      purpose: "Add origin and location identity.",
      supportLevel: "high",
      newLanguageLoad: "medium",
      notes: {
        pattern: "Iš means 'from'. Place names change their ending when used with iš — notice Škotija becomes Škotijos. You don't need to explain this yet, just notice the pattern.",
        usage: [
          "Aš esu iš Škotijos — I am from Scotland",
          "Aš esu iš Anglijos — I am from England",
          "Aš esu iš Lietuvos — I am from Lithuania",
          "Iš kur jūs esate? — Where are you from? (formal)",
          "Iš kur tu esi? — Where are you from? (informal)",
        ],
      },
      blocks: [
        {
          id: "s1m2l2_b1",
          type: "learn",
          title: "Where you're from",
          items: [
            { id: "fr0", lt: "Aš esu iš…", en: "I am from…", audioText: "Aš esu iš", saveable: false, core: true },
            { id: "fr1", lt: "Škotija", en: "Scotland", audioText: "Škotija", saveable: true, core: true },
            { id: "fr2", lt: "Anglija", en: "England", audioText: "Anglija", saveable: true, core: true },
            { id: "fr3", lt: "Lietuva", en: "Lithuania", audioText: "Lietuva", saveable: true, core: true },
            { id: "fr4", lt: "Ukraina", en: "Ukraine", audioText: "Ukraina", saveable: true, core: true },
            { id: "fr5", lt: "Amerika", en: "America", audioText: "Amerika", saveable: true, core: true },
            { id: "fr8", lt: "Vokietija", en: "Germany", audioText: "Vokietija", saveable: true, core: true },
            { id: "fr9", lt: "Prancūzija", en: "France", audioText: "Prancūzija", saveable: true, core: true },
            { id: "fr6", lt: "Iš kur jūs esate?", en: "Where are you from? (formal)", audioText: "Iš kur jūs esate", saveable: true, core: true },
            { id: "fr7", lt: "Iš kur tu esi?", en: "Where are you from? (informal)", audioText: "Iš kur tu esi", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l2_b2",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Aš esu iš Lietuvos", audioText: "Aš esu iš Lietuvos" },
          options: [
            { id: "a", text: "I am from Scotland", isCorrect: false },
            { id: "b", text: "I am from Lithuania", isCorrect: true },
            { id: "c", text: "I am from Ukraine", isCorrect: false },
          ],
        },
        {
          id: "s1m2l2_b3",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Iš kur jūs esate?", audioText: "Iš kur jūs esate" },
          options: [
            { id: "a", text: "Where are you from? (informal)", isCorrect: false },
            { id: "b", text: "What is your name?", isCorrect: false },
            { id: "c", text: "Where are you from? (formal)", isCorrect: true },
          ],
          feedback: { correct: "Jūs esate is the formal/polite form — use it with strangers and older people." },
        },
        {
          id: "s1m2l2_b4",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Iš kur tu esi?", audioText: "Iš kur tu esi" },
          options: [
            { id: "a", text: "Where are you from? (formal)", isCorrect: false },
            { id: "b", text: "Where are you going?", isCorrect: false },
            { id: "c", text: "Where are you from? (informal)", isCorrect: true },
          ],
        },
        {
          id: "s1m2l2_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "I am from Scotland" },
          tokens: [
            { id: "t4", text: "Škotijos", correctIndex: 3 },
            { id: "t1", text: "Aš", correctIndex: 0 },
            { id: "t5", text: "Vokietijos", isDistractor: true },
            { id: "t3", text: "iš", correctIndex: 2 },
            { id: "t2", text: "esu", correctIndex: 1 },
          ],
          answerText: "Aš esu iš Škotijos",
        },
        {
          id: "s1m2l2_b6",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Say where you are from in Lithuanian",
          targetText: "Aš esu iš Škotijos",
          audioText: "Aš esu iš Škotijos",
        },
        {
          id: "s1m2l2_b7",
          type: "scenario_chain",
          title: "Conversation",
          description: "You meet someone at a local community event in Vilnius.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Iš kur jūs esate?",
              audioText: "Laba diena. Iš kur jūs esate",
              options: [
                { id: "a", text: "Aš esu iš Škotijos.", isCorrect: true },
                { id: "b", text: "Mano vardas Davidas.", isCorrect: false },
                { id: "c", text: "Ne, ačiū.", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Aš esu iš Lietuvos.",
              audioText: "Aš esu iš Lietuvos",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Gerai, ačiū!", isCorrect: false },
                { id: "c", text: "Puiku! Aš esu iš Škotijos.", isCorrect: true },
              ],
            },
          ],
        },
      ],
    },

    // ── Lesson 3 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_3",
      code: "1.2.3",
      title: "Nice to Meet You",
      purpose: "Complete the first-meeting exchange.",
      supportLevel: "medium",
      newLanguageLoad: "low",
      notes: {
        pattern: "Malonu susipažinti is a fixed phrase — learn it as one chunk, not word by word. Man irgi is the natural reply.",
        usage: [
          "Malonu susipažinti — Nice to meet you",
          "Man irgi — Me too / Likewise",
          "Labai malonu — Very pleased to meet you (slightly warmer)",
        ],
      },
      blocks: [
        {
          id: "s1m2l3_b1",
          type: "learn",
          title: "First meeting phrases",
          items: [
            { id: "nm1", lt: "Malonu susipažinti", en: "Nice to meet you", audioText: "Malonu susipažinti", saveable: true, core: true },
            { id: "nm2", lt: "Man irgi", en: "Me too / Likewise", audioText: "Man irgi", saveable: true, core: true },
            { id: "nm3", lt: "Labai malonu", en: "Very pleased to meet you", audioText: "Labai malonu", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l3_b2",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Malonu susipažinti", audioText: "Malonu susipažinti" },
          options: [
            { id: "a", text: "Goodbye", isCorrect: false },
            { id: "b", text: "Nice to meet you", isCorrect: true },
            { id: "c", text: "How are you?", isCorrect: false },
          ],
        },
        {
          id: "s1m2l3_b3",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "Rokas says: Malonu susipažinti.", audioText: "Malonu susipažinti" },
          options: [
            { id: "a", text: "Viso gero", isCorrect: false },
            { id: "b", text: "Man irgi", isCorrect: true },
            { id: "c", text: "Atsiprašau", isCorrect: false },
          ],
          feedback: { correct: "Man irgi — me too / likewise. The natural response to Malonu susipažinti." },
        },
        {
          id: "s1m2l3_b4",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Labai malonu", audioText: "Labai malonu" },
          options: [
            { id: "a", text: "Nice to meet you", isCorrect: false },
            { id: "b", text: "Me too", isCorrect: false },
            { id: "c", text: "Very pleased to meet you", isCorrect: true },
          ],
          feedback: { correct: "Labai means 'very' — so labai malonu is a slightly warmer version of nice to meet you." },
        },
        {
          id: "s1m2l3_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "Nice to meet you" },
          tokens: [
            { id: "t2", text: "susipažinti", correctIndex: 1 },
            { id: "t1", text: "Malonu", correctIndex: 0 },
            { id: "t3", text: "irgi", isDistractor: true },
          ],
          answerText: "Malonu susipažinti",
        },
        {
          id: "s1m2l3_b6",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Someone introduces themselves — respond politely",
          targetText: "Malonu susipažinti",
          audioText: "Malonu susipažinti",
        },
        {
          id: "s1m2l3_b7",
          type: "scenario_chain",
          title: "Conversation",
          description: "A colleague introduces you to Ona. Say hello, give your name, and respond to her greeting.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Aš esu Ona.",
              audioText: "Laba diena. Aš esu Ona",
              options: [
                { id: "a", text: "Iki!", isCorrect: false },
                { id: "b", text: "Laba diena! Mano vardas Davidas.", isCorrect: true },
                { id: "c", text: "Ne, ačiū", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Malonu susipažinti, Davidas!",
              audioText: "Malonu susipažinti",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Man irgi!", isCorrect: true },
                { id: "c", text: "Atsiprašau", isCorrect: false },
              ],
            },
          ],
        },
      ],
    },

    // ── Lesson 4 ──────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_lesson_4",
      code: "1.2.4",
      title: "This Is…",
      purpose: "Introduce another person in a simple social setting.",
      supportLevel: "medium",
      newLanguageLoad: "medium",
      notes: {
        pattern: "Čia yra introduces a person or thing. Jis yra means he is, ji yra means she is. Lithuanian marks gender — draugas is a male friend, draugė is a female friend.",
        usage: [
          "Čia Barbora — This is Barbora (shorter, natural in speech)",
          "Čia yra Rokas — This is Rokas (slightly fuller form)",
          "Jis yra mano draugas — He is my friend",
          "Ji yra mano draugė — She is my friend",
          "Jis yra iš Lenkijos — He is from Poland",
          "Ji yra iš Vokietijos — She is from Germany",
        ],
      },
      blocks: [
        {
          id: "s1m2l4_b1",
          type: "learn",
          title: "Introducing others",
          items: [
            { id: "ti1", lt: "Čia…", en: "This is…", audioText: "Čia", saveable: false, core: true },
            { id: "ti2", lt: "Čia yra…", en: "This is… (fuller form)", audioText: "Čia yra", saveable: false, core: true },
            { id: "ti3", lt: "Jis yra mano draugas", en: "He is my friend", audioText: "Jis yra mano draugas", saveable: true, core: true },
            { id: "ti4", lt: "Ji yra mano draugė", en: "She is my friend", audioText: "Ji yra mano draugė", saveable: true, core: true },
            { id: "ti5", lt: "Jis yra iš Lenkijos", en: "He is from Poland", audioText: "Jis yra iš Lenkijos", saveable: true, core: true },
            { id: "ti6", lt: "Ji yra iš Vokietijos", en: "She is from Germany", audioText: "Ji yra iš Vokietijos", saveable: true, core: true },
          ],
        },
        {
          id: "s1m2l4_b2",
          type: "listen_mcq",
          title: "Listen and choose",
          prompt: { text: "Čia yra Rokas", audioText: "Čia yra Rokas" },
          options: [
            { id: "a", text: "He is my friend", isCorrect: false },
            { id: "b", text: "This is Rokas", isCorrect: true },
            { id: "c", text: "She is my friend", isCorrect: false },
          ],
        },
        {
          id: "s1m2l4_b3",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Ji yra mano draugė", audioText: "Ji yra mano draugė" },
          options: [
            { id: "a", text: "He is my friend", isCorrect: false },
            { id: "b", text: "This is my friend", isCorrect: false },
            { id: "c", text: "She is my friend", isCorrect: true },
          ],
          feedback: { correct: "Ji means she — draugė is the female form of friend. Draugas is the male form." },
        },
        {
          id: "s1m2l4_b4",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "You want to introduce your female friend to someone." },
          options: [
            { id: "a", text: "Jis yra mano draugas", isCorrect: false },
            { id: "b", text: "Ji yra mano draugė.", isCorrect: true },
            { id: "c", text: "Jis yra mano kolega", isCorrect: false },
          ],
          feedback: { correct: "Ji yra mano draugė — she is my friend. Ji for female, jis for male." },
        },
        {
          id: "s1m2l4_b5",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Jis yra iš Lenkijos", audioText: "Jis yra iš Lenkijos" },
          options: [
            { id: "a", text: "She is from Poland", isCorrect: false },
            { id: "b", text: "He is from Lithuania", isCorrect: false },
            { id: "c", text: "He is from Poland", isCorrect: true },
          ],
        },
        {
          id: "s1m2l4_b6",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "She is my friend" },
          tokens: [
            { id: "t1", text: "Ji", correctIndex: 0 },
            { id: "t2", text: "yra", correctIndex: 1 },
            { id: "t5", text: "draugas", isDistractor: true },
            { id: "t3", text: "mano", correctIndex: 2 },
            { id: "t4", text: "draugė", correctIndex: 3 },
          ],
          answerText: "Ji yra mano draugė",
        },
        {
          id: "s1m2l4_b7",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Introduce a female friend — say 'She is my friend'",
          targetText: "Ji yra mano draugė",
          audioText: "Ji yra mano draugė",
        },
        {
          id: "s1m2l4_b8",
          type: "scenario_chain",
          title: "Conversation",
          description: "You run into an old colleague, Rokas, and introduce your friend Barbora.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Labas! Kaip sekasi?",
              audioText: "Labas. Kaip sekasi",
              options: [
                { id: "a", text: "Gerai, ačiū! Čia Barbora. Ji yra mano draugė.", isCorrect: true },
                { id: "b", text: "Ne, ačiū", isCorrect: false },
                { id: "c", text: "Prašau dar kartą", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Malonu susipažinti! Iš kur ji yra?",
              audioText: "Malonu susipažinti. Iš kur ji yra",
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: false },
                { id: "b", text: "Ji yra iš Škotijos.", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
            },
          ],
        },
      ],
    },

    // ── Checkpoint ────────────────────────────────────────────────────────────
    {
      id: "section_1_module_2_checkpoint",
      code: "1.2.C",
      title: "Checkpoint",
      purpose: "Check you can recall and use Module 1.2 language without support.",
      supportLevel: "none",
      newLanguageLoad: "none",
      isCheckpoint: true,
      blocks: [
        {
          id: "s1m2c_b1",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "You meet someone at a formal event. They ask: Koks jūsų vardas?" },
          options: [
            { id: "a", text: "Aš esu iš Škotijos", isCorrect: false },
            { id: "b", text: "Mano vardas Davidas.", isCorrect: true },
            { id: "c", text: "Malonu susipažinti", isCorrect: false },
          ],
          feedback: { correct: "Mano vardas is the direct and natural reply to a name question." },
        },
        {
          id: "s1m2c_b2",
          type: "listen_mcq",
          title: "Listen and identify",
          prompt: { text: "Aš esu iš Ukrainos", audioText: "Aš esu iš Ukrainos" },
          options: [
            { id: "a", text: "I am from Lithuania", isCorrect: false },
            { id: "b", text: "I am from America", isCorrect: false },
            { id: "c", text: "I am from Ukraine", isCorrect: true },
          ],
        },
        {
          id: "s1m2c_b3",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "You want to say your colleague is from Poland. He is male." },
          options: [
            { id: "a", text: "Ji yra iš Lenkijos", isCorrect: false },
            { id: "b", text: "Jis yra iš Lenkijos", isCorrect: true },
            { id: "c", text: "Aš esu iš Lenkijos", isCorrect: false },
          ],
          feedback: { correct: "Jis for a male — ji would be used for a female colleague. Aš esu means I am, not he is." },
        },
        {
          id: "s1m2c_b4",
          type: "recognise_mcq",
          title: "Choose the correct meaning",
          prompt: { text: "Jis yra iš Vokietijos", audioText: "Jis yra iš Vokietijos" },
          options: [
            { id: "a", text: "She is from Germany", isCorrect: false },
            { id: "b", text: "He is from Poland", isCorrect: false },
            { id: "c", text: "He is from Germany", isCorrect: true },
          ],
        },
        {
          id: "s1m2c_b5",
          type: "build_phrase",
          title: "Build the phrase",
          prompt: { text: "Where are you from? (formal)" },
          tokens: [
            { id: "t1", text: "Iš", correctIndex: 0 },
            { id: "t2", text: "kur", correctIndex: 1 },
            { id: "t3", text: "jūsų", isDistractor: true },
            { id: "t4", text: "jūs", correctIndex: 2 },
            { id: "t5", text: "esate?", correctIndex: 3 },
          ],
          answerText: "Iš kur jūs esate?",
        },
        {
          id: "s1m2c_b6",
          type: "listen_mcq",
          title: "Listen and identify",
          prompt: { text: "Malonu susipažinti", audioText: "Malonu susipažinti" },
          options: [
            { id: "a", text: "How are you?", isCorrect: false },
            { id: "b", text: "Nice to meet you", isCorrect: true },
            { id: "c", text: "Me too", isCorrect: false },
          ],
        },
        {
          id: "s1m2c_b7",
          type: "speak_self_check",
          title: "Say it out loud",
          prompt: "Say where you are from",
          targetText: "Aš esu iš Škotijos",
          audioText: "Aš esu iš Škotijos",
        },
        {
          id: "s1m2c_b8",
          type: "best_response",
          title: "Choose the best response",
          prompt: { text: "Ona says Malonu susipažinti. What do you say back?" },
          options: [
            { id: "a", text: "Man irgi.", isCorrect: true },
            { id: "b", text: "Gerai, ačiū", isCorrect: false },
            { id: "c", text: "Iš kur tu esi?", isCorrect: false },
          ],
          feedback: { correct: "Man irgi — me too. The natural reply to Malonu susipažinti." },
        },
        {
          id: "s1m2c_b9",
          type: "scenario_chain",
          title: "Conversation",
          description: "You're at a welcome event in Vilnius. A local, Rokas, comes over to say hello.",
          steps: [
            {
              id: "step_1",
              actor: "other",
              text: "Laba diena! Aš esu Rokas. Koks jūsų vardas?",
              audioText: "Laba diena. Aš esu Rokas. Koks jūsų vardas",
              options: [
                { id: "a", text: "Ne, ačiū", isCorrect: false },
                { id: "b", text: "Laba diena! Mano vardas Davidas.", isCorrect: true },
                { id: "c", text: "Prašau dar kartą", isCorrect: false },
              ],
            },
            {
              id: "step_2",
              actor: "other",
              text: "Iš kur jūs esate?",
              audioText: "Iš kur jūs esate",
              options: [
                { id: "a", text: "Aš esu iš Škotijos.", isCorrect: true },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Gerai, ačiū", isCorrect: false },
              ],
            },
            {
              id: "step_3",
              actor: "other",
              text: "Malonu susipažinti!",
              audioText: "Malonu susipažinti",
              options: [
                { id: "a", text: "Viso gero!", isCorrect: false },
                { id: "b", text: "Man irgi!", isCorrect: true },
                { id: "c", text: "Iki", isCorrect: false },
              ],
            },
          ],
        },
        {
          id: "s1m2c_b10",
          type: "word_match",
          title: "Match the pairs",
          pairs: [
            { id: "wm1",  lt: "Aš esu",                    en: "I am",                             audioText: "Aš esu" },
            { id: "wm2",  lt: "Mano vardas",                en: "My name is",                       audioText: "Mano vardas" },
            { id: "wm3",  lt: "Koks tavo vardas?",          en: "What is your name? (informal)",    audioText: "Koks tavo vardas" },
            { id: "wm4",  lt: "Koks jūsų vardas?",          en: "What is your name? (formal)",      audioText: "Koks jūsų vardas" },
            { id: "wm5",  lt: "Aš esu iš Škotijos",         en: "I am from Scotland",               audioText: "Aš esu iš Škotijos" },
            { id: "wm6",  lt: "Aš esu iš Lietuvos",         en: "I am from Lithuania",              audioText: "Aš esu iš Lietuvos" },
            { id: "wm7",  lt: "Aš esu iš Ukrainos",         en: "I am from Ukraine",                audioText: "Aš esu iš Ukrainos" },
            { id: "wm8",  lt: "Aš esu iš Amerikos",         en: "I am from America",                audioText: "Aš esu iš Amerikos" },
            { id: "wm9",  lt: "Iš kur jūs esate?",          en: "Where are you from? (formal)",     audioText: "Iš kur jūs esate" },
            { id: "wm10", lt: "Iš kur tu esi?",             en: "Where are you from? (informal)",   audioText: "Iš kur tu esi" },
            { id: "wm11", lt: "Malonu susipažinti",          en: "Nice to meet you",                 audioText: "Malonu susipažinti" },
            { id: "wm12", lt: "Man irgi",                   en: "Me too / Likewise",                audioText: "Man irgi" },
            { id: "wm13", lt: "Labai malonu",               en: "Very pleased to meet you",         audioText: "Labai malonu" },
            { id: "wm14", lt: "Jis yra mano kolega",        en: "He is my colleague",               audioText: "Jis yra mano kolega" },
            { id: "wm15", lt: "Jis yra mano draugas",       en: "He is my friend",                  audioText: "Jis yra mano draugas" },
            { id: "wm16", lt: "Ji yra mano draugė",         en: "She is my friend",                 audioText: "Ji yra mano draugė" },
            { id: "wm17", lt: "Jis yra iš Lenkijos",        en: "He is from Poland",                audioText: "Jis yra iš Lenkijos" },
            { id: "wm18", lt: "Ji yra iš Vokietijos",       en: "She is from Germany",              audioText: "Ji yra iš Vokietijos" },
            { id: "wm19", lt: "Aš esu iš Anglijos",         en: "I am from England",                audioText: "Aš esu iš Anglijos" },
            { id: "wm20", lt: "Prancūzija",                  en: "France",                           audioText: "Prancūzija" },
          ],
        },
      ],
    },
  ],
};

export default module_1_2;
