// src/content/learning/section1/module_1_3.js
// Module 1.3 — I Don't Understand

export default function createModule_1_3(profile = {}) {
  const {
    userNameSafe = "Davidas",
    userFromPhrase = "Aš esu iš Škotijos",
  } = profile;

  return {
    id: "module_1_3",
    code: "1.3",
    title: "I Don't Understand",
    status: "active",
    lessonCount: 5,
    lessons: [

      // ── Lesson 1 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_3_lesson_1",
        code: "1.3.1",
        title: "I Don't Understand",
        purpose: "Teach the core comprehension breakdown phrase.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Nesuprantu and suprantu are the same verb — ne- makes it negative. Ar starts yes/no questions in Lithuanian. You don't need to produce Ar questions yet — just recognise them when you hear them.",
          usage: [
            "Aš nesuprantu — I don't understand (full form)",
            "Nesuprantu — I don't understand (shorter, equally natural)",
            "Suprantu — I understand",
            "Taip, suprantu — Yes, I understand",
            "Ne, nesuprantu — No, I don't understand",
            "Ar suprantate? — Do you understand? (formal) — Ar signals a yes/no question",
          ],
        },
        blocks: [
          {
            id: "s1m3l1_b1",
            type: "learn",
            title: "Understanding and not understanding",
            items: [
              { id: "u1", lt: "Aš nesuprantu", en: "I don't understand", audioText: "Aš nesuprantu", saveable: true, core: true },
              { id: "u2", lt: "Nesuprantu", en: "I don't understand (short form)", audioText: "Nesuprantu", saveable: true, core: true },
              { id: "u3", lt: "Suprantu", en: "I understand", audioText: "Suprantu", saveable: true, core: true },
              { id: "u4", lt: "Taip, suprantu", en: "Yes, I understand", audioText: "Taip, suprantu", saveable: true, core: true },
              { id: "u5", lt: "Ne, nesuprantu", en: "No, I don't understand", audioText: "Ne, nesuprantu", saveable: true, core: true },
              { id: "u6", lt: "Ar suprantate?", en: "Do you understand? (formal)", audioText: "Ar suprantate", saveable: true, core: true },
            ],
          },
          {
            id: "s1m3l1_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Nesuprantu", audioText: "Nesuprantu" },
            options: [
              { id: "a", text: "I understand", isCorrect: false },
              { id: "b", text: "I don't understand", isCorrect: true },
              { id: "c", text: "Please repeat", isCorrect: false },
            ],
          },
          {
            id: "s1m3l1_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Taip, suprantu", audioText: "Taip, suprantu" },
            options: [
              { id: "a", text: "No, I don't understand", isCorrect: false },
              { id: "b", text: "Yes, I understand", isCorrect: true },
              { id: "c", text: "Please repeat", isCorrect: false },
            ],
          },
          {
            id: "s1m3l1_b4",
            type: "recognise_mcq",
            title: "Choose the right phrase",
            prompt: { text: "Someone explains something quickly and you've lost track completely." },
            options: [
              { id: "a", text: "Nesuprantu", isCorrect: true },
              { id: "b", text: "Suprantu", isCorrect: false },
              { id: "c", text: "Taip", isCorrect: false },
            ],
            feedback: { correct: "Nesuprantu is the short, direct form. Aš nesuprantu is also natural; here we're practising the shorter repair phrase." },
          },
          {
            id: "s1m3l1_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "No, I don't understand" },
            tokens: [
              { id: "t1", text: "Ne,", correctIndex: 0 },
              { id: "t2", text: "nesuprantu", correctIndex: 1 },
              { id: "t3", text: "suprantu", isDistractor: true },
            ],
            answerText: "Ne, nesuprantu",
          },
          {
            id: "s1m3l1_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Someone explains something — you've lost the thread. Say it in Lithuanian.",
            targetText: "Nesuprantu",
            audioText: "Nesuprantu",
          },
          {
  id: "s1m3l1_b7_v2",
  type: "scenario_v2",
  title: "At hotel reception",
  description: "The receptionist gives you a room detail in Lithuanian. Respond based on what you understand; use Nesuprantu if you need help.",
  sceneIntro: "The receptionist gives you a room detail in Lithuanian. Respond based on what you understand; use Nesuprantu if you need help.",
  location: "hotel reception",
  userRole: "guest",
  register: "polite_service",
  goal: "Use Nesuprantu when you genuinely do not understand, then recognise when the help has made the meaning clear.",
  focus: ["Nesuprantu", "Supratau"],
  participants: [
    {
      id: "receptionist",
      label: "Receptionist",
      name: "Austėja",
      role: "receptionist",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "receptionist",
      speakerLabel: "Receptionist",
      speakerText: "Jūsų kambarys yra trečiame aukšte.",
      sceneDirection: "The receptionist hands you a key card and points towards the lifts.",
      learnerPrompt: "Respond based on what you understand. If you are lost, use Nesuprantu.",
      help: {
        levels: [
          {
            sceneDirection: "She slows down, holds up three fingers and points upstairs.",
            speakerText: "Trečias aukštas.",
          },
          {
            sceneDirection: "She points to the number 3 on the key-card sleeve, then points upstairs again.",
            speakerText: "Trečias.",
          },
          {
            speakerText: "Third floor.",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Supratau, ačiū!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "The receptionist is giving you information, not ending the conversation.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "Nothing is being offered. Respond to the information or ask for help.",
          progresses: false,
        },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 2 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_3_lesson_2",
        code: "1.3.2",
        title: "Please Repeat / More Slowly",
        purpose: "Give the learner control over conversation pace.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "These three phrases should feel automatic. Any time you don't catch something — reach for one of these immediately.",
          usage: [
            "Pakartokite, prašau — Please repeat (polite imperative form)",
            "Prašau kalbėkite lėčiau — Please speak more slowly",
            "Dar kartą, prašau — One more time, please",
            "Lėčiau, prašau — More slowly, please (shorter version)",
          ],
        },
        blocks: [
          {
            id: "s1m3l2_b1",
            type: "learn",
            title: "Repair phrases",
            items: [
              { id: "r1", lt: "Pakartokite, prašau", en: "Please repeat", audioText: "Pakartokite, prašau", saveable: true, core: true },
              { id: "r2", lt: "Prašau kalbėkite lėčiau", en: "Please speak more slowly", audioText: "Prašau kalbėkite lėčiau", saveable: true, core: true },
              { id: "r3", lt: "Dar kartą, prašau", en: "One more time, please", audioText: "Dar kartą, prašau", saveable: true, core: true },
              { id: "r4", lt: "Lėčiau, prašau", en: "More slowly, please", audioText: "Lėčiau, prašau", saveable: true, core: true },
              { id: "r5", lt: "Dabar", en: "Now", audioText: "Dabar", saveable: true, core: true },
            ],
          },
          {
            id: "s1m3l2_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Pakartokite, prašau", audioText: "Pakartokite, prašau" },
            options: [
              { id: "a", text: "Please speak more slowly", isCorrect: false },
              { id: "b", text: "I don't understand", isCorrect: false },
              { id: "c", text: "Please repeat", isCorrect: true },
            ],
          },
          {
            id: "s1m3l2_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Lėčiau, prašau", audioText: "Lėčiau, prašau" },
            options: [
              { id: "a", text: "Please repeat", isCorrect: false },
              { id: "b", text: "More slowly, please", isCorrect: true },
              { id: "c", text: "One more time", isCorrect: false },
            ],
            feedback: { correct: "Lėčiau means 'more slowly' — a useful short form when you just need the speed to drop." },
          },
          {
            id: "s1m3l2_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "They repeat the sentence, but the speed is still the problem." },
            options: [
              { id: "a", text: "Dar kartą, prašau", isCorrect: false },
              { id: "b", text: "Prašau kalbėkite lėčiau", isCorrect: true },
              { id: "c", text: "Suprantu", isCorrect: false },
            ],
            feedback: { correct: "Prašau kalbėkite lėčiau — please speak more slowly. Use this when pace is the problem, not repetition." },
          },
          {
            id: "s1m3l2_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You heard most of it but missed the last word." },
            options: [
              { id: "a", text: "Prašau kalbėkite lėčiau", isCorrect: false },
              { id: "b", text: "Pakartokite, prašau", isCorrect: true },
              { id: "c", text: "Nesuprantu", isCorrect: false },
            ],
            feedback: { correct: "Pakartokite, prašau — please repeat. This is the more natural polite repair phrase." },
          },
          {
            id: "s1m3l2_b6",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Please speak more slowly" },
            tokens: [
              { id: "t1", text: "Prašau", correctIndex: 0 },
              { id: "t2", text: "kalbėkite", correctIndex: 1 },
              { id: "t3", text: "lėčiau", correctIndex: 2 },
              { id: "t4", text: "pakartokite", isDistractor: true },
            ],
            answerText: "Prašau kalbėkite lėčiau",
          },
          {
            id: "s1m3l2_b7",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask someone to repeat what they said",
            targetText: "Pakartokite, prašau",
            audioText: "Pakartokite, prašau",
          },
          {
  id: "s1m3l2_b8_v2",
  type: "scenario_v2",
  title: "At the pharmacy",
  description: "The pharmacist gives you medicine instructions quickly. Use a specific pace request when that is what you need, or Nesuprantu if you are simply lost.",
  sceneIntro: "The pharmacist gives you medicine instructions quickly. Use a specific pace request when that is what you need, or Nesuprantu if you are simply lost.",
  location: "pharmacy",
  userRole: "customer",
  register: "polite_service",
  goal: "Choose between a specific request to slow down and the more general Nesuprantu help route.",
  focus: ["Prašau kalbėkite lėčiau", "Nesuprantu", "Supratau"],
  participants: [
    {
      id: "pharmacist",
      label: "Pharmacist",
      name: "Rasa",
      role: "pharmacist",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "pharmacist",
      speakerLabel: "Pharmacist",
      speakerText: "Šiuos vaistus reikia vartoti du kartus per dieną.",
      sceneDirection: "The pharmacist hands you the medicine and speaks quickly.",
      learnerPrompt: "Respond based on what you need.",
      help: {
        levels: [
          {
            sceneDirection: "She slows down, holds up two fingers and taps the medicine box.",
            speakerText: "Du kartus per dieną.",
          },
          {
            sceneDirection: "She points to the medicine, holds up two fingers, then points to a clock.",
            speakerText: "Du kartus.",
          },
          {
            speakerText: "Twice a day.",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Prašau kalbėkite lėčiau.",
          result: "best",
          progresses: true,
          followUp: {
            speakerId: "pharmacist",
            speakerLabel: "Pharmacist",
            speakerText: "Du kartus per dieną.",
            sceneDirection: "She repeats the important part more slowly and holds up two fingers.",
          },
        },
        {
          id: "b",
          text: "Supratau, ačiū!",
          result: "acceptable",
          feedback: "If you understood the instruction, this is a natural response. If not, ask for help rather than pretending.",
          progresses: true,
        },
        {
          id: "c",
          text: "Viso gero.",
          result: "wrong",
          feedback: "The pharmacist is still giving you important instructions.",
          progresses: false,
        },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 3 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_3_lesson_3",
        code: "1.3.3",
        title: "What Does This Mean?",
        purpose: "Bridge comprehension repair with pointing and reference language.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Tai means 'this / it' and ten means 'that / there'. These two words appear constantly — start noticing them in any Lithuanian you see.",
          usage: [
            "Ką tai reiškia? — What does this mean?",
            "Kas tai? — What is this?",
            "Kas ten? — What is that / what is there?",
            "Ką tai reiškia angliškai? — What does this mean in English?",
            "Tai reiškia… — It means… (how a Lithuanian speaker would reply)",
          ],
        },
        blocks: [
          {
            id: "s1m3l3_b1",
            type: "learn",
            title: "Asking what things mean",
            items: [
              { id: "m1", lt: "Ką tai reiškia?", en: "What does this mean?", audioText: "Ką tai reiškia", saveable: true, core: true },
              { id: "m2", lt: "Kas tai?", en: "What is this?", audioText: "Kas tai", saveable: true, core: true },
              { id: "m3", lt: "Kas ten?", en: "What is that?", audioText: "Kas ten", saveable: true, core: true },
              { id: "m4", lt: "Ką tai reiškia angliškai?", en: "What does this mean in English?", audioText: "Ką tai reiškia angliškai", saveable: true, core: true },
              { id: "m5", lt: "Žodis", en: "Word", audioText: "Žodis", saveable: true, core: true },
              { id: "m6", lt: "Ženklas", en: "Sign", audioText: "Ženklas", saveable: true, core: true },
            ],
          },
          {
            id: "s1m3l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ką tai reiškia?", audioText: "Ką tai reiškia" },
            options: [
              { id: "a", text: "What is that?", isCorrect: false },
              { id: "b", text: "What does this mean?", isCorrect: true },
              { id: "c", text: "What is this?", isCorrect: false },
            ],
          },
          {
            id: "s1m3l3_b3",
            type: "context_gap_select",
            title: "Choose the phrase that fits",
            prompt: "The thing you are asking about is across the room.",
            sentence: "You point across the room: ___",
            translation_en: "What is that / what is there?",
            options: [
              { id: "a", text: "Kas tai?", isCorrect: false },
              { id: "b", text: "Kas ten?", isCorrect: true },
              { id: "c", text: "Ką tai reiškia?", isCorrect: false },
            ],
            explanation: "Kas ten? fits something further away. Ten points away from you: there / over there.",
          },
          {
            id: "s1m3l3_b4",
            type: "context_gap_select",
            title: "Choose the phrase that fits",
            prompt: "You are holding an unfamiliar object in your hand.",
            sentence: "You hold it up and ask: ___",
            translation_en: "What is this?",
            options: [
              { id: "a", text: "Kas ten?", isCorrect: false },
              { id: "b", text: "Kas tai?", isCorrect: true },
              { id: "c", text: "Ką tai reiškia angliškai?", isCorrect: false },
            ],
            explanation: "Kas tai? fits the object you are holding or indicating right here. Kas ten? points to something further away.",
          },
          {
            id: "s1m3l3_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "What does this mean?" },
            tokens: [
              { id: "t1", text: "Ką", correctIndex: 0 },
              { id: "t2", text: "tai", correctIndex: 1 },
              { id: "t3", text: "reiškia?", correctIndex: 2 },
              { id: "t4", text: "angliškai?", isDistractor: true },
            ],
            answerText: "Ką tai reiškia?",
          },
          {
            id: "s1m3l3_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Point to something unfamiliar and ask what it means",
            targetText: "Ką tai reiškia?",
            audioText: "Ką tai reiškia",
          },
          {
  id: "s1m3l3_b7_v2",
  type: "scenario_v2",
  title: "Reading a café menu",
  description: "A server notices you looking at an unfamiliar menu word. Ask what it means, then decide whether you need more help.",
  sceneIntro: "A server notices you looking at an unfamiliar menu word. Ask what it means, then decide whether you need more help.",
  location: "café",
  userRole: "customer",
  register: "polite_service",
  goal: "Use Ką tai reiškia? for an unfamiliar word and Nesuprantu if the Lithuanian explanation is still too difficult.",
  focus: ["Ką tai reiškia?", "Ką tai reiškia angliškai?", "Nesuprantu"],
  participants: [
    {
      id: "server",
      label: "Server",
      name: "Rasa",
      role: "server",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Cepelinai?",
      sceneDirection: "The server taps the word “cepelinai” on the menu after noticing you looking at it.",
      learnerPrompt: "Ask what the word means.",
      options: [
        {
          id: "a",
          text: "Ką tai reiškia?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Kas ten?",
          result: "wrong",
          feedback: "The word is right in front of you. Ask what it means rather than what is over there.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero.",
          result: "wrong",
          feedback: "You are asking about the menu, not ending the conversation.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Tai lietuviškas patiekalas.",
      sceneDirection: "She points to a photo of the dish on the menu.",
      learnerPrompt: "If that explanation is enough, acknowledge it. If not, ask for more help.",
      help: {
        levels: [
          {
            sceneDirection: "She points more clearly at the photo and mimics eating.",
            speakerText: "Patiekalas. Cepelinai.",
          },
          {
            sceneDirection: "She points at the picture again and circles the dish with her finger.",
            speakerText: "Cepelinai.",
          },
          {
            speakerText: "Potato dumplings.",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Supratau, ačiū!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ką tai reiškia angliškai?",
          result: "acceptable",
          feedback: "That is a clear way to ask for an English meaning when the Lithuanian explanation is not enough.",
          progresses: true,
          followUp: {
            speakerId: "server",
            speakerLabel: "Server",
            speakerText: "Potato dumplings.",
            spokenLanguage: "en",
            audio: false,
            sceneDirection: "She gives you the English meaning.",
          },
        },
        {
          id: "c",
          text: "Kas ten?",
          result: "wrong",
          feedback: "You are asking about the meaning of the menu word, not something further away.",
          progresses: false,
        },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 4 ────────────────────────────────────────────────────────────
      {
        id: "section_1_module_3_lesson_4",
        code: "1.3.4",
        title: "Do You Speak English?",
        purpose: "Teach fallback language for when comprehension fully breaks down.",
        supportLevel: "medium",
        newLanguageLoad: "low_to_medium",
        notes: {
          pattern: "This is a rescue tool, not a way to avoid Lithuanian. Use it when you genuinely need help — then try to get back to Lithuanian as soon as possible.",
          usage: [
            "Ar jūs kalbate angliškai? — Do you speak English? (formal)",
            "Ar tu kalbi angliškai? — Do you speak English? (informal)",
            "Truputį — a little (casual, conversational — what most Lithuanians say in everyday speech)",
            "Šiek tiek — a little (standard/neutral — equally correct, more common in written Lithuanian)",
            "Both are natural and interchangeable. When in doubt, truputį sounds more like a native speaker in conversation.",
          ],
        },
        blocks: [
          {
            id: "s1m3l4_b1",
            type: "learn",
            title: "Language fallback phrases",
            items: [
              { id: "lb1", lt: "Ar jūs kalbate angliškai?", en: "Do you speak English? (formal)", audioText: "Ar jūs kalbate angliškai", saveable: true, core: true },
              { id: "lb2", lt: "Taip, truputį", en: "Yes, a little (casual)", audioText: "Taip, truputį", saveable: true, core: true },
              { id: "lb2b", lt: "Taip, šiek tiek", en: "Yes, a little (standard)", audioText: "Taip, šiek tiek", saveable: true, core: true },
              { id: "lb4", lt: "Aš kalbu truputį lietuviškai", en: "I speak a little Lithuanian (casual)", audioText: "Aš kalbu truputį lietuviškai", saveable: true, core: true },
              { id: "lb4b", lt: "Aš kalbu šiek tiek lietuviškai", en: "I speak a little Lithuanian (standard)", audioText: "Aš kalbu šiek tiek lietuviškai", saveable: true, core: true },
              { id: "lb5", lt: "Truputį", en: "A little (casual)", audioText: "Truputį", saveable: true, core: true },
              { id: "lb5b", lt: "Šiek tiek", en: "A little (standard)", audioText: "Šiek tiek", saveable: true, core: true },
            ],
          },
          {
            id: "s1m3l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar jūs kalbate angliškai?", audioText: "Ar jūs kalbate angliškai" },
            options: [
              { id: "a", text: "I speak a little Lithuanian", isCorrect: false },
              { id: "b", text: "Do you speak English?", isCorrect: true },
              { id: "c", text: "A little", isCorrect: false },
            ],
          },
          {
            id: "s1m3l4_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Aš kalbu šiek tiek lietuviškai", audioText: "Aš kalbu šiek tiek lietuviškai" },
            options: [
              { id: "a", text: "Do you speak Lithuanian?", isCorrect: false },
              { id: "b", text: "Yes, a little", isCorrect: false },
              { id: "c", text: "I speak a little Lithuanian", isCorrect: true },
            ],
            feedback: { correct: "Aš kalbu means I speak. Šiek tiek = a little. Lietuviškai = Lithuanian (language form)." },
          },
          {
            id: "s1m3l4_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You've tried everything and really need English help." },
            options: [
              { id: "a", text: "Dar kartą, prašau", isCorrect: false },
              { id: "b", text: "Ar jūs kalbate angliškai?", isCorrect: true },
              { id: "c", text: "Kas tai?", isCorrect: false },
            ],
            feedback: { correct: "Ar jūs kalbate angliškai? — Do you speak English? The last resort that can save you." },
          },
          {
            id: "s1m3l4_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "I speak a little Lithuanian (casual)" },
            tokens: [
              { id: "t1", text: "Aš", correctIndex: 0 },
              { id: "t2", text: "kalbu", correctIndex: 1 },
              { id: "t3", text: "truputį", correctIndex: 2 },
              { id: "t4", text: "lietuviškai", correctIndex: 3 },
              { id: "t5", text: "angliškai", isDistractor: true },
              { id: "t6", text: "šiek", isDistractor: true },
            ],
            answerText: "Aš kalbu truputį lietuviškai",
          },
          {
            id: "s1m3l4_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask someone if they speak English",
            targetText: "Ar jūs kalbate angliškai",
            audioText: "Ar jūs kalbate angliškai",
          },
          {
  id: "s1m3l4_b7_v2",
  type: "scenario_v2",
  title: "When Lithuanian is not enough",
  description: "At an information desk, the assistant offers help in Lithuanian. Try to follow the context; if you still cannot, ask whether they speak English.",
  sceneIntro: "At an information desk, the assistant offers help in Lithuanian. Try to follow the context; if you still cannot, ask whether they speak English.",
  location: "information desk",
  userRole: "visitor",
  register: "polite_service",
  goal: "Use Ar jūs kalbate angliškai? as a genuine fallback after simpler Lithuanian and context still are not enough.",
  focus: ["Ar jūs kalbate angliškai?", "Nesuprantu"],
  participants: [
    {
      id: "assistant",
      label: "Assistant",
      name: "Rasa",
      role: "information assistant",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "assistant",
      speakerLabel: "Assistant",
      speakerText: "Laba diena. Kuo galiu padėti?",
      sceneDirection: "At the information desk, the assistant looks up and gestures that she is ready to help.",
      learnerPrompt: "If you still cannot follow, use Nesuprantu for contextual help or ask for English.",
      help: {
        levels: [
          {
            sceneDirection: "She points to herself, then to you, and opens her hands as if offering help.",
            speakerText: "Padėti?",
          },
          {
            sceneDirection: "She repeats the same gesture slowly and points to the information desk sign.",
            speakerText: "Padėti?",
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Ar jūs kalbate angliškai?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "The assistant is offering help. If Lithuanian has broken down, ask whether she speaks English.",
          progresses: false,
        },
        {
          id: "c",
          text: "Taip, suprantu.",
          result: "wrong",
          feedback: "The scene says you still cannot follow. Use a genuine fallback rather than claiming you understand.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "assistant",
      speakerLabel: "Assistant",
      speakerText: "Taip, truputį.",
      sceneDirection: "She nods and says she speaks a little.",
      learnerPrompt: "Acknowledge the help.",
      options: [
        {
          id: "a",
          text: "Ačiū!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "She has just said she speaks a little English. Thank her before continuing.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "You asked for English help, so declining it does not fit here.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "assistant",
        speakerLabel: "Assistant",
        speakerText: "Gerai.",
        sceneDirection: "She smiles and waits for you to continue.",
      },
    },
  ],
},
        ],
      },

      // ── Checkpoint ────────────────────────────────────────────────────────
      {
        id: "section_1_module_3_checkpoint",
        code: "1.3.C",
        title: "Checkpoint",
        purpose: "Check you can repair a conversation and ask for what you need without panic.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s1m3c_b1",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "They have repeated the sentence, but the speed is still the problem." },
            options: [
              { id: "a", text: "Suprantu", isCorrect: false },
              { id: "b", text: "Prašau kalbėkite lėčiau", isCorrect: true },
              { id: "c", text: "Ačiū labai", isCorrect: false },
            ],
            feedback: { correct: "Prašau kalbėkite lėčiau — please speak more slowly. Speed is the problem here, not the words themselves." },
          },
          {
            id: "s1m3c_b2",
            type: "listen_mcq",
            title: "Listen and identify",
            prompt: { text: "Ką tai reiškia angliškai?", audioText: "Ką tai reiškia angliškai" },
            options: [
              { id: "a", text: "What is this?", isCorrect: false },
              { id: "b", text: "Please repeat", isCorrect: false },
              { id: "c", text: "What does this mean in English?", isCorrect: true },
            ],
          },
          {
            id: "s1m3c_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You need help and everything else has failed. What's your last resort?" },
            options: [
              { id: "a", text: "Dar kartą, prašau", isCorrect: false },
              { id: "b", text: "Ką tai reiškia?", isCorrect: false },
              { id: "c", text: "Ar jūs kalbate angliškai?", isCorrect: true },
            ],
            feedback: { correct: "Ar jūs kalbate angliškai? — Do you speak English? Save this for genuine breakdown moments." },
          },
          {
            id: "s1m3c_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ne, nesuprantu", audioText: "Ne, nesuprantu" },
            options: [
              { id: "a", text: "Yes, I understand", isCorrect: false },
              { id: "b", text: "No, I don't understand", isCorrect: true },
              { id: "c", text: "Please repeat", isCorrect: false },
            ],
          },
          {
            id: "s1m3c_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Please repeat" },
            tokens: [
              { id: "t1", text: "Pakartokite,", correctIndex: 0 },
              { id: "t2", text: "prašau", correctIndex: 1 },
              { id: "t3", text: "lėčiau", isDistractor: true },
            ],
            answerText: "Pakartokite, prašau",
          },
          {
            id: "s1m3c_b6",
            type: "listen_mcq",
            title: "Listen and identify",
            prompt: { text: "Aš kalbu šiek tiek lietuviškai", audioText: "Aš kalbu šiek tiek lietuviškai" },
            options: [
              { id: "a", text: "Do you speak Lithuanian?", isCorrect: false },
              { id: "b", text: "I speak a little Lithuanian", isCorrect: true },
              { id: "c", text: "Yes, a little", isCorrect: false },
            ],
          },
          {
            id: "s1m3c_b7",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Tell someone you don't understand",
            targetText: "Nesuprantu",
            audioText: "Nesuprantu",
          },
          {
            id: "s1m3c_b8",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You almost caught the sentence but missed one word near the end." },
            options: [
              { id: "a", text: "Prašau kalbėkite lėčiau", isCorrect: false },
              { id: "b", text: "Ar jūs kalbate angliškai?", isCorrect: false },
              { id: "c", text: "Pakartokite, prašau", isCorrect: true },
            ],
            feedback: { correct: "Pakartokite, prašau — please repeat. Use this when you need the sentence again. Prašau kalbėkite lėčiau is for when the speed is the problem." },
          },
          {
            id: "s1m3c_b8b",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Truputį", audioText: "Truputį" },
            options: [
              { id: "a", text: "A little (standard written form)", isCorrect: false },
              { id: "b", text: "Please repeat", isCorrect: false },
              { id: "c", text: "A little (casual, conversational)", isCorrect: true },
            ],
            feedback: { correct: "Truputį is the casual, conversational form. Šiek tiek is the standard/written form. Both mean a little — your Lithuanian friends will likely say truputį." },
          },
          {
  id: "s1m3c_b9_v2",
  type: "scenario_v2",
  title: "Welcome event",
  description: "At a welcome event, you meet Rokas, introduce yourself, then handle an unfamiliar Lithuanian word without leaving the conversation.",
  sceneIntro: "At a welcome event, you meet Rokas, introduce yourself, then handle an unfamiliar Lithuanian word without leaving the conversation.",
  location: "welcome event",
  userRole: "learner",
  register: "polite_neutral",
  goal: "Combine first-contact language with repair, meaning questions and an English fallback only when needed.",
  focus: ["first contact", "Nesuprantu", "Ką tai reiškia angliškai?"],
  participants: [
    {
      id: "local",
      label: "Local",
      name: "Rokas",
      role: "local speaker",
      gender: "male",
      relationshipToUser: "stranger",
      register: "polite_neutral",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Laba diena! Aš esu Rokas. Koks jūsų vardas?",
      sceneDirection: "Rokas comes over and introduces himself.",
      learnerPrompt: "Introduce yourself.",
      options: [
        {
          id: "a",
          text: `Laba diena! Mano vardas ${userNameSafe}. Malonu susipažinti.`,
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "Rokas has just introduced himself. Respond to the introduction.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ne, ačiū.",
          result: "wrong",
          feedback: "Nothing has been offered. Introduce yourself.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Malonu susipažinti! Iš kur jūs esate?",
      sceneDirection: "He continues the first-meeting conversation.",
      learnerPrompt: "Say where you are from.",
      options: [
        {
          id: "a",
          text: `${userFromPhrase}.`,
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Taip, suprantu.",
          result: "wrong",
          feedback: "Rokas is asking where you are from.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ačiū!",
          result: "wrong",
          feedback: "Answer the question about where you are from.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_3",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Išėjimas.",
      sceneDirection: "Rokas points to an unfamiliar word on a sign beside the door.",
      learnerPrompt: "You do not know this word. Ask for the meaning you need.",
      help: {
        levels: [
          {
            sceneDirection: "He points from the word on the sign to the door.",
            speakerText: "Išėjimas.",
          },
          {
            sceneDirection: "He mimics walking out through the door, then points back to the word.",
            speakerText: "Išėjimas.",
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Ką tai reiškia angliškai?",
          result: "best",
          progresses: true,
          followUp: {
            speakerId: "local",
            speakerLabel: "Local",
            speakerText: "Exit.",
            spokenLanguage: "en",
            audio: false,
            sceneDirection: "Rokas gives you the English meaning.",
          },
        },
        {
          id: "b",
          text: "Kas ten?",
          result: "wrong",
          feedback: "He is pointing to the word right beside you. Ask what it means.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero!",
          result: "wrong",
          feedback: "You still need the meaning of the unfamiliar word.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_4",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Ar suprantate?",
      sceneDirection: "Rokas checks that the explanation helped.",
      learnerPrompt: "Confirm that you understand.",
      options: [
        {
          id: "a",
          text: "Taip, suprantu. Ačiū!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "Rokas is checking whether you understand.",
          progresses: false,
        },
        {
          id: "c",
          text: "Malonu susipažinti.",
          result: "wrong",
          feedback: "You already completed the introduction. Answer the understanding check.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "local",
        speakerLabel: "Local",
        speakerText: "Puiku. Viso gero!",
        sceneDirection: "Rokas smiles and heads back to the event.",
      },
    },
  ],
},
          {
            id: "s1m3c_b10",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "wm1",  lt: "Aš nesuprantu",               en: "I don't understand",                    audioText: "Aš nesuprantu" },
              { id: "wm2",  lt: "Nesuprantu",                   en: "I don't understand (short)",            audioText: "Nesuprantu" },
              { id: "wm3",  lt: "Suprantu",                     en: "I understand",                          audioText: "Suprantu" },
              { id: "wm4",  lt: "Taip, suprantu",               en: "Yes, I understand",                     audioText: "Taip, suprantu" },
              { id: "wm5",  lt: "Ne, nesuprantu",               en: "No, I don't understand",                audioText: "Ne, nesuprantu" },
              { id: "wm6",  lt: "Pakartokite, prašau",          en: "Please repeat",                         audioText: "Pakartokite, prašau" },
              { id: "wm7",  lt: "Prašau kalbėkite lėčiau",     en: "Please speak more slowly",              audioText: "Prašau kalbėkite lėčiau" },
              { id: "wm8",  lt: "Dar kartą, prašau",            en: "One more time, please",                 audioText: "Dar kartą, prašau" },
              { id: "wm9",  lt: "Lėčiau, prašau",               en: "More slowly, please",                   audioText: "Lėčiau, prašau" },
              { id: "wm10", lt: "Ką tai reiškia?",              en: "What does this mean?",                  audioText: "Ką tai reiškia" },
              { id: "wm11", lt: "Kas tai?",                     en: "What is this?",                         audioText: "Kas tai" },
              { id: "wm12", lt: "Kas ten?",                     en: "What is that?",                         audioText: "Kas ten" },
              { id: "wm13", lt: "Ką tai reiškia angliškai?",   en: "What does this mean in English?",       audioText: "Ką tai reiškia angliškai" },
              { id: "wm14", lt: "Ar jūs kalbate angliškai?",   en: "Do you speak English?",                 audioText: "Ar jūs kalbate angliškai" },
              { id: "wm15", lt: "Taip, šiek tiek",              en: "Yes, a little",                         audioText: "Taip, šiek tiek" },
              { id: "wm16", lt: "Aš kalbu šiek tiek lietuviškai", en: "I speak a little Lithuanian",        audioText: "Aš kalbu šiek tiek lietuviškai" },
              { id: "wm17", lt: "Šiek tiek",                    en: "A little",                              audioText: "Šiek tiek" },
              { id: "wm17b", lt: "Dabar",                        en: "Now",                                   audioText: "Dabar" },
              { id: "wm18", lt: "Žodis",                        en: "Word",                                  audioText: "Žodis" },
              { id: "wm19", lt: "Ženklas",                      en: "Sign",                                  audioText: "Ženklas" },
              { id: "wm20", lt: "Vaistinė",                     en: "Pharmacy",                              audioText: "Vaistinė" },
              { id: "wm21", lt: "Truputį",                       en: "A little (casual)",                     audioText: "Truputį" },
            ],
          },
        ],
      },
    ],
  };
}
