// src/content/learning/section1/module_1_1.js
// Module 1.1 — Greeting and Politeness

const module_1_1 =     {
      id: "module_1_1",
      code: "1.1",
      title: "Greeting and Politeness",
      status: "active",
      lessonCount: 5,
      lessons: [

        // ── Lesson 1 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_1",
          code: "1.1.1",
          title: "Hello and Goodbye",
          purpose: "Introduce first-contact opening and closing language.",
          supportLevel: "high",
          newLanguageLoad: "very_low",
          notes: {
            pattern: "Lithuanian greetings change by time of day. Labas works any time; Laba diena is daytime only.",
            usage: [
              "Labas — casual, any time of day",
              "Laba diena — formal or daytime",
              "Labas rytas / Labas vakaras — morning and evening specifically",
              "Viso gero / Iki — both mean goodbye, Iki is more casual",
            ],
          },
          blocks: [
            {
              id: "s1m1l1_b1",
              type: "learn",
              title: "Greetings and farewells",
              items: [
                { id: "g1", lt: "Labas", en: "Hello (casual)", audioText: "Labas", saveable: true, core: true },
                { id: "g2", lt: "Laba diena", en: "Good day / Hello (formal)", audioText: "Laba diena", saveable: true, core: true },
                { id: "g3", lt: "Labas rytas", en: "Good morning", audioText: "Labas rytas", saveable: true, core: true },
                { id: "g4", lt: "Labas vakaras", en: "Good evening", audioText: "Labas vakaras", saveable: true, core: true },
                { id: "g5", lt: "Viso gero", en: "Goodbye (take care)", audioText: "Viso gero", saveable: true, core: true },
                { id: "g6", lt: "Iki", en: "Bye (casual)", audioText: "Iki", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l1_b2",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Labas", audioText: "Labas" },
              options: [
                { id: "a", text: "Goodbye", isCorrect: false },
                { id: "b", text: "Hello", isCorrect: true },
                { id: "c", text: "Good morning", isCorrect: false },
              ],
            },
            {
              id: "s1m1l1_b3",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Laba diena", audioText: "Laba diena" },
              options: [
                { id: "a", text: "Good morning", isCorrect: false },
                { id: "b", text: "Good day / Hello", isCorrect: true },
                { id: "c", text: "Goodbye", isCorrect: false },
              ],
            },
            {
              id: "s1m1l1_b3b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Labas vakaras", audioText: "Labas vakaras" },
              options: [
                { id: "a", text: "Good morning", isCorrect: false },
                { id: "b", text: "Good evening", isCorrect: true },
                { id: "c", text: "Goodbye", isCorrect: false },
              ],
            },
            {
              id: "s1m1l1_b3c",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Iki", audioText: "Iki" },
              options: [
                { id: "a", text: "Hello", isCorrect: false },
                { id: "b", text: "Good evening", isCorrect: false },
                { id: "c", text: "Bye (casual)", isCorrect: true },
              ],
            },
            {
              id: "s1m1l1_b4",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone says Laba diena to you in a shop." },
              options: [
                { id: "a", text: "Labas rytas", isCorrect: false },
                { id: "b", text: "Laba diena", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
              feedback: { correct: "Match the register — laba diena for laba diena." },
            },
            {
              id: "s1m1l1_b5",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "Say hello in Lithuanian",
              targetText: "Labas",
              audioText: "Labas",
            },
            {
              id: "s1m1l1_b6",
              type: "build_phrase",
              title: "Build the phrase",
              prompt: { text: "Good morning" },
              tokens: [
                { id: "t3", text: "vakaras", isDistractor: true },
                { id: "t2", text: "rytas", correctIndex: 1 },
                { id: "t1", text: "Labas", correctIndex: 0 },
              ],
              answerText: "Labas rytas",
            },
            {
              id: "s1m1l1_b7",
              type: "scenario_chain",
              title: "Conversation",
              description: "Complete a short greeting exchange.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Labas!",
                  audioText: "Labas",
                  options: [
                    { id: "a", text: "Labas!", isCorrect: true },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Ne", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Laba diena", isCorrect: false },
                    { id: "b", text: "Iki!", isCorrect: true },
                    { id: "c", text: "Taip", isCorrect: false },
                  ],
                },
              ],
            },
          ],
        },

        // ── Lesson 2 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_2",
          code: "1.1.2",
          title: "Yes, No, Please, Thank You",
          purpose: "Core polite responses that work in almost every situation.",
          supportLevel: "high",
          newLanguageLoad: "very_low",
          notes: {
            pattern: "Prašau does double duty — it means both 'please' and 'here you go / you're welcome'. Words combine naturally: Ne, ačiū is the polite way to say no.",
            usage: [
              "Taip / Ne — yes and no",
              "Taip, prašau — yes please (accepting something politely)",
              "Ne, ačiū — no thank you (declining something politely)",
              "Prašau — please (when asking) or here you go / you're welcome (when giving)",
              "Ačiū — thank you",
              "Ačiū labai — thank you very much",
            ],
          },
          blocks: [
            {
              id: "s1m1l2_b1",
              type: "learn",
              title: "Essential polite words",
              items: [
                { id: "p1", lt: "Taip", en: "Yes", audioText: "Taip", saveable: true, core: true },
                { id: "p2", lt: "Ne", en: "No", audioText: "Ne", saveable: true, core: true },
                { id: "p3", lt: "Prašau", en: "Please / Here you go / You're welcome", audioText: "Prašau", saveable: true, core: true },
                { id: "p4", lt: "Ačiū", en: "Thank you", audioText: "Ačiū", saveable: true, core: true },
                { id: "p5", lt: "Ačiū labai", en: "Thank you very much", audioText: "Ačiū labai", saveable: true, core: true },
                { id: "p6", lt: "Taip, prašau", en: "Yes please", audioText: "Taip, prašau", saveable: true, core: true },
                { id: "p7", lt: "Ne, ačiū", en: "No thank you", audioText: "Ne, ačiū", saveable: true, core: true },
                { id: "p8", lt: "Norėčiau kavos, prašau", en: "I'd like a coffee, please", audioText: "Norėčiau kavos, prašau", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l2_b1b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Taip", audioText: "Taip" },
              options: [
                { id: "a", text: "No", isCorrect: false },
                { id: "b", text: "Please", isCorrect: false },
                { id: "c", text: "Yes", isCorrect: true },
              ],
            },
            {
              id: "s1m1l2_b1c",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone offers you a second helping and you don't want it." },
              options: [
                { id: "a", text: "Taip, prašau", isCorrect: false },
                { id: "b", text: "Ne, ačiū", isCorrect: true },
                { id: "c", text: "Ačiū labai", isCorrect: false },
              ],
              feedback: { correct: "Ne, ačiū — no thank you. Bare 'Ne' can sound abrupt; adding ačiū keeps it polite." },
            },
            {
              id: "s1m1l2_b1d",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone offers you a coffee and you'd like one." },
              options: [
                { id: "a", text: "Ne, ačiū", isCorrect: false },
                { id: "b", text: "Taip, prašau", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
              feedback: { correct: "Taip, prašau — yes please. Much more natural than Taip alone." },
            },
            {
              id: "s1m1l2_b2",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Ačiū", audioText: "Ačiū" },
              options: [
                { id: "a", text: "Please", isCorrect: false },
                { id: "b", text: "Yes", isCorrect: false },
                { id: "c", text: "Thank you", isCorrect: true },
              ],
            },
            {
              id: "s1m1l2_b3",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone hands you something and says Prašau." },
              options: [
                { id: "a", text: "Ačiū", isCorrect: true },
                { id: "b", text: "Ne", isCorrect: false },
                { id: "c", text: "Labas", isCorrect: false },
              ],
              feedback: { correct: "Prašau here means 'here you go' — Ačiū is the natural reply." },
            },
            {
              id: "s1m1l2_b4",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Ačiū labai", audioText: "Ačiū labai" },
              options: [
                { id: "a", text: "Thank you very much", isCorrect: true },
                { id: "b", text: "You're welcome", isCorrect: false },
                { id: "c", text: "Please", isCorrect: false },
              ],
            },
            {
              id: "s1m1l2_b4b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Ne, ačiū", audioText: "Ne, ačiū" },
              options: [
                { id: "a", text: "Yes please", isCorrect: false },
                { id: "b", text: "No thank you", isCorrect: true },
                { id: "c", text: "Thank you very much", isCorrect: false },
              ],
            },
            {
              id: "s1m1l2_b4c",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Norėčiau kavos, prašau", audioText: "Norėčiau kavos, prašau" },
              options: [
                { id: "a", text: "Here is your coffee", isCorrect: false },
                { id: "b", text: "I'd like a coffee, please", isCorrect: true },
                { id: "c", text: "No thank you", isCorrect: false },
              ],
              feedback: { correct: "Norėčiau means 'I would like' — a polite and natural way to order anything." },
            },
            {
              id: "s1m1l2_b5",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "Say thank you in Lithuanian",
              targetText: "Ačiū",
              audioText: "Ačiū",
            },
            {
              id: "s1m1l2_b6",
              type: "scenario_chain",
              title: "Conversation",
              description: "You walk into a café. Order a coffee and complete the exchange.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Laba diena!",
                  audioText: "Laba diena",
                  options: [
                    { id: "a", text: "Laba diena!", isCorrect: true },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Ne, ačiū", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Ko norite?",
                  audioText: "Ko norite",
                  helperText: "The barista is asking what you'd like.",
                  options: [
                    { id: "a", text: "Ačiū labai", isCorrect: false },
                    { id: "b", text: "Ne, ačiū", isCorrect: false },
                    { id: "c", text: "Norėčiau kavos, prašau", isCorrect: true },
                  ],
                },
                {
                  id: "step_3",
                  actor: "other",
                  text: "Prašau.",
                  audioText: "Prašau",
                  options: [
                    { id: "a", text: "Ačiū labai!", isCorrect: true },
                    { id: "b", text: "Ne, ačiū", isCorrect: false },
                    { id: "c", text: "Taip", isCorrect: false },
                  ],
                },
                {
                  id: "step_4",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Atsiprašau", isCorrect: false },
                    { id: "b", text: "Taip, prašau", isCorrect: false },
                    { id: "c", text: "Iki!", isCorrect: true },
                  ],
                },
              ],
            },
            {
              id: "scenario_cafe_order_coffee_v2",
              type: "scenario_v2",
              title: "Ordering coffee at a café",
              sceneIntro: "You are at a café counter. The barista, Ieva, is ready to take your order.",
              location: "café counter",
              userRole: "customer",
              register: "polite_service",
              goal: "Order one coffee and pay by card.",
              focus: ["ordering", "polite requests", "payment"],
              participants: [
                {
                  id: "barista",
                  label: "Barista",
                  name: "Ieva",
                  role: "barista",
                  gender: "female",
                  relationshipToUser: "stranger",
                  register: "polite_service",
                },
              ],
              objects: [
                {
                  id: "coffee",
                  lt: "kava",
                  en: "coffee",
                  gender: "feminine",
                  number: "singular",
                },
                {
                  id: "card_reader",
                  lt: "kortelių skaitytuvas",
                  en: "card reader",
                  gender: "masculine",
                  number: "singular",
                },
              ],
              steps: [
                {
                  id: "step_1_order",
                  speakerId: "barista",
                  speakerLabel: "Barista",
                  speakerText: "Laba diena. Ko norėtumėte?",
                  speakerTextEn: "Good afternoon. What would you like?",
                  sceneDirection: "Ieva smiles and waits for your order.",
                  learnerPrompt: "You want one coffee. What do you say?",
                  helperText: "You have not fully learned “norėtumėte” yet. It is a polite way to ask “would you like”.",
                  options: [
                    {
                      id: "step_1_best",
                      text: "Norėčiau kavos, prašau.",
                      textEn: "I would like coffee, please.",
                      result: "best",
                      feedback: "Good. This is polite and natural in a café.",
                      progresses: true,
                    },
                    {
                      id: "step_1_acceptable",
                      text: "Kavos, prašau.",
                      textEn: "Coffee, please.",
                      result: "acceptable",
                      feedback: "This works. It is short, but still polite because you added “prašau”.",
                      betterAnswer: "Norėčiau kavos, prašau.",
                      progresses: true,
                    },
                    {
                      id: "step_1_awkward",
                      text: "Noriu kavos.",
                      textEn: "I want coffee.",
                      result: "awkward",
                      feedback: "Understandable, but too direct for a café. “Norėčiau kavos, prašau” sounds more polite.",
                      betterAnswer: "Norėčiau kavos, prašau.",
                      progresses: true,
                    },
                    {
                      id: "step_1_wrong",
                      text: "Viso gero.",
                      textEn: "Goodbye.",
                      result: "wrong",
                      feedback: "This ends the conversation instead of ordering. Choose the answer that asks for coffee.",
                      progresses: false,
                    },
                  ],
                },
                {
                  id: "step_2_payment",
                  speakerId: "barista",
                  speakerLabel: "Barista",
                  speakerText: "Mokėsite kortele ar grynais?",
                  speakerTextEn: "Will you pay by card or cash?",
                  sceneDirection: "Ieva enters the coffee into the till.",
                  learnerPrompt: "You want to pay by card. What do you say?",
                  helperText: "You have not fully learned this question yet. “Kortele” means “by card” here.",
                  options: [
                    {
                      id: "step_2_best",
                      text: "Kortele, prašau.",
                      textEn: "By card, please.",
                      result: "best",
                      feedback: "Good. This is short, clear, and polite.",
                      progresses: true,
                    },
                    {
                      id: "step_2_acceptable",
                      text: "Kortele.",
                      textEn: "By card.",
                      result: "acceptable",
                      feedback: "This is correct and common. Adding “prašau” makes it a little more polite.",
                      betterAnswer: "Kortele, prašau.",
                      progresses: true,
                    },
                    {
                      id: "step_2_repair",
                      text: "Pakartokite, prašau.",
                      textEn: "Please repeat.",
                      result: "repair",
                      feedback: "Valid. If you did not understand the payment question, this is a useful repair phrase.",
                      progresses: true,
                    },
                    {
                      id: "step_2_wrong",
                      text: "Aš esu iš Škotijos.",
                      textEn: "I am from Scotland.",
                      result: "wrong",
                      feedback: "This does not answer the payment question. Choose the answer for paying by card.",
                      progresses: false,
                    },
                  ],
                },
                {
                  id: "step_3_receive_coffee",
                  speakerId: "barista",
                  speakerLabel: "Barista",
                  speakerText: "Prašom, jūsų kava.",
                  speakerTextEn: "Here is your coffee.",
                  sceneDirection: "Ieva places the coffee on the counter.",
                  learnerPrompt: "The barista gives you the coffee. What do you say?",
                  options: [
                    {
                      id: "step_3_best",
                      text: "Ačiū. Geros dienos.",
                      textEn: "Thank you. Have a good day.",
                      result: "best",
                      feedback: "Good. This is polite and naturally closes the interaction.",
                      progresses: true,
                    },
                    {
                      id: "step_3_acceptable",
                      text: "Ačiū.",
                      textEn: "Thank you.",
                      result: "acceptable",
                      feedback: "This is correct. Adding “Geros dienos” gives a warmer ending.",
                      betterAnswer: "Ačiū. Geros dienos.",
                      progresses: true,
                    },
                    {
                      id: "step_3_awkward",
                      text: "Taip.",
                      textEn: "Yes.",
                      result: "awkward",
                      feedback: "This is understandable as acknowledgement, but it sounds unnatural here. A simple “Ačiū” is better.",
                      betterAnswer: "Ačiū.",
                      progresses: true,
                    },
                    {
                      id: "step_3_wrong",
                      text: "Kiek kainuoja?",
                      textEn: "How much does it cost?",
                      result: "wrong",
                      feedback: "You have already paid. The barista is giving you the coffee now.",
                      progresses: false,
                    },
                  ],
                  finalSystemLine: {
                    speakerId: "barista",
                    speakerLabel: "Barista",
                    speakerText: "Geros dienos!",
                    speakerTextEn: "Have a good day!",
                    sceneDirection: "Ieva smiles and turns to the next customer.",
                  },
                },
              ],
            },
          ],
        },

        // ── Lesson 3 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_3",
          code: "1.1.3",
          title: "Sorry and Excuse Me",
          purpose: "Teach interruption and light apology language.",
          supportLevel: "medium",
          newLanguageLoad: "low_to_medium",
          notes: {
            pattern: "One English idea often maps to different Lithuanian words depending on situation.",
            usage: [
              "Atsiprašau — sorry (apology) or excuse me (interruption)",
              "Atleiskite — more formal excuse me / forgive me",
              "Prašau dar kartą — one more time please (when you didn't catch something)",
            ],
          },
          blocks: [
            {
              id: "s1m1l3_b1",
              type: "learn",
              title: "Apology and interruption language",
              items: [
                { id: "sorry_1", lt: "Atsiprašau", en: "Sorry / Excuse me", audioText: "Atsiprašau", saveable: true, core: true },
                { id: "sorry_2", lt: "Prašau dar kartą", en: "One more time, please", audioText: "Prašau dar kartą", saveable: true, core: true },
                { id: "sorry_3", lt: "Atleiskite", en: "Excuse me / Forgive me (formal)", audioText: "Atleiskite", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l3_b2",
              type: "recognise_mcq",
              title: "Choose the right phrase",
              prompt: { text: "You bump into someone lightly and want to apologise." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: true },
                { id: "b", text: "Taip", isCorrect: false },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
            },
            {
              id: "s1m1l3_b3",
              type: "recognise_mcq",
              title: "Choose the right phrase",
              prompt: { text: "You need someone to repeat what they said." },
              options: [
                { id: "a", text: "Prašau dar kartą", isCorrect: true },
                { id: "b", text: "Labas vakaras", isCorrect: false },
                { id: "c", text: "Ne", isCorrect: false },
              ],
            },
            {
              id: "s1m1l3_b3b",
              type: "recognise_mcq",
              title: "Choose the right phrase",
              prompt: { text: "You want to formally excuse yourself — more polite than usual." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: false },
                { id: "b", text: "Atleiskite", isCorrect: true },
                { id: "c", text: "Prašau", isCorrect: false },
              ],
              feedback: { correct: "Atleiskite is the more formal version — used when you want to be especially polite or respectful." },
            },
            {
              id: "s1m1l3_b4",
              type: "build_phrase",
              title: "Build the phrase",
              prompt: { text: "One more time, please" },
              tokens: [
                { id: "t3", text: "kartą", correctIndex: 2 },
                { id: "t1", text: "Prašau", correctIndex: 0 },
                { id: "t2", text: "dar", correctIndex: 1 },
              ],
              answerText: "Prašau dar kartą",
            },
            {
              id: "s1m1l3_b5",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Atsiprašau", audioText: "Atsiprašau" },
              options: [
                { id: "a", text: "Thank you", isCorrect: false },
                { id: "b", text: "Sorry / Excuse me", isCorrect: true },
                { id: "c", text: "Please / Here you go", isCorrect: false },
              ],
            },
            {
              id: "s1m1l3_b5b",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Atleiskite", audioText: "Atleiskite" },
              options: [
                { id: "a", text: "One more time please", isCorrect: false },
                { id: "b", text: "Sorry / Excuse me (casual)", isCorrect: false },
                { id: "c", text: "Excuse me / Forgive me (formal)", isCorrect: true },
              ],
            },
            {
              id: "s1m1l3_b6",
              type: "best_response",
              title: "Use the right phrase",
              prompt: { text: "You want to get someone's attention politely on the street." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: true },
                { id: "b", text: "Iki", isCorrect: false },
                { id: "c", text: "Ne", isCorrect: false },
              ],
              feedback: { correct: "Atsiprašau works both as 'excuse me' to get attention and 'sorry' to apologise." },
            },
            {
              id: "s1m1l3_b7",
              type: "best_response",
              title: "Use the right phrase",
              prompt: { text: "Someone speaks too quickly and you didn't catch it." },
              options: [
                { id: "a", text: "Prašau dar kartą", isCorrect: true },
                { id: "b", text: "Ačiū labai", isCorrect: false },
                { id: "c", text: "Labas rytas", isCorrect: false },
              ],
              feedback: { correct: "Prašau dar kartą — one more time please. A phrase you'll use constantly as a learner." },
            },
          ],
        },

        // ── Lesson 4 ──────────────────────────────────────────────────────────
        {
          id: "section_1_module_1_lesson_4",
          code: "1.1.4",
          title: "Polite Mini Exchanges",
          purpose: "Move from isolated words to short realistic exchanges.",
          supportLevel: "medium",
          newLanguageLoad: "very_low",
          notes: {
            pattern: "This lesson is about chaining phrases together — real conversations are just short chains.",
            usage: [
              "Kaip sekasi? — How are you? (casual, very common)",
              "Gerai, ačiū — Good, thank you (the standard reply)",
              "Puiku — Great (a more upbeat reply)",
            ],
          },
          blocks: [
            {
              id: "s1m1l4_b0",
              type: "learn",
              title: "How are you?",
              items: [
                { id: "ks1", lt: "Kaip sekasi?", en: "How are you?", audioText: "Kaip sekasi", saveable: true, core: true },
                { id: "ks2", lt: "Gerai, ačiū", en: "Good, thank you", audioText: "Gerai, ačiū", saveable: true, core: true },
                { id: "ks3", lt: "Puiku", en: "Great", audioText: "Puiku", saveable: true, core: true },
              ],
            },
            {
              id: "s1m1l4_b0b",
              type: "recognise_mcq",
              title: "Choose the correct meaning",
              prompt: { text: "Kaip sekasi?", audioText: "Kaip sekasi" },
              options: [
                { id: "a", text: "What would you like?", isCorrect: false },
                { id: "b", text: "How are you?", isCorrect: true },
                { id: "c", text: "Where are you going?", isCorrect: false },
              ],
              feedback: { correct: "Kaip sekasi? — you'll hear this constantly. It's casual and warm." },
            },
            {
              id: "s1m1l4_b0c",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone asks: Kaip sekasi?", audioText: "Kaip sekasi" },
              options: [
                { id: "a", text: "Norėčiau kavos, prašau", isCorrect: false },
                { id: "b", text: "Gerai, ačiū", isCorrect: true },
                { id: "c", text: "Atsiprašau", isCorrect: false },
              ],
              feedback: { correct: "Gerai, ačiū — good, thank you. Simple, natural, and expected." },
            },
            {
              id: "s1m1l4_b0d",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "Someone asks Kaip sekasi? — reply out loud",
              targetText: "Gerai, ačiū",
              audioText: "Gerai, ačiū",
            },
            {
              id: "s1m1l4_b0e",
              type: "listen_mcq",
              title: "Listen and choose",
              prompt: { text: "Puiku", audioText: "Puiku" },
              options: [
                { id: "a", text: "Good, thank you", isCorrect: false },
                { id: "b", text: "How are you?", isCorrect: false },
                { id: "c", text: "Great", isCorrect: true },
              ],
            },
            {
              id: "s1m1l4_b0f",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone asks Kaip sekasi? and things are going well." },
              options: [
                { id: "a", text: "Ne, ačiū", isCorrect: false },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Puiku", isCorrect: true },
              ],
              feedback: { correct: "Puiku — great! A more upbeat reply than Gerai, ačiū when things are going well." },
            },
            {
              id: "s1m1l4_b1",
              type: "best_response",
              title: "Choose the correct response",
              prompt: { text: "Someone greets you with Labas as you walk in.", audioText: "Labas" },
              options: [
                { id: "a", text: "Labas!", isCorrect: true },
                { id: "b", text: "Viso gero", isCorrect: false },
                { id: "c", text: "Ne", isCorrect: false },
              ],
              feedback: { correct: "Match the greeting — Labas to Labas." },
            },
            {
              id: "s1m1l4_b2",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "Someone helps you and hands something over saying Prašau.", audioText: "Prašau" },
              options: [
                { id: "a", text: "Ačiū", isCorrect: true },
                { id: "b", text: "Iki", isCorrect: false },
                { id: "c", text: "Labas rytas", isCorrect: false },
              ],
              feedback: { correct: "Prašau here means 'here you go' — Ačiū is the natural reply." },
            },
            {
              id: "s1m1l4_b3",
              type: "speak_self_check",
              title: "Say the response",
              prompt: "Someone says Labas to you — reply out loud",
              targetText: "Labas",
              audioText: "Labas",
            },
            {
              id: "s1m1l4_b4",
              type: "speak_self_check",
              title: "Say the response",
              prompt: "Someone hands you your coffee and says Prašau — reply out loud",
              targetText: "Ačiū",
              audioText: "Ačiū",
            },
            {
              id: "s1m1l4_b5",
              type: "scenario_chain",
              title: "Conversation",
              description: "You're at a hotel reception. The receptionist checks you in.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Laba diena!",
                  audioText: "Laba diena",
                  options: [
                    { id: "a", text: "Laba diena!", isCorrect: true },
                    { id: "b", text: "Ne", isCorrect: false },
                    { id: "c", text: "Ačiū", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Kaip sekasi?",
                  audioText: "Kaip sekasi",
                  options: [
                    { id: "a", text: "Atsiprašau", isCorrect: false },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Gerai, ačiū", isCorrect: true },
                  ],
                },
                {
                  id: "step_3",
                  actor: "other",
                  text: "Prašau.",
                  audioText: "Prašau",
                  options: [
                    { id: "a", text: "Ačiū!", isCorrect: true },
                    { id: "b", text: "Viso gero", isCorrect: false },
                    { id: "c", text: "Atsiprašau", isCorrect: false },
                  ],
                },
                {
                  id: "step_4",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Iki!", isCorrect: true },
                    { id: "b", text: "Taip", isCorrect: false },
                    { id: "c", text: "Prašau dar kartą", isCorrect: false },
                  ],
                },
              ],
            },
          ],
        },

        // ── Checkpoint ────────────────────────────────────────────────────────
        // No verbatim repeats from lessons. Every block uses a new framing,
        // new situation, or reversed prompt so the user has to actually recall
        // rather than recognise something they just saw.
        {
          id: "section_1_module_1_checkpoint",
          code: "1.1.C",
          title: "Checkpoint",
          purpose: "Check you can recall and use Module 1.1 language without support.",
          supportLevel: "none",
          newLanguageLoad: "none",
          isCheckpoint: true,
          blocks: [
            // Greetings — time-of-day reasoning (not just matching a sound)
            {
              id: "s1m1c_b1",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "It's 9am. You walk into a shop. What do you say?" },
              options: [
                { id: "a", text: "Labas vakaras", isCorrect: false },
                { id: "b", text: "Labas rytas", isCorrect: true },
                { id: "c", text: "Viso gero", isCorrect: false },
              ],
              feedback: { correct: "Labas rytas — good morning. Time-appropriate and natural." },
            },
            // Farewell — choose the right register
            {
              id: "s1m1c_b2",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "You're leaving a formal meeting. What's the right farewell?" },
              options: [
                { id: "a", text: "Iki", isCorrect: false },
                { id: "b", text: "Labas", isCorrect: false },
                { id: "c", text: "Viso gero", isCorrect: true },
              ],
              feedback: { correct: "Viso gero is more formal. Iki is casual — save it for friends." },
            },
            // Polite decline — new framing
            {
              id: "s1m1c_b3",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "A waiter offers you dessert and you don't want any." },
              options: [
                { id: "a", text: "Taip, prašau", isCorrect: false },
                { id: "b", text: "Atsiprašau", isCorrect: false },
                { id: "c", text: "Ne, ačiū", isCorrect: true },
              ],
              feedback: { correct: "Ne, ačiū — polite, clear, and natural in any service situation." },
            },
            // Listen — Prašau dar kartą (new context: heard in the wild)
            {
              id: "s1m1c_b4",
              type: "listen_mcq",
              title: "Listen and identify",
              prompt: { text: "Prašau dar kartą", audioText: "Prašau dar kartą" },
              options: [
                { id: "a", text: "Here you go", isCorrect: false },
                { id: "b", text: "One more time, please", isCorrect: true },
                { id: "c", text: "You're welcome", isCorrect: false },
              ],
            },
            // Formal vs informal — Atleiskite vs Atsiprašau
            {
              id: "s1m1c_b5",
              type: "best_response",
              title: "Choose the best response",
              prompt: { text: "You need to interrupt an older person politely to ask for directions." },
              options: [
                { id: "a", text: "Atsiprašau", isCorrect: false },
                { id: "b", text: "Atleiskite", isCorrect: true },
                { id: "c", text: "Prašau dar kartą", isCorrect: false },
              ],
              feedback: { correct: "Atleiskite signals more respect — the right choice with someone older or in a formal context." },
            },
            // Build phrase — Labas vakaras this time (not Labas rytas)
            {
              id: "s1m1c_b6",
              type: "build_phrase",
              title: "Build the phrase",
              prompt: { text: "Good evening" },
              tokens: [
                { id: "t2", text: "vakaras", correctIndex: 1 },
                { id: "t3", text: "rytas", isDistractor: true },
                { id: "t1", text: "Labas", correctIndex: 0 },
              ],
              answerText: "Labas vakaras",
            },
            // Speak — Atsiprašau (different prompt from the lesson)
            {
              id: "s1m1c_b7",
              type: "speak_self_check",
              title: "Say it out loud",
              prompt: "You've just bumped into someone — say sorry",
              targetText: "Atsiprašau",
              audioText: "Atsiprašau",
            },
            // Listen — Ačiū labai in a new option set
            {
              id: "s1m1c_b8",
              type: "listen_mcq",
              title: "Listen and identify",
              prompt: { text: "Ačiū labai", audioText: "Ačiū labai" },
              options: [
                { id: "a", text: "No thank you", isCorrect: false },
                { id: "b", text: "You're welcome", isCorrect: false },
                { id: "c", text: "Thank you very much", isCorrect: true },
              ],
            },
            // Scenario — café order but in reverse: user is the server
            // Tests whether they can produce the right response even when
            // the role is flipped
            {
              id: "s1m1c_b9",
              type: "scenario_chain",
              title: "Conversation",
              description: "You're meeting a Lithuanian colleague for the first time at a café.",
              steps: [
                {
                  id: "step_1",
                  actor: "other",
                  text: "Laba diena!",
                  audioText: "Laba diena",
                  options: [
                    { id: "a", text: "Viso gero!", isCorrect: false },
                    { id: "b", text: "Laba diena!", isCorrect: true },
                    { id: "c", text: "Atsiprašau", isCorrect: false },
                  ],
                },
                {
                  id: "step_2",
                  actor: "other",
                  text: "Kaip sekasi?",
                  audioText: "Kaip sekasi",
                  options: [
                    { id: "a", text: "Ne, ačiū", isCorrect: false },
                    { id: "b", text: "Prašau dar kartą", isCorrect: false },
                    { id: "c", text: "Gerai, ačiū", isCorrect: true },
                  ],
                },
                {
                  id: "step_3",
                  actor: "other",
                  text: "Prašau.",
                  audioText: "Prašau",
                  options: [
                    { id: "a", text: "Ne, ačiū", isCorrect: false },
                    { id: "b", text: "Ačiū labai!", isCorrect: true },
                    { id: "c", text: "Atsiprašau", isCorrect: false },
                  ],
                },
                {
                  id: "step_4",
                  actor: "other",
                  text: "Viso gero!",
                  audioText: "Viso gero",
                  options: [
                    { id: "a", text: "Taip, prašau", isCorrect: false },
                    { id: "b", text: "Labas rytas", isCorrect: false },
                    { id: "c", text: "Iki!", isCorrect: true },
                  ],
                },
              ],
            },
            // Final block — match pairs covering all vocabulary from Module 1.1
            // 17 pairs, 5 per page = 4 pages (last page has 2)
            {
              id: "s1m1c_b10",
              type: "word_match",
              title: "Match the pairs",
              pairs: [
                { id: "m1",  lt: "Labas",                   en: "Hello (casual)",             audioText: "Labas" },
                { id: "m2",  lt: "Laba diena",               en: "Good day / Hello (formal)",  audioText: "Laba diena" },
                { id: "m3",  lt: "Labas rytas",              en: "Good morning",               audioText: "Labas rytas" },
                { id: "m4",  lt: "Labas vakaras",            en: "Good evening",               audioText: "Labas vakaras" },
                { id: "m5",  lt: "Viso gero",                en: "Goodbye (take care)",        audioText: "Viso gero" },
                { id: "m6",  lt: "Iki",                      en: "Bye (casual)",               audioText: "Iki" },
                { id: "m7",  lt: "Taip",                     en: "Yes",                        audioText: "Taip" },
                { id: "m8",  lt: "Ne",                       en: "No",                         audioText: "Ne" },
                { id: "m9",  lt: "Prašau",                   en: "Please / Here you go",       audioText: "Prašau" },
                { id: "m10", lt: "Ačiū",                     en: "Thank you",                  audioText: "Ačiū" },
                { id: "m11", lt: "Ačiū labai",               en: "Thank you very much",        audioText: "Ačiū labai" },
                { id: "m12", lt: "Taip, prašau",             en: "Yes please",                 audioText: "Taip, prašau" },
                { id: "m13", lt: "Ne, ačiū",                 en: "No thank you",               audioText: "Ne, ačiū" },
                { id: "m14", lt: "Norėčiau kavos, prašau",   en: "I'd like a coffee, please",  audioText: "Norėčiau kavos, prašau" },
                { id: "m15", lt: "Atsiprašau",               en: "Sorry / Excuse me",          audioText: "Atsiprašau" },
                { id: "m16", lt: "Prašau dar kartą",         en: "One more time, please",      audioText: "Prašau dar kartą" },
                { id: "m17", lt: "Atleiskite",               en: "Excuse me (formal)",         audioText: "Atleiskite" },
                { id: "m18", lt: "Kaip sekasi?",             en: "How are you?",               audioText: "Kaip sekasi" },
                { id: "m19", lt: "Gerai, ačiū",              en: "Good, thank you",            audioText: "Gerai, ačiū" },
                { id: "m20", lt: "Puiku",                    en: "Great",                      audioText: "Puiku" },
              ],
            },
          ],
        },
      ],
    };

export default module_1_1;
