// src/content/learning/section5/module_5_4.js
// Module 5.4 — Asking and Understanding Directions

export default function createModule_5_4(profile = {}) {
  const { userNameSafe = "Davidas" } = profile;

  return {
    id: "module_5_4",
    code: "5.4",
    title: "Asking and Understanding Directions",
    status: "active",
    lessonCount: 5,
    lessons: [

      // ── Lesson 1 — How Do I Get To…? ─────────────────────────────────────
      {
        id: "section_5_module_4_lesson_1",
        code: "5.4.1",
        title: "How Do I Get To…?",
        purpose: "Teach one of the most valuable route questions in the app.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Kaip man nusigauti į…? is a long phrase but it works as a chunk. You don't need to break it down — just learn it as one unit. It means how do I get to somewhere and it is immediately useful for travel.",
          usage: [
            "Kaip man nusigauti į stotį? — How do I get to the station?",
            "Kaip man nusigauti į viešbutį? — How do I get to the hotel?",
            "Kaip nuvykti į oro uostą? — How do I get to the airport?",
          ],
        },
        blocks: [
          {
            id: "s5m4l1_b1",
            type: "learn",
            title: "How do I get to…?",
            items: [
              { id: "i1", lt: "Kaip man nusigauti į stotį?",   en: "How do I get to the station?",  audioText: "Kaip man nusigauti į stotį",   saveable: true, core: true },
              { id: "i2", lt: "Kaip man nusigauti į viešbutį?",en: "How do I get to the hotel?",    audioText: "Kaip man nusigauti į viešbutį",saveable: true, core: true },
              { id: "i3", lt: "Kaip nuvykti į oro uostą?",     en: "How do I get to the airport?",  audioText: "Kaip nuvykti į oro uostą",     saveable: true, core: false },
            ],
          },
          {
            id: "s5m4l1_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kaip man nusigauti į stotį?", audioText: "Kaip man nusigauti į stotį" },
            options: [
              { id: "a", text: "Where is the station?",        isCorrect: false },
              { id: "b", text: "How do I get to the station?", isCorrect: true  },
              { id: "c", text: "Is the station far?",          isCorrect: false },
            ],
          },
          {
            id: "s5m4l1_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kaip man nusigauti į viešbutį?", audioText: "Kaip man nusigauti į viešbutį" },
            options: [
              { id: "a", text: "Where is the hotel?",           isCorrect: false },
              { id: "b", text: "How do I get to the hotel?",    isCorrect: true  },
              { id: "c", text: "Is the hotel near?",            isCorrect: false },
            ],
          },
          {
            id: "s5m4l1_b4",
            type: "context_gap_select",
            prompt: "Complete the question",
            sentence: "Kaip man nusigauti ___ stotį?",
            translation_en: "How do I get to the station?",
            options: [
              { id: "a", text: "iš",  isCorrect: false },
              { id: "b", text: "į",   isCorrect: true  },
              { id: "c", text: "prie",isCorrect: false },
            ],
            explanation: "Į shows destination — how do I get TO the station. Iš would mean from, which changes the meaning entirely.",
          },
          {
            id: "s5m4l1_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: How do I get to the station?",
            targetText: "Kaip man nusigauti į stotį",
            audioText: "Kaip man nusigauti į stotį",
          },
          {
  id: "s5m4l1_b6_v2",
  type: "scenario_v2",
  title: "Finding the train station",
  description: "You need to get to the train station. Ask for the route, then show that you understood the directions.",
  sceneIntro: "You need to get to the train station. Ask for the route, then show that you understood the directions.",
  location: "street",
  userRole: "traveller",
  register: "polite_service",
  goal: "Use the route question and accurately understand straight/right directions.",
  focus: ["Kaip man nusigauti…?", "tiesiai", "dešinėn", "Ar toli?"],
  participants: [
    { id: "assistant", label: "Local", name: "Rasa", role: "passer-by", gender: "female", relationshipToUser: "stranger", register: "polite_service" },
  ],
  objects: [{ id: "station", lt: "traukinių stotis", en: "train station", gender: "feminine", number: "singular" }],
  steps: [
    {
      id: "step_1",
      speakerId: "assistant",
      speakerLabel: "Local",
      speakerText: "Laba diena! Ar galiu padėti?",
      sceneDirection: "You need the train station.",
      learnerPrompt: "Choose the question for the place you actually need.",
      options: [
        { id: "a", text: "Laba diena! Kaip man nusigauti į traukinių stotį?", result: "best", progresses: true },
        { id: "b", text: "Laba diena! Kaip man nusigauti į autobusų stotį?", result: "wrong", feedback: "That asks for the bus station, not the train station.", progresses: false },
        { id: "c", text: "Laba diena! Kaip man nusigauti į viešbutį?", result: "wrong", feedback: "That asks for the hotel.", progresses: false },
      ],
    },
    {
      id: "step_2",
      speakerId: "assistant",
      speakerLabel: "Local",
      speakerText: "Eikite tiesiai, paskui pasukite dešinėn.",
      sceneDirection: "Rasa says: go straight, then turn right.",
      learnerPrompt: "Confirm the route you heard, then ask whether it is far.",
      options: [
        { id: "a", text: "Tiesiai, paskui dešinėn? Ar toli?", result: "best", progresses: true },
        { id: "b", text: "Tiesiai, paskui kairėn? Ar toli?", result: "wrong", feedback: "She said right — dešinėn — not left.", progresses: false },
        { id: "c", text: "Dešinėn, paskui tiesiai? Ar toli?", result: "wrong", feedback: "The order is reversed. She said straight first, then right.", progresses: false },
      ],
    },
    {
      id: "step_3",
      speakerId: "assistant",
      speakerLabel: "Local",
      speakerText: "Ne, tai netoli. Penkios minutės.",
      sceneDirection: "The train station is nearby, only five minutes away.",
      learnerPrompt: "Respond naturally to the short distance.",
      options: [
        { id: "a", text: "Puiku! Ačiū labai.", result: "best", progresses: true },
        { id: "b", text: "Gerai, ačiū.", result: "acceptable", feedback: "That is also a natural response.", progresses: true },
        { id: "c", text: "Penkios minutės? Tai labai toli.", result: "wrong", feedback: "The speaker has just described five minutes as nearby.", progresses: false },
      ],
      finalSystemLine: { speakerId: "assistant", speakerLabel: "Local", speakerText: "Prašom. Geros kelionės!", supportText: "geros kelionės — have a good journey", sceneDirection: "Rasa wishes you a good journey and the exchange ends." },
    },
  ],
},
        ],
      },

      // ── Lesson 2 — Is It Far? ─────────────────────────────────────────────
      {
        id: "section_5_module_4_lesson_2",
        code: "5.4.2",
        title: "Is It Far?",
        purpose: "Reuse familiar near/far language while following and checking a route.",
        supportLevel: "high",
        newLanguageLoad: "none",
        blocks: [
          {
            id: "s5m4l2_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Labai toli.", audioText: "Labai toli" },
            options: [
              { id: "a", text: "Not far.",  isCorrect: false },
              { id: "b", text: "Very far.", isCorrect: true  },
              { id: "c", text: "Near.",     isCorrect: false },
            ],
          },
          {
            id: "s5m4l2_b3",
            type: "best_response",
            title: "Choose the useful follow-up",
            prompt: { text: "A local tells you: Eikite tiesiai. You still need to know whether the hotel is far. What do you ask?" },
            options: [
              { id: "a", text: "Ar toli?", isCorrect: true },
              {
                id: "b",
                text: "Ačiū labai.",
                isCorrect: false,
                result: "awkward",
                feedback: "A thank-you is natural, but it does not get the distance information you still need.",
                betterAnswer: "Ar toli?",
              },
              { id: "c", text: "Kur yra stotis?", isCorrect: false },
            ],
            feedback: {
              correct: "Ar toli? — Is it far? That is the useful follow-up once you already have the direction.",
            },
          },
          {
            id: "s5m4l2_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Is it far?",
            targetText: "Ar tai toli",
            audioText: "Ar tai toli",
          },
          {
  id: "s5m4l2_b5_v2",
  type: "scenario_v2",
  title: "Finding the pharmacy",
  description: "You are on the street and need a pharmacy. Ask a passer-by how to get there, then check the distance.",
  sceneIntro: "You are on the street and need a pharmacy. Ask a passer-by how to get there, then check the distance.",
  location: "street",
  userRole: "traveller",
  register: "polite_neutral",
  goal: "Use the route question for the correct destination and ask a natural distance follow-up.",
  focus: ["Kaip man nusigauti…?", "vaistinė", "Ar toli?"],
  participants: [
    { id: "pharmacist", label: "Local", name: "Rasa", role: "passer-by", gender: "female", relationshipToUser: "stranger", register: "polite_neutral" },
  ],
  objects: [{ id: "pharmacy", lt: "vaistinė", en: "pharmacy", gender: "feminine", number: "singular" }],
  steps: [
    {
      id: "step_1",
      speakerId: "pharmacist",
      speakerLabel: "Local",
      speakerText: "Laba diena!",
      sceneDirection: "You need the pharmacy.",
      learnerPrompt: "Use the new route question for the correct destination.",
      options: [
        { id: "a", text: "Laba diena! Kaip man nusigauti į vaistinę?", result: "best", progresses: true },
        { id: "b", text: "Laba diena! Kaip man nusigauti į viešbutį?", result: "wrong", feedback: "That asks for the hotel, not the pharmacy.", progresses: false },
        { id: "c", text: "Laba diena! Kaip man nusigauti į stotį?", result: "wrong", feedback: "That asks for the station, not the pharmacy.", progresses: false },
      ],
    },
    {
      id: "step_2",
      speakerId: "pharmacist",
      speakerLabel: "Local",
      speakerText: "Eikite tiesiai.",
      sceneDirection: "Rasa tells you to go straight. You also want to know the distance to the pharmacy.",
      learnerPrompt: "Ask whether the pharmacy is far.",
      options: [
        { id: "a", text: "Ačiū. Ar vaistinė toli?", result: "best", progresses: true },
        { id: "b", text: "Ačiū. Ar toli?", result: "acceptable", feedback: "The shorter question is natural because the destination is already clear.", progresses: true },
        { id: "c", text: "Ačiū. Ar viešbutis toli?", result: "wrong", feedback: "You are asking about the pharmacy, not the hotel.", progresses: false },
      ],
    },
    {
      id: "step_3",
      speakerId: "pharmacist",
      speakerLabel: "Local",
      speakerText: "Ne, netoli. Trys minutės.",
      sceneDirection: "The pharmacy is nearby, only three minutes away.",
      learnerPrompt: "Respond naturally to the short distance.",
      options: [
        { id: "a", text: "Puiku! Ačiū labai.", result: "best", progresses: true },
        { id: "b", text: "Ačiū!", result: "acceptable", feedback: "A shorter thank-you is also natural.", progresses: true },
        { id: "c", text: "Trys minutės? Tai labai toli.", result: "wrong", feedback: "The speaker has just described three minutes as nearby.", progresses: false },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 3 — Go Left / Go Right / Go Straight ───────────────────────
      {
        id: "section_5_module_4_lesson_3",
        code: "5.4.3",
        title: "Chaining Directions",
        purpose: "Practice chaining familiar direction instructions into short routes.",
        supportLevel: "medium",
        newLanguageLoad: "none",
        notes: {
          pattern: "You already know the direction instructions and paskui. This lesson combines them into short routes such as Tiesiai, paskui kairėn.",
          usage: [
            "Eikite tiesiai — go straight ahead",
            "Pasukite kairėn — turn left",
            "Pasukite dešinėn — turn right",
            "Tiesiai, paskui kairėn — straight, then left",
          ],
        },
        blocks: [
          {
            id: "s5m4l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Pasukite dešinėn.", audioText: "Pasukite dešinėn" },
            options: [
              { id: "a", text: "Go straight ahead.", isCorrect: false },
              { id: "b", text: "Turn left.",         isCorrect: false },
              { id: "c", text: "Turn right.",        isCorrect: true  },
            ],
          },
          {
            id: "s5m4l3_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Tiesiai, paskui kairėn.", audioText: "Tiesiai, paskui kairėn" },
            options: [
              { id: "a", text: "Left, then straight.",  isCorrect: false },
              { id: "b", text: "Straight, then left.",  isCorrect: true  },
              { id: "c", text: "Straight, then right.", isCorrect: false },
            ],
          },
          {
            id: "s5m4l3_b4",
            type: "context_gap_select",
            prompt: "Complete the directions",
            sentence: "Eikite tiesiai, paskui ___ kairėn.",
            translation_en: "Go straight, then turn left.",
            options: [
              { id: "a", text: "eikite",   isCorrect: false },
              { id: "b", text: "pasukite", isCorrect: true  },
              { id: "c", text: "ar",       isCorrect: false },
            ],
            explanation: "Pasukite means turn — it's the you-form command. Eikite means go. Straight uses eikite, turns use pasukite.",
          },
          {
            id: "s5m4l3_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: Turn left",
            targetText: "Pasukite kairėn",
            audioText: "Pasukite kairėn",
          },
          {
  id: "s5m4l3_b6_v2",
  type: "scenario_v2",
  title: "Give the directions",
  description: "Someone asks you how to reach the bus station. You know the route is straight ahead, then left at the next junction.",
  sceneIntro: "Someone asks you how to reach the bus station. You know the route is straight ahead, then left at the next junction.",
  location: "street",
  userRole: "local helper",
  register: "polite_neutral",
  goal: "Produce and confirm the correct two-part route.",
  focus: ["tiesiai", "kairėn", "paskui"],
  participants: [
    { id: "assistant", label: "Traveller", name: "Rasa", role: "traveller", gender: "female", relationshipToUser: "stranger", register: "polite_neutral" },
  ],
  objects: [{ id: "station", lt: "autobusų stotis", en: "bus station", gender: "feminine", number: "singular" }],
  steps: [
    {
      id: "step_1",
      speakerId: "assistant",
      speakerLabel: "Traveller",
      speakerText: "Atsiprašau! Kaip man nusigauti į autobusų stotį?",
      sceneDirection: "The correct route is straight ahead, then left at the next junction.",
      learnerPrompt: "Choose the directions that match the route.",
      options: [
        { id: "a", text: "Eikite tiesiai, paskui pasukite kairėn.", result: "best", progresses: true },
        { id: "b", text: "Eikite tiesiai, paskui pasukite dešinėn.", result: "wrong", feedback: "The second turn is left — kairėn — not right.", progresses: false },
        { id: "c", text: "Pasukite kairėn, paskui eikite tiesiai.", result: "wrong", feedback: "The actions are reversed. Go straight first, then turn left.", progresses: false },
      ],
    },
    {
      id: "step_2",
      speakerId: "assistant",
      speakerLabel: "Traveller",
      speakerText: "Suprantu. Tiesiai, paskui kairėn?",
      sceneDirection: "The traveller repeats the correct route back to you.",
      learnerPrompt: "Confirm the route accurately.",
      options: [
        { id: "a", text: "Taip, tiesiai, paskui kairėn.", result: "best", progresses: true },
        { id: "b", text: "Ne, tiesiai, paskui dešinėn.", result: "wrong", feedback: "That changes the left turn to a right turn.", progresses: false },
        { id: "c", text: "Ne, kairėn, paskui tiesiai.", result: "wrong", feedback: "That reverses the order of the route.", progresses: false },
      ],
      finalSystemLine: { speakerId: "assistant", speakerLabel: "Traveller", speakerText: "Ačiū labai!", sceneDirection: "The traveller thanks you and heads toward the station." },
    },
  ],
},
        ],
      },

      // ── Lesson 4 — On Foot / By Bus ───────────────────────────────────────
      {
        id: "section_5_module_4_lesson_4",
        code: "5.4.4",
        title: "On Foot / By Bus",
        purpose: "Teach very basic route-mode language.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Lithuanian uses different movement verbs depending on how you travel. Eiti means to go / walk on foot; you already know eikite, the polite command form used in directions. Važiuoti means to go / travel by a vehicle. After galite (you can), use eiti when the person can walk and važiuoti when they can travel by bus, car, train, and similar transport.",
          usage: [
            "eiti — to go / walk on foot",
            "eikite — go / walk (polite command; already familiar from directions)",
            "važiuoti — to go / travel by vehicle",
            "Galite eiti pėsčiomis. — You can go on foot.",
            "Galite važiuoti autobusu. — You can go by bus.",
          ],
        },
        blocks: [
          {
            id: "s5m4l4_b1",
            type: "learn",
            title: "How to get there",
            items: [
              { id: "i1", lt: "pėsčiomis",                   en: "on foot",              audioText: "pėsčiomis",                   saveable: true, core: true },
              { id: "i2", lt: "autobusu",                    en: "by bus",               audioText: "autobusu",                    saveable: true, core: true },
              { id: "i3", lt: "Galite eiti pėsčiomis.",      en: "You can go on foot.",  audioText: "Galite eiti pėsčiomis",       saveable: true, core: true },
              { id: "i4", lt: "Galite važiuoti autobusu.",   en: "You can go by bus.",   audioText: "Galite važiuoti autobusu",    saveable: true, core: true },
            ],
          },
          {
            id: "s5m4l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Galite eiti pėsčiomis.", audioText: "Galite eiti pėsčiomis" },
            options: [
              { id: "a", text: "You can go by bus.",   isCorrect: false },
              { id: "b", text: "You can go on foot.",  isCorrect: true  },
              { id: "c", text: "You can go by taxi.",  isCorrect: false },
            ],
          },
          {
            id: "s5m4l4_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Someone asks: Kaip man nusigauti į stotį? It's a 20 minute walk but there's a bus. What do you suggest?", audioText: "" },
            options: [
              { id: "a", text: "Tai labai toli.",              isCorrect: false },
              { id: "b", text: "Galite važiuoti autobusu.",    isCorrect: true  },
              { id: "c", text: "Eikite tiesiai.",              isCorrect: false },
            ],
            feedback: { correct: "Galite važiuoti autobusu — you can go by bus. The practical suggestion when walking is inconvenient." },
          },
          {
            id: "s5m4l4_b4",
            type: "context_gap_select",
            prompt: "Complete the reply",
            sentence: "Stotis netoli. Galite eiti ___.",
            translation_en: "The station is near. You can go on foot.",
            options: [
              { id: "a", text: "autobusu",   isCorrect: false },
              { id: "b", text: "pėsčiomis",  isCorrect: true  },
              { id: "c", text: "taksi",     isCorrect: false },
            ],
            explanation: "Netoli (not far) makes pėsčiomis (on foot) the natural suggestion. Autobusu would suit a longer distance.",
          },
          {
            id: "s5m4l4_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: You can go by bus",
            targetText: "Galite važiuoti autobusu",
            audioText: "Galite važiuoti autobusu",
          },
          {
  id: "s5m4l4_b6_v2",
  type: "scenario_v2",
  title: "Getting to the airport",
  description: "You need to reach the airport. It is too far to walk, so after asking the route you need to find the bus stop.",
  sceneIntro: "You need to reach the airport. It is too far to walk, so after asking the route you need to find the bus stop.",
  location: "street",
  userRole: "traveller",
  register: "polite_neutral",
  goal: "Ask for the correct destination, follow transport advice, and understand a final direction.",
  focus: ["oro uostas", "autobusu", "autobusų stotelė", "kairėn"],
  participants: [
    { id: "local", label: "Local", name: "Rasa", role: "passer-by", gender: "female", relationshipToUser: "stranger", register: "polite_neutral" },
  ],
  objects: [
    { id: "airport", lt: "oro uostas", en: "airport", gender: "masculine", number: "singular" },
    { id: "bus", lt: "autobusas", en: "bus", gender: "masculine", number: "singular" },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Laba diena! Ar galiu padėti?",
      sceneDirection: "You need to get to the airport.",
      learnerPrompt: "Choose the question for the destination you actually need.",
      options: [
        { id: "a", text: "Laba diena! Kaip nuvykti į oro uostą?", result: "best", progresses: true },
        { id: "b", text: "Laba diena! Kaip man nusigauti į autobusų stotį?", result: "wrong", feedback: "That asks for the bus station, not the airport.", progresses: false },
        { id: "c", text: "Laba diena! Kaip man nusigauti į viešbutį?", result: "wrong", feedback: "That asks for the hotel.", progresses: false },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Oro uostas yra toli. Galite važiuoti autobusu.",
      sceneDirection: "The airport is far, so you decide to take the bus.",
      learnerPrompt: "Ask for the bus stop you need next.",
      options: [
        { id: "a", text: "Suprantu. Kur yra autobusų stotelė?", result: "best", progresses: true },
        { id: "b", text: "Suprantu. Kur yra autobusų stotis?", result: "wrong", feedback: "You need the nearby bus stop — stotelė — not the bus station.", progresses: false },
        { id: "c", text: "Suprantu. Kur yra traukinių stotis?", result: "wrong", feedback: "That asks for the train station instead of the bus stop.", progresses: false },
      ],
    },
    {
      id: "step_3",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Stotelė yra ten, kairėn. Netoli.",
      sceneDirection: "Rasa points out the nearby bus stop to the left.",
      learnerPrompt: "Confirm the direction you heard and close the exchange.",
      options: [
        { id: "a", text: "Kairėn? Puiku, ačiū labai. Viso gero.", result: "best", progresses: true },
        { id: "b", text: "Dešinėn? Puiku, ačiū labai. Viso gero.", result: "wrong", feedback: "She said left — kairėn — not right.", progresses: false },
        { id: "c", text: "Tiesiai? Puiku, ačiū labai. Viso gero.", result: "wrong", feedback: "She pointed to the left, not straight ahead.", progresses: false },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 5 — Short Direction Scenario ──────────────────────────────
      {
        id: "section_5_module_4_lesson_5",
        code: "5.4.5",
        title: "Short Direction Scenario",
        purpose: "Bring route language together in a practical exchange.",
        supportLevel: "medium",
        newLanguageLoad: "very_low",
        blocks: [
          {
            id: "s5m4l5_b1",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Galite važiuoti autobusu arba eiti pėsčiomis.", audioText: "Galite važiuoti autobusu arba eiti pėsčiomis" },
            options: [
              { id: "a", text: "You can only go by bus.",                   isCorrect: false },
              { id: "b", text: "You can go by bus or on foot.",             isCorrect: true  },
              { id: "c", text: "You should go on foot, not by bus.",        isCorrect: false },
            ],
          },
          {
            id: "s5m4l5_b2",
            type: "listen_mcq",
            title: "Understand the route",
            prompt: {
              text: "Eikite tiesiai, paskui pasukite dešinėn.",
              audioText: "Eikite tiesiai, paskui pasukite dešinėn",
            },
            options: [
              { id: "a", text: "Go straight, then turn left.",  isCorrect: false },
              { id: "b", text: "Go straight, then turn right.", isCorrect: true  },
              { id: "c", text: "Turn right, then go straight.", isCorrect: false },
            ],
          },
          {
            id: "s5m4l5_b3",
            type: "listen_mcq",
            title: "Listen to the route",
            prompt: {
              text: "Eikite tiesiai, paskui pasukite kairėn.",
              audioText: "Eikite tiesiai, paskui pasukite kairėn",
            },
            options: [
              { id: "a", text: "Go straight, then turn left.", isCorrect: true },
              { id: "b", text: "Turn left, then go straight.", isCorrect: false },
              { id: "c", text: "Go straight, then turn right.", isCorrect: false },
            ],
          },
          {
            id: "s5m4l5_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: How do I get to the hotel?",
            targetText: "Kaip man nusigauti į viešbutį",
            audioText: "Kaip man nusigauti į viešbutį",
          },
          {
  id: "s5m4l5_b5_v2",
  type: "scenario_v2",
  title: "Find the bus station",
  description: "You need the bus station. You are happy to walk if it is reasonably close.",
  sceneIntro: "You need the bus station. You are happy to walk if it is reasonably close.",
  location: "street",
  userRole: "traveller",
  register: "polite_neutral",
  goal: "Ask for the right place, verify the route, check distance and act on the answer.",
  focus: ["autobusų stotis", "directions", "Ar toli?", "pėsčiomis"],
  participants: [
    { id: "local", label: "Local", name: "Rasa", role: "passer-by", gender: "female", relationshipToUser: "stranger", register: "polite_neutral" },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Laba diena! Ar galiu padėti?",
      sceneDirection: "You need the bus station.",
      learnerPrompt: "Choose the question for the correct destination.",
      options: [
        { id: "a", text: "Laba diena! Atsiprašau, kaip man nusigauti į autobusų stotį?", result: "best", progresses: true },
        { id: "b", text: "Laba diena! Atsiprašau, kaip man nusigauti į traukinių stotį?", result: "wrong", feedback: "That asks for the train station, not the bus station.", progresses: false },
        { id: "c", text: "Laba diena! Atsiprašau, kaip man nusigauti į vaistinę?", result: "wrong", feedback: "That asks for the pharmacy.", progresses: false },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Eikite tiesiai, paskui pasukite kairėn.",
      sceneDirection: "Rasa gives you a two-part route.",
      learnerPrompt: "What route did Rasa give you?",
      interactionMode: "comprehension",
      help: {
        levels: [
          { sceneDirection: "Rasa points straight ahead, then gestures left.", speakerText: "Tiesiai. Paskui kairėn." },
          { sceneDirection: "She traces the route with her finger: straight, then left." },
          { speakerText: "Straight, then left.", spokenLanguage: "en", audio: false },
        ],
      },
      options: [
        { id: "a", text: "Go straight, then turn left.", result: "best", progresses: true },
        { id: "b", text: "Go straight, then turn right.", result: "wrong", feedback: "Dešinėn is right; Rasa said kairėn — left.", progresses: false },
        { id: "c", text: "Turn left, then go straight.", result: "wrong", feedback: "The order is reversed. Rasa said straight first, then left.", progresses: false },
      ],
    },
    {
      id: "step_3",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Nelabai toli. Galite eiti pėsčiomis — dešimt minučių.",
      sceneDirection: "Rasa adds that it is not very far and that you can walk. Ten minutes is fine for you.",
      learnerPrompt: "Respond consistently with your decision to walk.",
      options: [
        { id: "a", text: "Puiku! Ačiū labai.", result: "best", progresses: true },
        { id: "b", text: "Gerai, ačiū.", result: "acceptable", feedback: "That is also a natural response.", progresses: true },
        { id: "c", text: "Ne, per toli.", result: "wrong", feedback: "The scene says ten minutes is fine for you.", progresses: false },
      ],
      finalSystemLine: { speakerId: "local", speakerLabel: "Local", speakerText: "Prašom! Viso gero.", sceneDirection: "Rasa says goodbye and the exchange ends." },
    },
  ],
},
        ],
      },

      // ── Module 5.4 Checkpoint ─────────────────────────────────────────────
      {
        id: "section_5_module_4_checkpoint",
        code: "5.4.C",
        title: "Directions Check",
        purpose: "Confirm route-asking and direction-following is working.",
        supportLevel: "low",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s5m4c_b1",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kaip man nusigauti į viešbutį?", audioText: "Kaip man nusigauti į viešbutį" },
            options: [
              { id: "a", text: "Where is the hotel?",           isCorrect: false },
              { id: "b", text: "How do I get to the hotel?",    isCorrect: true  },
              { id: "c", text: "Is the hotel far?",             isCorrect: false },
            ],
          },
          {
            id: "s5m4c_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Galite eiti pėsčiomis.", audioText: "Galite eiti pėsčiomis" },
            options: [
              { id: "a", text: "You can go by bus.",   isCorrect: false },
              { id: "b", text: "You can go on foot.",  isCorrect: true  },
              { id: "c", text: "You should take a taxi.", isCorrect: false },
            ],
          },
          {
            id: "s5m4c_b3",
            type: "context_gap_select",
            prompt: "Complete the reply",
            sentence: "Stotis yra toli. Galite važiuoti ___.",
            translation_en: "The station is far. You can go by bus.",
            options: [
              { id: "a", text: "pėsčiomis", isCorrect: false },
              { id: "b", text: "autobusu",  isCorrect: true  },
              { id: "c", text: "tiesiai",   isCorrect: false },
            ],
            explanation: "Toli (far) makes autobusu (by bus) the logical suggestion. Pėsčiomis (on foot) suits short distances.",
          },
          {
            id: "s5m4c_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: How do I get to the station?",
            targetText: "Kaip man nusigauti į stotį",
            audioText: "Kaip man nusigauti į stotį",
          },
          {
            id: "s5m4c_b5",
            type: "build_phrase",
            title: "Build the route",
            prompt: { text: "Build: Go straight, then turn right." },
            tokens: [
              { id: "t1", text: "Eikite", correctIndex: 0 },
              { id: "t2", text: "tiesiai,", correctIndex: 1 },
              { id: "t3", text: "paskui", correctIndex: 2 },
              { id: "t4", text: "pasukite", correctIndex: 3 },
              { id: "t5", text: "dešinėn.", correctIndex: 4 },
              { id: "t6", text: "kairėn.", isDistractor: true, repairHint: "Kairėn is to the left. The route turns right." },
              { id: "t7", text: "toli.", isDistractor: true, repairHint: "Toli describes distance, not the next route action." },
            ],
            answerText: "Eikite tiesiai, paskui pasukite dešinėn.",
          },
          {
  id: "s5m4c_b6_v2",
  type: "scenario_v2",
  title: "Route and transport check",
  description: "You need the train station. If it is far, you are willing to take a bus.",
  sceneIntro: "You need the train station. If it is far, you are willing to take a bus.",
  location: "street",
  userRole: "traveller",
  register: "polite_neutral",
  goal: "Combine destination, route, distance and transport language in one grounded exchange.",
  focus: ["traukinių stotis", "directions", "autobusu", "autobusų stotelė"],
  participants: [
    { id: "local", label: "Local", name: "Rasa", role: "passer-by", gender: "female", relationshipToUser: "stranger", register: "polite_neutral" },
  ],
  objects: [
    { id: "station", lt: "traukinių stotis", en: "train station", gender: "feminine", number: "singular" },
    { id: "bus", lt: "autobusas", en: "bus", gender: "masculine", number: "singular" },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Laba diena! Ar galiu jums padėti?",
      sceneDirection: "You need the train station.",
      learnerPrompt: "Choose the question for the correct destination.",
      options: [
        { id: "a", text: "Taip! Kaip man nusigauti į traukinių stotį?", result: "best", progresses: true },
        { id: "b", text: "Taip! Kaip man nusigauti į autobusų stotį?", result: "wrong", feedback: "That asks for the bus station, not the train station.", progresses: false },
        { id: "c", text: "Taip! Kaip man nusigauti į viešbutį?", result: "wrong", feedback: "That asks for the hotel.", progresses: false },
      ],
    },
    {
      id: "step_2",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Eikite tiesiai, paskui pasukite kairėn.",
      sceneDirection: "Rasa gives you a two-part route.",
      learnerPrompt: "What route did Rasa give you?",
      interactionMode: "comprehension",
      help: {
        levels: [
          { sceneDirection: "The local points straight ahead, then clearly gestures left.", speakerText: "Tiesiai. Kairėn." },
          { sceneDirection: "They trace the route with a finger: straight, then left." },
          { speakerText: "Straight, then left.", spokenLanguage: "en", audio: false },
        ],
      },
      options: [
        { id: "a", text: "Go straight, then turn left.", result: "best", progresses: true },
        { id: "b", text: "Go straight, then turn right.", result: "wrong", feedback: "Dešinėn is right; Rasa said kairėn — left.", progresses: false },
        { id: "c", text: "Turn left, then go straight.", result: "wrong", feedback: "The order is reversed. Rasa said straight first, then left.", progresses: false },
      ],
    },
    {
      id: "step_3",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Šiek tiek toli. Galite važiuoti autobusu.",
      sceneDirection: "Rasa adds that it is a bit far and suggests the bus, so you decide to take it.",
      learnerPrompt: "Ask for the bus stop you need next.",
      options: [
        { id: "a", text: "Suprantu. Kur yra autobusų stotelė?", result: "best", progresses: true },
        { id: "b", text: "Suprantu. Kur yra autobusų stotis?", result: "wrong", feedback: "You need the nearby bus stop — stotelė — not the bus station.", progresses: false },
        { id: "c", text: "Suprantu. Kur yra traukinių stotis?", result: "wrong", feedback: "That repeats your final destination instead of asking for the bus stop.", progresses: false },
      ],
    },
    {
      id: "step_4",
      speakerId: "local",
      speakerLabel: "Local",
      speakerText: "Stotelė yra ten, dešinėn. Netoli.",
      sceneDirection: "Rasa gives you the bus-stop location.",
      learnerPrompt: "Where did Rasa say the bus stop is?",
      interactionMode: "comprehension",
      options: [
        { id: "a", text: "Over there, to the right.", result: "best", progresses: true },
        { id: "b", text: "Over there, to the left.", result: "wrong", feedback: "Kairėn is left; Rasa said dešinėn — right.", progresses: false },
        { id: "c", text: "Straight ahead.", result: "wrong", feedback: "Rasa said the stop is over there, to the right.", progresses: false },
      ],
      finalSystemLine: { speakerId: "local", speakerLabel: "Local", speakerText: "Viso gero!", sceneDirection: "The exchange ends." },
    },
  ],
},
          {
            id: "s5m4c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Kaip man nusigauti į stotį?",    en: "How do I get to the station?",   audioText: "Kaip man nusigauti į stotį" },
              { id: "m2",  lt: "Kaip man nusigauti į viešbutį?", en: "How do I get to the hotel?",     audioText: "Kaip man nusigauti į viešbutį" },
              { id: "m3",  lt: "Kaip nuvykti į oro uostą?",      en: "How do I get to the airport?",   audioText: "Kaip nuvykti į oro uostą" },
              { id: "m4",  lt: "Ar toli?",                   en: "Is it far?",                     audioText: "Ar tai toli" },
              { id: "m5",  lt: "Ar netoli?",                 en: "Is it near?",                    audioText: "Ar tai netoli" },
              { id: "m6",  lt: "Netoli.",                        en: "Not far.",                       audioText: "Netoli" },
              { id: "m7",  lt: "Labai toli.",                    en: "Very far.",                      audioText: "Labai toli" },
              { id: "m8",  lt: "Eikite tiesiai.",                en: "Go straight ahead.",             audioText: "Eikite tiesiai" },
              { id: "m9",  lt: "Pasukite kairėn.",               en: "Turn left.",                     audioText: "Pasukite kairėn" },
              { id: "m10", lt: "Pasukite dešinėn.",              en: "Turn right.",                    audioText: "Pasukite dešinėn" },
              { id: "m11", lt: "Tiesiai, paskui kairėn.",        en: "Straight, then left.",           audioText: "Tiesiai, paskui kairėn" },
              { id: "m12", lt: "pėsčiomis",                      en: "on foot",                        audioText: "pėsčiomis" },
              { id: "m13", lt: "autobusu",                       en: "by bus",                         audioText: "autobusu" },
              { id: "m14", lt: "Galite eiti pėsčiomis.",         en: "You can go on foot.",            audioText: "Galite eiti pėsčiomis" },
              { id: "m15", lt: "Galite važiuoti autobusu.",      en: "You can go by bus.",             audioText: "Galite važiuoti autobusu" },
              { id: "m16", lt: "Suprantu.",                      en: "I understand.",                  audioText: "Suprantu" },
              { id: "m17", lt: "šiek tiek toli",                 en: "a bit far",                      audioText: "šiek tiek toli" },
              { id: "m18", lt: "arba",                           en: "or",                             audioText: "arba" },
              { id: "m19", lt: "Geros kelionės!",                en: "Have a good journey!",           audioText: "Geros kelionės" },
              { id: "m20", lt: "Nelabai.",                       en: "Not really.",                    audioText: "Nelabai" },
            ],
          },
        ],
      },
    ],
  };
}
