// src/content/learning/section5/module_5_1.js
// Module 5.1 — Where Is…?

export default function createModule_5_1(profile = {}) {
  const { userNameSafe = "Davidas" } = profile;

  return {
    id: "module_5_1",
    code: "5.1",
    title: "Where Is…?",
    status: "active",
    lessonCount: 5,
    lessons: [

      // ── Lesson 1 — Where Is…? ─────────────────────────────────────────────
      {
        id: "section_5_module_1_lesson_1",
        code: "5.1.1",
        title: "Where Is…?",
        purpose: "Lock in the main question frame for location.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Kur yra…? is one of the most useful frames in the whole app. It works with any place word. You already know several — stotis, tualetas, viešbutis, vaistinė all slot straight in.",
          usage: [
            "Kur yra stotis? — Where is the station?",
            "Kur yra tualetas? — Where is the toilet?",
            "Kur yra viešbutis? — Where is the hotel?",
            "Kur yra vaistinė? — Where is the pharmacy?",
          ],
        },
        blocks: [
          {
            id: "s5m1l1_b1",
            type: "learn",
            title: "Where is…?",
            items: [
              { id: "i1", lt: "Kur yra…?",          en: "Where is…?",            audioText: "Kur yra",           saveable: true,  core: true  },
              { id: "i2", lt: "Kur yra stotis?",     en: "Where is the station?", audioText: "Kur yra stotis",    saveable: true,  core: true  },
              { id: "i3", lt: "Kur yra tualetas?",   en: "Where is the toilet?",  audioText: "Kur yra tualetas",  saveable: true,  core: true  },
              { id: "i4", lt: "Kur yra viešbutis?",  en: "Where is the hotel?",   audioText: "Kur yra viešbutis", saveable: true,  core: true  },
              { id: "i5", lt: "Kur yra vaistinė?",   en: "Where is the pharmacy?",audioText: "Kur yra vaistinė",  saveable: true,  core: true  },
            ],
          },
          {
            id: "s5m1l1_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kur yra stotis?", audioText: "Kur yra stotis" },
            options: [
              { id: "a", text: "Where is the hotel?",    isCorrect: false },
              { id: "b", text: "Where is the station?",  isCorrect: true  },
              { id: "c", text: "Where is the toilet?",   isCorrect: false },
            ],
          },
          {
            id: "s5m1l1_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kur yra vaistinė?", audioText: "Kur yra vaistinė" },
            options: [
              { id: "a", text: "Where is the hotel?",    isCorrect: false },
              { id: "b", text: "Where is the pharmacy?", isCorrect: true  },
              { id: "c", text: "Where is the toilet?",   isCorrect: false },
            ],
          },
          {
            id: "s5m1l1_b4",
            type: "context_gap_select",
            prompt: "Choose the correct word",
            sentence: "Atsiprašau, ___ yra tualetas?",
            translation_en: "Excuse me, where is the toilet?",
            options: [
              { id: "a", text: "Kas",  isCorrect: false },
              { id: "b", text: "Kur",  isCorrect: true  },
              { id: "c", text: "Kada", isCorrect: false },
            ],
            explanation: "Kur means where. Kas means what or who, Kada means when.",
          },
          {
            id: "s5m1l1_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Where is the hotel?",
            targetText: "Kur yra viešbutis",
            audioText: "Kur yra viešbutis",
          },
          {
            id: "s5m1l1_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You've just arrived in a Lithuanian city. You need the pharmacy.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ar galiu jums padėti?",
                audioText: "Laba diena! Ar galiu jums padėti",
                helperText: "Good day! Can I help you?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Laba diena! Atsiprašau, kur yra vaistinė?", en: "Good day! Excuse me, where is the pharmacy?", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Vaistinė yra ten.",
                audioText: "Vaistinė yra ten",
                helperText: "The pharmacy is over there.",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom. Viso gero!",
                audioText: "Prašom. Viso gero",
                helperText: "You're welcome. Goodbye!",
                options: [
                  { id: "a", text: "Laba diena.", isCorrect: false },
                  { id: "b", text: "Viso gero!", en: "Goodbye!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 2 — Here / There ───────────────────────────────────────────
      {
        id: "section_5_module_1_lesson_2",
        code: "5.1.2",
        title: "Here / There",
        purpose: "Teach the learner to handle short location replies.",
        supportLevel: "high",
        newLanguageLoad: "low",
        blocks: [
          {
            id: "s5m1l2_b1",
            type: "learn",
            title: "Here and there",
            items: [
              { id: "i1", lt: "čia",       en: "here",        audioText: "čia",       saveable: true,  core: true },
              { id: "i2", lt: "ten",       en: "there",       audioText: "ten",       saveable: true,  core: true },
              { id: "i3", lt: "Tai čia.",  en: "It's here.",  audioText: "Tai čia",   saveable: true,  core: true },
              { id: "i4", lt: "Tai ten.",  en: "It's there.", audioText: "Tai ten",   saveable: true,  core: true },
            ],
          },
          {
            id: "s5m1l2_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Tai ten.", audioText: "Tai ten" },
            options: [
              { id: "a", text: "It's here.",  isCorrect: false },
              { id: "b", text: "It's there.", isCorrect: true  },
              { id: "c", text: "It's far.",   isCorrect: false },
            ],
          },
          {
            id: "s5m1l2_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Tai čia.", audioText: "Tai čia" },
            options: [
              { id: "a", text: "It's there.", isCorrect: false },
              { id: "b", text: "It's here.",  isCorrect: true  },
              { id: "c", text: "It's near.",  isCorrect: false },
            ],
          },
          {
            id: "s5m1l2_b4",
            type: "conversation_turn_fill",
            scene_label: "On the street",
            lines: [
              { speaker: "You",   text: "Kur yra tualetas?", audioText: "Kur yra tualetas", hasGap: false },
              { speaker: "Local", text: "___.",               hasGap: true },
            ],
            options: [
              { id: "a", text: "Ačiū.",   isCorrect: false },
              { id: "b", text: "Ten.",    isCorrect: true  },
              { id: "c", text: "Labas.",  isCorrect: false },
            ],
            explanation: "Ten — there. A single pointing word is the most natural short answer to a location question.",
            translation_en: "Where is the toilet? — There.",
          },
          {
            id: "s5m1l2_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You ask where the station is. A local points and says one word. What are they most likely saying?", audioText: "" },
            noOptionAudio: true,
            options: [
              { id: "a", text: "Ačiū.",  isCorrect: false },
              { id: "b", text: "Ten.",   isCorrect: true  },
              { id: "c", text: "Taip.",  isCorrect: false },
            ],
            feedback: { correct: "Ten — there. Short pointing answers are very common. Listen for čia (here) and ten (there) in any location exchange." },
          },
          {
            id: "s5m1l2_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You need the hotel. A passer-by points you in the right direction.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena!",
                audioText: "Laba diena",
                helperText: "Good day!",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Laba diena! Atsiprašau, kur yra viešbutis?", en: "Good day! Excuse me, where is the hotel?", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Viešbutis? Tai ten.",
                audioText: "Viešbutis? Tai ten",
                helperText: "The hotel? It's there.",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Per brangu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom!",
                audioText: "Prašom",
                helperText: "You're welcome!",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Viso gero!", en: "Goodbye!", isCorrect: true },
                  { id: "c", text: "Laba diena.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 3 — Near / Far ─────────────────────────────────────────────
      {
        id: "section_5_module_1_lesson_3",
        code: "5.1.3",
        title: "Near / Far",
        purpose: "Add quick distance judgment language.",
        supportLevel: "high",
        newLanguageLoad: "low",
        blocks: [
          {
            id: "s5m1l3_b1",
            type: "learn",
            title: "Near and far",
            items: [
              { id: "i1", lt: "netoli",        en: "near / not far",  audioText: "netoli",        saveable: true, core: true },
              { id: "i2", lt: "toli",          en: "far",             audioText: "toli",          saveable: true, core: true },
              { id: "i3", lt: "Ar tai toli?",  en: "Is it far?",      audioText: "Ar tai toli",   saveable: true, core: true },
              { id: "i4", lt: "Ar tai netoli?",en: "Is it near?",     audioText: "Ar tai netoli", saveable: true, core: true },
              { id: "i5", lt: "Tai netoli.",   en: "It's near.",      audioText: "Tai netoli",    saveable: true, core: true },
              { id: "i6", lt: "Tai toli.",     en: "It's far.",       audioText: "Tai toli",      saveable: true, core: true },
            ],
          },
          {
            id: "s5m1l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Tai netoli.", audioText: "Tai netoli" },
            options: [
              { id: "a", text: "It's far.",   isCorrect: false },
              { id: "b", text: "It's there.", isCorrect: false },
              { id: "c", text: "It's near.",  isCorrect: true  },
            ],
          },
          {
            id: "s5m1l3_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar tai toli?", audioText: "Ar tai toli" },
            options: [
              { id: "a", text: "It's far.",  isCorrect: false },
              { id: "b", text: "Is it far?", isCorrect: true  },
              { id: "c", text: "Is it near?",isCorrect: false },
            ],
          },
          {
            id: "s5m1l3_b4",
            type: "context_gap_select",
            prompt: "Choose the correct word",
            sentence: "Vaistinė yra ___, tik penkios minutės.",
            translation_en: "The pharmacy is near, only five minutes.",
            options: [
              { id: "a", text: "toli",   isCorrect: false },
              { id: "b", text: "čia",    isCorrect: false },
              { id: "c", text: "netoli", isCorrect: true  },
            ],
            explanation: "Netoli means near or not far. Toli is the opposite — far. The context clue here is 'only five minutes'.",
          },
          {
            id: "s5m1l3_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Is it far?",
            targetText: "Ar tai toli",
            audioText: "Ar tai toli",
          },
          {
            id: "s5m1l3_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You're looking for the bus station and need to know if it's far.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ar galiu padėti?",
                audioText: "Laba diena! Ar galiu padėti",
                helperText: "Good day! Can I help?",
                options: [
                  { id: "a", text: "Ne, ačiū.", isCorrect: false },
                  { id: "b", text: "Taip! Kur yra autobusų stotis?", en: "Yes! Where is the bus station?", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Autobusų stotis yra ten.",
                audioText: "Autobusų stotis yra ten",
                helperText: "The bus station is over there.",
                options: [
                  { id: "a", text: "Ačiū labai!", isCorrect: false },
                  { id: "b", text: "Ar tai toli?", en: "Is it far?", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Ne, tai netoli. Penkios minutės.",
                audioText: "Ne, tai netoli. Penkios minutės",
                helperText: "No, it's near. Five minutes.",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Puiku! Ačiū labai.", en: "Great! Thank you very much.", isCorrect: true },
                  { id: "c", text: "Per brangu.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom. Viso gero!",
                audioText: "Prašom. Viso gero",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Viso gero!", en: "Goodbye!", isCorrect: true },
                  { id: "c", text: "Laba diena.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 4 — Left / Right / Straight Ahead ─────────────────────────
      {
        id: "section_5_module_1_lesson_4",
        code: "5.1.4",
        title: "Left / Right / Straight Ahead",
        purpose: "Teach the minimum viable direction set.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Lithuanian direction words have a built-in sense of movement. Kairėn means to the left, dešinėn means to the right. You will hear these as one-word replies or paired with Eikite (go) and Pasukite (turn).",
          usage: [
            "tiesiai — straight ahead",
            "kairėn — to the left",
            "dešinėn — to the right",
            "Eikite tiesiai — go straight ahead",
            "Pasukite kairėn — turn left",
            "Pasukite dešinėn — turn right",
          ],
        },
        blocks: [
          {
            id: "s5m1l4_b1",
            type: "learn",
            title: "Directions",
            items: [
              { id: "i1", lt: "tiesiai",           en: "straight ahead",  audioText: "tiesiai",           saveable: true, core: true },
              { id: "i2", lt: "kairėn",            en: "to the left",     audioText: "kairėn",            saveable: true, core: true },
              { id: "i3", lt: "dešinėn",           en: "to the right",    audioText: "dešinėn",           saveable: true, core: true },
              { id: "i4", lt: "Eikite tiesiai.",   en: "Go straight ahead.", audioText: "Eikite tiesiai",  saveable: true, core: true },
              { id: "i5", lt: "Pasukite kairėn.",  en: "Turn left.",       audioText: "Pasukite kairėn",   saveable: true, core: true },
              { id: "i6", lt: "Pasukite dešinėn.", en: "Turn right.",      audioText: "Pasukite dešinėn",  saveable: true, core: true },
              { id: "i7", lt: "paskui",            en: "then",             audioText: "paskui",            saveable: true, core: false },
            ],
          },
          {
            id: "s5m1l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Pasukite kairėn.", audioText: "Pasukite kairėn" },
            options: [
              { id: "a", text: "Go straight ahead.", isCorrect: false },
              { id: "b", text: "Turn right.",        isCorrect: false },
              { id: "c", text: "Turn left.",         isCorrect: true  },
            ],
          },
          {
            id: "s5m1l4_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Eikite tiesiai.", audioText: "Eikite tiesiai" },
            options: [
              { id: "a", text: "Turn left.",         isCorrect: false },
              { id: "b", text: "Go straight ahead.", isCorrect: true  },
              { id: "c", text: "Turn right.",        isCorrect: false },
            ],
          },
          {
            id: "s5m1l4_b4",
            type: "context_gap_select",
            prompt: "Complete the direction",
            sentence: "Pasukite ___.",
            translation_en: "Turn right.",
            options: [
              { id: "a", text: "tiesiai",  isCorrect: false },
              { id: "b", text: "kairėn",   isCorrect: false },
              { id: "c", text: "dešinėn",  isCorrect: true  },
            ],
            explanation: "Dešinėn means to the right. Kairėn is left. Tiesiai is straight ahead.",
          },
          {
            id: "s5m1l4_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: Go straight ahead",
            targetText: "Eikite tiesiai",
            audioText: "Eikite tiesiai",
          },
          {
            id: "s5m1l4_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You ask for directions to the pharmacy. Listen carefully.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ko ieškote?",
                audioText: "Laba diena! Ko ieškote",
                helperText: "Good day! What are you looking for?",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Laba diena! Kur yra vaistinė?", en: "Good day! Where is the pharmacy?", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Eikite tiesiai, paskui pasukite kairėn.",
                audioText: "Eikite tiesiai, paskui pasukite kairėn",
                helperText: "Go straight, then turn left.",
                options: [
                  { id: "a", text: "Prašau kalbėkite lėčiau.", isCorrect: false },
                  { id: "b", text: "Suprantu. Tiesiai, paskui kairėn.", en: "I understand. Straight, then left.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Taip, teisingai. Tai netoli.",
                audioText: "Taip, teisingai. Tai netoli",
                helperText: "Yes, that's right. It's not far.",
                options: [
                  { id: "a", text: "Ar tai toli?", isCorrect: false },
                  { id: "b", text: "Ačiū labai! Viso gero.", en: "Thank you very much! Goodbye.", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 5 — Basic Location Exchange ───────────────────────────────
      {
        id: "section_5_module_1_lesson_5",
        code: "5.1.5",
        title: "Basic Location Exchange",
        purpose: "Bring the core location tools together in one short exchange.",
        supportLevel: "medium",
        newLanguageLoad: "very_low",
        blocks: [
          {
            id: "s5m1l5_b1",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Eikite tiesiai, paskui dešinėn.", audioText: "Eikite tiesiai, paskui dešinėn" },
            options: [
              { id: "a", text: "Turn left, then go straight.",  isCorrect: false },
              { id: "b", text: "Go straight, then turn right.", isCorrect: true  },
              { id: "c", text: "Turn right, then go straight.", isCorrect: false },
            ],
          },
          {
            id: "s5m1l5_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar tai netoli?", audioText: "Ar tai netoli" },
            options: [
              { id: "a", text: "Is it far?",   isCorrect: false },
              { id: "b", text: "Is it here?",  isCorrect: false },
              { id: "c", text: "Is it near?",  isCorrect: true  },
            ],
          },
          {
            id: "s5m1l5_b3",
            type: "conversation_turn_fill",
            scene_label: "On the street",
            lines: [
              { speaker: "You",   text: "Atsiprašau, kur yra viešbutis?", audioText: "Atsiprašau, kur yra viešbutis", hasGap: false },
              { speaker: "Local", text: "Tai ___.",                        hasGap: true },
            ],
            options: [
              { id: "a", text: "toli",  isCorrect: false },
              { id: "b", text: "čia",   isCorrect: false },
              { id: "c", text: "ten",   isCorrect: true  },
            ],
            explanation: "Ten — there. A short pointing reply. You would say čia only if the hotel were right where you are standing.",
            translation_en: "Excuse me, where is the hotel? — It's there.",
          },
          {
            id: "s5m1l5_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Someone tells you: Eikite tiesiai, paskui kairėn. What did they say?", audioText: "" },
            noOptionAudio: true,
            options: [
              { id: "a", text: "Turn left, then go straight.", isCorrect: false },
              { id: "b", text: "Go straight, then turn left.", isCorrect: true  },
              { id: "c", text: "Go right, then turn left.",    isCorrect: false },
            ],
            feedback: { correct: "Tiesiai = straight, paskui = then, kairėn = left. Order matters — straight first, then the turn." },
          },
          {
            id: "s5m1l5_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Where is the pharmacy?",
            targetText: "Kur yra vaistinė",
            audioText: "Kur yra vaistinė",
          },
          {
            id: "s5m1l5_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "A full short location exchange — ask, get directions, check distance, close.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ar galiu jums padėti?",
                audioText: "Laba diena! Ar galiu jums padėti",
                helperText: "Good day! Can I help you?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Taip! Kur yra tualetas?", en: "Yes! Where is the toilet?", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Eikite tiesiai, paskui dešinėn. Tai čia.",
                audioText: "Eikite tiesiai, paskui dešinėn. Tai čia",
                helperText: "Go straight, then right. It's here.",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Ar tai toli?", en: "Is it far?", isCorrect: true },
                  { id: "c", text: "Kur yra stotis?", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Ne, tai netoli. Viena minutė.",
                audioText: "Ne, tai netoli. Viena minutė",
                helperText: "No, it's near. One minute.",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Puiku! Ačiū labai.", en: "Great! Thank you very much.", isCorrect: true },
                  { id: "c", text: "Prašau kalbėkite lėčiau.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom! Viso gero.",
                audioText: "Prašom! Viso gero",
                options: [
                  { id: "a", text: "Laba diena.", isCorrect: false },
                  { id: "b", text: "Viso gero!", en: "Goodbye!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Module 5.1 Checkpoint ─────────────────────────────────────────────
      {
        id: "section_5_module_1_checkpoint",
        code: "5.1.C",
        title: "Location Basics Check",
        purpose: "Confirm the core location-question system is fast and reliable.",
        supportLevel: "low",
        newLanguageLoad: "none",
        blocks: [
          {
            id: "s5m1c_b1",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kur yra viešbutis?", audioText: "Kur yra viešbutis" },
            options: [
              { id: "a", text: "Where is the pharmacy?", isCorrect: false },
              { id: "b", text: "Where is the hotel?",    isCorrect: true  },
              { id: "c", text: "Where is the station?",  isCorrect: false },
            ],
          },
          {
            id: "s5m1c_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Tai netoli.", audioText: "Tai netoli" },
            options: [
              { id: "a", text: "It's far.",   isCorrect: false },
              { id: "b", text: "It's there.", isCorrect: false },
              { id: "c", text: "It's near.",  isCorrect: true  },
            ],
          },
          {
            id: "s5m1c_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You want to know if the hotel is far. What do you ask?", audioText: "" },
            noOptionAudio: true,
            options: [
              { id: "a", text: "Kur yra viešbutis?", isCorrect: false },
              { id: "b", text: "Ar tai toli?",        isCorrect: true  },
              { id: "c", text: "Tai ten.",            isCorrect: false },
            ],
            feedback: { correct: "Ar tai toli? — Is it far? This is the standard distance check for any destination." },
          },
          {
            id: "s5m1c_b4",
            type: "context_gap_select",
            prompt: "Complete the direction",
            sentence: "Pasukite ___, paskui eikite tiesiai.",
            translation_en: "Turn left, then go straight.",
            options: [
              { id: "a", text: "tiesiai",  isCorrect: false },
              { id: "b", text: "dešinėn",  isCorrect: false },
              { id: "c", text: "kairėn",   isCorrect: true  },
            ],
            explanation: "Kairėn means to the left. Dešinėn is right. Tiesiai is straight ahead.",
          },
          {
            id: "s5m1c_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Where is the pharmacy?",
            targetText: "Kur yra vaistinė",
            audioText: "Kur yra vaistinė",
          },
          {
            id: "s5m1c_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You need the train station. Ask a passer-by, check the distance, get one direction.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ar galiu padėti?",
                audioText: "Laba diena! Ar galiu padėti",
                helperText: "Good day! Can I help?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Taip! Kur yra geležinkelio stotis?", en: "Yes! Where is the train station?", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Stotis? Eikite tiesiai, paskui dešinėn.",
                audioText: "Stotis? Eikite tiesiai, paskui dešinėn",
                helperText: "The station? Go straight, then right.",
                options: [
                  { id: "a", text: "Ačiū!", isCorrect: false },
                  { id: "b", text: "Suprantu. Ar tai toli?", en: "I understand. Is it far?", isCorrect: true },
                  { id: "c", text: "Prašau kalbėkite lėčiau.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Ne, tai netoli. Apie penkios minutės.",
                audioText: "Ne, tai netoli. Apie penkios minutės",
                helperText: "No, it's near. About five minutes.",
                options: [
                  { id: "a", text: "Per toli.", isCorrect: false },
                  { id: "b", text: "Ačiū labai! Viso gero.", en: "Thank you very much! Goodbye.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom. Geros kelionės!",
                audioText: "Prašom. Geros kelionės",
                helperText: "You're welcome. Have a good journey!",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Ačiū! Viso gero!", en: "Thank you! Goodbye!", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
            ],
          },
          {
            id: "s5m1c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Kur yra…?",          en: "Where is…?",            audioText: "Kur yra" },
              { id: "m2",  lt: "Kur yra stotis?",     en: "Where is the station?", audioText: "Kur yra stotis" },
              { id: "m3",  lt: "Kur yra tualetas?",   en: "Where is the toilet?",  audioText: "Kur yra tualetas" },
              { id: "m4",  lt: "Kur yra viešbutis?",  en: "Where is the hotel?",   audioText: "Kur yra viešbutis" },
              { id: "m5",  lt: "Kur yra vaistinė?",   en: "Where is the pharmacy?",audioText: "Kur yra vaistinė" },
              { id: "m6",  lt: "čia",                 en: "here",                  audioText: "čia" },
              { id: "m7",  lt: "ten",                 en: "there",                 audioText: "ten" },
              { id: "m8",  lt: "Tai čia.",            en: "It's here.",            audioText: "Tai čia" },
              { id: "m9",  lt: "Tai ten.",            en: "It's there.",           audioText: "Tai ten" },
              { id: "m10", lt: "netoli",              en: "near",                  audioText: "netoli" },
              { id: "m11", lt: "toli",                en: "far",                   audioText: "toli" },
              { id: "m12", lt: "Ar tai toli?",        en: "Is it far?",            audioText: "Ar tai toli" },
              { id: "m13", lt: "Tai netoli.",         en: "It's near.",            audioText: "Tai netoli" },
              { id: "m14", lt: "tiesiai",             en: "straight ahead",        audioText: "tiesiai" },
              { id: "m15", lt: "kairėn",              en: "to the left",           audioText: "kairėn" },
              { id: "m16", lt: "dešinėn",             en: "to the right",          audioText: "dešinėn" },
              { id: "m17", lt: "Eikite tiesiai.",     en: "Go straight ahead.",    audioText: "Eikite tiesiai" },
              { id: "m18", lt: "Pasukite kairėn.",    en: "Turn left.",            audioText: "Pasukite kairėn" },
              { id: "m19", lt: "Pasukite dešinėn.",   en: "Turn right.",           audioText: "Pasukite dešinėn" },
              { id: "m20", lt: "paskui",              en: "then",                  audioText: "paskui" },
            ],
          },
        ],
      },
    ],
  };
}
