// src/content/learning/section2/module_2_1.js
// Module 2.1 — I Want / I Need / I Have

export default function createModule_2_1(profile = {}) {
  const {
    userNameSafe = "Davidas",
    userFromPhrase = "Aš esu iš Škotijos",
  } = profile;

  return {
    id: "module_2_1",
    code: "2.1",
    title: "I Want / I Need / I Have",
    status: "active",
    lessonCount: 4,
    lessons: [

      // ── Lesson 1 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_1_lesson_1",
        code: "2.1.1",
        title: "I Want…",
        purpose: "Teach the learner to express simple wants using a reusable first-person frame.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Aš noriu… / Noriu… — 'I want…'. The noun after noriu takes the genitive case — you'll see word endings shift slightly. Treat it as a pattern to get used to, not a rule to memorise.",
          usage: [
            "Noriu kavos — [I] want coffee (in a café; Aš is usually implied)",
            "Noriu vandens — [I] want water",
            "Noriu šito — I want this (pointing at something)",
            "Noriu to — I want that",
            "Ko norėtumėte? — What would you like? (polite service form)",
            "Ko nori? — What do you want? (casual, one person)",
          ],
        },
        blocks: [
          {
            id: "s2m1l1_b1",
            type: "learn",
            title: "I want…",
            items: [
              { id: "w1", lt: "Noriu…", en: "I want…", audioText: "Noriu", saveable: true, core: true },
              { id: "w2", lt: "Noriu kavos.", en: "[I] want coffee.", audioText: "Noriu kavos", saveable: true, core: true },
              { id: "w3", lt: "Noriu vandens.", en: "[I] want water.", audioText: "Noriu vandens", saveable: true, core: true },
              { id: "w4", lt: "Noriu šito.", en: "I want this.", audioText: "Noriu šito", saveable: true, core: true },
              { id: "w5", lt: "Noriu to.", en: "I want that.", audioText: "Noriu to", saveable: true, core: true },
              { id: "w6", lt: "Ko norėtumėte?", en: "What would you like?", audioText: "Ko norėtumėte", saveable: true, core: false },
              { id: "w6b", lt: "Ko nori?", en: "What do you want? (casual)", audioText: "Ko nori", saveable: true, core: false },
              { id: "w7", lt: "Arbata", en: "Tea", audioText: "Arbata", saveable: true, core: false },
              { id: "w8", lt: "Sultys", en: "Juice", audioText: "Sultys", saveable: true, core: false },
              { id: "w9", lt: "Sumuštinis", en: "Sandwich", audioText: "Sumuštinis", saveable: true, core: false },
            ],
          },
          {
            id: "s2m1l1_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Noriu kavos.", audioText: "Noriu kavos" },
            options: [
              { id: "a", text: "I have coffee.", isCorrect: false },
              { id: "b", text: "I want coffee.", isCorrect: true },
              { id: "c", text: "I need coffee.", isCorrect: false },
            ],
          },
          {
            id: "s2m1l1_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Noriu vandens.", audioText: "Noriu vandens" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I want water.", isCorrect: true },
              { id: "c", text: "I want this.", isCorrect: false },
            ],
          },
          {
            id: "s2m1l1_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "I want coffee." },
            tokens: [
              { id: "t1", text: "Noriu", correctIndex: 0 },
              { id: "t2", text: "kavos.", correctIndex: 1 },
              { id: "t3", text: "vandens.", isDistractor: true },
            ],
            answerText: "Noriu kavos.",
          },
          {
            id: "s2m1l1_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I want water",
            targetText: "Noriu vandens.",
            audioText: "Noriu vandens",
          },
          {
  id: "s2m1l1_b6_v2",
  type: "scenario_v2",
  title: "Ordering coffee",
  description: "You're at a café in Vilnius and want a coffee.",
  sceneIntro: "You're at a café in Vilnius and want a coffee.",
  location: "café",
  userRole: "customer",
  register: "polite_service",
  goal: "Use Noriu… in a simple café exchange and use Nesuprantu if the service question is not clear.",
  focus: ["Noriu…", "Ko norėtumėte?", "Nesuprantu"],
  participants: [
    {
      id: "server",
      label: "Server",
      name: "Rasa",
      role: "server",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Laba diena! Ko norėtumėte?",
      sceneDirection: "The server comes to your table with the drinks menu.",
      learnerPrompt: "Order the coffee you came for. If the question is not clear, use Nesuprantu.",
      help: {
        levels: [
          {
            sceneDirection: "She opens the drinks menu and gestures towards the coffee section.",
          },
          {
            sceneDirection: "She points to the coffee machine and then to you as a question.",
            speakerText: "Kavos?",
          },
          {
            speakerText: "What would you like?",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Laba diena! Noriu kavos, prašau.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Viso gero!",
          result: "wrong",
          feedback: "You have just arrived and the server is asking for your order.",
          progresses: false,
        },
        {
          id: "c",
          text: "Man reikia bilieto.",
          result: "wrong",
          feedback: "You are in a café and came for coffee.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "server",
      speakerLabel: "Server",
      speakerText: "Prašau.",
      sceneDirection: "The server places the coffee in front of you.",
      learnerPrompt: "Acknowledge the handover.",
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Noriu to.",
          result: "wrong",
          feedback: "Nothing else is being pointed out. The server has just handed you the coffee.",
          progresses: false,
        },
        {
          id: "c",
          text: "Kur yra stotis?",
          result: "wrong",
          feedback: "The server has just handed you the coffee you ordered.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "server",
        speakerLabel: "Server",
        speakerText: "Prašom.",
        sceneDirection: "She smiles and returns to the counter.",
      },
    },
  ],
},
        ],
      },

      // ── Lesson 2 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_1_lesson_2",
        code: "2.1.2",
        title: "I Need…",
        purpose: "Teach practical need language. Man reikia pagalbos was introduced in 1.4 — this lesson properly establishes the full man reikia… frame.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Man reikia… — 'I need…'. This doesn't map word-for-word to English, but it's one of the most useful beginner frames. Learn it as a chunk.",
          usage: [
            "Man reikia vandens — I need water",
            "Man reikia pagalbos — I need help (already seen in 1.4 — now you know the frame behind it)",
            "Man reikia bilieto — I need a ticket",
            "Man reikia tualeto — I need a toilet",
            "Ko jums reikia? — What do you need? (what you might hear)",
          ],
        },
        blocks: [
          {
            id: "s2m1l2_b1",
            type: "learn",
            title: "I need…",
            items: [
              { id: "n1", lt: "Man reikia…", en: "I need…", audioText: "Man reikia", saveable: true, core: true },
              { id: "n2", lt: "Man reikia vandens.", en: "I need water.", audioText: "Man reikia vandens", saveable: true, core: true },
              { id: "n4", lt: "Man reikia bilieto.", en: "I need a ticket.", audioText: "Man reikia bilieto", saveable: true, core: true },
              { id: "n5", lt: "Man reikia tualeto.", en: "I need a toilet.", audioText: "Man reikia tualeto", saveable: true, core: true },
              { id: "n6", lt: "Bilietas", en: "Ticket", audioText: "Bilietas", saveable: true, core: false },
              { id: "n7", lt: "Vaistai", en: "Medicine / medication", audioText: "Vaistai", saveable: true, core: false },
              { id: "n8", lt: "Pasas", en: "Passport", audioText: "Pasas", saveable: true, core: false },
            ],
          },
          {
            id: "s2m1l2_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Man reikia bilieto.", audioText: "Man reikia bilieto" },
            options: [
              { id: "a", text: "I want a ticket.", isCorrect: false },
              { id: "b", text: "I have a ticket.", isCorrect: false },
              { id: "c", text: "I need a ticket.", isCorrect: true },
            ],
          },
          {
            id: "s2m1l2_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're at a station and urgently need the toilet. What do you say?" },
            options: [
              { id: "a", text: "Noriu kavos.", isCorrect: false },
              { id: "b", text: "Man reikia tualeto!", isCorrect: true },
              { id: "c", text: "Ačiū labai.", isCorrect: false },
            ],
            feedback: { correct: "Man reikia tualeto — need, not want. The right frame for urgency." },
          },
          {
            id: "s2m1l2_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Man reikia pagalbos.", audioText: "Man reikia pagalbos" },
            options: [
              { id: "a", text: "I want help.", isCorrect: false },
              { id: "b", text: "I need help.", isCorrect: true },
              { id: "c", text: "I have help.", isCorrect: false },
            ],
          },
          {
            id: "s2m1l2_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "I need a ticket." },
            tokens: [
              { id: "t1", text: "Man", correctIndex: 0 },
              { id: "t2", text: "reikia", correctIndex: 1 },
              { id: "t3", text: "bilieto.", correctIndex: 2 },
              { id: "t4", text: "vandens.", isDistractor: true },
            ],
            answerText: "Man reikia bilieto.",
          },
          {
            id: "s2m1l2_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I need help",
            targetText: "Man reikia pagalbos.",
            audioText: "Man reikia pagalbos",
          },
          {
  id: "s2m1l2_b7_v2",
  type: "scenario_v2",
  title: "At the ticket office",
  description: "You're at the station ticket office and need a ticket.",
  sceneIntro: "You're at the station ticket office and need a ticket.",
  location: "ticket office",
  userRole: "traveller",
  register: "polite_service",
  goal: "Use Man reikia… for a practical need.",
  focus: ["Man reikia…"],
  participants: [
    {
      id: "clerk",
      label: "Clerk",
      name: "Rasa",
      role: "ticket clerk",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  objects: [
    {
      id: "ticket",
      lt: "bilietas",
      en: "ticket",
      gender: "masculine",
      number: "singular",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "clerk",
      speakerLabel: "Clerk",
      speakerText: "Laba diena! Ar galiu jums padėti?",
      sceneDirection: "The clerk looks up from the ticket desk and offers help.",
      learnerPrompt: "Say what you need.",
      options: [
        {
          id: "a",
          text: "Taip! Man reikia bilieto.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Noriu kavos.",
          result: "wrong",
          feedback: "You are at the ticket office because you need a ticket.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero!",
          result: "wrong",
          feedback: "The clerk has just offered to help you.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "clerk",
      speakerLabel: "Clerk",
      speakerText: "Prašau.",
      sceneDirection: "The clerk hands you the ticket.",
      learnerPrompt: "Acknowledge the handover.",
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Man reikia vandens.",
          result: "wrong",
          feedback: "The clerk has just handed you the ticket you needed.",
          progresses: false,
        },
        {
          id: "c",
          text: "Ne, neturiu.",
          result: "wrong",
          feedback: "Nothing has been asked about what you have.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "clerk",
        speakerLabel: "Clerk",
        speakerText: "Prašom. Viso gero!",
        sceneDirection: "The clerk smiles as you leave the desk.",
      },
    },
  ],
},
        ],
      },

      // ── Lesson 3 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_1_lesson_3",
        code: "2.1.3",
        title: "I Have / I Don't Have",
        purpose: "Teach basic possession and its negation in practical contexts.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Turiu = I have. Neturiu = I don't have. The negation matters early — it changes what you can do in real situations.",
          usage: [
            "Turiu bilietą — I have a ticket",
            "Neturiu grynųjų — I don't have cash",
            "Pinigai — money",
            "Turiu kortelę — I have a card",
            "Neturiu laiko — I don't have time",
            "tik — only / just, as in tik kortelę — only a card",
          ],
        },
        blocks: [
          {
            id: "s2m1l3_b1",
            type: "learn",
            title: "I have / I don't have",
            items: [
              { id: "h1", lt: "Turiu…", en: "I have…", audioText: "Turiu", saveable: true, core: true },
              { id: "h2", lt: "Neturiu…", en: "I don't have…", audioText: "Neturiu", saveable: true, core: true },
              { id: "h3", lt: "Turiu bilietą.", en: "I have a ticket.", audioText: "Turiu bilietą", saveable: true, core: true },
              { id: "h4", lt: "Neturiu grynųjų.", en: "I don't have cash.", audioText: "Neturiu grynųjų", saveable: true, core: true },
              { id: "h5", lt: "Turiu kortelę.", en: "I have a card.", audioText: "Turiu kortelę", saveable: true, core: true },
              { id: "h6", lt: "Neturiu laiko.", en: "I don't have time.", audioText: "Neturiu laiko", saveable: true, core: true },
              { id: "h7", lt: "Kortelė", en: "Card (payment)", audioText: "Kortelė", saveable: true, core: false },
              { id: "h8", lt: "Pinigai", en: "Money", audioText: "Pinigai", saveable: true, core: false },
              { id: "h9", lt: "Tik", en: "Only / just", audioText: "Tik", saveable: true, core: false },
            ],
          },
          {
            id: "s2m1l3_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Neturiu grynųjų.", audioText: "Neturiu grynųjų" },
            options: [
              { id: "a", text: "I have cash.", isCorrect: false },
              { id: "b", text: "I need cash.", isCorrect: false },
              { id: "c", text: "I don't have cash.", isCorrect: true },
            ],
          },
          {
            id: "s2m1l3_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Turiu kortelę.", audioText: "Turiu kortelę" },
            options: [
              { id: "a", text: "I don't have a card.", isCorrect: false },
              { id: "b", text: "I need a card.", isCorrect: false },
              { id: "c", text: "I have a card.", isCorrect: true },
            ],
          },
          {
            id: "s2m1l3_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Someone asks if you can pay cash. You only have a card." },
            options: [
              { id: "a", text: "Turiu grynųjų.", isCorrect: false },
              { id: "b", text: "Man reikia pagalbos.", isCorrect: false },
              { id: "c", text: "Neturiu grynųjų, tik kortelę.", isCorrect: true },
            ],
            feedback: { correct: "Neturiu grynųjų, tik kortelę — I don't have cash, only a card. Clear and natural." },
          },
          {
            id: "s2m1l3_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I have a ticket",
            targetText: "Turiu bilietą.",
            audioText: "Turiu bilietą",
          },
          {
            id: "s2m1l3_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I don't have cash",
            targetText: "Neturiu grynųjų.",
            audioText: "Neturiu grynųjų",
          },
          {
  id: "s2m1l3_b7_v2",
  type: "scenario_v2",
  title: "Showing your ticket",
  description: "You reach the station barrier with your ticket ready on your phone.",
  sceneIntro: "You reach the station barrier with your ticket ready on your phone.",
  location: "station barrier",
  userRole: "traveller",
  register: "polite_service",
  goal: "Use Turiu… naturally to say what you have.",
  focus: ["Turiu…", "Neturiu…"],
  participants: [
    {
      id: "staff",
      label: "Staff",
      name: "Tomas",
      role: "station staff",
      gender: "male",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  objects: [
    {
      id: "ticket",
      lt: "bilietas",
      en: "ticket",
      gender: "masculine",
      number: "singular",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "staff",
      speakerLabel: "Staff",
      speakerText: "Bilietas?",
      sceneDirection: "The staff member gestures towards the ticket scanner.",
      learnerPrompt: "Tell him that you have a ticket.",
      options: [
        {
          id: "a",
          text: "Turiu bilietą.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Neturiu grynųjų.",
          result: "wrong",
          feedback: "He is asking about your ticket, not cash.",
          progresses: false,
        },
        {
          id: "c",
          text: "Man reikia pagalbos.",
          result: "wrong",
          feedback: "Your ticket is ready on your phone. Tell him that you have it.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "staff",
      speakerLabel: "Staff",
      speakerText: "Gerai, ačiū.",
      sceneDirection: "He scans the ticket and the barrier opens.",
      learnerPrompt: "Acknowledge him.",
      options: [
        {
          id: "a",
          text: "Ačiū!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Neturiu laiko.",
          result: "wrong",
          feedback: "The barrier is open and the exchange is finished.",
          progresses: false,
        },
        {
          id: "c",
          text: "Noriu kavos.",
          result: "wrong",
          feedback: "You are at the station barrier, not ordering in a café.",
          progresses: false,
        },
      ],
    },
  ],
},
        ],
      },

      // ── Lesson 4 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_1_lesson_4",
        code: "2.1.4",
        title: "Do You Have…?",
        purpose: "Turn possession language into interaction — asking about availability.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "Ar turite…? — Do you have…? Ar is a clear, beginner-safe way to mark a yes/no question. In natural speech it can sometimes be omitted when intonation and context make the question clear; for now, produce Ar turite…?. Turime = we have. Neturime = we don't.",
          usage: [
            "Ar turite vandens? — Do you have water?",
            "Ar turite kavos? — Do you have coffee?",
            "Ar turite meniu? — Do you have a menu?",
            "Taip, turime. — Yes, we do.",
            "Ne, neturime. — No, we don't.",
          ],
        },
        blocks: [
          {
            id: "s2m1l4_b1",
            type: "learn",
            title: "Do you have…?",
            items: [
              { id: "d1", lt: "Ar turite…?", en: "Do you have…?", audioText: "Ar turite", saveable: true, core: true },
              { id: "d2", lt: "Ar turite vandens?", en: "Do you have water?", audioText: "Ar turite vandens", saveable: true, core: true },
              { id: "d3", lt: "Ar turite kavos?", en: "Do you have coffee?", audioText: "Ar turite kavos", saveable: true, core: true },
              { id: "d4", lt: "Ar turite meniu?", en: "Do you have a menu?", audioText: "Ar turite meniu", saveable: true, core: true },
              { id: "d5", lt: "Taip, turime.", en: "Yes, we do.", audioText: "Taip, turime", saveable: false, core: false },
              { id: "d6", lt: "Ne, neturime.", en: "No, we don't.", audioText: "Ne, neturime", saveable: false, core: false },
              { id: "d7", lt: "Meniu", en: "Menu", audioText: "Meniu", saveable: true, core: false },
              { id: "d8", lt: "Laikraštis", en: "Newspaper", audioText: "Laikraštis", saveable: true, core: false },
            ],
          },
          {
            id: "s2m1l4_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar turite meniu?", audioText: "Ar turite meniu" },
            options: [
              { id: "a", text: "I need a menu.", isCorrect: false },
              { id: "b", text: "Do you have a menu?", isCorrect: true },
              { id: "c", text: "I want a menu.", isCorrect: false },
            ],
          },
          {
            id: "s2m1l4_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar turite vandens?", audioText: "Ar turite vandens" },
            options: [
              { id: "a", text: "I need water.", isCorrect: false },
              { id: "b", text: "Do you have water?", isCorrect: true },
              { id: "c", text: "Do you have coffee?", isCorrect: false },
            ],
          },
          {
            id: "s2m1l4_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Do you have coffee?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "turite", correctIndex: 1 },
              { id: "t3", text: "kavos?", correctIndex: 2 },
              { id: "t4", text: "vandens?", isDistractor: true },
            ],
            answerText: "Ar turite kavos?",
          },
          {
            id: "s2m1l4_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You sit down at a restaurant and want to see the menu first." },
            options: [
              { id: "a", text: "Noriu kavos.", isCorrect: false },
              { id: "b", text: "Ar turite meniu?", isCorrect: true },
              { id: "c", text: "Man reikia pagalbos.", isCorrect: false },
            ],
            feedback: { correct: "Ar turite meniu? — natural first question in any restaurant." },
          },
          {
            id: "s2m1l4_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask if they have water",
            targetText: "Ar turite vandens?",
            audioText: "Ar turite vandens",
          },
          {
  id: "s2m1l4_b7_v2",
  type: "scenario_v2",
  title: "Do you have coffee?",
  description: "You're in a small café and want to check whether coffee is available before ordering.",
  sceneIntro: "You're in a small café and want to check whether coffee is available before ordering.",
  location: "café",
  userRole: "customer",
  register: "polite_service",
  goal: "Ask Ar turite…? and understand a simple availability reply.",
  focus: ["Ar turite…?", "Taip, turime"],
  participants: [
    {
      id: "barista",
      label: "Barista",
      name: "Ieva",
      role: "barista",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  objects: [
    {
      id: "coffee",
      lt: "kava",
      en: "coffee",
      gender: "feminine",
      number: "singular",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "barista",
      speakerLabel: "Barista",
      speakerText: "Laba diena!",
      sceneDirection: "The barista greets you at the counter.",
      learnerPrompt: "Ask whether they have coffee.",
      options: [
        {
          id: "a",
          text: "Laba diena! Ar turite kavos?",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Man reikia bilieto.",
          result: "wrong",
          feedback: "You are at a café and want to check whether coffee is available.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero!",
          result: "wrong",
          feedback: "You have just arrived at the counter.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "barista",
      speakerLabel: "Barista",
      speakerText: "Taip, turime.",
      sceneDirection: "She nods and gestures towards the coffee machine.",
      learnerPrompt: "Order the coffee.",
      options: [
        {
          id: "a",
          text: "Puiku! Noriu kavos, prašau.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Man reikia bilieto.",
          result: "wrong",
          feedback: "The barista has confirmed that coffee is available.",
          progresses: false,
        },
        {
          id: "c",
          text: "Kur yra stotis?",
          result: "wrong",
          feedback: "You are at the café counter ordering coffee.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_3",
      speakerId: "barista",
      speakerLabel: "Barista",
      speakerText: "Prašau.",
      sceneDirection: "The barista places the coffee in front of you.",
      learnerPrompt: "Acknowledge the handover.",
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Ne, neturiu.",
          result: "wrong",
          feedback: "Nothing has been asked about what you have.",
          progresses: false,
        },
        {
          id: "c",
          text: "Noriu to.",
          result: "wrong",
          feedback: "Nothing else is being pointed out. Your coffee has just been handed to you.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "barista",
        speakerLabel: "Barista",
        speakerText: "Prašom.",
        sceneDirection: "She smiles and turns back to the counter.",
      },
    },
  ],
},
          {
            id: "s2m1l4_b8",
            type: "learn",
            title: "At hotel reception",
            items: [
              { id: "hk1", lt: "Raktas", en: "Key", audioText: "Raktas", saveable: true, core: false },
              { id: "hk2", lt: "Kambario raktas", en: "Room key", audioText: "Kambario raktas", saveable: true, core: false },
              { id: "hk3", lt: "Čia jūsų kambario raktas.", en: "Here is your room key.", audioText: "Čia jūsų kambario raktas", saveable: true, core: false },
            ],
          },
          {
            id: "s2m1l4_b9_v2",
            type: "scenario_v2",
            title: "Your room key",
            description: "You collect your room key at hotel reception and ask for some water before heading upstairs.",
            sceneIntro: "You collect your room key at hotel reception and ask for some water before heading upstairs.",
            location: "hotel reception",
            userRole: "guest",
            register: "polite_service",
            goal: "Recognise the room-key handover, then reuse Ar turite…? and familiar polite language in a natural hotel exchange.",
            focus: ["raktas", "kambario raktas", "Ar turite…?", "Noriu…", "Ačiū", "Viso gero"],
            participants: [
              {
                id: "receptionist",
                label: "Receptionist",
                name: "Rasa",
                role: "hotel receptionist",
                gender: "female",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            objects: [
              {
                id: "room_key",
                lt: "kambario raktas",
                en: "room key",
                gender: "masculine",
                number: "singular",
              },
              {
                id: "water",
                lt: "vanduo",
                en: "water",
                number: "singular",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Laba diena. Čia jūsų kambario raktas.",
                sceneDirection: "Rasa places the room key on the reception desk and slides it towards you.",
                learnerPrompt: "Acknowledge the handover naturally.",
                options: [
                  {
                    id: "a",
                    text: "Ačiū! Puiku.",
                    result: "best",
                    progresses: true,
                  },
                  {
                    id: "b",
                    text: "Ačiū!",
                    result: "acceptable",
                    progresses: true,
                    feedback: "Perfectly natural. Adding Puiku simply makes the response a little warmer.",
                    betterAnswer: "Ačiū! Puiku.",
                  },
                  {
                    id: "c",
                    text: "Puiku!",
                    result: "awkward",
                    progresses: true,
                    feedback: "Understandable, but after someone hands you your key it is more natural to thank them as well.",
                    betterAnswer: "Ačiū! Puiku.",
                  },
                  {
                    id: "d",
                    text: "Prašom.",
                    result: "wrong",
                    feedback: "Prašom is what the receptionist might say after you thank her. Here, you are receiving the key.",
                    progresses: false,
                  },
                ],
              },
              {
                id: "step_2",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Prašom.",
                sceneDirection: "As you pick up the key, you realise you are thirsty and want some water before going upstairs.",
                learnerPrompt: "Ask whether they have water.",
                options: [
                  {
                    id: "a",
                    text: "Ar turite vandens?",
                    result: "best",
                    progresses: true,
                  },
                  {
                    id: "b",
                    text: "Noriu vandens, prašau.",
                    result: "acceptable",
                    progresses: true,
                    feedback: "That works as a polite request. Ar turite vandens? checks availability first, which is the pattern you are practising here.",
                    betterAnswer: "Ar turite vandens?",
                  },
                  {
                    id: "c",
                    text: "Man reikia vandens.",
                    result: "awkward",
                    progresses: true,
                    feedback: "You would be understood, but 'I need water' is more direct than simply asking whether the hotel has some.",
                    betterAnswer: "Ar turite vandens?",
                  },
                  {
                    id: "d",
                    text: "Ar turite kavos?",
                    result: "wrong",
                    feedback: "That asks about coffee. You are trying to get some water before going upstairs.",
                    progresses: false,
                  },
                ],
              },
              {
                id: "step_3",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Taip, turime.",
                sceneDirection: "Rasa nods and reaches for some water behind the desk.",
                learnerPrompt: "Ask for the water politely.",
                options: [
                  {
                    id: "a",
                    text: "Noriu vandens, prašau.",
                    result: "best",
                    progresses: true,
                  },
                  {
                    id: "b",
                    text: "Man reikia vandens.",
                    result: "acceptable",
                    progresses: true,
                    feedback: "This is understandable and fits the situation, although Noriu vandens, prašau is softer and more natural here.",
                    betterAnswer: "Noriu vandens, prašau.",
                  },
                  {
                    id: "c",
                    text: "Ar turite vandens?",
                    result: "awkward",
                    progresses: true,
                    feedback: "She has just told you that they do have water, so repeating the availability question is unnecessary.",
                    betterAnswer: "Noriu vandens, prašau.",
                  },
                  {
                    id: "d",
                    text: "Viso gero!",
                    result: "wrong",
                    feedback: "You asked about water and she is getting it for you. Do not end the exchange yet.",
                    progresses: false,
                  },
                ],
              },
              {
                id: "step_4",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Prašom.",
                sceneDirection: "Rasa hands you the water. You now have your room key and can head upstairs.",
                learnerPrompt: "Thank her and close the exchange.",
                options: [
                  {
                    id: "a",
                    text: "Ačiū! Viso gero!",
                    result: "best",
                    progresses: true,
                  },
                  {
                    id: "b",
                    text: "Ačiū!",
                    result: "acceptable",
                    progresses: true,
                    feedback: "Ačiū is completely natural. Adding Viso gero also closes the exchange clearly.",
                    betterAnswer: "Ačiū! Viso gero!",
                  },
                  {
                    id: "c",
                    text: "Viso gero!",
                    result: "awkward",
                    progresses: true,
                    feedback: "The goodbye is fine, but after she has handed you the water it is more natural to thank her too.",
                    betterAnswer: "Ačiū! Viso gero!",
                  },
                  {
                    id: "d",
                    text: "Prašom.",
                    result: "wrong",
                    feedback: "Rasa has just said Prašom while handing you the water. Your role here is to thank her and leave.",
                    progresses: false,
                  },
                ],
                finalSystemLine: {
                  speakerId: "receptionist",
                  speakerLabel: "Receptionist",
                  speakerText: "Viso gero!",
                  sceneDirection: "Rasa smiles as you leave reception with your room key and water.",
                },
              },
            ],
          },
        ],
      },

      // ── Checkpoint ──────────────────────────────────────────────────────────
      {
        id: "section_2_module_1_checkpoint",
        code: "2.1.C",
        title: "Checkpoint",
        purpose: "Check you can use all Module 2.1 frames without support.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s2m1c_b1",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're thirsty and want to order something. What do you say?" },
            options: [
              { id: "a", text: "Turiu bilietą.", isCorrect: false },
              { id: "b", text: "Noriu vandens, prašau.", isCorrect: true },
              { id: "c", text: "Ar turite meniu?", isCorrect: false },
            ],
            feedback: { correct: "Noriu vandens, prašau — direct, natural, and polite." },
          },
          {
            id: "s2m1c_b2",
            type: "listen_mcq",
            title: "Listen and identify",
            prompt: { text: "Man reikia bilieto.", audioText: "Man reikia bilieto" },
            options: [
              { id: "a", text: "I want a ticket.", isCorrect: false },
              { id: "b", text: "I need a ticket.", isCorrect: true },
              { id: "c", text: "I have a ticket.", isCorrect: false },
            ],
          },
          {
            id: "s2m1c_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "A cashier asks if you have cash. You don't — only a card." },
            options: [
              { id: "a", text: "Turiu grynųjų.", isCorrect: false },
              { id: "b", text: "Noriu to.", isCorrect: false },
              { id: "c", text: "Neturiu grynųjų, tik kortelę.", isCorrect: true },
            ],
            feedback: { correct: "Neturiu grynųjų, tik kortelę — I don't have cash, only a card." },
          },
          {
            id: "s2m1c_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Do you have a menu?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "turite", correctIndex: 1 },
              { id: "t3", text: "meniu?", correctIndex: 2 },
              { id: "t4", text: "kavos?", isDistractor: true },
            ],
            answerText: "Ar turite meniu?",
          },
          {
            id: "s2m1c_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I need help",
            targetText: "Man reikia pagalbos.",
            audioText: "Man reikia pagalbos",
          },
          {
  id: "s2m1c_b6_v2",
  type: "scenario_v2",
  title: "At the ticket office",
  description: "You're at the ticket office. You need a ticket and have a card with you.",
  sceneIntro: "You're at the ticket office. You need a ticket and have a card with you.",
  location: "ticket office",
  userRole: "traveller",
  register: "polite_service",
  goal: "Retrieve Man reikia…, Turiu… and Ar turite… in one practical exchange.",
  focus: ["Man reikia…", "Turiu…", "Ar turite…?", "Nesuprantu"],
  participants: [
    {
      id: "clerk",
      label: "Clerk",
      name: "Austėja",
      role: "ticket clerk",
      gender: "female",
      relationshipToUser: "stranger",
      register: "polite_service",
    },
  ],
  objects: [
    {
      id: "ticket",
      lt: "bilietas",
      en: "ticket",
      gender: "masculine",
      number: "singular",
    },
    {
      id: "card",
      lt: "kortelė",
      en: "card",
      gender: "feminine",
      number: "singular",
    },
  ],
  steps: [
    {
      id: "step_1",
      speakerId: "clerk",
      speakerLabel: "Clerk",
      speakerText: "Laba diena! Ar galiu jums padėti?",
      sceneDirection: "The clerk looks up from the ticket desk and offers help.",
      learnerPrompt: "Say what you need.",
      options: [
        {
          id: "a",
          text: "Taip! Man reikia bilieto.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Noriu kavos.",
          result: "wrong",
          feedback: "You are at the ticket office because you need a ticket.",
          progresses: false,
        },
        {
          id: "c",
          text: "Viso gero!",
          result: "wrong",
          feedback: "The clerk has just offered to help you.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_2",
      speakerId: "clerk",
      speakerLabel: "Clerk",
      speakerText: "Ar turite kortelę?",
      sceneDirection: "The clerk gestures towards the card terminal.",
      learnerPrompt: "Answer the question. If you are lost, use Nesuprantu.",
      help: {
        levels: [
          {
            sceneDirection: "She holds up a payment card and taps the card terminal.",
            speakerText: "Kortelę?",
          },
          {
            sceneDirection: "She points to the card symbol on the terminal and then to you.",
          },
          {
            speakerText: "Do you have a card?",
            spokenLanguage: "en",
            audio: false,
          },
        ],
      },
      options: [
        {
          id: "a",
          text: "Taip, turiu kortelę.",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Neturiu grynųjų.",
          result: "wrong",
          feedback: "She is asking whether you have a card.",
          progresses: false,
        },
        {
          id: "c",
          text: "Noriu vandens.",
          result: "wrong",
          feedback: "She is asking about the card terminal.",
          progresses: false,
        },
      ],
    },
    {
      id: "step_3",
      speakerId: "clerk",
      speakerLabel: "Clerk",
      speakerText: "Prašau.",
      sceneDirection: "The clerk hands you the ticket.",
      learnerPrompt: "Acknowledge the handover.",
      options: [
        {
          id: "a",
          text: "Ačiū labai!",
          result: "best",
          progresses: true,
        },
        {
          id: "b",
          text: "Man reikia pagalbos.",
          result: "wrong",
          feedback: "You have the ticket you needed.",
          progresses: false,
        },
        {
          id: "c",
          text: "Noriu to.",
          result: "wrong",
          feedback: "Nothing else is being pointed out. The clerk has handed you the ticket.",
          progresses: false,
        },
      ],
      finalSystemLine: {
        speakerId: "clerk",
        speakerLabel: "Clerk",
        speakerText: "Prašom.",
        sceneDirection: "Austėja smiles and the exchange ends.",
      },
    },
  ],
},
          {
            id: "s2m1c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Noriu…",             en: "I want…",                  audioText: "Noriu" },
              { id: "m2",  lt: "Noriu kavos.",        en: "[I] want coffee.",          audioText: "Noriu kavos" },
              { id: "m3",  lt: "Noriu vandens.",      en: "[I] want water.",           audioText: "Noriu vandens" },
              { id: "m4",  lt: "Noriu šito.",         en: "I want this.",              audioText: "Noriu šito" },
              { id: "m5",  lt: "Noriu to.",           en: "I want that.",              audioText: "Noriu to" },
              { id: "m6",  lt: "Man reikia…",         en: "I need…",                  audioText: "Man reikia" },
              { id: "m7",  lt: "Man reikia bilieto.", en: "I need a ticket.",          audioText: "Man reikia bilieto" },
              { id: "m8",  lt: "Man reikia tualeto.", en: "I need a toilet.",          audioText: "Man reikia tualeto" },
              { id: "m9",  lt: "Turiu bilietą.",      en: "I have a ticket.",          audioText: "Turiu bilietą" },
              { id: "m10", lt: "Neturiu grynųjų.",    en: "I don't have cash.",        audioText: "Neturiu grynųjų" },
              { id: "m11", lt: "Turiu kortelę.",      en: "I have a card.",            audioText: "Turiu kortelę" },
              { id: "m12", lt: "Neturiu laiko.",      en: "I don't have time.",        audioText: "Neturiu laiko" },
              { id: "m13", lt: "Ar turite vandens?",  en: "Do you have water?",        audioText: "Ar turite vandens" },
              { id: "m14", lt: "Ar turite kavos?",    en: "Do you have coffee?",       audioText: "Ar turite kavos" },
              { id: "m15", lt: "Ar turite meniu?",    en: "Do you have a menu?",       audioText: "Ar turite meniu" },
              { id: "m16", lt: "Taip, turime.",       en: "Yes, we do.",               audioText: "Taip, turime" },
              { id: "m17", lt: "Ne, neturime.",       en: "No, we don't.",             audioText: "Ne, neturime" },
              { id: "m18", lt: "Bilietas",            en: "Ticket",                    audioText: "Bilietas" },
              { id: "m19", lt: "Kortelė",             en: "Card (payment)",            audioText: "Kortelė" },
              { id: "m20", lt: "Ko norėtumėte?",      en: "What would you like?",      audioText: "Ko norėtumėte" },
            ],
          },
        ],
      },

    ],
  };
}
