// src/content/learning/section2/module_2_4.js
// Module 2.4 — Basic Questions

export default function createModule_2_4(profile = {}) {
  const {
    userFromPhrase = "Aš esu iš Škotijos",
    userFromCountryLabelEn = "Scotland",
  } = profile;

  return {
    id: "module_2_4",
    code: "2.4",
    title: "Basic Questions",
    status: "active",
    lessonCount: 3,
    lessons: [

      // ── Lesson 1 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_4_lesson_1",
        code: "2.4.1",
        title: "What?",
        purpose: "Build recognition of common Lithuanian 'what' question chunks without pretending English 'what' maps to one fixed Lithuanian word.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "English 'what' appears in different Lithuanian chunks. Learn the whole useful question: Kas tai? for identifying something, Ko norėtumėte? in polite service, and Kuo galėčiau padėti? as a natural 'How can I help?' service phrase.",
          usage: [
            "Kas tai? — What is this?",
            "Ko norėtumėte? — What would you like?",
            "Kuo galėčiau padėti? — How can I help?",
            "Kas? — What? / Who? depending on context",
          ],
        },
        blocks: [
          {
            id: "s2m4l1_b1",
            type: "learn",
            title: "Useful question chunks",
            items: [
              { id: "q1", lt: "Kas?", en: "What? / Who? (depends on context)", audioText: "Kas", saveable: true, core: true },
              { id: "q4", lt: "Kuo galėčiau padėti?", en: "How can I help?", audioText: "Kuo galėčiau padėti", saveable: true, core: true },
            ],
          },
          {
            id: "s2m4l1_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kuo galėčiau padėti?", audioText: "Kuo galėčiau padėti" },
            options: [
              { id: "a", text: "What do you need?", isCorrect: false },
              { id: "b", text: "How can I help?", isCorrect: true },
              { id: "c", text: "What would you like?", isCorrect: false },
            ],
          },
          {
            id: "s2m4l1_b3",
            type: "context_gap_select",
            title: "Choose the question chunk",
            prompt: "A server is politely asking a customer what they would like to order.",
            sentence: "___ norėtumėte?",
            translation_en: "What would you like?",
            options: [
              { id: "a", text: "Ko", isCorrect: true },
              { id: "b", text: "Kas", isCorrect: false },
              { id: "c", text: "Kur", isCorrect: false },
            ],
            explanation: "Learn Ko norėtumėte? as a complete polite service question rather than trying to translate 'what' word by word.",
          },
          {
            id: "s2m4l1_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kas tai?", audioText: "Kas tai" },
            options: [
              { id: "a", text: "What is this?", isCorrect: true },
              { id: "b", text: "Who is she?", isCorrect: false },
              { id: "c", text: "Where is it?", isCorrect: false },
            ],
          },
          {
            id: "s2m4l1_b5_v2",
            type: "scenario_v2",
            title: "At the help desk",
            description: "You go to a help desk because you need a ticket. The assistant offers to help.",
            sceneIntro: "You go to a help desk because you need a ticket. The assistant offers to help.",
            location: "help desk",
            userRole: "traveller",
            register: "polite_service",
            goal: "Recognise Kuo galėčiau padėti? and answer with a need you already know.",
            focus: ["Kuo galėčiau padėti?", "Man reikia…", "Nesuprantu"],
            participants: [
              {
                id: "assistant",
                label: "Assistant",
                name: "Rasa",
                role: "help-desk assistant",
                gender: "female",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "assistant",
                speakerLabel: "Assistant",
                speakerText: "Laba diena! Kuo galėčiau padėti?",
                sceneDirection: "You need a ticket. The assistant looks up from the desk and opens her hands to offer help.",
                learnerPrompt: "You need a ticket. Tell her what you need.",
                help: {
                  levels: [
                    {
                      sceneDirection: "She gestures between herself and you as if offering help.",
                      speakerText: "Padėti?",
                    },
                    {
                      sceneDirection: "She points to the help-desk sign, then to you, waiting for your request.",
                    },
                    {
                      speakerText: "How can I help?",
                      spokenLanguage: "en",
                      audio: false,
                    },
                  ],
                },
                options: [
                  { id: "a", text: "Man reikia bilieto.", result: "best", progresses: true },
                  { id: "b", text: "Ko norėtumėte?", result: "wrong", feedback: "The assistant is offering to help you; tell her what you need.", progresses: false },
                  { id: "c", text: "Viso gero!", result: "wrong", feedback: "You have just arrived at the help desk.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "assistant",
                speakerLabel: "Assistant",
                speakerText: "Prašau.",
                sceneDirection: "She hands you the ticket.",
                learnerPrompt: "Acknowledge the handover.",
                options: [
                  { id: "a", text: "Ačiū labai!", result: "best", progresses: true },
                  { id: "b", text: "Ne, ačiū.", result: "wrong", feedback: "She has just handed you the ticket you asked for.", progresses: false },
                  { id: "c", text: "Kas tai?", result: "wrong", feedback: "You asked for the ticket and she has just handed it to you.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 2 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_4_lesson_2",
        code: "2.4.2",
        title: "Where?",
        purpose: "Extend the familiar Kur yra…? frame into simple social questions such as where someone lives and where a group is going.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "Kur? = Where? Kur yra…? is already familiar. In polite speech, Kur gyvenate? is a natural concise 'Where do you live?'; Kur jūs gyvenate? is also correct, with jūs made explicit.",
          usage: [
            "Kur yra stotis? — Where is the station? (review)",
            "Kur gyvenate? — Where do you live? (polite / plural)",
            "Kur jūs gyvenate? — Where do you live? (jūs explicit)",
            "Kur einame? — Where are we going?",
          ],
        },
        blocks: [
          {
            id: "s2m4l2_b1",
            type: "learn",
            title: "Where?",
            items: [
              { id: "wh1", lt: "Kur?", en: "Where?", audioText: "Kur", saveable: true, core: true },
              { id: "wh3", lt: "Kur gyvenate?", en: "Where do you live?", audioText: "Kur gyvenate", saveable: true, core: true },
              { id: "wh4", lt: "Kur jūs gyvenate?", en: "Where do you live? (jūs explicit)", audioText: "Kur jūs gyvenate", saveable: false, core: false },
              { id: "wh5", lt: "Kur einame?", en: "Where are we going?", audioText: "Kur einame", saveable: true, core: true },
              { id: "wh6", lt: "Gyvenu Vilniuje.", en: "I live in Vilnius.", audioText: "Gyvenu Vilniuje", saveable: false, core: false },
            ],
          },
          {
            id: "s2m4l2_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kur gyvenate?", audioText: "Kur gyvenate" },
            options: [
              { id: "a", text: "Where are you going?", isCorrect: false },
              { id: "b", text: "Where do you live?", isCorrect: true },
              { id: "c", text: "Where are you from?", isCorrect: false },
            ],
          },
          {
            id: "s2m4l2_b3",
            type: "context_gap_select",
            title: "Choose the question that fits",
            prompt: "You are politely asking an unfamiliar adult where they live.",
            sentence: "Kur ___?",
            translation_en: "Where do you live?",
            options: [
              { id: "a", text: "gyvenate", isCorrect: true },
              { id: "b", text: "einame", isCorrect: false },
              { id: "c", text: "yra", isCorrect: false },
            ],
            explanation: "Kur gyvenate? is a natural polite question. The verb ending already marks polite/plural 'you', so jūs does not have to be stated.",
          },
          {
            id: "s2m4l2_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Kur einame?", audioText: "Kur einame" },
            options: [
              { id: "a", text: "Where do you live?", isCorrect: false },
              { id: "b", text: "Where are we going?", isCorrect: true },
              { id: "c", text: "Where is the station?", isCorrect: false },
            ],
          },
          {
            id: "s2m4l2_b5",
            type: "conversation_turn_fill",
            scene_label: "First meeting",
            prompt: "Complete your polite question to Rasa.",
            lines: [
              { speaker: "Rasa", text: "Laba diena!", audioText: "Laba diena", hasGap: false },
              { speaker: "You", text: "Laba diena! Kur ___?", hasGap: true },
            ],
            options: [
              { id: "a", text: "gyvenate", isCorrect: true },
              { id: "b", text: "einame", isCorrect: false },
              { id: "c", text: "yra", isCorrect: false },
            ],
            explanation: "Kur gyvenate? asks politely where the other person lives.",
            translation_en: "Rasa: Good day! — You: Good day! Where do you live?",
          },
          {
            id: "s2m4l2_b6_v2",
            type: "scenario_v2",
            title: "Where do you live?",
            description: "At a language exchange, you meet Rasa and ask where she lives.",
            sceneIntro: "At a language exchange, you meet Rasa and ask where she lives.",
            location: "language exchange",
            userRole: "learner",
            register: "polite_friendly",
            goal: "Use the natural concise Kur gyvenate? form in a first-meeting conversation.",
            focus: ["Kur gyvenate?"],
            participants: [
              {
                id: "local",
                label: "Rasa",
                name: "Rasa",
                role: "language-exchange participant",
                gender: "female",
                relationshipToUser: "new acquaintance",
                register: "polite_friendly",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "local",
                speakerLabel: "Rasa",
                speakerText: "Laba diena!",
                sceneDirection: "You have just met Rasa at the language exchange.",
                learnerPrompt: "Greet her and ask where she lives.",
                options: [
                  {
                    id: "a",
                    text: "Laba diena! Kur gyvenate?",
                    result: "best",
                    progresses: true,
                  },
                  {
                    id: "b",
                    text: "Laba diena! Kur jūs gyvenate?",
                    result: "acceptable",
                    feedback: "Also correct. The shorter Kur gyvenate? is the more concise form practised in this lesson.",
                    betterAnswer: "Kur gyvenate?",
                    progresses: true,
                  },
                  {
                    id: "c",
                    text: "Kur einame?",
                    result: "wrong",
                    feedback: "You have just met Rasa; you are asking where she lives, not where the two of you are going.",
                    progresses: false,
                  },
                ],
                finalSystemLine: {
                  speakerId: "local",
                  speakerLabel: "Rasa",
                  speakerText: "Gyvenu Vilniuje.",
                  sceneDirection: "Rasa tells you that she lives in Vilnius.",
                },
              },
            ],
          },
        ],
      },

      // ── Lesson 3 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_4_lesson_3",
        code: "2.4.3",
        title: "Who?",
        purpose: "Ask about people naturally using Kas jis? and Kas ji?, then answer with familiar people language.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "For a specific person, use Kas jis? (Who is he?) or Kas ji? (Who is she?). Keep Kas tai? / Kas čia? for identifying things or situations; do not use them as the beginner person-identification target.",
          usage: [
            "Kas jis? — Who is he?",
            "Kas ji? — Who is she?",
            "Jis mano brolis. — He is my brother.",
            "Ji mano sesuo. — She is my sister.",
            "Jis mano kaimynas. — He is my neighbour.",
            "Ji mano kaimynė. — She is my neighbour.",
          ],
        },
        blocks: [
          {
            id: "s2m4l3_b1",
            type: "learn",
            title: "Who?",
            items: [
              { id: "who1", lt: "Kas jis?", en: "Who is he?", audioText: "Kas jis", saveable: true, core: true },
              { id: "who2", lt: "Kas ji?", en: "Who is she?", audioText: "Kas ji", saveable: true, core: true },
              { id: "who3", lt: "Jis mano brolis.", en: "He is my brother.", audioText: "Jis mano brolis", saveable: true, core: true },
              { id: "who4", lt: "Ji mano sesuo.", en: "She is my sister.", audioText: "Ji mano sesuo", saveable: true, core: true },
              { id: "who5", lt: "Jis mano kaimynas.", en: "He is my neighbour.", audioText: "Jis mano kaimynas", saveable: true, core: false },
              { id: "who6", lt: "Ji mano kaimynė.", en: "She is my neighbour.", audioText: "Ji mano kaimynė", saveable: true, core: false },
            ],
          },
          {
            id: "s2m4l3_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kas ji?", audioText: "Kas ji" },
            options: [
              { id: "a", text: "Who is he?", isCorrect: false },
              { id: "b", text: "Who is she?", isCorrect: true },
              { id: "c", text: "What is this?", isCorrect: false },
            ],
          },
          {
            id: "s2m4l3_b3",
            type: "context_gap_select",
            title: "Choose the person question",
            prompt: "You point to a woman across the room and ask your friend who she is.",
            sentence: "Kas ___?",
            translation_en: "Who is she?",
            options: [
              { id: "a", text: "ji", isCorrect: true },
              { id: "b", text: "jis", isCorrect: false },
              { id: "c", text: "tai", isCorrect: false },
            ],
            explanation: "Use Kas ji? for a specific woman. Kas tai? is the object-identification question you already know.",
          },
          {
            id: "s2m4l3_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Jis mano kaimynas.", audioText: "Jis mano kaimynas" },
            options: [
              { id: "a", text: "He is my neighbour.", isCorrect: true },
              { id: "b", text: "He is my brother.", isCorrect: false },
              { id: "c", text: "She is my neighbour.", isCorrect: false },
            ],
          },
          {
            id: "s2m4l3_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Who is she?",
            targetText: "Kas ji?",
            audioText: "Kas ji",
          },
          {
            id: "s2m4l3_b6_v2",
            type: "scenario_v2",
            title: "Who is she?",
            description: "At a small gathering, Mantas is standing with a woman you have not met.",
            sceneIntro: "At a small gathering, Mantas is standing with a woman you have not met.",
            location: "small gathering",
            userRole: "friend",
            register: "casual",
            goal: "Ask naturally who a specific person is, then respond to the introduction.",
            focus: ["Kas ji?", "Ji mano sesuo"],
            participants: [
              {
                id: "friend",
                label: "Mantas",
                name: "Mantas",
                role: "friend",
                gender: "male",
                relationshipToUser: "friend",
                register: "casual",
              },
              {
                id: "sister",
                label: "Ieva",
                name: "Ieva",
                role: "Mantas's sister",
                gender: "female",
                relationshipToUser: "new acquaintance",
                register: "casual",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "friend",
                speakerLabel: "Mantas",
                speakerText: "Labas!",
                sceneDirection: "Mantas greets you while standing beside a woman you have not met.",
                learnerPrompt: "Greet him and ask who she is.",
                options: [
                  { id: "a", text: "Labas! Kas ji?", result: "best", progresses: true },
                  { id: "b", text: "Labas! Kas jis?", result: "wrong", feedback: "You are asking about the woman beside Mantas.", progresses: false },
                  { id: "c", text: "Labas! Kas tai?", result: "wrong", feedback: "Use Kas ji? for the specific woman. Kas tai? is for identifying a thing.", progresses: false },
                ],
                followUp: {
                  speakerId: "friend",
                  speakerLabel: "Mantas",
                  speakerText: "Ji mano sesuo Ieva.",
                  sceneDirection: "Mantas introduces his sister.",
                },
              },
              {
                id: "step_2",
                speakerId: "sister",
                speakerLabel: "Ieva",
                speakerText: "Labas!",
                sceneDirection: "Ieva joins the conversation and smiles.",
                learnerPrompt: "Respond to the introduction.",
                options: [
                  { id: "a", text: "Malonu susipažinti!", result: "best", progresses: true },
                  { id: "b", text: "Kas ji?", result: "wrong", feedback: "Mantas has just told you who Ieva is.", progresses: false },
                  { id: "c", text: "Viso gero!", result: "wrong", feedback: "You have just been introduced to Ieva.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 4 ────────────────────────────────────────────────────────────
            // ── Lesson 5 ────────────────────────────────────────────────────────────
            // ── Checkpoint ──────────────────────────────────────────────────────────
      {
        id: "section_2_module_4_checkpoint",
        code: "2.4.C",
        title: "Checkpoint",
        purpose: "Check you can recognise and use What / Where / Who questions in practical contexts.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s2m4c_b1",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kuo galėčiau padėti?", audioText: "Kuo galėčiau padėti" },
            options: [
              { id: "a", text: "How can I help?", isCorrect: true },
              { id: "b", text: "What would you like?", isCorrect: false },
              { id: "c", text: "Where do you live?", isCorrect: false },
            ],
          },
          {
            id: "s2m4c_b2",
            type: "context_gap_select",
            title: "Choose the question chunk",
            prompt: "A server is politely asking what the customer would like.",
            sentence: "___ norėtumėte?",
            translation_en: "What would you like?",
            options: [
              { id: "a", text: "Ko", isCorrect: true },
              { id: "b", text: "Kas", isCorrect: false },
              { id: "c", text: "Kur", isCorrect: false },
            ],
            explanation: "Ko norėtumėte? is the useful polite service chunk.",
          },
          {
            id: "s2m4c_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Kur gyvenate?", audioText: "Kur gyvenate" },
            options: [
              { id: "a", text: "Where are you going?", isCorrect: false },
              { id: "b", text: "Where do you live?", isCorrect: true },
              { id: "c", text: "Where are you from?", isCorrect: false },
            ],
          },
          {
            id: "s2m4c_b4",
            type: "context_gap_select",
            title: "Ask about a person",
            prompt: "You point to a man across the room and ask who he is.",
            sentence: "Kas ___?",
            translation_en: "Who is he?",
            options: [
              { id: "a", text: "jis", isCorrect: true },
              { id: "b", text: "ji", isCorrect: false },
              { id: "c", text: "tai", isCorrect: false },
            ],
            explanation: "Use Kas jis? for a specific man.",
          },
          {
            id: "s2m4c_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Where is the station?",
            targetText: "Kur yra stotis?",
            audioText: "Kur yra stotis",
          },
          {
            id: "s2m4c_b6_v2",
            type: "scenario_v2",
            title: "At reception",
            description: "At reception, you ask where the toilet is. As the exchange ends, a colleague joins the receptionist.",
            sceneIntro: "At reception, you ask where the toilet is. As the exchange ends, a colleague joins the receptionist.",
            location: "reception",
            userRole: "visitor",
            register: "polite_service",
            goal: "Combine a natural service question, a Where question and a Who question.",
            focus: ["Kuo galėčiau padėti?", "Kur yra…?", "Kas jis?", "Nesuprantu"],
            participants: [
              {
                id: "receptionist",
                label: "Receptionist",
                name: "Rasa",
                role: "receptionist",
                gender: "female",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
              {
                id: "colleague",
                label: "Colleague",
                name: "Tomas",
                role: "Rasa's colleague",
                gender: "male",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Laba diena! Kuo galėčiau padėti?",
                sceneDirection: "Rasa looks up from the reception desk and offers help.",
                learnerPrompt: "Ask where the toilet is. If the service phrase is not clear, use Nesuprantu.",
                help: {
                  levels: [
                    {
                      sceneDirection: "She gestures between herself and you as if offering help.",
                      speakerText: "Padėti?",
                    },
                    {
                      sceneDirection: "She points to the reception sign, then to you, waiting for your question.",
                    },
                    {
                      speakerText: "How can I help?",
                      spokenLanguage: "en",
                      audio: false,
                    },
                  ],
                },
                options: [
                  { id: "a", text: "Kur yra tualetas?", result: "best", progresses: true },
                  { id: "b", text: "Kas jis?", result: "wrong", feedback: "You first need to ask where the toilet is.", progresses: false },
                  { id: "c", text: "Viso gero!", result: "wrong", feedback: "Rasa has just offered to help you.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Tualetas — va ten.",
                sceneDirection: "Rasa points down the corridor towards the toilet sign.",
                learnerPrompt: "Acknowledge the directions.",
                options: [
                  { id: "a", text: "Ačiū!", result: "best", progresses: true },
                  { id: "b", text: "Kur gyvenate?", result: "wrong", feedback: "Rasa has just shown you where the toilet is.", progresses: false },
                  { id: "c", text: "Ne, ačiū.", result: "wrong", feedback: "She has just answered the question you asked.", progresses: false },
                ],
              },
              {
                id: "step_3",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Prašom.",
                sceneDirection: "A man joins Rasa behind the desk. You do not know who he is.",
                learnerPrompt: "Ask who he is.",
                options: [
                  { id: "a", text: "Kas jis?", result: "best", progresses: true },
                  { id: "b", text: "Kas ji?", result: "wrong", feedback: "You are asking about the man who just joined Rasa.", progresses: false },
                  { id: "c", text: "Kas tai?", result: "wrong", feedback: "Use Kas jis? for the specific man.", progresses: false },
                ],
                finalSystemLine: {
                  speakerId: "receptionist",
                  speakerLabel: "Receptionist",
                  speakerText: "Jis mano kolega Tomas.",
                  sceneDirection: "Rasa introduces her colleague.",
                },
              },
            ],
          },
          {
            id: "s2m4c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Kas?",                    en: "What? / Who? (context)",     audioText: "Kas" },
              { id: "m2",  lt: "Kas tai?",                en: "What is this?",              audioText: "Kas tai" },
              { id: "m3",  lt: "Ko norėtumėte?",         en: "What would you like?",        audioText: "Ko norėtumėte" },
              { id: "m4",  lt: "Kuo galėčiau padėti?",   en: "How can I help?",             audioText: "Kuo galėčiau padėti" },
              { id: "m5",  lt: "Kur?",                    en: "Where?",                      audioText: "Kur" },
              { id: "m6",  lt: "Kur yra stotis?",        en: "Where is the station?",       audioText: "Kur yra stotis" },
              { id: "m7",  lt: "Kur gyvenate?",          en: "Where do you live?",          audioText: "Kur gyvenate" },
              { id: "m8",  lt: "Kur einame?",            en: "Where are we going?",         audioText: "Kur einame" },
              { id: "m9",  lt: "Kas jis?",               en: "Who is he?",                  audioText: "Kas jis" },
              { id: "m10", lt: "Kas ji?",                en: "Who is she?",                 audioText: "Kas ji" },
              { id: "m11", lt: "Jis mano kaimynas.",     en: "He is my neighbour.",         audioText: "Jis mano kaimynas" },
              { id: "m12", lt: "Ji mano kaimynė.",       en: "She is my neighbour.",        audioText: "Ji mano kaimynė" },
              // Spaced retrieval from earlier Section 2 modules
              { id: "m13", lt: "Noriu kavos.",             en: "I want coffee.",                         audioText: "Noriu kavos" },
              { id: "m14", lt: "Man reikia bilieto.",       en: "I need a ticket.",                       audioText: "Man reikia bilieto" },
              { id: "m15", lt: "Ar galite parodyti?",       en: "Can you show me?",                        audioText: "Ar galite parodyti" },
              { id: "m16", lt: "Negaliu eiti.",             en: "I can't go.",                             audioText: "Negaliu eiti" },
              { id: "m17", lt: "Ar galima mokėti kortele?", en: "Is it possible to pay by card?",         audioText: "Ar galima mokėti kortele" },
              { id: "m18", lt: "Šitas obuolys",             en: "This apple",                              audioText: "Šitas obuolys" },
              { id: "m19", lt: "Noriu šitos.",              en: "I want this one. (feminine item)",       audioText: "Noriu šitos" },
              { id: "m20", lt: "Tos, prašau.",              en: "That one, please. (feminine item)",      audioText: "Tos, prašau" },
            ],
          },
        ],
      },

    ],
  };
}
