// src/content/learning/section2/module_2_2.js
// Module 2.2 — Can / Can't / Possible?

export default function createModule_2_2(profile = {}) {
  const {
    userNameSafe = "Davidas",
  } = profile;

  return {
    id: "module_2_2",
    code: "2.2",
    title: "Can / Can't / Possible?",
    status: "active",
    lessonCount: 5,
    lessons: [

      // ── Lesson 1 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_2_lesson_1",
        code: "2.2.1",
        title: "Can I or Can We?",
        purpose: "Consolidate the permission frames already introduced in Section 1 and make the learner choose between individual and shared action.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "Ar galiu…? is for what I can do. Ar galime…? is for what we can do. Lithuanian often leaves the subject unstated because the verb form already tells you who is acting.",
          usage: [
            "Ar galiu pažiūrėti? — Can I have a look?",
            "Ar galiu įeiti? — Can I come in?",
            "Ar galime čia atsisėsti? — Can we sit here?",
            "Ar galime palaukti? — Can we wait?",
          ],
        },
        blocks: [
          {
            id: "s2m2l1_b1",
            type: "learn",
            title: "I or we?",
            items: [
              { id: "r1", lt: "Ar galiu…?", en: "Can I…?", audioText: "Ar galiu", saveable: true, core: true },
              { id: "r2", lt: "Ar galime…?", en: "Can we…?", audioText: "Ar galime", saveable: true, core: true },
              { id: "r3", lt: "Ar galiu pažiūrėti?", en: "Can I have a look?", audioText: "Ar galiu pažiūrėti", saveable: true, core: true },
              { id: "r4", lt: "Ar galime palaukti?", en: "Can we wait?", audioText: "Ar galime palaukti", saveable: true, core: true },
              { id: "r5", lt: "Palaukti", en: "To wait", audioText: "Palaukti", saveable: false, core: false },
            ],
          },
          {
            id: "s2m2l1_b2",
            type: "context_gap_select",
            title: "I or we?",
            prompt: "You are by yourself in a shop and want to look at something behind the counter.",
            sentence: "Ar ___ pažiūrėti?",
            translation_en: "Can I have a look?",
            options: [
              { id: "a", text: "galiu", isCorrect: true },
              { id: "b", text: "galime", isCorrect: false },
              { id: "c", text: "galite", isCorrect: false },
            ],
            explanation: "Galiu means I can. You are asking about your own action.",
          },
          {
            id: "s2m2l1_b3",
            type: "context_gap_select",
            title: "I or we?",
            prompt: "You arrive at a café with a friend and want to ask if both of you can sit at the empty table.",
            sentence: "Ar ___ čia atsisėsti?",
            translation_en: "Can we sit here?",
            options: [
              { id: "a", text: "galiu", isCorrect: false },
              { id: "b", text: "galime", isCorrect: true },
              { id: "c", text: "galite", isCorrect: false },
            ],
            explanation: "Galime means we can. The question is about you and your friend together.",
          },
          {
            id: "s2m2l1_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar galime palaukti?", audioText: "Ar galime palaukti" },
            options: [
              { id: "a", text: "Can I wait?", isCorrect: false },
              { id: "b", text: "Can we wait?", isCorrect: true },
              { id: "c", text: "Can you wait?", isCorrect: false },
            ],
          },
          {
            id: "s2m2l1_b5",
            type: "conversation_turn_fill",
            scene_label: "At a café with a friend",
            prompt: "Complete your question to the server.",
            lines: [
              { speaker: "Server", text: "Laba diena!", audioText: "Laba diena", hasGap: false },
              { speaker: "You", text: "Ar ___ čia atsisėsti?", hasGap: true },
            ],
            options: [
              { id: "a", text: "galiu", isCorrect: false },
              { id: "b", text: "galime", isCorrect: true },
              { id: "c", text: "galite", isCorrect: false },
            ],
            explanation: "You are asking for yourself and your friend, so use galime.",
            translation_en: "Server: Good day! — You: Can we sit here?",
          },
          {
            id: "s2m2l1_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Can we wait?",
            targetText: "Ar galime palaukti?",
            audioText: "Ar galime palaukti",
          },
        ],
      },

      // ── Lesson 2 ────────────────────────────────────────────────────────────
      
      // ── Lesson 3 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_2_lesson_3",
        code: "2.2.2",
        title: "Can You…?",
        purpose: "Build a polite public-use frame for asking another person to do something.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Ar galite…? — Can you…? Use the polite/plural form with staff and unfamiliar adults. It turns verbs such as padėti, pakartoti and parodyti into useful requests.",
          usage: [
            "Ar galite padėti? — Can you help?",
            "Ar galite pakartoti? — Can you repeat?",
            "Ar galite parodyti? — Can you show me?",
            "Ar galite kalbėti lėčiau? — Can you speak more slowly?",
          ],
        },
        blocks: [
          {
            id: "s2m2l3_b1",
            type: "learn",
            title: "Can you…?",
            items: [
              { id: "cy1", lt: "Ar galite padėti?", en: "Can you help?", audioText: "Ar galite padėti", saveable: true, core: true },
              { id: "cy2", lt: "Ar galite pakartoti?", en: "Can you repeat?", audioText: "Ar galite pakartoti", saveable: true, core: true },
              { id: "cy3", lt: "Ar galite parodyti?", en: "Can you show me?", audioText: "Ar galite parodyti", saveable: true, core: true },
              { id: "cy4", lt: "Ar galite kalbėti lėčiau?", en: "Can you speak more slowly?", audioText: "Ar galite kalbėti lėčiau", saveable: true, core: true },
              { id: "cy5", lt: "Taip, žinoma.", en: "Yes, of course.", audioText: "Taip, žinoma", saveable: false, core: false },
            ],
          },
          {
            id: "s2m2l3_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar galite parodyti?", audioText: "Ar galite parodyti" },
            options: [
              { id: "a", text: "Can you repeat?", isCorrect: false },
              { id: "b", text: "Can you show me?", isCorrect: true },
              { id: "c", text: "Can you help?", isCorrect: false },
            ],
          },
          {
            id: "s2m2l3_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar galite kalbėti lėčiau?", audioText: "Ar galite kalbėti lėčiau" },
            options: [
              { id: "a", text: "Can you help?", isCorrect: false },
              { id: "b", text: "Can you repeat?", isCorrect: false },
              { id: "c", text: "Can you speak more slowly?", isCorrect: true },
            ],
          },
          {
            id: "s2m2l3_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "A shop assistant has an item behind the counter. You want them to show it to you." },
            options: [
              { id: "a", text: "Ar galite parodyti?", isCorrect: true },
              { id: "b", text: "Ar galite pakartoti?", isCorrect: false },
              { id: "c", text: "Ar galite kalbėti lėčiau?", isCorrect: false },
            ],
            feedback: { correct: "Ar galite parodyti? asks the other person to show you something." },
          },
          {
            id: "s2m2l3_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Can you repeat?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "galite", correctIndex: 1 },
              { id: "t3", text: "pakartoti?", correctIndex: 2 },
              { id: "t4", text: "parodyti?", isDistractor: true },
            ],
            answerText: "Ar galite pakartoti?",
          },
          {
            id: "s2m2l3_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Can you show me?",
            targetText: "Ar galite parodyti?",
            audioText: "Ar galite parodyti",
          },
          {
            id: "s2m2l3_b7_v2",
            type: "scenario_v2",
            title: "Can you show me?",
            description: "You're in a shop and an item you want to inspect is behind the counter.",
            sceneIntro: "You're in a shop and an item you want to inspect is behind the counter.",
            location: "shop counter",
            userRole: "customer",
            register: "polite_service",
            goal: "Use Ar galite…? to ask another person to act.",
            focus: ["Ar galite…?", "parodyti"],
            participants: [
              {
                id: "seller",
                label: "Seller",
                name: "Tomas",
                role: "seller",
                gender: "male",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Laba diena!",
                sceneDirection: "The seller greets you. The item you want to inspect is behind the counter.",
                learnerPrompt: "Ask him to show it to you.",
                options: [
                  { id: "a", text: "Laba diena! Ar galite parodyti?", result: "best", progresses: true },
                  { id: "b", text: "Ar galite pakartoti?", result: "wrong", feedback: "Nothing needs repeating. You want to see the item behind the counter.", progresses: false },
                  { id: "c", text: "Viso gero!", result: "wrong", feedback: "You have just arrived and want to inspect the item.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Taip, žinoma.",
                sceneDirection: "He takes the item from behind the counter and places it in front of you.",
                learnerPrompt: "Acknowledge the help.",
                options: [
                  { id: "a", text: "Ačiū labai!", result: "best", progresses: true },
                  { id: "b", text: "Ne, ačiū.", result: "wrong", feedback: "He has just done what you asked.", progresses: false },
                  { id: "c", text: "Ar galite pakartoti?", result: "wrong", feedback: "He has shown you the item rather than said something unclear.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 4 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_2_lesson_4",
        code: "2.2.3",
        title: "I Can / I Can't",
        purpose: "Add simple ability and limitation as response tools.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Galiu = I can. Negaliu = I can't. As with noriu, the subject is often unnecessary when the verb already makes the speaker clear.",
          usage: [
            "Galiu palaukti. — I can wait.",
            "Negaliu eiti. — I can't go.",
            "Galiu šiek tiek kalbėti lietuviškai. — I can speak a little Lithuanian.",
            "Taip, galiu. — Yes, I can.",
            "Ne, negaliu. — No, I can't.",
          ],
        },
        blocks: [
          {
            id: "s2m2l4_b1",
            type: "learn",
            title: "I can / I can't",
            items: [
              { id: "ic1", lt: "Galiu…", en: "I can…", audioText: "Galiu", saveable: true, core: true },
              { id: "ic2", lt: "Negaliu…", en: "I can't…", audioText: "Negaliu", saveable: true, core: true },
              { id: "ic3", lt: "Galiu palaukti.", en: "I can wait.", audioText: "Galiu palaukti", saveable: true, core: true },
              { id: "ic4", lt: "Negaliu eiti.", en: "I can't go.", audioText: "Negaliu eiti", saveable: true, core: true },
              { id: "ic5", lt: "Galiu šiek tiek kalbėti lietuviškai.", en: "I can speak a little Lithuanian.", audioText: "Galiu šiek tiek kalbėti lietuviškai", saveable: true, core: true },
              { id: "ic6", lt: "Taip, galiu.", en: "Yes, I can.", audioText: "Taip, galiu", saveable: false, core: false },
              { id: "ic7", lt: "Ne, negaliu.", en: "No, I can't.", audioText: "Ne, negaliu", saveable: false, core: false },
            ],
          },
          {
            id: "s2m2l4_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Negaliu eiti.", audioText: "Negaliu eiti" },
            options: [
              { id: "a", text: "I can go.", isCorrect: false },
              { id: "b", text: "I can't go.", isCorrect: true },
              { id: "c", text: "I don't want to go.", isCorrect: false },
            ],
          },
          {
            id: "s2m2l4_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Galiu palaukti.", audioText: "Galiu palaukti" },
            options: [
              { id: "a", text: "I can't wait.", isCorrect: false },
              { id: "b", text: "I need to wait.", isCorrect: false },
              { id: "c", text: "I can wait.", isCorrect: true },
            ],
          },
          {
            id: "s2m2l4_b4",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Someone asks if you can go now. You cannot." },
            options: [
              { id: "a", text: "Taip, galiu.", isCorrect: false },
              { id: "b", text: "Ne, negaliu.", isCorrect: true },
              { id: "c", text: "Galiu palaukti.", isCorrect: false },
            ],
            feedback: { correct: "Ne, negaliu — a clear direct answer when you cannot." },
          },
          {
            id: "s2m2l4_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "I can wait." },
            tokens: [
              { id: "t1", text: "Galiu", correctIndex: 0 },
              { id: "t2", text: "palaukti.", correctIndex: 1 },
              { id: "t3", text: "Negaliu", isDistractor: true },
            ],
            answerText: "Galiu palaukti.",
          },
          {
            id: "s2m2l4_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I can speak a little Lithuanian",
            targetText: "Galiu šiek tiek kalbėti lietuviškai.",
            audioText: "Galiu šiek tiek kalbėti lietuviškai",
          },
          {
            id: "s2m2l4_b7_v2",
            type: "scenario_v2",
            title: "Can you wait?",
            description: "At reception, the receptionist needs a moment before she can help you.",
            sceneIntro: "At reception, the receptionist needs a moment before she can help you.",
            location: "reception",
            userRole: "visitor",
            register: "polite_service",
            goal: "Understand an ability question and answer with galiu or negaliu.",
            focus: ["galiu", "negaliu", "Nesuprantu"],
            participants: [
              {
                id: "receptionist",
                label: "Receptionist",
                name: "Rasa",
                role: "receptionist",
                gender: "female",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "receptionist",
                speakerLabel: "Receptionist",
                speakerText: "Ar galite palaukti?",
                sceneDirection: "The receptionist gestures towards the waiting chairs while she finishes something at the desk.",
                learnerPrompt: "If you can wait, tell her. If the question is not clear, use Nesuprantu.",
                help: {
                  levels: [
                    {
                      sceneDirection: "She points to the chairs and makes a small waiting gesture with her hand.",
                      speakerText: "Palaukti?",
                    },
                    {
                      sceneDirection: "She points to the chair, then to you, and holds up a hand to mean wait.",
                    },
                    {
                      speakerText: "Can you wait?",
                      spokenLanguage: "en",
                      audio: false,
                    },
                  ],
                },
                options: [
                  { id: "a", text: "Taip, galiu.", result: "best", progresses: true },
                  { id: "b", text: "Ne, neturiu.", result: "wrong", feedback: "She is asking whether you can wait, not whether you have something.", progresses: false },
                  { id: "c", text: "Viso gero!", result: "wrong", feedback: "She is asking you to wait for a moment.", progresses: false },
                ],
                finalSystemLine: {
                  speakerId: "receptionist",
                  speakerLabel: "Receptionist",
                  speakerText: "Ačiū.",
                  sceneDirection: "She smiles and returns to the desk while you wait.",
                },
              },
            ],
          },
        ],
      },

      // ── Lesson 5 ────────────────────────────────────────────────────────────
      {
        id: "section_2_module_2_lesson_5",
        code: "2.2.4",
        title: "Is It Possible?",
        purpose: "Introduce the impersonal Ar galima…? frame for asking whether something is allowed or possible.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "Ar galima…? asks whether something is allowed or possible without focusing on a particular person. Compare Ar galiu…? when you are specifically asking what I may do.",
          usage: [
            "Ar galima mokėti kortele? — Is it possible to pay by card?",
            "Ar galima čia laukti? — Is it allowed to wait here?",
            "Ar galima įeiti? — Is it allowed to enter?",
            "Taip, galima. — Yes, that's allowed / possible.",
          ],
        },
        blocks: [
          {
            id: "s2m2l5_b1",
            type: "learn",
            title: "Is it allowed / possible?",
            items: [
              { id: "p1", lt: "Ar galima…?", en: "Is it allowed / possible…?", audioText: "Ar galima", saveable: true, core: true },
              { id: "p2", lt: "Ar galima mokėti kortele?", en: "Is it possible to pay by card?", audioText: "Ar galima mokėti kortele", saveable: true, core: true },
              { id: "p3", lt: "Ar galima čia laukti?", en: "Is it allowed to wait here?", audioText: "Ar galima čia laukti", saveable: true, core: true },
              { id: "p4", lt: "Ar galima įeiti?", en: "Is it allowed to enter?", audioText: "Ar galima įeiti", saveable: true, core: true },
              { id: "p5", lt: "Taip, galima.", en: "Yes, that's allowed / possible.", audioText: "Taip, galima", saveable: false, core: false },
            ],
          },
          {
            id: "s2m2l5_b2",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Ar galima mokėti kortele?", audioText: "Ar galima mokėti kortele" },
            options: [
              { id: "a", text: "Can you pay by card?", isCorrect: false },
              { id: "b", text: "Do you have a card?", isCorrect: false },
              { id: "c", text: "Is it possible to pay by card?", isCorrect: true },
            ],
          },
          {
            id: "s2m2l5_b3",
            type: "context_gap_select",
            title: "I or generally allowed?",
            prompt: "At a shop, you want to ask whether card payment is accepted here in general.",
            sentence: "___ mokėti kortele?",
            translation_en: "Is it possible to pay by card?",
            options: [
              { id: "a", text: "Ar galima", isCorrect: true },
              { id: "b", text: "Ar galiu", isCorrect: false },
              { id: "c", text: "Ar galite", isCorrect: false },
            ],
            explanation: "Ar galima…? asks about what is allowed or possible in the situation generally.",
          },
          {
            id: "s2m2l5_b4",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Ar galima čia laukti?", audioText: "Ar galima čia laukti" },
            options: [
              { id: "a", text: "Is it allowed to wait here?", isCorrect: true },
              { id: "b", text: "Can I sit here?", isCorrect: false },
              { id: "c", text: "Can you wait here?", isCorrect: false },
            ],
          },
          {
            id: "s2m2l5_b5",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Is it possible to pay by card?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "galima", correctIndex: 1 },
              { id: "t3", text: "mokėti", correctIndex: 2 },
              { id: "t4", text: "kortele?", correctIndex: 3 },
              { id: "t5", text: "galiu", isDistractor: true },
            ],
            answerText: "Ar galima mokėti kortele?",
          },
          {
            id: "s2m2l5_b6",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask: Is it allowed to wait here?",
            targetText: "Ar galima čia laukti?",
            audioText: "Ar galima čia laukti",
          },
          {
            id: "s2m2l5_b7_v2",
            type: "scenario_v2",
            title: "Paying by card",
            description: "At a market stall, you want to check whether card payment is accepted.",
            sceneIntro: "At a market stall, you want to check whether card payment is accepted.",
            location: "market stall",
            userRole: "customer",
            register: "polite_service",
            goal: "Use Ar galima…? for a general possibility question.",
            focus: ["Ar galima…?", "mokėti kortele"],
            participants: [
              {
                id: "seller",
                label: "Seller",
                name: "Tomas",
                role: "seller",
                gender: "male",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Prašau.",
                sceneDirection: "The seller places your item beside the card terminal and cash tray.",
                learnerPrompt: "Ask whether card payment is possible.",
                options: [
                  { id: "a", text: "Ar galima mokėti kortele?", result: "best", progresses: true },
                  { id: "b", text: "Ar galite pakartoti?", result: "wrong", feedback: "Nothing needs repeating. You want to check the payment method.", progresses: false },
                  { id: "c", text: "Ar galime palaukti?", result: "wrong", feedback: "You are ready to pay, not asking whether your group can wait.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Taip, galima.",
                sceneDirection: "He turns the card terminal towards you.",
                learnerPrompt: "Acknowledge the answer.",
                options: [
                  { id: "a", text: "Ačiū!", result: "best", progresses: true },
                  { id: "b", text: "Ne, negaliu.", result: "wrong", feedback: "He has just confirmed that card payment is possible.", progresses: false },
                  { id: "c", text: "Ar galite parodyti?", result: "wrong", feedback: "The card terminal is already in front of you.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Checkpoint ──────────────────────────────────────────────────────────
      {
        id: "section_2_module_2_checkpoint",
        code: "2.2.C",
        title: "Checkpoint",
        purpose: "Check you can choose between I/we/you, express ability and ask whether something is generally allowed or possible.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s2m2c_b1",
            type: "context_gap_select",
            title: "I or we?",
            prompt: "You are with a friend and want to ask whether both of you can wait here.",
            sentence: "Ar ___ čia palaukti?",
            translation_en: "Can we wait here?",
            options: [
              { id: "a", text: "galiu", isCorrect: false },
              { id: "b", text: "galime", isCorrect: true },
              { id: "c", text: "galite", isCorrect: false },
            ],
            explanation: "Galime because the action is shared by you and your friend.",
          },
          {
            id: "s2m2c_b2",
            type: "listen_mcq",
            title: "Listen and identify",
            prompt: { text: "Ar galite pakartoti?", audioText: "Ar galite pakartoti" },
            options: [
              { id: "a", text: "Can you help?", isCorrect: false },
              { id: "b", text: "Can you repeat?", isCorrect: true },
              { id: "c", text: "Can you show me?", isCorrect: false },
            ],
          },
          {
            id: "s2m2c_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Someone asks if you can wait. You can." },
            options: [
              { id: "a", text: "Taip, galiu.", isCorrect: true },
              { id: "b", text: "Ne, negaliu.", isCorrect: false },
              { id: "c", text: "Ar galima palaukti?", isCorrect: false },
            ],
            feedback: { correct: "Taip, galiu — yes, I can." },
          },
          {
            id: "s2m2c_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Is it possible to pay by card?" },
            tokens: [
              { id: "t1", text: "Ar", correctIndex: 0 },
              { id: "t2", text: "galima", correctIndex: 1 },
              { id: "t3", text: "mokėti", correctIndex: 2 },
              { id: "t4", text: "kortele?", correctIndex: 3 },
              { id: "t5", text: "galite", isDistractor: true },
            ],
            answerText: "Ar galima mokėti kortele?",
          },
          {
            id: "s2m2c_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask if they can speak more slowly",
            targetText: "Ar galite kalbėti lėčiau?",
            audioText: "Ar galite kalbėti lėčiau",
          },
          {
            id: "s2m2c_b6_v2",
            type: "scenario_v2",
            title: "At the information desk",
            description: "You and a friend arrive at an information desk and need a place to wait and a map from behind the counter.",
            sceneIntro: "You and a friend arrive at an information desk and need a place to wait and a map from behind the counter.",
            location: "information desk",
            userRole: "visitor",
            register: "polite_service",
            goal: "Use Can we…? and Can you…? in one natural public interaction.",
            focus: ["Ar galime…?", "Ar galite…?"],
            participants: [
              {
                id: "assistant",
                label: "Assistant",
                name: "Rasa",
                role: "information assistant",
                gender: "female",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1",
                speakerId: "assistant",
                speakerLabel: "Assistant",
                speakerText: "Laba diena! Ar galiu jums padėti?",
                sceneDirection: "You and your friend are standing beside an empty waiting area.",
                learnerPrompt: "Ask if both of you can wait here.",
                options: [
                  { id: "a", text: "Taip. Ar galime čia palaukti?", result: "best", progresses: true },
                  { id: "b", text: "Ar galiu čia palaukti?", result: "acceptable", feedback: "That asks only for yourself. Because your friend is with you too, galime is more precise here.", betterAnswer: "Ar galime čia palaukti?", progresses: true },
                  { id: "c", text: "Viso gero!", result: "wrong", feedback: "The assistant has offered to help you and your friend.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "assistant",
                speakerLabel: "Assistant",
                speakerText: "Taip, galite.",
                sceneDirection: "She gestures towards the waiting chairs. You then notice a map behind the desk.",
                learnerPrompt: "Ask her to show you the map.",
                options: [
                  { id: "a", text: "Ačiū. Ar galite parodyti?", result: "best", progresses: true },
                  { id: "b", text: "Ar galime parodyti?", result: "wrong", feedback: "You want the assistant to show something to you, so use galite.", progresses: false },
                  { id: "c", text: "Ne, negaliu.", result: "wrong", feedback: "She has just said that you may wait here.", progresses: false },
                ],
              },
              {
                id: "step_3",
                speakerId: "assistant",
                speakerLabel: "Assistant",
                speakerText: "Taip, žinoma.",
                sceneDirection: "She takes the map from behind the desk and places it in front of you.",
                learnerPrompt: "Acknowledge the help.",
                options: [
                  { id: "a", text: "Ačiū labai!", result: "best", progresses: true },
                  { id: "b", text: "Ar galima mokėti kortele?", result: "wrong", feedback: "Nothing is being bought in this exchange.", progresses: false },
                  { id: "c", text: "Ne, ačiū.", result: "wrong", feedback: "She has just done what you asked.", progresses: false },
                ],
              },
            ],
          },
          {
            id: "s2m2c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Ar galiu…?",                       en: "Can I…?",                              audioText: "Ar galiu" },
              { id: "m2",  lt: "Ar galime…?",                      en: "Can we…?",                             audioText: "Ar galime" },
              { id: "m3",  lt: "Ar galiu pažiūrėti?",              en: "Can I have a look?",                   audioText: "Ar galiu pažiūrėti" },
              { id: "m4",  lt: "Ar galime palaukti?",              en: "Can we wait?",                         audioText: "Ar galime palaukti" },
              { id: "m5",  lt: "Ar galite padėti?",                en: "Can you help?",                        audioText: "Ar galite padėti" },
              { id: "m6",  lt: "Ar galite pakartoti?",             en: "Can you repeat?",                      audioText: "Ar galite pakartoti" },
              { id: "m7",  lt: "Ar galite parodyti?",              en: "Can you show me?",                     audioText: "Ar galite parodyti" },
              { id: "m8",  lt: "Ar galite kalbėti lėčiau?",        en: "Can you speak more slowly?",           audioText: "Ar galite kalbėti lėčiau" },
              { id: "m9",  lt: "Galiu…",                           en: "I can…",                               audioText: "Galiu" },
              { id: "m10", lt: "Negaliu…",                         en: "I can't…",                             audioText: "Negaliu" },
              { id: "m11", lt: "Galiu palaukti.",                  en: "I can wait.",                          audioText: "Galiu palaukti" },
              { id: "m12", lt: "Negaliu eiti.",                    en: "I can't go.",                          audioText: "Negaliu eiti" },
              { id: "m13", lt: "Galiu šiek tiek kalbėti lietuviškai.", en: "I can speak a little Lithuanian.", audioText: "Galiu šiek tiek kalbėti lietuviškai" },
              { id: "m14", lt: "Ar galima…?",                      en: "Is it allowed / possible…?",           audioText: "Ar galima" },
              { id: "m15", lt: "Ar galima mokėti kortele?",        en: "Is it possible to pay by card?",       audioText: "Ar galima mokėti kortele" },
              { id: "m16", lt: "Ar galima čia laukti?",            en: "Is it allowed to wait here?",          audioText: "Ar galima čia laukti" },
              { id: "m17", lt: "Ar galima įeiti?",                 en: "Is it allowed to enter?",              audioText: "Ar galima įeiti" },
              { id: "m18", lt: "Taip, galima.",                    en: "Yes, that's allowed / possible.",      audioText: "Taip, galima" },
              { id: "m19", lt: "Taip, galite.",                    en: "Yes, you can.",                        audioText: "Taip, galite" },
              { id: "m20", lt: "Taip, galiu.",                     en: "Yes, I can.",                          audioText: "Taip, galiu" },
            ],
          },
        ],
      },

    ],
  };
}
