// src/content/learning/section4/module_4_2.js
// Module 4.2 — At the Café

export default function createModule_4_2(profile = {}) {
  const { userNameSafe = "Davidas" } = profile;

  return {
    id: "module_4_2",
    code: "4.2",
    title: "At the Café",
    status: "active",
    lessonCount: 5,
    lessons: [

      // ── Lesson 1 — Coffee, Tea, Water ────────────────────────────────────────
      {
        id: "section_4_module_2_lesson_1",
        code: "4.2.1",
        title: "Coffee, Tea, Water",
        purpose: "Lock in the core drink items and the ordering question you will hear in every café.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Kava, arbata, vanduo are the base forms. In orders you use the genitive: kavos, arbatos, vandens — the same endings you have already been using since Module 2.1.",
          usage: [
            "kava — coffee",
            "arbata — tea",
            "vanduo — water",
            "Norėčiau kavos — I would like coffee",
            "Vandens, prašau — Water, please",
          ],
        },
        blocks: [
          {
            id: "s4m2l1_b1",
            type: "learn",
            title: "Core drink vocabulary",
            items: [
              { id: "dr1", lt: "kava", en: "coffee", audioText: "kava", saveable: true, core: true },
              { id: "dr2", lt: "arbata", en: "tea", audioText: "arbata", saveable: true, core: true },
              { id: "dr3", lt: "vanduo", en: "water", audioText: "vanduo", saveable: true, core: true },
              { id: "dr4", lt: "Norėčiau kavos.", en: "I would like coffee.", audioText: "Norėčiau kavos", saveable: true, core: true },
              { id: "dr5", lt: "Norėčiau arbatos.", en: "I would like tea.", audioText: "Norėčiau arbatos", saveable: true, core: true },
              { id: "dr6", lt: "Vandens, prašau.", en: "Water, please.", audioText: "Vandens, prašau", saveable: true, core: true },
              { id: "noun_sultys", lt: "sultys", en: "juice", audioText: "sultys", saveable: true, core: false },
            ],
          },
          {
            id: "s4m2l1_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Norėčiau kavos.", audioText: "Norėčiau kavos" },
            options: [
              { id: "a", text: "I would like tea.", isCorrect: false },
              { id: "b", text: "I would like coffee.", isCorrect: true },
              { id: "c", text: "Water, please.", isCorrect: false },
            ],
          },
          {
            id: "s4m2l1_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Vandens, prašau.", audioText: "Vandens, prašau" },
            options: [
              { id: "a", text: "Tea, please.", isCorrect: false },
              { id: "b", text: "Coffee, please.", isCorrect: false },
              { id: "c", text: "Water, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m2l1_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I would like coffee",
            targetText: "Norėčiau kavos",
            audioText: "Norėčiau kavos",
          },
          {
            id: "s4m2l1_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "You sit down at a café. The staff comes to take your order.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ko norėtumėte?",
                audioText: "Laba diena! Ko norėtumėte",
                helperText: "Good day! What would you like?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Norėčiau kavos, prašau.", en: "I would like coffee, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Žinoma. Prašom.",
                audioText: "Žinoma. Prašom",
                helperText: "Of course. Here you go.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū!", en: "Thank you!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 2 — For Here / To Go ──────────────────────────────────────────
      {
        id: "section_4_module_2_lesson_2",
        code: "4.2.2",
        title: "For Here / To Go",
        purpose: "Handle one of the most common modern café interactions — the for-here or to-go question.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Čia ar išsinešti? — For here or to go? You already know čia (here). Išsinešti is the to-go form — learn it as a fixed chunk for now.",
          usage: [
            "Čia ar išsinešti? — For here or to go?",
            "Čia, prašau — For here, please",
            "Išsinešti, prašau — To go, please",
          ],
        },
        blocks: [
          {
            id: "s4m2l2_b1",
            type: "learn",
            title: "For here or to go",
            items: [
              { id: "fg1", lt: "Čia ar išsinešti?", en: "For here or to go?", audioText: "Čia ar išsinešti", saveable: true, core: true },
              { id: "fg2", lt: "Čia, prašau.", en: "For here, please.", audioText: "Čia, prašau", saveable: true, core: true },
              { id: "fg3", lt: "Išsinešti, prašau.", en: "To go, please.", audioText: "Išsinešti, prašau", saveable: true, core: true },
            ],
          },
          {
            id: "s4m2l2_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Čia ar išsinešti?", audioText: "Čia ar išsinešti" },
            options: [
              { id: "a", text: "Coffee or tea?", isCorrect: false },
              { id: "b", text: "For here or to go?", isCorrect: true },
              { id: "c", text: "Card or cash?", isCorrect: false },
            ],
          },
          {
            id: "s4m2l2_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Staff asks: Čia ar išsinešti? You want to sit down and drink it here." },
            options: [
              { id: "a", text: "Išsinešti, prašau.", isCorrect: false },
              { id: "b", text: "Čia, prašau.", isCorrect: true },
              { id: "c", text: "Norėčiau kavos.", isCorrect: false },
            ],
            feedback: { correct: "Čia, prašau — For here, please. Short and clear." },
          },
          {
            id: "s4m2l2_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say you want it to go",
            targetText: "Išsinešti, prašau",
            audioText: "Išsinešti, prašau",
          },
          {
            id: "s4m2l2_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "You order a coffee at a takeaway counter. They ask the for-here question.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Ko norėtumėte?",
                audioText: "Ko norėtumėte",
                helperText: "What would you like?",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Norėčiau kavos, prašau.", en: "I would like coffee, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Čia ar išsinešti?",
                audioText: "Čia ar išsinešti",
                helperText: "For here or to go?",
                options: [
                  { id: "a", text: "Norėčiau arbatos.", isCorrect: false },
                  { id: "b", text: "Išsinešti, prašau.", en: "To go, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Gerai. Prašom.",
                audioText: "Gerai. Prašom",
                helperText: "OK. Here you go.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū!", en: "Thank you!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 3 — With / Without ─────────────────────────────────────────────
      {
        id: "section_4_module_2_lesson_3",
        code: "4.2.3",
        title: "With / Without",
        purpose: "Customise a drink simply — the most useful café language after ordering.",
        supportLevel: "medium",
        newLanguageLoad: "medium",
        notes: {
          pattern: "Su… (with) and be… (without) are small but powerful chunks. They work with any drink or food item.",
          usage: [
            "su pienu — with milk",
            "be cukraus — without sugar",
            "su citrina — with lemon",
            "Su pienu ar be pieno? — With milk or without milk?",
          ],
        },
        blocks: [
          {
            id: "s4m2l3_b1",
            type: "learn",
            title: "Customising with su and be",
            items: [
              { id: "cu1", lt: "su pienu", en: "with milk", audioText: "su pienu", saveable: true, core: true },
              { id: "cu2", lt: "be cukraus", en: "without sugar", audioText: "be cukraus", saveable: true, core: true },
              { id: "cu3", lt: "su citrina", en: "with lemon", audioText: "su citrina", saveable: true, core: true },
              { id: "cu4", lt: "pienas", en: "milk", audioText: "pienas", saveable: true, core: true },
              { id: "cu5", lt: "cukrus", en: "sugar", audioText: "cukrus", saveable: true, core: true },
              { id: "cu6", lt: "citrina", en: "lemon", audioText: "citrina", saveable: true, core: true },
              { id: "cu7", lt: "Norėčiau kavos su pienu.", en: "I would like coffee with milk.", audioText: "Norėčiau kavos su pienu", saveable: true, core: true },
              { id: "cu8", lt: "Arbatos be cukraus, prašau.", en: "Tea without sugar, please.", audioText: "Arbatos be cukraus, prašau", saveable: true, core: true },
              { id: "cu9", lt: "Su pienu ar be pieno?", en: "With milk or without milk?", audioText: "Su pienu ar be pieno", saveable: false, core: false },
            ],
          },
          {
            id: "s4m2l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Su pienu ar be pieno?", audioText: "Su pienu ar be pieno" },
            options: [
              { id: "a", text: "With sugar or without?", isCorrect: false },
              { id: "b", text: "With milk or without milk?", isCorrect: true },
              { id: "c", text: "Coffee or tea?", isCorrect: false },
            ],
          },
          {
            id: "s4m2l3_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Arbatos be cukraus, prašau.", audioText: "Arbatos be cukraus, prašau" },
            options: [
              { id: "a", text: "Coffee with sugar, please.", isCorrect: false },
              { id: "b", text: "Tea with lemon, please.", isCorrect: false },
              { id: "c", text: "Tea without sugar, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m2l3_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Tea without sugar, please." },
            tokens: [
              { id: "t1", text: "Arbatos", correctIndex: 0 },
              { id: "t2", text: "be", correctIndex: 1 },
              { id: "t3", text: "cukraus,", correctIndex: 2 },
              { id: "t4", text: "prašau", correctIndex: 3 },
              { id: "t5", text: "su", isDistractor: true },
              { id: "t6", text: "pienu,", isDistractor: true },
            ],
            answerText: "Arbatos be cukraus, prašau",
          },
          // ── Pattern to Notice ────────────────────────────────────────────────
          {
            id: "s4m2l3_b5",
            type: "learn",
            title: "Pattern to notice — words change form",
            items: [
              { id: "pn1", lt: "pienas → su pienu", en: "milk → with milk", audioText: "pienas. su pienu", saveable: false, core: false },
              { id: "pn2", lt: "cukrus → be cukraus", en: "sugar → without sugar", audioText: "cukrus. be cukraus", saveable: false, core: false },
              { id: "pn3", lt: "arbata → arbatos", en: "tea → (of) tea", audioText: "arbata. arbatos", saveable: false, core: false },
            ],
            notes: {
              pattern: "You may have noticed that pienas becomes pienu after su, and cukrus becomes cukraus after be. Lithuanian words change their endings depending on how they are used in a sentence — this is completely normal and you will see it throughout the language. You have already seen it with kavos, arbatos, vandens when ordering. For now, just notice it happening. The chunks work as they are — you do not need to know the rules to use them correctly.",
            },
          },
          {
            id: "s4m2l3_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You order a coffee and customise it exactly how you want it.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Ko norėtumėte?",
                audioText: "Ko norėtumėte",
                helperText: "What would you like?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Norėčiau kavos, prašau.", en: "I would like coffee, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Su pienu ar be pieno?",
                audioText: "Su pienu ar be pieno",
                helperText: "With milk or without milk?",
                options: [
                  { id: "a", text: "Čia, prašau.", isCorrect: false },
                  { id: "b", text: "Su pienu, prašau.", en: "With milk, please.", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Ar su cukrumi?",
                audioText: "Ar su cukrumi",
                helperText: "With sugar?",
                options: [
                  { id: "a", text: "Su pienu.", isCorrect: false },
                  { id: "b", text: "Ne, be cukraus, prašau.", en: "No, without sugar, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom.",
                audioText: "Prašom",
                helperText: "Here you go.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Kur yra tualetas?", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 4 — The Bill, Please ───────────────────────────────────────────
      {
        id: "section_4_module_2_lesson_4",
        code: "4.2.4",
        title: "The Bill, Please",
        purpose: "Close the café interaction cleanly — ask for the bill, pay, and leave.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "Sąskaitą, prašau and Noriu sumokėti are already in your vocabulary from Section 3. This lesson brings them into a natural closing sequence.",
          usage: [
            "Sąskaitą, prašau — The bill, please",
            "Noriu sumokėti — I want to pay",
            "Galima mokėti kortele? — Can I pay by card?",
          ],
        },
        blocks: [
          {
            id: "s4m2l4_b1",
            type: "learn",
            title: "Closing the café interaction",
            items: [
              { id: "bl1", lt: "Sąskaitą, prašau.", en: "The bill, please.", audioText: "Sąskaitą, prašau", saveable: true, core: true },
              { id: "bl2", lt: "Noriu sumokėti.", en: "I want to pay.", audioText: "Noriu sumokėti", saveable: true, core: true },
              { id: "bl3", lt: "Galima mokėti kortele?", en: "Can I pay by card?", audioText: "Galima mokėti kortele", saveable: true, core: true },
              { id: "bl4", lt: "Grynaisiais ar kortele?", en: "Cash or card?", audioText: "Grynaisiais ar kortele", saveable: false, core: false },
            ],
          },
          {
            id: "s4m2l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Sąskaitą, prašau.", audioText: "Sąskaitą, prašau" },
            options: [
              { id: "a", text: "The coffee, please.", isCorrect: false },
              { id: "b", text: "The bill, please.", isCorrect: true },
              { id: "c", text: "One more, please.", isCorrect: false },
            ],
          },
          {
            id: "s4m2l4_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You are finished at the café and want to pay. What do you say?" },
            options: [
              { id: "a", text: "Norėčiau kavos.", isCorrect: false },
              { id: "b", text: "Sąskaitą, prašau.", isCorrect: true },
              { id: "c", text: "Viso gero.", isCorrect: false },
            ],
            feedback: { correct: "Sąskaitą, prašau — The bill, please. The natural way to close any café or restaurant interaction." },
          },
          {
            id: "s4m2l4_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask for the bill",
            targetText: "Sąskaitą, prašau",
            audioText: "Sąskaitą, prašau",
          },
          {
            id: "s4m2l4_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "You have finished your coffee. Time to pay and leave.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Ar gerai?",
                audioText: "Ar gerai",
                helperText: "Is everything OK?",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Taip, ačiū! Sąskaitą, prašau.", en: "Yes, thank you! The bill, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Žinoma. Grynaisiais ar kortele?",
                audioText: "Žinoma. Grynaisiais ar kortele",
                helperText: "Of course. Cash or card?",
                options: [
                  { id: "a", text: "Sąskaitą, prašau.", isCorrect: false },
                  { id: "b", text: "Kortele, prašau.", en: "By card, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom. Ačiū!",
                audioText: "Prašom. Ačiū",
                helperText: "Here you are. Thank you!",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū! Viso gero!", en: "Thank you! Goodbye!", isCorrect: true },
                  { id: "c", text: "Kur yra tualetas?", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 5 — Simple Café Flow ───────────────────────────────────────────
      {
        id: "section_4_module_2_lesson_5",
        code: "4.2.5",
        title: "Simple Café Flow",
        purpose: "Bring the full café sequence together — almost entirely recycled language, just the flow is new.",
        supportLevel: "low",
        newLanguageLoad: "very_low",
        notes: {
          pattern: "A real café interaction is just a sequence of already-known steps: greet, order, for here / to go, customise, pay, close.",
        },
        blocks: [
          {
            id: "s4m2l5_b1",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Čia ar išsinešti?", audioText: "Čia ar išsinešti" },
            options: [
              { id: "a", text: "With milk or without?", isCorrect: false },
              { id: "b", text: "For here or to go?", isCorrect: true },
              { id: "c", text: "Cash or card?", isCorrect: false },
            ],
          },
          {
            id: "s4m2l5_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Grynaisiais ar kortele?", audioText: "Grynaisiais ar kortele" },
            options: [
              { id: "a", text: "For here or to go?", isCorrect: false },
              { id: "b", text: "Coffee or tea?", isCorrect: false },
              { id: "c", text: "Cash or card?", isCorrect: true },
            ],
          },
          {
            id: "s4m2l5_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Staff asks: Su pienu ar be pieno? You want it with milk." },
            options: [
              { id: "a", text: "Be cukraus, prašau.", isCorrect: false },
              { id: "b", text: "Su pienu, prašau.", isCorrect: true },
              { id: "c", text: "Išsinešti, prašau.", isCorrect: false },
            ],
            feedback: { correct: "Su pienu, prašau — With milk, please." },
          },
          {
            id: "s4m2l5_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask for the bill",
            targetText: "Sąskaitą, prašau",
            audioText: "Sąskaitą, prašau",
          },
          {
            id: "s4m2l5_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "A complete café visit from greeting to goodbye.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ko norėtumėte?",
                audioText: "Laba diena! Ko norėtumėte",
                helperText: "Good day! What would you like?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Laba diena! Norėčiau kavos.", en: "Good day! I would like coffee.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Čia ar išsinešti?",
                audioText: "Čia ar išsinešti",
                helperText: "For here or to go?",
                options: [
                  { id: "a", text: "Su pienu, prašau.", isCorrect: false },
                  { id: "b", text: "Čia, prašau.", en: "For here, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Su pienu ar be pieno?",
                audioText: "Su pienu ar be pieno",
                helperText: "With milk or without milk?",
                options: [
                  { id: "a", text: "Čia, prašau.", isCorrect: false },
                  { id: "b", text: "Be pieno, prašau.", en: "Without milk, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom.",
                audioText: "Prašom",
                helperText: "Here you go.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū! Sąskaitą, prašau.", en: "Thank you! The bill, please.", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
              {
                id: "step_5",
                actor: "other",
                text: "Grynaisiais ar kortele?",
                audioText: "Grynaisiais ar kortele",
                helperText: "Cash or card?",
                options: [
                  { id: "a", text: "Sąskaitą, prašau.", isCorrect: false },
                  { id: "b", text: "Kortele, prašau.", en: "By card, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_6",
                actor: "other",
                text: "Ačiū! Viso gero!",
                audioText: "Ačiū! Viso gero",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Ačiū! Viso gero!", en: "Thank you! Goodbye!", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Module 4.2 Checkpoint ─────────────────────────────────────────────────
      {
        id: "section_4_module_2_checkpoint",
        code: "4.2.C",
        title: "At the Café",
        purpose: "Check you can handle a full café interaction without support.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s4m2c_b1",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You want to order a tea. What do you say?" },
            options: [
              { id: "a", text: "Arbata, prašau!", isCorrect: false },
              { id: "b", text: "Norėčiau arbatos.", isCorrect: true },
              { id: "c", text: "Noriu.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau arbatos — I would like tea. The polite, natural ordering frame." },
          },
          {
            id: "s4m2c_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Čia ar išsinešti?", audioText: "Čia ar išsinešti" },
            options: [
              { id: "a", text: "Cash or card?", isCorrect: false },
              { id: "b", text: "For here or to go?", isCorrect: true },
              { id: "c", text: "With milk or without?", isCorrect: false },
            ],
          },
          {
            id: "s4m2c_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Staff asks: Su pienu ar be pieno? You don't want milk." },
            options: [
              { id: "a", text: "Su pienu, prašau.", isCorrect: false },
              { id: "b", text: "Be pieno, prašau.", isCorrect: true },
              { id: "c", text: "Išsinešti, prašau.", isCorrect: false },
            ],
            feedback: { correct: "Be pieno, prašau — Without milk, please. Be… is the without chunk." },
          },
          {
            id: "s4m2c_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Coffee with milk, please." },
            tokens: [
              { id: "t1", text: "Kavos", correctIndex: 0 },
              { id: "t2", text: "su", correctIndex: 1 },
              { id: "t3", text: "pienu,", correctIndex: 2 },
              { id: "t4", text: "prašau", correctIndex: 3 },
              { id: "t5", text: "be", isDistractor: true },
              { id: "t6", text: "cukraus,", isDistractor: true },
            ],
            answerText: "Kavos su pienu, prašau",
          },
          {
            id: "s4m2c_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask for the bill",
            targetText: "Sąskaitą, prašau",
            audioText: "Sąskaitą, prašau",
          },
          {
            id: "s4m2c_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "A complete café visit — order, customise, pay, and close.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ko norėtumėte?",
                audioText: "Laba diena! Ko norėtumėte",
                helperText: "Good day! What would you like?",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Laba diena! Norėčiau arbatos, prašau.", en: "Good day! I would like tea, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Čia ar išsinešti?",
                audioText: "Čia ar išsinešti",
                helperText: "For here or to go?",
                options: [
                  { id: "a", text: "Su citrina, prašau.", isCorrect: false },
                  { id: "b", text: "Išsinešti, prašau.", en: "To go, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Su citrina ar be?",
                audioText: "Su citrina ar be",
                helperText: "With lemon or without?",
                options: [
                  { id: "a", text: "Išsinešti.", isCorrect: false },
                  { id: "b", text: "Su citrina, prašau.", en: "With lemon, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom. Grynaisiais ar kortele?",
                audioText: "Prašom. Grynaisiais ar kortele",
                helperText: "Here you go. Cash or card?",
                options: [
                  { id: "a", text: "Sąskaitą, prašau.", isCorrect: false },
                  { id: "b", text: "Grynaisiais, prašau.", en: "Cash, please.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_5",
                actor: "other",
                text: "Ačiū! Viso gero!",
                audioText: "Ačiū! Viso gero",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū! Viso gero!", en: "Thank you! Goodbye!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
          {
            id: "s4m2c_b7",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "kava",                    en: "coffee",                     audioText: "kava" },
              { id: "m2",  lt: "arbata",                  en: "tea",                        audioText: "arbata" },
              { id: "m3",  lt: "vanduo",                  en: "water",                      audioText: "vanduo" },
              { id: "m4",  lt: "sultys",                  en: "juice",                      audioText: "sultys" },
              { id: "m5",  lt: "Norėčiau kavos.",         en: "I would like coffee.",       audioText: "Norėčiau kavos" },
              { id: "m6",  lt: "Vandens, prašau.",        en: "Water, please.",             audioText: "Vandens, prašau" },
              { id: "m7",  lt: "Čia ar išsinešti?",       en: "For here or to go?",         audioText: "Čia ar išsinešti" },
              { id: "m8",  lt: "Čia, prašau.",            en: "For here, please.",          audioText: "Čia, prašau" },
              { id: "m9",  lt: "Išsinešti, prašau.",      en: "To go, please.",             audioText: "Išsinešti, prašau" },
              { id: "m10", lt: "su pienu",                en: "with milk",                  audioText: "su pienu" },
              { id: "m11", lt: "be cukraus",              en: "without sugar",              audioText: "be cukraus" },
              { id: "m12", lt: "su citrina",              en: "with lemon",                 audioText: "su citrina" },
              { id: "m13", lt: "pienas",                  en: "milk",                       audioText: "pienas" },
              { id: "m14", lt: "cukrus",                  en: "sugar",                      audioText: "cukrus" },
              { id: "m15", lt: "citrina",                 en: "lemon",                      audioText: "citrina" },
              { id: "m16", lt: "Sąskaitą, prašau.",       en: "The bill, please.",          audioText: "Sąskaitą, prašau" },
              { id: "m17", lt: "Galima mokėti kortele?",  en: "Can I pay by card?",         audioText: "Galima mokėti kortele" },
              { id: "m18", lt: "Grynaisiais ar kortele?", en: "Cash or card?",              audioText: "Grynaisiais ar kortele" },
              { id: "m19", lt: "Su pienu ar be pieno?",   en: "With milk or without milk?", audioText: "Su pienu ar be pieno" },
              { id: "m20", lt: "Norėčiau užsisakyti.",    en: "I would like to order.",     audioText: "Norėčiau užsisakyti" },
            ],
          },
        ],
      },
    ],
  };
}
