// src/content/learning/section4/module_4_1.js
// Module 4.1 — Ordering Basics

export default function createModule_4_1(profile = {}) {
  const { userNameSafe = "Davidas" } = profile;

  return {
    id: "module_4_1",
    code: "4.1",
    title: "Ordering Basics",
    status: "active",
    lessonCount: 4,
    lessons: [

      // ── Lesson 1 — I Want… ───────────────────────────────────────────────────
      {
        id: "section_4_module_1_lesson_1",
        code: "4.1.1",
        title: "I Want…",
        purpose: "Bring already-known want-frames into food and drink use immediately.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Noriu + genitive — the same frame you've used since Section 2. In food and drink contexts it becomes instantly useful.",
          usage: [
            "Noriu kavos — I want coffee",
            "Noriu arbatos — I want tea",
            "Noriu vandens — I want water",
            "Noriu šito — I want this",
          ],
        },
        blocks: [
          {
            id: "s4m1l1_b1",
            type: "learn",
            title: "Ordering with Noriu",
            items: [
              { id: "ow1", lt: "Noriu kavos.", en: "I want coffee.", audioText: "Noriu kavos", saveable: true, core: true },
              { id: "ow2", lt: "Noriu arbatos.", en: "I want tea.", audioText: "Noriu arbatos", saveable: true, core: true },
              { id: "ow3", lt: "Noriu vandens.", en: "I want water.", audioText: "Noriu vandens", saveable: true, core: true },
              { id: "ow4", lt: "Noriu sriubos.", en: "I want soup.", audioText: "Noriu sriubos", saveable: true, core: true },
              { id: "ow5", lt: "Noriu šito.", en: "I want this.", audioText: "Noriu šito", saveable: true, core: true },
              { id: "ow6", lt: "Noriu to.", en: "I want that.", audioText: "Noriu to", saveable: true, core: true },
              { id: "noun_tortas", lt: "tortas", en: "cake", audioText: "tortas", saveable: true, core: false },
              { id: "noun_ledai", lt: "ledai", en: "ice cream", audioText: "ledai", saveable: true, core: false },
            ],
          },
          {
            id: "s4m1l1_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Noriu kavos.", audioText: "Noriu kavos" },
            options: [
              { id: "a", text: "I want tea.", isCorrect: false },
              { id: "b", text: "I want coffee.", isCorrect: true },
              { id: "c", text: "I want water.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l1_b3",
            type: "recognise_mcq",
            noOptionAudio: true,
            title: "Choose the correct meaning",
            prompt: { text: "Noriu arbatos.", audioText: "Noriu arbatos" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I want soup.", isCorrect: false },
              { id: "c", text: "I want tea.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l1_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I want coffee",
            targetText: "Noriu kavos",
            audioText: "Noriu kavos",
          },
          {
            id: "s4m1l1_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "You stop at a counter. The staff asks what you want.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Ko norite?",
                audioText: "Ko norite",
                helperText: "What do you want?",
                options: [
                  { id: "a", text: "Viso gero.", isCorrect: false },
                  { id: "b", text: "Noriu kavos.", en: "I want coffee.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Prašom.",
                audioText: "Prašom",
                helperText: "Here you go.",
                options: [
                  { id: "a", text: "Ne, ačiū.", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 2 — I Would Like… ─────────────────────────────────────────────
      {
        id: "section_4_module_1_lesson_2",
        code: "4.1.2",
        title: "I Would Like…",
        purpose: "Upgrade to the polite ordering frame — the natural default in cafés and restaurants.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Norėčiau… is more polite than Noriu… and sounds better in public service situations. You saw it once in Lesson 1.1 — now it becomes your default when ordering.",
          usage: [
            "Norėčiau kavos — I would like coffee",
            "Norėčiau arbatos — I would like tea",
            "Norėčiau šito — I would like this",
            "Norėčiau užsisakyti — I would like to order",
          ],
        },
        blocks: [
          {
            id: "s4m1l2_b1",
            type: "learn",
            title: "Polite ordering with Norėčiau",
            items: [
              { id: "po1", lt: "Norėčiau kavos.", en: "I would like coffee.", audioText: "Norėčiau kavos", saveable: true, core: true },
              { id: "po2", lt: "Norėčiau arbatos.", en: "I would like tea.", audioText: "Norėčiau arbatos", saveable: true, core: true },
              { id: "po3", lt: "Norėčiau vandens.", en: "I would like water.", audioText: "Norėčiau vandens", saveable: true, core: true },
              { id: "po4", lt: "Norėčiau šito.", en: "I would like this.", audioText: "Norėčiau šito", saveable: true, core: true },
              { id: "po5", lt: "Norėčiau užsisakyti.", en: "I would like to order.", audioText: "Norėčiau užsisakyti", saveable: true, core: true },
              { id: "po6", lt: "Ko norėtumėte?", en: "What would you like?", audioText: "Ko norėtumėte", saveable: false, core: false },
            ],
          },
          {
            id: "s4m1l2_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Norėčiau kavos.", audioText: "Norėčiau kavos" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I would like coffee.", isCorrect: true },
              { id: "c", text: "I would like tea.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l2_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're ordering at a café. A member of staff is waiting. What sounds most natural?" },
            options: [
              { id: "a", text: "Noriu kavos.", isCorrect: false },
              { id: "b", text: "Norėčiau kavos.", isCorrect: true },
              { id: "c", text: "Kavos.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau kavos — I would like coffee. Polite and natural in any café or restaurant setting." },
          },
          {
            id: "s4m1l2_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Order politely: I would like tea",
            targetText: "Norėčiau arbatos",
            audioText: "Norėčiau arbatos",
          },
          {
            id: "s4m1l2_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "You walk into a café in Vilnius and order your drink.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ko norėtumėte?",
                audioText: "Laba diena! Ko norėtumėte",
                helperText: "Good day! What would you like? — a slightly more formal service phrasing.",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Laba diena! Norėčiau kavos.", en: "Good day! I would like coffee.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Žinoma. Moment.",
                audioText: "Žinoma. Moment",
                helperText: "Of course. One moment.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū.", en: "Thank you.", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom.",
                audioText: "Prašom",
                helperText: "Here you go.",
                options: [
                  { id: "a", text: "Atsiprašau.", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Ko norite?", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 3 — This / That, Please ───────────────────────────────────────
      {
        id: "section_4_module_1_lesson_3",
        code: "4.1.3",
        title: "This / That, Please",
        purpose: "Apply demonstratives directly to ordering — pointing and choosing at a counter or menu.",
        supportLevel: "high",
        newLanguageLoad: "low_to_medium",
        notes: {
          pattern: "Šito/To work after Noriu/Norėčiau (genitive). Šitą/Tą work as a standalone 'give me this one' (accusative). For ordering at a counter, both patterns work naturally — use whichever comes to mind.",
          usage: [
            "Šito, prašau — This one, please",
            "To, prašau — That one, please",
            "Norėčiau šito — I would like this one",
          ],
        },
        blocks: [
          {
            id: "s4m1l3_b1",
            type: "learn",
            title: "Pointing to order",
            items: [
              { id: "pt1", lt: "Šito, prašau.", en: "This one, please.", audioText: "Šito, prašau", saveable: true, core: true },
              { id: "pt2", lt: "To, prašau.", en: "That one, please.", audioText: "To, prašau", saveable: true, core: true },
              { id: "pt3", lt: "Šitą, prašau.", en: "This, please.", audioText: "Šitą, prašau", saveable: true, core: true },
              { id: "pt4", lt: "Tą, prašau.", en: "That, please.", audioText: "Tą, prašau", saveable: true, core: true },
              { id: "pt5", lt: "Kurio norite?", en: "Which one do you want?", audioText: "Kurio norite", saveable: false, core: false },
            ],
          },
          {
            id: "s4m1l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Šito, prašau.", audioText: "Šito, prašau" },
            options: [
              { id: "a", text: "That one, please.", isCorrect: false },
              { id: "b", text: "Which one?", isCorrect: false },
              { id: "c", text: "This one, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l3_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "To, prašau.", audioText: "To, prašau" },
            options: [
              { id: "a", text: "This one, please.", isCorrect: false },
              { id: "b", text: "One more, please.", isCorrect: false },
              { id: "c", text: "That one, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l3_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Point and say: This one, please",
            targetText: "Šito, prašau",
            audioText: "Šito, prašau",
          },
          {
            id: "s4m1l3_b5",
            type: "scenario_chain",
            title: "Conversation",
            description: "You're at a bakery counter. The staff asks which item you want.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Kurio norite?",
                audioText: "Kurio norite",
                helperText: "Which one would you like?",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Šito, prašau.", en: "This one, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Ar dar ko norite?",
                audioText: "Ar dar ko norite",
                helperText: "Do you want anything else?",
                options: [
                  { id: "a", text: "Taip, labai.", isCorrect: false },
                  { id: "b", text: "Norėčiau to, prašau.", en: "I would like that one, please.", isCorrect: true },
                  { id: "c", text: "Man reikia pagalbos.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom.",
                audioText: "Prašom",
                helperText: "Here you go.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 4 — One / Two / More ──────────────────────────────────────────
      {
        id: "section_4_module_1_lesson_4",
        code: "4.1.4",
        title: "One / Two / More",
        purpose: "Bring quantity into ordering — the small numbers that come up in every food and drink situation.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "When you order, the drink word changes its ending. Kava becomes kavą (Vieną kavą), arbata becomes arbatas (Dvi arbatas), vanduo becomes vandenį (Vieną vandenį). Lithuanian shows the role a word plays in a sentence through these endings rather than word order — a system called cases. You don't need to learn the rules yet. Just notice it happening. The more you hear it, the more natural it will feel.",
          usage: [
            "vieną kavą — one coffee (kavą, not kava)",
            "dvi arbatas — two teas (arbatas, not arbata)",
            "vieną vandenį — one water (vandenį, not vanduo)",
            "Dar vieną, prašau — one more, please (no noun needed here)",
          ],
        },
        blocks: [
          {
            id: "s4m1l4_b1",
            type: "learn",
            title: "Ordering with quantity",
            items: [
              { id: "oq1", lt: "Vieną kavą, prašau.", en: "One coffee, please.", audioText: "Vieną kavą, prašau", saveable: true, core: true },
              { id: "oq2", lt: "Dvi arbatas, prašau.", en: "Two teas, please.", audioText: "Dvi arbatas, prašau", saveable: true, core: true },
              { id: "oq3", lt: "Vieną vandenį, prašau.", en: "One water, please.", audioText: "Vieną vandenį, prašau", saveable: true, core: true },
              { id: "oq4", lt: "Dar vieną, prašau.", en: "One more, please.", audioText: "Dar vieną, prašau", saveable: true, core: true },
              { id: "oq5", lt: "Kiek?", en: "How many?", audioText: "Kiek", saveable: false, core: false },
            ],
          },
          {
            id: "s4m1l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Vieną kavą, prašau.", audioText: "Vieną kavą, prašau" },
            options: [
              { id: "a", text: "Two coffees, please.", isCorrect: false },
              { id: "b", text: "One coffee, please.", isCorrect: true },
              { id: "c", text: "One tea, please.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l4_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Dvi arbatas, prašau.", audioText: "Dvi arbatas, prašau" },
            options: [
              { id: "a", text: "Two coffees, please.", isCorrect: false },
              { id: "b", text: "One tea, please.", isCorrect: false },
              { id: "c", text: "Two teas, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l4_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "One coffee, please." },
            tokens: [
              { id: "t1", text: "Vieną", correctIndex: 0 },
              { id: "t2", text: "kavą,", correctIndex: 1 },
              { id: "t3", text: "prašau", correctIndex: 2 },
              { id: "t4", text: "Dvi", isDistractor: true },
              { id: "t5", text: "arbatas,", isDistractor: true },
            ],
            answerText: "Vieną kavą, prašau",
          },
          {
            id: "s4m1l4_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Order: two teas, please",
            targetText: "Dvi arbatas, prašau",
            audioText: "Dvi arbatas, prašau",
          },
          {
            id: "s4m1l4_b6",
            type: "scenario_chain",
            title: "Conversation",
            description: "You're at a café with a colleague. You order for both of you.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Ko norėtumėte?",
                audioText: "Ko norėtumėte",
                helperText: "What would you like?",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Dvi arbatas, prašau.", en: "Two teas, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Ar dar ko norite?",
                audioText: "Ar dar ko norite",
                helperText: "Anything else?",
                options: [
                  { id: "a", text: "Ne, ačiū.", isCorrect: false },
                  { id: "b", text: "Taip! Vieną kavą, prašau.", en: "Yes! One coffee, please.", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Gerai. Prašom.",
                audioText: "Gerai. Prašom",
                helperText: "OK. Here you go.",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Ačiū labai!", en: "Thank you very much!", isCorrect: true },
                  { id: "c", text: "Dar vieną, prašau.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Prašom. Dar vieną?",
                audioText: "Prašom. Dar vieną",
                helperText: "Here you are. One more?",
                options: [
                  { id: "a", text: "Taip, labai.", isCorrect: false },
                  { id: "b", text: "Ne, ačiū. Pakanka.", en: "No, thank you. That's enough.", isCorrect: true },
                  { id: "c", text: "Ko norite?", isCorrect: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Module 4.1 Checkpoint ─────────────────────────────────────────────────
      {
        id: "section_4_module_1_checkpoint",
        code: "4.1.C",
        title: "Ordering Basics",
        purpose: "Check you can use core ordering frames, demonstratives, and quantity without support.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s4m1c_b1",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're ordering at a café counter. Staff are waiting. Which sounds most natural?" },
            options: [
              { id: "a", text: "Kava, prašau!", isCorrect: false },
              { id: "b", text: "Norėčiau kavos.", isCorrect: true },
              { id: "c", text: "Noriu.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau kavos — the polite, natural default when ordering in a café or restaurant." },
          },
          {
            id: "s4m1c_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Norėčiau arbatos.", audioText: "Norėčiau arbatos" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I would like water.", isCorrect: false },
              { id: "c", text: "I would like tea.", isCorrect: true },
            ],
          },
          {
            id: "s4m1c_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Dvi arbatas, prašau.", audioText: "Dvi arbatas, prašau" },
            options: [
              { id: "a", text: "Two coffees, please.", isCorrect: false },
              { id: "b", text: "Two teas, please.", isCorrect: true },
              { id: "c", text: "One tea, please.", isCorrect: false },
            ],
          },
          {
            id: "s4m1c_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Šito, prašau.", audioText: "Šito, prašau" },
            options: [
              { id: "a", text: "That one, please.", isCorrect: false },
              { id: "b", text: "One more, please.", isCorrect: false },
              { id: "c", text: "This one, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1c_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Staff asks: Ko norėtumėte? You want tea." },
            options: [
              { id: "a", text: "Arbata.", isCorrect: false },
              { id: "b", text: "Norėčiau arbatos.", isCorrect: true },
              { id: "c", text: "Noriu kavos.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau arbatos — polite, with the correct genitive ending. The go-to ordering frame." },
          },
          {
            id: "s4m1c_b6",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Two teas, please." },
            tokens: [
              { id: "t1", text: "Dvi", correctIndex: 0 },
              { id: "t2", text: "arbatas,", correctIndex: 1 },
              { id: "t3", text: "prašau", correctIndex: 2 },
              { id: "t4", text: "Vieną", isDistractor: true },
              { id: "t5", text: "kavą,", isDistractor: true },
            ],
            answerText: "Dvi arbatas, prašau",
          },
          {
            id: "s4m1c_b7",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Order politely: I would like water",
            targetText: "Norėčiau vandens",
            audioText: "Norėčiau vandens",
          },
          {
            id: "s4m1c_b8",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask for one more",
            targetText: "Dar vieną, prašau",
            audioText: "Dar vieną, prašau",
          },
          {
            id: "s4m1c_b9",
            type: "scenario_chain",
            title: "Conversation",
            description: "You stop at a café kiosk with a colleague. Order for both of you and close naturally.",
            steps: [
              {
                id: "step_1",
                actor: "other",
                text: "Laba diena! Ko norėtumėte?",
                audioText: "Laba diena! Ko norėtumėte",
                helperText: "Good day! What would you like?",
                options: [
                  { id: "a", text: "Nesuprantu.", isCorrect: false },
                  { id: "b", text: "Laba diena! Vieną kavą ir vieną arbatą, prašau.", en: "Good day! One coffee and one tea, please.", isCorrect: true },
                  { id: "c", text: "Viso gero.", isCorrect: false },
                ],
              },
              {
                id: "step_2",
                actor: "other",
                text: "Gerai. Šito ar to?",
                audioText: "Gerai. Šito ar to",
                helperText: "OK. This one or that one? — pointing to two different coffees.",
                options: [
                  { id: "a", text: "Nesuprantu. Prašau kalbėkite lėčiau.", isCorrect: false },
                  { id: "b", text: "To, prašau.", en: "That one, please.", isCorrect: true },
                  { id: "c", text: "Ko norite?", isCorrect: false },
                ],
              },
              {
                id: "step_3",
                actor: "other",
                text: "Prašom.",
                audioText: "Prašom",
                helperText: "Here you go.",
                options: [
                  { id: "a", text: "Prašom.", isCorrect: false },
                  { id: "b", text: "Ačiū!", en: "Thank you!", isCorrect: true },
                  { id: "c", text: "Atsiprašau.", isCorrect: false },
                ],
              },
              {
                id: "step_4",
                actor: "other",
                text: "Ar dar ko norite?",
                audioText: "Ar dar ko norite",
                helperText: "Would you like anything else?",
                options: [
                  { id: "a", text: "Taip, labai.", isCorrect: false },
                  { id: "b", text: "Ne, ačiū. Pakanka.", en: "No, thank you. That's enough.", isCorrect: true },
                  { id: "c", text: "Dar vieną, prašau.", isCorrect: false },
                ],
              },
              {
                id: "step_5",
                actor: "other",
                text: "Gerai. Viso gero!",
                audioText: "Gerai. Viso gero",
                options: [
                  { id: "a", text: "Ko norite?", isCorrect: false },
                  { id: "b", text: "Viso gero! Ačiū!", en: "Goodbye! Thank you!", isCorrect: true },
                  { id: "c", text: "Nesuprantu.", isCorrect: false },
                ],
              },
            ],
          },
          {
            id: "s4m1c_b10",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Noriu kavos.",          en: "I want coffee.",           audioText: "Noriu kavos" },
              { id: "m2",  lt: "Noriu arbatos.",         en: "I want tea.",              audioText: "Noriu arbatos" },
              { id: "m3",  lt: "Noriu vandens.",         en: "I want water.",            audioText: "Noriu vandens" },
              { id: "m4",  lt: "Noriu šito.",            en: "I want this.",             audioText: "Noriu šito" },
              { id: "m5",  lt: "Norėčiau kavos.",        en: "I would like coffee.",     audioText: "Norėčiau kavos" },
              { id: "m6",  lt: "Norėčiau arbatos.",      en: "I would like tea.",        audioText: "Norėčiau arbatos" },
              { id: "m7",  lt: "Norėčiau šito.",         en: "I would like this.",       audioText: "Norėčiau šito" },
              { id: "m8",  lt: "Norėčiau užsisakyti.",   en: "I would like to order.",   audioText: "Norėčiau užsisakyti" },
              { id: "m9",  lt: "Šito, prašau.",          en: "This one, please.",        audioText: "Šito, prašau" },
              { id: "m10", lt: "To, prašau.",            en: "That one, please.",        audioText: "To, prašau" },
              { id: "m11", lt: "Šitą, prašau.",          en: "This, please.",            audioText: "Šitą, prašau" },
              { id: "m12", lt: "Tą, prašau.",            en: "That, please.",            audioText: "Tą, prašau" },
              { id: "m13", lt: "Vieną kavą, prašau.",    en: "One coffee, please.",      audioText: "Vieną kavą, prašau" },
              { id: "m14", lt: "Dvi arbatas, prašau.",   en: "Two teas, please.",        audioText: "Dvi arbatas, prašau" },
              { id: "m15", lt: "Vieną vandenį, prašau.", en: "One water, please.",       audioText: "Vieną vandenį, prašau" },
              { id: "m16", lt: "Dar vieną, prašau.",     en: "One more, please.",        audioText: "Dar vieną, prašau" },
              { id: "m17", lt: "Ko norite?",             en: "What do you want?",        audioText: "Ko norite" },
              { id: "m18", lt: "Ko norėtumėte?",         en: "What would you like?",     audioText: "Ko norėtumėte" },
              { id: "m19", lt: "tortas",                 en: "cake",                     audioText: "tortas" },
              { id: "m20", lt: "ledai",                  en: "ice cream",                audioText: "ledai" },
            ],
          },
        ],
      },
    ],
  };
}
