// src/content/learning/section4/module_4_1.js
// Module 4.1 — Ordering Basics

export default function createModule_4_1(profile = {}) {
  const { userNameSafe = "Davidas" } = profile;

  return {
    id: "module_4_1",
    code: "4.1",
    title: "Ordering Basics",
    status: "active",
    lessonCount: 4,
    lessons: [

      // ── Lesson 1 — I Want… ───────────────────────────────────────────────────
      {
        id: "section_4_module_1_lesson_1",
        code: "4.1.1",
        title: "I Want…",
        purpose: "Reuse the familiar Noriu frame while adding food vocabulary inside a fuller café exchange.",
        supportLevel: "high",
        newLanguageLoad: "medium",
        notes: {
          pattern: "You already know Noriu… from Section 2. This lesson uses that familiar frame to add food: sriuba becomes sriubos, tortas becomes torto, and ledai becomes ledų after Noriu. Learn the useful chunks rather than memorising a grammar label.",
          usage: [
            "Noriu kavos — I want coffee (already known)",
            "Noriu vandens — I want water (already known)",
            "Noriu sriubos — I want soup",
            "Noriu torto — I want cake",
            "Noriu ledų — I want ice cream",
          ],
        },
        blocks: [
          {
            id: "s4m1l1_b1",
            type: "learn",
            title: "New food with a familiar pattern",
            items: [
              { id: "ow4", lt: "Noriu sriubos.", en: "I want soup.", audioText: "Noriu sriubos", saveable: true, core: true },
              { id: "ow5", lt: "Noriu torto.", en: "I want cake.", audioText: "Noriu torto", saveable: true, core: true },
              { id: "ow6", lt: "Noriu ledų.", en: "I want ice cream.", audioText: "Noriu ledų", saveable: true, core: true },
            ],
          },
          {
            id: "s4m1l1_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Noriu sriubos.", audioText: "Noriu sriubos" },
            options: [
              { id: "a", text: "I want cake.", isCorrect: false },
              { id: "b", text: "I want soup.", isCorrect: true },
              { id: "c", text: "I want ice cream.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l1_b3",
            type: "recognise_mcq",
            noOptionAudio: true,
            title: "Choose the correct meaning",
            prompt: { text: "Noriu torto.", audioText: "Noriu torto" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I want cake.", isCorrect: true },
              { id: "c", text: "I want soup.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l1_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Say: I want ice cream",
            targetText: "Noriu ledų",
            audioText: "Noriu ledų",
          },
          {
            id: "s4m1l1_b5_v2",
            type: "scenario_v2",
            title: "Café order",
            description: "You stop at a café counter. Choose something to eat, add water, check the price, pay by card, and close the exchange.",
            sceneIntro: "You stop at a café counter. Choose something to eat, add water, check the price, pay by card, and close the exchange.",
            location: "café counter",
            userRole: "customer",
            register: "polite_service",
            goal: "Use the new food vocabulary while reusing language from earlier sections in one complete café exchange.",
            focus: ["Noriu sriubos", "Noriu torto", "Noriu ledų", "price", "payment"],
            participants: [
              {
                id: "staff",
                label: "Staff",
                name: "Ieva",
                role: "server",
                gender: "female",
                relationshipToUser: "stranger",
                register: "polite_service",
              },
            ],
            steps: [
              {
                id: "step_1_order",
                speakerId: "staff",
                speakerLabel: "Staff",
                speakerText: "Laba diena! Ko norėtumėte?",
                sceneDirection: "Soup, cake and ice cream are all available. Choose one.",
                learnerPrompt: "Greet Ieva and choose something to eat.",
                options: [
                  { id: "a", text: "Laba diena! Noriu sriubos, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Laba diena! Noriu torto, prašau.", result: "best", progresses: true },
                  { id: "c", text: "Laba diena! Noriu ledų, prašau.", result: "best", progresses: true },
                  { id: "d", text: "Viso gero.", result: "wrong", feedback: "That ends the conversation instead of ordering.", progresses: false },
                ],
              },
              {
                id: "step_2_water",
                speakerId: "staff",
                speakerLabel: "Staff",
                speakerText: "Žinoma. Ar dar ko nors?",
                sceneDirection: "You also want water.",
                learnerPrompt: "Add water to your order.",
                options: [
                  { id: "a", text: "Taip, noriu vandens, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Ne, ačiū.", result: "wrong", feedback: "The scene says you also want water.", progresses: false },
                  { id: "c", text: "Daugiau vandens, prašau.", result: "wrong", feedback: "Daugiau means more; you have not been given water yet.", progresses: false },
                ],
              },
              {
                id: "step_3_price",
                speakerId: "staff",
                speakerLabel: "Staff",
                speakerText: "Gerai.",
                sceneDirection: "Before paying, you want to know the total price.",
                learnerPrompt: "Ask how much it costs.",
                options: [
                  { id: "a", text: "Kiek tai kainuoja?", result: "best", progresses: true },
                  { id: "b", text: "Kiek bilietų?", result: "wrong", feedback: "You are paying for food, not asking how many tickets.", progresses: false },
                  { id: "c", text: "Užtenka.", result: "wrong", feedback: "You need to ask for the price before paying.", progresses: false },
                ],
              },
              {
                id: "step_4_payment",
                speakerId: "staff",
                speakerLabel: "Staff",
                speakerText: "Dešimt eurų.",
                sceneDirection: "You want to pay by card.",
                learnerPrompt: "Ask whether you can pay by card.",
                options: [
                  { id: "a", text: "Ar galima mokėti kortele?", result: "best", progresses: true },
                  { id: "b", text: "Grynaisiais, prašau.", result: "wrong", feedback: "The scene says you want to pay by card.", progresses: false },
                  { id: "c", text: "Per brangu.", result: "wrong", feedback: "You decided to buy the order; ask about card payment.", progresses: false },
                ],
              },
              {
                id: "step_5_close",
                speakerId: "staff",
                speakerLabel: "Staff",
                speakerText: "Taip, galima. Prašom.",
                sceneDirection: "Your payment is complete and Ieva hands over the order.",
                learnerPrompt: "Thank Ieva and say goodbye.",
                options: [
                  { id: "a", text: "Ačiū labai! Viso gero.", result: "best", progresses: true },
                  { id: "b", text: "Atsiprašau.", result: "wrong", feedback: "Nothing needs an apology; the transaction is complete.", progresses: false },
                  { id: "c", text: "Dar vieną, prašau.", result: "wrong", feedback: "The scene says you are finished and ready to leave.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 2 — I Would Like… ─────────────────────────────────────────────
      {
        id: "section_4_module_1_lesson_2",
        code: "4.1.2",
        title: "I Would Like…",
        purpose: "Upgrade to the polite ordering frame — the natural default in cafés and restaurants.",
        supportLevel: "high",
        newLanguageLoad: "low",
        notes: {
          pattern: "Norėčiau… is more polite than Noriu… and sounds better in public service situations. You saw it once in Lesson 1.1 — now it becomes your default when ordering.",
          usage: [
            "Norėčiau kavos — I would like coffee",
            "Norėčiau arbatos — I would like tea",
            "Norėčiau šito — I would like this",
            "Norėčiau užsisakyti — I would like to order",
          ],
        },
        blocks: [
          {
            id: "s4m1l2_b1",
            type: "learn",
            title: "Polite ordering with Norėčiau",
            items: [
              { id: "po1", lt: "Norėčiau kavos.", en: "I would like coffee.", audioText: "Norėčiau kavos", saveable: true, core: true },
              { id: "po2", lt: "Norėčiau arbatos.", en: "I would like tea.", audioText: "Norėčiau arbatos", saveable: true, core: true },
              { id: "po3", lt: "Norėčiau vandens.", en: "I would like water.", audioText: "Norėčiau vandens", saveable: true, core: true },
              { id: "po4", lt: "Norėčiau šito.", en: "I would like this.", audioText: "Norėčiau šito", saveable: true, core: true },
              { id: "po5", lt: "Norėčiau užsisakyti.", en: "I would like to order.", audioText: "Norėčiau užsisakyti", saveable: true, core: true },
            ],
          },
          {
            id: "s4m1l2_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Norėčiau kavos.", audioText: "Norėčiau kavos" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I would like coffee.", isCorrect: true },
              { id: "c", text: "I would like tea.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l2_b3",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're ordering at a café. A member of staff is waiting. What sounds most natural?" },
            options: [
              { id: "a", text: "Noriu kavos.", isCorrect: false },
              { id: "b", text: "Norėčiau kavos.", isCorrect: true },
              { id: "c", text: "Kavos.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau kavos — I would like coffee. Polite and natural in any café or restaurant setting." },
          },
          {
            id: "s4m1l2_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Order politely: I would like tea",
            targetText: "Norėčiau arbatos",
            audioText: "Norėčiau arbatos",
          },
          {
            id: "s4m1l2_b5_v2",
            type: "scenario_v2",
            title: "Polite café order",
            description: "You order coffee and water politely, check the price, pay by card, and close the exchange.",
            sceneIntro: "You order coffee and water politely, check the price, pay by card, and close the exchange.",
            location: "café",
            userRole: "customer",
            register: "polite_service",
            goal: "Use Norėčiau as the new polite ordering frame while reusing earlier café language.",
            focus: ["Norėčiau", "price", "payment"],
            participants: [{ id: "server", label: "Server", name: "Ieva", role: "server", gender: "female", relationshipToUser: "stranger", register: "polite_service" }],
            steps: [
              {
                id: "step_1",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Laba diena! Ko norėtumėte?",
                sceneDirection: "You want coffee.",
                learnerPrompt: "Greet Ieva and order coffee politely.",
                options: [
                  { id: "a", text: "Laba diena! Norėčiau kavos, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Laba diena! Noriu kavos.", result: "awkward", feedback: "Understandable, but Norėčiau is the more natural polite service form you are practising.", betterAnswer: "Laba diena! Norėčiau kavos, prašau.", progresses: true },
                  { id: "c", text: "Viso gero.", result: "wrong", feedback: "That ends the conversation instead of ordering.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Žinoma. Ar dar ko nors?",
                sceneDirection: "You also want water.",
                learnerPrompt: "Add water politely.",
                options: [
                  { id: "a", text: "Norėčiau vandens, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Ne, ačiū.", result: "wrong", feedback: "The scene says you also want water.", progresses: false },
                  { id: "c", text: "Viso gero.", result: "wrong", feedback: "You are still ordering.", progresses: false },
                ],
              },
              {
                id: "step_3",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Gerai.",
                sceneDirection: "Before paying, you want to know the total.",
                learnerPrompt: "Ask how much it costs.",
                options: [
                  { id: "a", text: "Kiek tai kainuoja?", result: "best", progresses: true },
                  { id: "b", text: "Kur yra tualetas?", result: "wrong", feedback: "You are checking the price before paying.", progresses: false },
                  { id: "c", text: "Užtenka.", result: "wrong", feedback: "You need the price, not an amount check.", progresses: false },
                ],
              },
              {
                id: "step_4",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Aštuoni eurai.",
                sceneDirection: "You want to pay by card.",
                learnerPrompt: "Ask whether card payment is possible.",
                options: [
                  { id: "a", text: "Ar galima mokėti kortele?", result: "best", progresses: true },
                  { id: "b", text: "Per brangu.", result: "wrong", feedback: "The scene says you are paying, not declining the order.", progresses: false },
                  { id: "c", text: "Grynaisiais, prašau.", result: "wrong", feedback: "The scene says you want to pay by card.", progresses: false },
                ],
              },
              {
                id: "step_5",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Taip, galima. Prašom.",
                sceneDirection: "Payment is complete and Ieva hands you the order.",
                learnerPrompt: "Thank her and say goodbye.",
                options: [
                  { id: "a", text: "Ačiū labai! Viso gero.", result: "best", progresses: true },
                  { id: "b", text: "Atsiprašau.", result: "wrong", feedback: "Nothing needs an apology.", progresses: false },
                  { id: "c", text: "Dar vieną, prašau.", result: "wrong", feedback: "The transaction is finished.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 3 — This / That, Please ───────────────────────────────────────
      {
        id: "section_4_module_1_lesson_3",
        code: "4.1.3",
        title: "This / That, Please",
        purpose: "Apply this/that forms directly to ordering — pointing and choosing at a counter or menu.",
        supportLevel: "high",
        newLanguageLoad: "low_to_medium",
        notes: {
          pattern: "After Noriu/Norėčiau, use Šito/To. When you're simply pointing and saying 'this one/that one, please', use Šitą/Tą. Both patterns work naturally at a counter — learn them as two useful chunks.",
          usage: [
            "Šito, prašau — This one, please",
            "To, prašau — That one, please",
            "Norėčiau šito — I would like this one",
          ],
        },
        blocks: [
          {
            id: "s4m1l3_b1",
            type: "learn",
            title: "Pointing to order",
            items: [
              { id: "pt2", lt: "To, prašau.", en: "That one, please.", audioText: "To, prašau", saveable: true, core: true },
              { id: "pt3", lt: "Šitą, prašau.", en: "This, please.", audioText: "Šitą, prašau", saveable: true, core: true },
              { id: "pt4", lt: "Tą, prašau.", en: "That, please.", audioText: "Tą, prašau", saveable: true, core: true },
              { id: "pt5", lt: "Kurio norėtumėte?", en: "Which one would you like?", audioText: "Kurio norėtumėte", saveable: false, core: false },
            ],
          },
          {
            id: "s4m1l3_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Šito, prašau.", audioText: "Šito, prašau" },
            options: [
              { id: "a", text: "That one, please.", isCorrect: false },
              { id: "b", text: "Which one?", isCorrect: false },
              { id: "c", text: "This one, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l3_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "To, prašau.", audioText: "To, prašau" },
            options: [
              { id: "a", text: "This one, please.", isCorrect: false },
              { id: "b", text: "One more, please.", isCorrect: false },
              { id: "c", text: "That one, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l3_b4",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Point and say: This one, please",
            targetText: "Šito, prašau",
            audioText: "Šito, prašau",
          },
          {
            id: "s4m1l3_b5_v2",
            type: "scenario_v2",
            title: "Choosing at the counter",
            description: "At a bakery counter, you point to two items, then check the total and pay.",
            sceneIntro: "At a bakery counter, you point to two items, then check the total and pay.",
            location: "bakery counter",
            userRole: "customer",
            register: "polite_service",
            goal: "Use this/that naturally inside a complete counter interaction.",
            focus: ["Šito", "To", "price", "payment"],
            participants: [{ id: "seller", label: "Seller", name: "Tomas", role: "seller", gender: "male", relationshipToUser: "stranger", register: "polite_service" }],
            steps: [
              {
                id: "step_1",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Laba diena! Kurio norėtumėte?",
                sceneDirection: "Tomas gestures between two items. You want the one nearest you.",
                learnerPrompt: "Greet him and choose this one.",
                help: { levels: [
                  { sceneDirection: "Tomas points between the two items.", speakerText: "Kurio?" },
                  { speakerText: "Which one would you like?", spokenLanguage: "en", audio: false },
                ]},
                options: [
                  { id: "a", text: "Laba diena! Šito, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Laba diena! To, prašau.", result: "wrong", feedback: "The scene says you want the item nearest you.", progresses: false },
                  { id: "c", text: "Viso gero.", result: "wrong", feedback: "You have just arrived.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Ar dar ko nors norėtumėte?",
                sceneDirection: "Your colleague points to the other item and asks you to add it.",
                learnerPrompt: "Add that one too.",
                options: [
                  { id: "a", text: "Taip. To, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Ne, ačiū.", result: "wrong", feedback: "Your colleague wants the other item too.", progresses: false },
                  { id: "c", text: "Šito, prašau.", result: "wrong", feedback: "You already chose the nearer item; your colleague wants the other one.", progresses: false },
                ],
              },
              {
                id: "step_3",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Gerai.",
                sceneDirection: "You want to know the total before paying.",
                learnerPrompt: "Ask the price.",
                options: [
                  { id: "a", text: "Kiek tai kainuoja?", result: "best", progresses: true },
                  { id: "b", text: "Kur yra bankas?", result: "wrong", feedback: "You need the price of your order.", progresses: false },
                ],
              },
              {
                id: "step_4",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Devyni eurai.",
                sceneDirection: "You want to pay by card.",
                learnerPrompt: "Ask to pay by card.",
                options: [
                  { id: "a", text: "Ar galima mokėti kortele?", result: "best", progresses: true },
                  { id: "b", text: "Nepakanka laiko.", result: "wrong", feedback: "Time is not the issue here.", progresses: false },
                ],
              },
              {
                id: "step_5",
                speakerId: "seller",
                speakerLabel: "Seller",
                speakerText: "Taip, galima. Prašom.",
                sceneDirection: "The purchase is complete.",
                learnerPrompt: "Close naturally.",
                options: [
                  { id: "a", text: "Ačiū! Viso gero.", result: "best", progresses: true },
                  { id: "b", text: "Atsiprašau.", result: "wrong", feedback: "Nothing needs an apology.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Lesson 4 — One / Two / More ──────────────────────────────────────────
      {
        id: "section_4_module_1_lesson_4",
        code: "4.1.4",
        title: "One / Two / More",
        purpose: "Bring quantity into ordering — the small numbers that come up in every food and drink situation.",
        supportLevel: "medium",
        newLanguageLoad: "low",
        notes: {
          pattern: "When you order, the drink word changes its ending — and so does the number. Du (two) becomes dvi before feminine nouns like arbata: dvi arbatas. Kava becomes kavą, arbata becomes arbatas, vanduo becomes vandenį. This is Lithuanian showing the role of words through their endings. Just notice it for now — the patterns will become familiar.",
          usage: [
            "vieną kavą — one coffee (kavą, not kava)",
            "dvi arbatas — two teas (dvi, not du; arbatas, not arbata)",
            "vieną stiklinę vandens — one glass of water",
            "Dar vieną, prašau — one more, please",
          ],
        },
        blocks: [
          {
            id: "s4m1l4_b1",
            type: "learn",
            title: "Ordering with quantity",
            items: [
              { id: "oq1", lt: "Vieną kavą, prašau.", en: "One coffee, please.", audioText: "Vieną kavą, prašau", saveable: true, core: true },
              { id: "oq2", lt: "Dvi arbatas, prašau.", en: "Two teas, please.", audioText: "Dvi arbatas, prašau", saveable: true, core: true },
              { id: "oq3", lt: "Vieną stiklinę vandens, prašau.", en: "One glass of water, please.", audioText: "Vieną stiklinę vandens, prašau", saveable: true, core: true },
            ],
          },
          {
            id: "s4m1l4_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Vieną kavą, prašau.", audioText: "Vieną kavą, prašau" },
            options: [
              { id: "a", text: "Two coffees, please.", isCorrect: false },
              { id: "b", text: "One coffee, please.", isCorrect: true },
              { id: "c", text: "One tea, please.", isCorrect: false },
            ],
          },
          {
            id: "s4m1l4_b3",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Dvi arbatas, prašau.", audioText: "Dvi arbatas, prašau" },
            options: [
              { id: "a", text: "Two coffees, please.", isCorrect: false },
              { id: "b", text: "One tea, please.", isCorrect: false },
              { id: "c", text: "Two teas, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1l4_b4",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "One coffee, please." },
            tokens: [
              { id: "t1", text: "Vieną", correctIndex: 0 },
              { id: "t2", text: "kavą,", correctIndex: 1 },
              { id: "t3", text: "prašau", correctIndex: 2 },
              { id: "t4", text: "Dvi", isDistractor: true },
              { id: "t5", text: "arbatas,", isDistractor: true },
            ],
            answerText: "Vieną kavą, prašau",
          },
          {
            id: "s4m1l4_b5",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Order: two teas, please",
            targetText: "Dvi arbatas, prašau",
            audioText: "Dvi arbatas, prašau",
          },
          {
            id: "s4m1l4_b6_v2",
            type: "scenario_v2",
            title: "Ordering for two",
            description: "You and a colleague order two teas and a glass of water, then pay.",
            sceneIntro: "You and a colleague order two teas and a glass of water, then pay.",
            location: "café",
            userRole: "customer",
            register: "polite_service",
            goal: "Use quantity forms in a realistic order while retrieving price and payment language.",
            focus: ["Dvi arbatas", "Vieną stiklinę vandens", "payment"],
            participants: [{ id: "server", label: "Server", name: "Ieva", role: "server", gender: "female", relationshipToUser: "stranger", register: "polite_service" }],
            steps: [
              {
                id: "step_1",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Laba diena! Ko norėtumėte?",
                sceneDirection: "You and your colleague both want tea.",
                learnerPrompt: "Order two teas.",
                options: [
                  { id: "a", text: "Laba diena! Dvi arbatas, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Laba diena! Du arbatos, prašau.", result: "wrong", feedback: "With arbata, use the feminine quantity form dvi and the order form arbatas.", progresses: false },
                  { id: "c", text: "Viso gero.", result: "wrong", feedback: "You have just arrived.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Ar dar ko nors?",
                sceneDirection: "You also want one glass of water.",
                learnerPrompt: "Add one glass of water.",
                options: [
                  { id: "a", text: "Vieną stiklinę vandens, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Dvi arbatas, prašau.", result: "wrong", feedback: "You already ordered the teas; now add the water.", progresses: false },
                  { id: "c", text: "Ne, ačiū.", result: "wrong", feedback: "The scene says you also want water.", progresses: false },
                ],
              },
              {
                id: "step_3",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Gerai.",
                sceneDirection: "You want to know the total.",
                learnerPrompt: "Ask how much it costs.",
                options: [
                  { id: "a", text: "Kiek tai kainuoja?", result: "best", progresses: true },
                  { id: "b", text: "Kiek jūsų?", result: "wrong", feedback: "You are asking for the price, not the group size.", progresses: false },
                ],
              },
              {
                id: "step_4",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Dešimt eurų. Grynaisiais ar kortele?",
                sceneDirection: "You want to pay by card.",
                learnerPrompt: "Choose card.",
                options: [
                  { id: "a", text: "Kortele, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Grynaisiais, prašau.", result: "wrong", feedback: "The scene says you want to use your card.", progresses: false },
                ],
              },
              {
                id: "step_5",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Prašom.",
                sceneDirection: "Ieva hands over the drinks.",
                learnerPrompt: "Thank her and close.",
                options: [
                  { id: "a", text: "Ačiū labai! Viso gero.", result: "best", progresses: true },
                  { id: "b", text: "Dar vieną, prašau.", result: "wrong", feedback: "Your order is complete.", progresses: false },
                ],
              },
            ],
          },
        ],
      },

      // ── Module 4.1 Checkpoint ─────────────────────────────────────────────────
      {
        id: "section_4_module_1_checkpoint",
        code: "4.1.C",
        title: "Ordering Basics",
        purpose: "Check you can use core ordering frames, demonstratives, and quantity without support.",
        supportLevel: "none",
        newLanguageLoad: "none",
        isCheckpoint: true,
        blocks: [
          {
            id: "s4m1c_b1",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "You're ordering at a café counter. Staff are waiting. Which sounds most natural?" },
            options: [
              { id: "a", text: "Kava, prašau!", isCorrect: false },
              { id: "b", text: "Norėčiau kavos.", isCorrect: true },
              { id: "c", text: "Noriu.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau kavos — the polite, natural default when ordering in a café or restaurant." },
          },
          {
            id: "s4m1c_b2",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Norėčiau arbatos.", audioText: "Norėčiau arbatos" },
            options: [
              { id: "a", text: "I want coffee.", isCorrect: false },
              { id: "b", text: "I would like water.", isCorrect: false },
              { id: "c", text: "I would like tea.", isCorrect: true },
            ],
          },
          {
            id: "s4m1c_b3",
            type: "listen_mcq",
            title: "Listen and choose",
            prompt: { text: "Dvi arbatas, prašau.", audioText: "Dvi arbatas, prašau" },
            options: [
              { id: "a", text: "Two coffees, please.", isCorrect: false },
              { id: "b", text: "Two teas, please.", isCorrect: true },
              { id: "c", text: "One tea, please.", isCorrect: false },
            ],
          },
          {
            id: "s4m1c_b4",
            type: "recognise_mcq",
            title: "Choose the correct meaning",
            prompt: { text: "Šito, prašau.", audioText: "Šito, prašau" },
            options: [
              { id: "a", text: "That one, please.", isCorrect: false },
              { id: "b", text: "One more, please.", isCorrect: false },
              { id: "c", text: "This one, please.", isCorrect: true },
            ],
          },
          {
            id: "s4m1c_b5",
            type: "best_response",
            title: "Choose the best response",
            prompt: { text: "Staff asks: Ko norėtumėte? You want tea." },
            options: [
              { id: "a", text: "Arbata.", isCorrect: false },
              { id: "b", text: "Norėčiau arbatos.", isCorrect: true },
              { id: "c", text: "Noriu kavos.", isCorrect: false },
            ],
            feedback: { correct: "Norėčiau arbatos — polite, and arbata changes to arbatos after Norėčiau. The go-to ordering frame." },
          },
          {
            id: "s4m1c_b6",
            type: "build_phrase",
            title: "Build the phrase",
            prompt: { text: "Two teas, please." },
            tokens: [
              { id: "t1", text: "Dvi", correctIndex: 0 },
              { id: "t2", text: "arbatas,", correctIndex: 1 },
              { id: "t3", text: "prašau", correctIndex: 2 },
              { id: "t4", text: "Vieną", isDistractor: true },
              { id: "t5", text: "kavą,", isDistractor: true },
            ],
            answerText: "Dvi arbatas, prašau",
          },
          {
            id: "s4m1c_b7",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Order politely: I would like water",
            targetText: "Norėčiau vandens",
            audioText: "Norėčiau vandens",
          },
          {
            id: "s4m1c_b8",
            type: "speak_self_check",
            title: "Say it out loud",
            prompt: "Ask for one more",
            targetText: "Dar vieną, prašau",
            audioText: "Dar vieną, prašau",
          },
          {
            id: "s4m1c_b9_v2",
            type: "scenario_v2",
            title: "Ordering basics check",
            description: "You and a colleague stop at a café kiosk. Order one coffee and one tea, add a pastry by pointing, check the price, pay, and close.",
            sceneIntro: "You and a colleague stop at a café kiosk. Order one coffee and one tea, add a pastry by pointing, check the price, pay, and close.",
            location: "café kiosk",
            userRole: "customer",
            register: "polite_service",
            goal: "Combine polite ordering, quantity and pointing with earlier price and payment language.",
            focus: ["ordering", "quantity", "this/that"],
            participants: [{ id: "server", label: "Server", name: "Ieva", role: "server", gender: "female", relationshipToUser: "stranger", register: "polite_service" }],
            steps: [
              {
                id: "step_1",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Laba diena! Ko norėtumėte?",
                sceneDirection: "You want one coffee and your colleague wants one tea.",
                learnerPrompt: "Order both drinks.",
                options: [
                  { id: "a", text: "Laba diena! Vieną kavą ir vieną arbatą, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Laba diena! Dvi arbatas, prašau.", result: "wrong", feedback: "The scene says one coffee and one tea.", progresses: false },
                  { id: "c", text: "Viso gero.", result: "wrong", feedback: "You have just arrived.", progresses: false },
                ],
              },
              {
                id: "step_2",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Ar dar ko nors norėtumėte?",
                sceneDirection: "Ieva points to two pastries. Your colleague wants the one farther away.",
                learnerPrompt: "Add that one.",
                options: [
                  { id: "a", text: "To, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Šito, prašau.", result: "wrong", feedback: "The scene says your colleague wants the farther item.", progresses: false },
                  { id: "c", text: "Ne, ačiū.", result: "wrong", feedback: "Your colleague wants one of the pastries.", progresses: false },
                ],
              },
              {
                id: "step_3",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Gerai.",
                sceneDirection: "You want the total price.",
                learnerPrompt: "Ask how much it costs.",
                options: [
                  { id: "a", text: "Kiek tai kainuoja?", result: "best", progresses: true },
                  { id: "b", text: "Kiek jūsų?", result: "wrong", feedback: "You need the price, not the party size.", progresses: false },
                ],
              },
              {
                id: "step_4",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Dvylika eurų. Grynaisiais ar kortele?",
                sceneDirection: "You want to pay by card.",
                learnerPrompt: "Choose card.",
                options: [
                  { id: "a", text: "Kortele, prašau.", result: "best", progresses: true },
                  { id: "b", text: "Grynaisiais, prašau.", result: "wrong", feedback: "The scene says you want card.", progresses: false },
                ],
              },
              {
                id: "step_5",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Prašom. Ar dar ko nors?",
                sceneDirection: "That is everything you and your colleague want.",
                learnerPrompt: "Say no thanks and that you have enough.",
                options: [
                  { id: "a", text: "Ne, ačiū. Užtenka.", result: "best", progresses: true },
                  { id: "b", text: "Dar vieną, prašau.", result: "wrong", feedback: "The scene says the order is complete.", progresses: false },
                ],
              },
              {
                id: "step_6",
                speakerId: "server",
                speakerLabel: "Server",
                speakerText: "Gerai. Viso gero!",
                sceneDirection: "The transaction is complete.",
                learnerPrompt: "Close naturally.",
                options: [
                  { id: "a", text: "Ačiū! Viso gero!", result: "best", progresses: true },
                  { id: "b", text: "Atsiprašau.", result: "wrong", feedback: "Nothing needs an apology.", progresses: false },
                ],
              },
            ],
          },
          {
            id: "s4m1c_b10",
            type: "word_match",
            title: "Match the pairs",
            pairs: [
              { id: "m1",  lt: "Noriu kavos.",          en: "I want coffee.",           audioText: "Noriu kavos" },
              { id: "m2",  lt: "Noriu arbatos.",         en: "I want tea.",              audioText: "Noriu arbatos" },
              { id: "m3",  lt: "Noriu vandens.",         en: "I want water.",            audioText: "Noriu vandens" },
              { id: "m4",  lt: "Noriu šito.",            en: "I want this.",             audioText: "Noriu šito" },
              { id: "m5",  lt: "Norėčiau kavos.",        en: "I would like coffee.",     audioText: "Norėčiau kavos" },
              { id: "m6",  lt: "Norėčiau arbatos.",      en: "I would like tea.",        audioText: "Norėčiau arbatos" },
              { id: "m7",  lt: "Norėčiau šito.",         en: "I would like this.",       audioText: "Norėčiau šito" },
              { id: "m8",  lt: "Norėčiau užsisakyti.",   en: "I would like to order.",   audioText: "Norėčiau užsisakyti" },
              { id: "m9",  lt: "Šito, prašau.",          en: "This one, please.",        audioText: "Šito, prašau" },
              { id: "m10", lt: "To, prašau.",            en: "That one, please.",        audioText: "To, prašau" },
              { id: "m11", lt: "Šitą, prašau.",          en: "This, please.",            audioText: "Šitą, prašau" },
              { id: "m12", lt: "Tą, prašau.",            en: "That, please.",            audioText: "Tą, prašau" },
              { id: "m13", lt: "Vieną kavą, prašau.",    en: "One coffee, please.",      audioText: "Vieną kavą, prašau" },
              { id: "m14", lt: "Dvi arbatas, prašau.",   en: "Two teas, please.",        audioText: "Dvi arbatas, prašau" },
              { id: "m15", lt: "Vieną stiklinę vandens, prašau.", en: "One glass of water, please.", audioText: "Vieną stiklinę vandens, prašau" },
              { id: "m16", lt: "Dar vieną, prašau.",     en: "One more, please.",        audioText: "Dar vieną, prašau" },
              { id: "m17", lt: "Ko norėtumėte?",         en: "What would you like?",     audioText: "Ko norėtumėte" },
              { id: "m18", lt: "Ko norėtumėte?",         en: "What would you like?",     audioText: "Ko norėtumėte" },
              { id: "m19", lt: "tortas",                 en: "cake",                     audioText: "tortas" },
              { id: "m20", lt: "ledai",                  en: "ice cream",                audioText: "ledai" },
            ],
          },
        ],
      },
    ],
  };
}
